import msgspec
from nautilus_trader.adapters.binance.common.constants import BINANCE_FUTURES_ORDER_COUNT_KEYS as BINANCE_FUTURES_ORDER_COUNT_KEYS
from nautilus_trader.adapters.binance.common.enums import BinanceAccountType as BinanceAccountType, BinanceFuturesPositionSide as BinanceFuturesPositionSide, BinanceOrderSide as BinanceOrderSide, BinanceOrderType as BinanceOrderType, BinanceSecurityType as BinanceSecurityType, BinanceTimeInForce as BinanceTimeInForce
from nautilus_trader.adapters.binance.common.schemas.account import BinanceStatusCode as BinanceStatusCode
from nautilus_trader.adapters.binance.common.symbol import BinanceSymbol as BinanceSymbol
from nautilus_trader.adapters.binance.futures.enums import BinanceFuturesMarginType as BinanceFuturesMarginType
from nautilus_trader.adapters.binance.futures.schemas.account import BinanceFuturesAccountInfo as BinanceFuturesAccountInfo, BinanceFuturesAlgoOrder as BinanceFuturesAlgoOrder, BinanceFuturesAlgoOrderCancelResponse as BinanceFuturesAlgoOrderCancelResponse, BinanceFuturesDualSidePosition as BinanceFuturesDualSidePosition, BinanceFuturesLeverage as BinanceFuturesLeverage, BinanceFuturesMarginTypeResponse as BinanceFuturesMarginTypeResponse, BinanceFuturesPositionRisk as BinanceFuturesPositionRisk, BinanceFuturesSymbolConfig as BinanceFuturesSymbolConfig
from nautilus_trader.adapters.binance.http.account import BinanceAccountHttpAPI as BinanceAccountHttpAPI
from nautilus_trader.adapters.binance.http.client import BinanceHttpClient as BinanceHttpClient
from nautilus_trader.adapters.binance.http.endpoint import BinanceHttpEndpoint as BinanceHttpEndpoint
from nautilus_trader.adapters.binance.http.error import BinanceClientError as BinanceClientError
from nautilus_trader.common.component import LiveClock as LiveClock
from nautilus_trader.common.config import PositiveInt as PositiveInt
from nautilus_trader.core.nautilus_pyo3 import HttpMethod as HttpMethod
from typing import Any

class BinanceFuturesPositionModeHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class GetParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        timestamp: str
        recvWindow: str | None = ...
    class PostParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        timestamp: str
        dualSidePosition: str
        recvWindow: str | None = ...
    async def get(self, params: GetParameters) -> BinanceFuturesDualSidePosition: ...
    async def post(self, params: PostParameters) -> BinanceStatusCode: ...

class BinanceFuturesAllOpenOrdersHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class DeleteParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        timestamp: str
        symbol: BinanceSymbol
        recvWindow: str | None = ...
    async def delete(self, params: DeleteParameters) -> BinanceStatusCode: ...

class BinanceFuturesCancelMultipleOrdersHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class DeleteParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        timestamp: str
        symbol: BinanceSymbol
        orderIdList: str | None = ...
        origClientOrderIdList: str | None = ...
        recvWindow: str | None = ...
    async def delete(self, params: DeleteParameters) -> list[dict[str, Any]] | dict[str, Any]: ...

class BinanceFuturesAccountHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class GetParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        timestamp: str
        recvWindow: str | None = ...
    async def get(self, params: GetParameters) -> BinanceFuturesAccountInfo: ...

class BinanceFuturesPositionRiskHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class GetParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        timestamp: str
        symbol: BinanceSymbol | None = ...
        recvWindow: str | None = ...
    async def get(self, params: GetParameters) -> list[BinanceFuturesPositionRisk]: ...

class BinanceFuturesSymbolConfigHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class GetParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        timestamp: str
        symbol: BinanceSymbol | None = ...
        recvWindow: str | None = ...
    async def get(self, params: GetParameters) -> list[BinanceFuturesSymbolConfig]: ...

class BinanceFuturesLeverageHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class PostParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        symbol: BinanceSymbol
        leverage: PositiveInt
        timestamp: str
        recvWindow: str | None = ...
    async def post(self, params: PostParameters) -> BinanceFuturesLeverage: ...

class BinanceFuturesMarginTypeHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class PostParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        symbol: BinanceSymbol
        marginType: str
        timestamp: str
        recvWindow: str | None = ...
    async def post(self, params: PostParameters) -> BinanceFuturesMarginTypeResponse: ...

class BinanceFuturesAlgoOrderHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class GetDeleteParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        timestamp: str
        algoId: int | None = ...
        clientAlgoId: str | None = ...
        recvWindow: str | None = ...
    class PostParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        symbol: BinanceSymbol
        side: BinanceOrderSide
        type: BinanceOrderType
        algoType: str
        timestamp: str
        positionSide: BinanceFuturesPositionSide | None = ...
        quantity: str | None = ...
        price: str | None = ...
        triggerPrice: str | None = ...
        timeInForce: BinanceTimeInForce | None = ...
        workingType: str | None = ...
        priceMatch: str | None = ...
        closePosition: str | None = ...
        priceProtect: str | None = ...
        reduceOnly: str | None = ...
        activatePrice: str | None = ...
        callbackRate: str | None = ...
        clientAlgoId: str | None = ...
        goodTillDate: int | None = ...
        recvWindow: str | None = ...
    async def get(self, params: GetDeleteParameters) -> BinanceFuturesAlgoOrder: ...
    async def delete(self, params: GetDeleteParameters) -> BinanceFuturesAlgoOrderCancelResponse: ...
    async def post(self, params: PostParameters) -> BinanceFuturesAlgoOrder: ...

class BinanceFuturesOpenAlgoOrdersHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class GetParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        timestamp: str
        algoType: str | None = ...
        symbol: BinanceSymbol | None = ...
        algoId: int | None = ...
        recvWindow: str | None = ...
    async def get(self, params: GetParameters) -> list[BinanceFuturesAlgoOrder]: ...

class BinanceFuturesAllAlgoOrdersHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class GetParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        timestamp: str
        symbol: BinanceSymbol
        algoId: int | None = ...
        startTime: str | None = ...
        endTime: str | None = ...
        page: int | None = ...
        limit: int | None = ...
        recvWindow: str | None = ...
    async def get(self, params: GetParameters) -> list[BinanceFuturesAlgoOrder]: ...

class BinanceFuturesCancelAllAlgoOrdersHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class DeleteParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        timestamp: str
        symbol: BinanceSymbol
        recvWindow: str | None = ...
    async def delete(self, params: DeleteParameters) -> BinanceStatusCode: ...

class BinanceFuturesAccountHttpAPI(BinanceAccountHttpAPI):
    def __init__(self, client: BinanceHttpClient, clock: LiveClock, account_type: BinanceAccountType = ...) -> None: ...
    async def query_futures_hedge_mode(self, recv_window: str | None = None) -> BinanceFuturesDualSidePosition: ...
    async def set_leverage(self, symbol: BinanceSymbol, leverage: PositiveInt, recv_window: str | None = None) -> BinanceFuturesLeverage: ...
    async def set_margin_type(self, symbol: BinanceSymbol, margin_type: BinanceFuturesMarginType, recv_window: str | None = None) -> BinanceFuturesMarginTypeResponse: ...
    async def set_futures_hedge_mode(self, dual_side_position: bool, recv_window: str | None = None) -> BinanceStatusCode: ...
    async def cancel_all_open_orders(self, symbol: str, recv_window: str | None = None) -> bool: ...
    async def cancel_multiple_orders(self, symbol: str, client_order_ids: list[str], recv_window: str | None = None) -> list[dict[str, Any]]: ...
    async def query_futures_account_info(self, recv_window: str | None = None) -> BinanceFuturesAccountInfo: ...
    async def query_futures_position_risk(self, symbol: str | None = None, recv_window: str | None = None) -> list[BinanceFuturesPositionRisk]: ...
    async def query_futures_symbol_config(self, symbol: str | None = None, recv_window: str | None = None) -> list[BinanceFuturesSymbolConfig]: ...
    async def new_algo_order(self, symbol: str, side: BinanceOrderSide, order_type: BinanceOrderType, position_side: BinanceFuturesPositionSide | None = None, quantity: str | None = None, price: str | None = None, trigger_price: str | None = None, time_in_force: BinanceTimeInForce | None = None, working_type: str | None = None, price_match: str | None = None, close_position: str | None = None, price_protect: str | None = None, reduce_only: str | None = None, activation_price: str | None = None, callback_rate: str | None = None, client_algo_id: str | None = None, good_till_date: int | None = None, recv_window: str | None = None) -> BinanceFuturesAlgoOrder: ...
    async def cancel_algo_order(self, algo_id: int | None = None, client_algo_id: str | None = None, recv_window: str | None = None) -> BinanceFuturesAlgoOrderCancelResponse: ...
    async def query_algo_order(self, algo_id: int | None = None, client_algo_id: str | None = None, recv_window: str | None = None) -> BinanceFuturesAlgoOrder: ...
    async def query_open_algo_orders(self, symbol: str | None = None, recv_window: str | None = None) -> list[BinanceFuturesAlgoOrder]: ...
    async def query_all_algo_orders(self, symbol: str, start_time: int | None = None, end_time: int | None = None, page: int | None = None, limit: int | None = None, recv_window: str | None = None) -> list[BinanceFuturesAlgoOrder]: ...
    async def cancel_all_open_algo_orders(self, symbol: str, recv_window: str | None = None) -> bool: ...
