import _cython_3_2_9
import nautilus_trader.core.data
from _typeshed import Incomplete
from decimal import Decimal
from typing import Any, ClassVar

USD_EQUIVALENT_CURRENCY_CODES: frozenset
__pyx_capi__: dict
__test__: dict
instruments_from_pyo3: _cython_3_2_9.cython_function_or_method

class Instrument(nautilus_trader.core.data.Data):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    asset_class: Incomplete
    id: Incomplete
    info: Incomplete
    instrument_class: Incomplete
    is_inverse: Incomplete
    lot_size: Incomplete
    maker_fee: Incomplete
    margin_init: Incomplete
    margin_maint: Incomplete
    max_notional: Incomplete
    max_price: Incomplete
    max_quantity: Incomplete
    min_notional: Incomplete
    min_price: Incomplete
    min_quantity: Incomplete
    multiplier: Incomplete
    price_increment: Incomplete
    price_precision: Incomplete
    quote_currency: Incomplete
    raw_symbol: Incomplete
    size_increment: Incomplete
    size_precision: Incomplete
    symbol: Incomplete
    taker_fee: Incomplete
    tick_scheme_name: Incomplete
    ts_event: Incomplete
    ts_init: Incomplete
    venue: Incomplete
    def __init__(self, InstrumentIdinstrument_id, Symbolraw_symbol, AssetClassasset_class, InstrumentClassinstrument_class, Currencyquote_currency, boolis_inverse, intprice_precision, intsize_precision, Quantitysize_increment, Quantitymultiplier, margin_init: Decimal, margin_maint: Decimal, maker_fee: Decimal, taker_fee: Decimal, uint64_tts_event, uint64_tts_init, Priceprice_increment: Price | None = ..., Quantitylot_size: Quantity | None = ..., Quantitymax_quantity: Quantity | None = ..., Quantitymin_quantity: Quantity | None = ..., Moneymax_notional: Money | None = ..., Moneymin_notional: Money | None = ..., Pricemax_price: Price | None = ..., Pricemin_price: Price | None = ..., strtick_scheme_name=..., dictinfo=...) -> None: ...
    def allows_negative_price(self) -> bool: ...
    @staticmethod
    def base_from_dict(dictvalues) -> Instrument: ...
    @staticmethod
    def base_to_dict(Instrumentobj) -> Any: ...
    def calculate_base_quantity(self, Quantityquantity, Pricelast_px) -> Quantity: ...
    def get_base_currency(self) -> Currency: ...
    def get_cost_currency(self) -> Currency: ...
    def get_settlement_currency(self) -> Currency: ...
    def is_spread(self) -> bool: ...
    def legs(self) -> list: ...
    def make_price(self, value) -> Price: ...
    def make_qty(self, value, boolround_down=...) -> Quantity: ...
    def next_ask_price(self, doublevalue, intnum_ticks=...) -> Price: ...
    def next_ask_prices(self, doublevalue, intnum_ticks=...) -> list: ...
    def next_bid_price(self, doublevalue, intnum_ticks=...) -> Price: ...
    def next_bid_prices(self, doublevalue, intnum_ticks=...) -> list: ...
    def notional_value(self, Quantityquantity, Priceprice, booluse_quote_for_inverse=..., Currencytarget_currency=..., Priceconversion_price=...) -> Money: ...
    def set_tick_scheme(self, strtick_scheme_name) -> void: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
