import nautilus_trader.model.instruments.base
from _typeshed import Incomplete
from decimal import Decimal
from typing import Any, ClassVar

__test__: dict

class BinaryOption(nautilus_trader.model.instruments.base.Instrument):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    activation_ns: Incomplete
    activation_utc: BinaryOption.activation_utc
    description: Incomplete
    expiration_ns: Incomplete
    expiration_utc: BinaryOption.expiration_utc
    outcome: Incomplete
    def __init__(self, InstrumentIdinstrument_id, Symbolraw_symbol, AssetClassasset_class, Currencycurrency, intprice_precision, intsize_precision, Priceprice_increment, Quantitysize_increment, uint64_tactivation_ns, uint64_texpiration_ns, uint64_tts_event, uint64_tts_init, Quantitymax_quantity: Quantity | None = ..., Quantitymin_quantity: Quantity | None = ..., maker_fee: Decimal | None = ..., taker_fee: Decimal | None = ..., stroutcome=..., strdescription=..., strtick_scheme_name=..., dictinfo=...) -> None: ...
    @staticmethod
    def from_dict(dictvalues) -> BinaryOption: ...
    @staticmethod
    def from_pyo3(pyo3_instrument) -> BinaryOption: ...
    @staticmethod
    def to_dict(BinaryOptionobj) -> dict[str, object]: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
