import nautilus_trader.model.instruments.base
from _typeshed import Incomplete
from decimal import Decimal
from typing import Any, ClassVar

__test__: dict

class Commodity(nautilus_trader.model.instruments.base.Instrument):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    isin: Incomplete
    def __init__(self, InstrumentIdinstrument_id, Symbolraw_symbol, AssetClassasset_class, Currencyquote_currency, intprice_precision, intsize_precision, Priceprice_increment, Quantitysize_increment, uint64_tts_event, uint64_tts_init, Currencybase_currency: Currency | None = ..., Quantitylot_size: Quantity | None = ..., Quantitymax_quantity: Quantity | None = ..., Quantitymin_quantity: Quantity | None = ..., Moneymax_notional: Money | None = ..., Moneymin_notional: Money | None = ..., Pricemax_price: Price | None = ..., Pricemin_price: Price | None = ..., margin_init: Decimal | None = ..., margin_maint: Decimal | None = ..., maker_fee: Decimal | None = ..., taker_fee: Decimal | None = ..., strtick_scheme_name=..., dictinfo=...) -> None: ...
    def allows_negative_price(self) -> bool: ...
    @staticmethod
    def from_dict(dictvalues) -> Commodity: ...
    @staticmethod
    def from_pyo3(pyo3_instrument) -> Any: ...
    @staticmethod
    def to_dict(Commodityobj) -> dict[str, object]: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
