import nautilus_trader.model.instruments.base
from _typeshed import Incomplete
from decimal import Decimal
from typing import Any, ClassVar

__test__: dict

class Equity(nautilus_trader.model.instruments.base.Instrument):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    isin: Incomplete
    def __init__(self, InstrumentIdinstrument_id, Symbolraw_symbol, Currencycurrency, intprice_precision, Priceprice_increment, Quantitylot_size, uint64_tts_event, uint64_tts_init, Quantitymax_quantity: Quantity | None = ..., Quantitymin_quantity: Quantity | None = ..., margin_init: Decimal | None = ..., margin_maint: Decimal | None = ..., maker_fee: Decimal | None = ..., taker_fee: Decimal | None = ..., strisin: str | None = ..., strtick_scheme_name=..., dictinfo=...) -> None: ...
    @staticmethod
    def from_dict(dictvalues) -> Instrument: ...
    @staticmethod
    def from_pyo3(pyo3_instrument) -> Equity: ...
    @staticmethod
    def to_dict(Instrumentobj) -> dict[str, object]: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
