import nautilus_trader.model.instruments.base
from typing import Any, ClassVar

__test__: dict

class IndexInstrument(nautilus_trader.model.instruments.base.Instrument):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, InstrumentIdinstrument_id, Symbolraw_symbol, Currencycurrency, intprice_precision, intsize_precision, Priceprice_increment, Quantitysize_increment, uint64_tts_event, uint64_tts_init, strtick_scheme_name=..., dictinfo=...) -> None: ...
    @staticmethod
    def from_dict(dictvalues) -> Instrument: ...
    @staticmethod
    def from_pyo3(pyo3_instrument) -> IndexInstrument: ...
    @staticmethod
    def to_dict(Instrumentobj) -> dict[str, object]: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
