import nautilus_trader.model.instruments.base
from _typeshed import Incomplete
from decimal import Decimal
from typing import Any, ClassVar

__test__: dict

class PerpetualContract(nautilus_trader.model.instruments.base.Instrument):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    base_currency: Incomplete
    is_quanto: Incomplete
    settlement_currency: Incomplete
    underlying: Incomplete
    def __init__(self, InstrumentIdinstrument_id, Symbolraw_symbol, strunderlying, AssetClassasset_class, Currencyquote_currency, Currencysettlement_currency, boolis_inverse, intprice_precision, intsize_precision, Priceprice_increment, Quantitysize_increment, uint64_tts_event, uint64_tts_init, Currencybase_currency: Currency | None = ..., multiplier=..., lot_size=..., Quantitymax_quantity: Quantity | None = ..., Quantitymin_quantity: Quantity | None = ..., Moneymax_notional: Money | None = ..., Moneymin_notional: Money | None = ..., Pricemax_price: Price | None = ..., Pricemin_price: Price | None = ..., margin_init: Decimal | None = ..., margin_maint: Decimal | None = ..., maker_fee: Decimal | None = ..., taker_fee: Decimal | None = ..., strtick_scheme_name=..., dictinfo=...) -> None: ...
    @staticmethod
    def from_dict(dictvalues) -> PerpetualContract: ...
    @staticmethod
    def from_pyo3(pyo3_instrument) -> Any: ...
    def get_base_currency(self) -> Currency: ...
    def get_cost_currency(self) -> Currency: ...
    def get_settlement_currency(self) -> Currency: ...
    def notional_value(self, Quantityquantity, Priceprice, booluse_quote_for_inverse=..., Currencytarget_currency=..., Priceconversion_price=...) -> Money: ...
    @staticmethod
    def to_dict(PerpetualContractobj) -> dict[str, object]: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
