import _cython_3_2_9
import nautilus_trader.core.data
from _typeshed import Incomplete
from typing import ClassVar

__reduce_cython__: _cython_3_2_9.cython_function_or_method
__setstate_cython__: _cython_3_2_9.cython_function_or_method
__test__: dict

class SyntheticInstrument(nautilus_trader.core.data.Data):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    components: SyntheticInstrument.components
    formula: SyntheticInstrument.formula
    id: Incomplete
    price_increment: SyntheticInstrument.price_increment
    price_precision: SyntheticInstrument.price_precision
    ts_event: SyntheticInstrument.ts_event
    ts_init: SyntheticInstrument.ts_init
    def __init__(self, Symbolsymbol, uint8_tprice_precision, listcomponents, strformula, uint64_tts_event, uint64_tts_init) -> None: ...
    def calculate(self, listinputs) -> Price: ...
    def change_formula(self, strformula) -> void: ...
    @staticmethod
    def from_dict(dictvalues) -> SyntheticInstrument: ...
    @staticmethod
    def to_dict(SyntheticInstrumentobj) -> dict[str, object]: ...
    def __del__(self, *args, **kwargs) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
