from decimal import Decimal
from nautilus_trader.config import LiveExecClientConfig as LiveExecClientConfig

class SandboxExecutionClientConfig(LiveExecClientConfig, frozen=True, kw_only=True):
    venue: str
    starting_balances: list[str]
    base_currency: str | None = ...
    oms_type: str = ...
    account_type: str = ...
    default_leverage: Decimal = ...
    leverages: dict[str, float] | None = ...
    book_type: str = ...
    frozen_account: bool = ...
    bar_execution: bool = ...
    trade_execution: bool = ...
    reject_stop_orders: bool = ...
    support_gtd_orders: bool = ...
    support_contingent_orders: bool = ...
    use_position_ids: bool = ...
    use_random_ids: bool = ...
    use_reduce_only: bool = ...
