import asyncio
from _typeshed import Incomplete
from nautilus_trader.adapters.sandbox.config import SandboxExecutionClientConfig as SandboxExecutionClientConfig
from nautilus_trader.backtest.engine import SimulatedExchange as SimulatedExchange
from nautilus_trader.backtest.execution_client import BacktestExecClient as BacktestExecClient
from nautilus_trader.backtest.models import FillModel as FillModel, LatencyModel as LatencyModel, MakerTakerFeeModel as MakerTakerFeeModel
from nautilus_trader.cache.cache import Cache as Cache
from nautilus_trader.common.component import LiveClock as LiveClock, MessageBus as MessageBus, TestClock as TestClock
from nautilus_trader.common.providers import InstrumentProvider as InstrumentProvider
from nautilus_trader.core.data import Data as Data
from nautilus_trader.execution.messages import GenerateFillReports as GenerateFillReports, GenerateOrderStatusReport as GenerateOrderStatusReport, GenerateOrderStatusReports as GenerateOrderStatusReports, GeneratePositionStatusReports as GeneratePositionStatusReports
from nautilus_trader.execution.reports import FillReport as FillReport, OrderStatusReport as OrderStatusReport, PositionStatusReport as PositionStatusReport
from nautilus_trader.live.execution_client import LiveExecutionClient as LiveExecutionClient
from nautilus_trader.model.data import Bar as Bar, InstrumentClose as InstrumentClose, InstrumentStatus as InstrumentStatus, OrderBookDelta as OrderBookDelta, OrderBookDeltas as OrderBookDeltas, OrderBookDepth10 as OrderBookDepth10, QuoteTick as QuoteTick, TradeTick as TradeTick
from nautilus_trader.model.enums import account_type_from_str as account_type_from_str, book_type_from_str as book_type_from_str, oms_type_from_str as oms_type_from_str
from nautilus_trader.model.identifiers import AccountId as AccountId, ClientId as ClientId, Venue as Venue
from nautilus_trader.model.instruments import Instrument as Instrument
from nautilus_trader.model.objects import Currency as Currency, Money as Money
from nautilus_trader.portfolio.base import PortfolioFacade as PortfolioFacade

class SandboxExecutionClient(LiveExecutionClient):
    test_clock: Incomplete
    exchange: Incomplete
    def __init__(self, loop: asyncio.AbstractEventLoop, portfolio: PortfolioFacade, msgbus: MessageBus, cache: Cache, clock: LiveClock, config: SandboxExecutionClientConfig) -> None: ...
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    async def generate_order_status_report(self, command: GenerateOrderStatusReport) -> OrderStatusReport | None: ...
    async def generate_order_status_reports(self, command: GenerateOrderStatusReports) -> list[OrderStatusReport]: ...
    async def generate_fill_reports(self, command: GenerateFillReports) -> list[FillReport]: ...
    async def generate_position_status_reports(self, command: GeneratePositionStatusReports) -> list[PositionStatusReport]: ...
    def submit_order(self, command): ...
    def submit_order_list(self, command): ...
    def modify_order(self, command): ...
    def cancel_order(self, command): ...
    def cancel_all_orders(self, command): ...
    def on_data(self, data: Data) -> None: ...
