from nautilus_trader.config import LiveDataClientConfig as LiveDataClientConfig
from nautilus_trader.model.identifiers import InstrumentId as InstrumentId

class DatabentoDataClientConfig(LiveDataClientConfig, frozen=True):
    api_key: str | None = ...
    http_gateway: str | None = ...
    live_gateway: str | None = ...
    use_exchange_as_venue: bool = ...
    timeout_initial_load: float | None = ...
    mbo_subscriptions_delay: float | None = ...
    bars_timestamp_on_close: bool = ...
    instrument_ids: list[InstrumentId] | None = ...
    parent_symbols: dict[str, set[str]] | None = ...
    venue_dataset_map: dict[str, str] | None = ...
    reconnect_timeout_mins: int | None = ...
