from _typeshed import Incomplete
from nautilus_trader import PACKAGE_ROOT as PACKAGE_ROOT
from nautilus_trader.adapters.databento.loaders import DatabentoDataLoader as DatabentoDataLoader
from nautilus_trader.persistence.catalog import ParquetDataCatalog as ParquetDataCatalog
from pathlib import Path
from typing import Any

DATA_PATH: Incomplete
client: Incomplete

def init_databento_client(databento_api_key: str | None = None) -> None: ...
def databento_cost(symbols: list[str], start_time: str, end_time: str, schema: str, dataset: str = 'GLBX.MDP3', **kwargs: Any) -> float: ...
def databento_data(symbols: list[str], start_time: str, end_time: str, schema: str, file_prefix: str, *folders: str, dataset: str = 'GLBX.MDP3', to_catalog: bool = True, base_path: Path | None = None, use_exchange_as_venue: bool = True, load_databento_files_if_exist: bool = False, as_legacy_cython: bool = False, **kwargs: Any) -> dict[str, Any]: ...
def databento_definition_dates(start_time: str, end_time: str | None = None) -> tuple[str, str]: ...
def next_day(date_str: str) -> str: ...
def save_data_to_catalog(*folders: str, definition_file: Path | str | None = None, data_file: Path | str | None = None, base_path: Path | None = None, use_exchange_as_venue: bool = True, as_legacy_cython: bool = False) -> dict[str, Any]: ...
def load_catalog(*folders: str, base_path: Path | None = None) -> ParquetDataCatalog: ...
def create_data_folder(*folders: str, base_path: Path | None = None) -> Path: ...
def data_path(*folders: str, base_path: Path | None = None) -> Path: ...
def query_catalog(catalog: ParquetDataCatalog, data_type: str = 'bars', **kwargs: Any) -> Any: ...
def load_databento_data(file: Path | str) -> Any: ...
def save_databento_data(data: Any, file: Path | str) -> Any: ...
