from nautilus_trader.adapters.databento.constants import PUBLISHERS_FILEPATH as PUBLISHERS_FILEPATH
from nautilus_trader.adapters.databento.enums import DatabentoSchema as DatabentoSchema
from nautilus_trader.core import nautilus_pyo3 as nautilus_pyo3
from nautilus_trader.core.data import Data as Data
from nautilus_trader.core.nautilus_pyo3 import drop_cvec_pycapsule as drop_cvec_pycapsule
from nautilus_trader.model.data import InstrumentStatus as InstrumentStatus, capsule_to_list as capsule_to_list
from nautilus_trader.model.identifiers import InstrumentId as InstrumentId, Venue as Venue
from nautilus_trader.model.instruments import instruments_from_pyo3 as instruments_from_pyo3
from os import PathLike

class DatabentoDataLoader:
    def __init__(self, venue_dataset_map: dict[str, str] | None = None) -> None: ...
    def load_publishers(self, path: PathLike[str] | str) -> None: ...
    def get_publishers(self) -> dict[int, nautilus_pyo3.DatabentoPublisher]: ...
    def get_dataset_for_venue(self, venue: Venue) -> str: ...
    def set_price_precision(self, symbol: str, price_precision: int) -> None: ...
    def get_price_precisions(self) -> dict[str, int]: ...
    def from_dbn_file(self, path: PathLike[str] | str, instrument_id: InstrumentId | None = None, price_precision: int | None = None, as_legacy_cython: bool = True, include_trades: bool = False, use_exchange_as_venue: bool = False, bars_timestamp_on_close: bool = True, skip_on_error: bool = False, expiration_overrides: dict[str, dict[str, str]] | None = None) -> list[Data]: ...
