import nautilus_trader.core.message
from _typeshed import Incomplete
from typing import Any, ClassVar

__test__: dict

class AccountState(nautilus_trader.core.message.Event):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    account_id: Incomplete
    account_type: Incomplete
    balances: Incomplete
    base_currency: Incomplete
    id: AccountState.id
    info: Incomplete
    is_reported: Incomplete
    margins: Incomplete
    ts_event: AccountState.ts_event
    ts_init: AccountState.ts_init
    def __init__(self, AccountIdaccount_id, AccountTypeaccount_type, Currencybase_currency, boolreported, listbalances, listmargins, dictinfo, UUID4event_id, uint64_tts_event, uint64_tts_init) -> Any: ...
    @staticmethod
    def from_dict(dictvalues) -> AccountState: ...
    @staticmethod
    def to_dict(AccountStateobj) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
