import _cython_3_2_9
import nautilus_trader.core.message
from _typeshed import Incomplete
from typing import Any, ClassVar

__reduce_cython__: _cython_3_2_9.cython_function_or_method
__setstate_cython__: _cython_3_2_9.cython_function_or_method
__test__: dict

class OrderAccepted(OrderEvent):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    account_id: OrderAccepted.account_id
    client_order_id: OrderAccepted.client_order_id
    id: OrderAccepted.id
    instrument_id: OrderAccepted.instrument_id
    reconciliation: OrderAccepted.reconciliation
    strategy_id: OrderAccepted.strategy_id
    trader_id: OrderAccepted.trader_id
    ts_event: OrderAccepted.ts_event
    ts_init: OrderAccepted.ts_init
    venue_order_id: OrderAccepted.venue_order_id
    def __init__(self, TraderIdtrader_id, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, VenueOrderIdvenue_order_id, AccountIdaccount_id, UUID4event_id, uint64_tts_event, uint64_tts_init, boolreconciliation=...) -> Any: ...
    @staticmethod
    def from_dict(dictvalues) -> OrderAccepted: ...
    def set_client_order_id(self, ClientOrderIdclient_order_id) -> Any: ...
    @staticmethod
    def to_dict(OrderAcceptedobj) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...

class OrderCancelRejected(OrderEvent):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    account_id: OrderCancelRejected.account_id
    client_order_id: OrderCancelRejected.client_order_id
    id: OrderCancelRejected.id
    instrument_id: OrderCancelRejected.instrument_id
    reason: OrderCancelRejected.reason
    reconciliation: OrderCancelRejected.reconciliation
    strategy_id: OrderCancelRejected.strategy_id
    trader_id: OrderCancelRejected.trader_id
    ts_event: OrderCancelRejected.ts_event
    ts_init: OrderCancelRejected.ts_init
    venue_order_id: OrderCancelRejected.venue_order_id
    def __init__(self, TraderIdtrader_id, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, VenueOrderIdvenue_order_id: VenueOrderId | None, AccountIdaccount_id: AccountId | None, strreason, UUID4event_id, uint64_tts_event, uint64_tts_init, boolreconciliation=...) -> Any: ...
    @staticmethod
    def from_dict(dictvalues) -> OrderCancelRejected: ...
    def set_client_order_id(self, ClientOrderIdclient_order_id) -> Any: ...
    @staticmethod
    def to_dict(OrderCancelRejectedobj) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class OrderCanceled(OrderEvent):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    account_id: OrderCanceled.account_id
    client_order_id: OrderCanceled.client_order_id
    id: OrderCanceled.id
    instrument_id: OrderCanceled.instrument_id
    reconciliation: OrderCanceled.reconciliation
    strategy_id: OrderCanceled.strategy_id
    trader_id: OrderCanceled.trader_id
    ts_event: OrderCanceled.ts_event
    ts_init: OrderCanceled.ts_init
    venue_order_id: OrderCanceled.venue_order_id
    def __init__(self, TraderIdtrader_id, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, VenueOrderIdvenue_order_id: VenueOrderId | None, AccountIdaccount_id: AccountId | None, UUID4event_id, uint64_tts_event, uint64_tts_init, boolreconciliation=...) -> Any: ...
    @staticmethod
    def from_dict(dictvalues) -> OrderCanceled: ...
    def set_client_order_id(self, ClientOrderIdclient_order_id) -> Any: ...
    @staticmethod
    def to_dict(OrderCanceledobj) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class OrderDenied(OrderEvent):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    account_id: OrderDenied.account_id
    client_order_id: OrderDenied.client_order_id
    id: OrderDenied.id
    instrument_id: OrderDenied.instrument_id
    reason: OrderDenied.reason
    reconciliation: OrderDenied.reconciliation
    strategy_id: OrderDenied.strategy_id
    trader_id: OrderDenied.trader_id
    ts_event: OrderDenied.ts_event
    ts_init: OrderDenied.ts_init
    venue_order_id: OrderDenied.venue_order_id
    def __init__(self, TraderIdtrader_id, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, strreason, UUID4event_id, uint64_tts_init) -> Any: ...
    @staticmethod
    def from_dict(dictvalues) -> OrderDenied: ...
    def set_client_order_id(self, ClientOrderIdclient_order_id) -> Any: ...
    @staticmethod
    def to_dict(OrderDeniedobj) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...

class OrderEmulated(OrderEvent):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    account_id: OrderEmulated.account_id
    client_order_id: OrderEmulated.client_order_id
    id: OrderEmulated.id
    instrument_id: OrderEmulated.instrument_id
    reconciliation: OrderEmulated.reconciliation
    strategy_id: OrderEmulated.strategy_id
    trader_id: OrderEmulated.trader_id
    ts_event: OrderEmulated.ts_event
    ts_init: OrderEmulated.ts_init
    venue_order_id: OrderEmulated.venue_order_id
    def __init__(self, TraderIdtrader_id, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, UUID4event_id, uint64_tts_init) -> Any: ...
    @staticmethod
    def from_dict(dictvalues) -> OrderEmulated: ...
    def set_client_order_id(self, ClientOrderIdclient_order_id) -> Any: ...
    @staticmethod
    def to_dict(OrderEmulatedobj) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...

class OrderEvent(nautilus_trader.core.message.Event):
    account_id: OrderEvent.account_id
    client_order_id: OrderEvent.client_order_id
    id: OrderEvent.id
    instrument_id: OrderEvent.instrument_id
    reconciliation: OrderEvent.reconciliation
    strategy_id: OrderEvent.strategy_id
    trader_id: OrderEvent.trader_id
    ts_event: OrderEvent.ts_event
    ts_init: OrderEvent.ts_init
    venue_order_id: OrderEvent.venue_order_id
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def set_client_order_id(self, ClientOrderIdclient_order_id) -> Any: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class OrderExpired(OrderEvent):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    account_id: OrderExpired.account_id
    client_order_id: OrderExpired.client_order_id
    id: OrderExpired.id
    instrument_id: OrderExpired.instrument_id
    reconciliation: OrderExpired.reconciliation
    strategy_id: OrderExpired.strategy_id
    trader_id: OrderExpired.trader_id
    ts_event: OrderExpired.ts_event
    ts_init: OrderExpired.ts_init
    venue_order_id: OrderExpired.venue_order_id
    def __init__(self, TraderIdtrader_id, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, VenueOrderIdvenue_order_id: VenueOrderId | None, AccountIdaccount_id: AccountId | None, UUID4event_id, uint64_tts_event, uint64_tts_init, boolreconciliation=...) -> Any: ...
    @staticmethod
    def from_dict(dictvalues) -> OrderExpired: ...
    def set_client_order_id(self, ClientOrderIdclient_order_id) -> Any: ...
    @staticmethod
    def to_dict(OrderExpiredobj) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class OrderFilled(OrderEvent):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    account_id: OrderFilled.account_id
    client_order_id: OrderFilled.client_order_id
    commission: Incomplete
    currency: Incomplete
    id: OrderFilled.id
    info: Incomplete
    instrument_id: OrderFilled.instrument_id
    is_buy: Incomplete
    is_sell: Incomplete
    last_px: Incomplete
    last_qty: Incomplete
    liquidity_side: Incomplete
    order_side: Incomplete
    order_type: Incomplete
    position_id: Incomplete
    reconciliation: OrderFilled.reconciliation
    strategy_id: OrderFilled.strategy_id
    trade_id: Incomplete
    trader_id: OrderFilled.trader_id
    ts_event: OrderFilled.ts_event
    ts_init: OrderFilled.ts_init
    venue_order_id: OrderFilled.venue_order_id
    def __init__(self, TraderIdtrader_id, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, VenueOrderIdvenue_order_id, AccountIdaccount_id, TradeIdtrade_id, PositionIdposition_id: PositionId | None, OrderSideorder_side, OrderTypeorder_type, Quantitylast_qty, Pricelast_px, Currencycurrency, Moneycommission, LiquiditySideliquidity_side, UUID4event_id, uint64_tts_event, uint64_tts_init, boolreconciliation=..., dictinfo=...) -> Any: ...
    @staticmethod
    def from_dict(dictvalues) -> OrderFilled: ...
    def set_client_order_id(self, ClientOrderIdclient_order_id) -> Any: ...
    @staticmethod
    def to_dict(OrderFilledobj) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class OrderInitialized(OrderEvent):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    account_id: OrderInitialized.account_id
    client_order_id: OrderInitialized.client_order_id
    contingency_type: Incomplete
    emulation_trigger: Incomplete
    exec_algorithm_id: Incomplete
    exec_algorithm_params: Incomplete
    exec_spawn_id: Incomplete
    id: OrderInitialized.id
    instrument_id: OrderInitialized.instrument_id
    linked_order_ids: Incomplete
    options: Incomplete
    order_list_id: Incomplete
    order_type: Incomplete
    parent_order_id: Incomplete
    post_only: Incomplete
    quantity: Incomplete
    quote_quantity: Incomplete
    reconciliation: OrderInitialized.reconciliation
    reduce_only: Incomplete
    side: Incomplete
    strategy_id: OrderInitialized.strategy_id
    tags: Incomplete
    time_in_force: Incomplete
    trader_id: OrderInitialized.trader_id
    trigger_instrument_id: Incomplete
    ts_event: OrderInitialized.ts_event
    ts_init: OrderInitialized.ts_init
    venue_order_id: OrderInitialized.venue_order_id
    def __init__(self, TraderIdtrader_id, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, OrderSideorder_side, OrderTypeorder_type, Quantityquantity, TimeInForcetime_in_force, boolpost_only, boolreduce_only, boolquote_quantity, dictoptions, TriggerTypeemulation_trigger, InstrumentIdtrigger_instrument_id: InstrumentId | None, ContingencyTypecontingency_type, OrderListIdorder_list_id: OrderListId | None, listlinked_order_ids: list[ClientOrderId] | None, ClientOrderIdparent_order_id: ClientOrderId | None, ExecAlgorithmIdexec_algorithm_id: ExecAlgorithmId | None, dictexec_algorithm_params: dict[str, object] | None, ClientOrderIdexec_spawn_id: ClientOrderId | None, listtags: list[str] | None, UUID4event_id, uint64_tts_init, boolreconciliation=...) -> Any: ...
    @staticmethod
    def from_dict(dictvalues) -> OrderInitialized: ...
    def set_client_order_id(self, ClientOrderIdclient_order_id) -> Any: ...
    @staticmethod
    def to_dict(OrderInitializedobj) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class OrderModifyRejected(OrderEvent):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    account_id: OrderModifyRejected.account_id
    client_order_id: OrderModifyRejected.client_order_id
    id: OrderModifyRejected.id
    instrument_id: OrderModifyRejected.instrument_id
    reason: OrderModifyRejected.reason
    reconciliation: OrderModifyRejected.reconciliation
    strategy_id: OrderModifyRejected.strategy_id
    trader_id: OrderModifyRejected.trader_id
    ts_event: OrderModifyRejected.ts_event
    ts_init: OrderModifyRejected.ts_init
    venue_order_id: OrderModifyRejected.venue_order_id
    def __init__(self, TraderIdtrader_id, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, VenueOrderIdvenue_order_id: VenueOrderId | None, AccountIdaccount_id: AccountId | None, strreason, UUID4event_id, uint64_tts_event, uint64_tts_init, boolreconciliation=...) -> Any: ...
    @staticmethod
    def from_dict(dictvalues) -> OrderModifyRejected: ...
    def set_client_order_id(self, ClientOrderIdclient_order_id) -> Any: ...
    @staticmethod
    def to_dict(OrderModifyRejectedobj) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class OrderPendingCancel(OrderEvent):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    account_id: OrderPendingCancel.account_id
    client_order_id: OrderPendingCancel.client_order_id
    id: OrderPendingCancel.id
    instrument_id: OrderPendingCancel.instrument_id
    reconciliation: OrderPendingCancel.reconciliation
    strategy_id: OrderPendingCancel.strategy_id
    trader_id: OrderPendingCancel.trader_id
    ts_event: OrderPendingCancel.ts_event
    ts_init: OrderPendingCancel.ts_init
    venue_order_id: OrderPendingCancel.venue_order_id
    def __init__(self, TraderIdtrader_id, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, VenueOrderIdvenue_order_id: VenueOrderId | None, AccountIdaccount_id: AccountId | None, UUID4event_id, uint64_tts_event, uint64_tts_init, boolreconciliation=...) -> Any: ...
    @staticmethod
    def from_dict(dictvalues) -> OrderPendingCancel: ...
    def set_client_order_id(self, ClientOrderIdclient_order_id) -> Any: ...
    @staticmethod
    def to_dict(OrderPendingCancelobj) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class OrderPendingUpdate(OrderEvent):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    account_id: OrderPendingUpdate.account_id
    client_order_id: OrderPendingUpdate.client_order_id
    id: OrderPendingUpdate.id
    instrument_id: OrderPendingUpdate.instrument_id
    reconciliation: OrderPendingUpdate.reconciliation
    strategy_id: OrderPendingUpdate.strategy_id
    trader_id: OrderPendingUpdate.trader_id
    ts_event: OrderPendingUpdate.ts_event
    ts_init: OrderPendingUpdate.ts_init
    venue_order_id: OrderPendingUpdate.venue_order_id
    def __init__(self, TraderIdtrader_id, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, VenueOrderIdvenue_order_id: VenueOrderId | None, AccountIdaccount_id: AccountId | None, UUID4event_id, uint64_tts_event, uint64_tts_init, boolreconciliation=...) -> Any: ...
    @staticmethod
    def from_dict(dictvalues) -> OrderPendingUpdate: ...
    def set_client_order_id(self, ClientOrderIdclient_order_id) -> Any: ...
    @staticmethod
    def to_dict(OrderPendingUpdateobj) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class OrderRejected(OrderEvent):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    account_id: OrderRejected.account_id
    client_order_id: OrderRejected.client_order_id
    due_post_only: OrderRejected.due_post_only
    id: OrderRejected.id
    instrument_id: OrderRejected.instrument_id
    reason: OrderRejected.reason
    reconciliation: OrderRejected.reconciliation
    strategy_id: OrderRejected.strategy_id
    trader_id: OrderRejected.trader_id
    ts_event: OrderRejected.ts_event
    ts_init: OrderRejected.ts_init
    venue_order_id: OrderRejected.venue_order_id
    def __init__(self, TraderIdtrader_id, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, AccountIdaccount_id, strreason, UUID4event_id, uint64_tts_event, uint64_tts_init, boolreconciliation=..., booldue_post_only=...) -> Any: ...
    @staticmethod
    def from_dict(dictvalues) -> OrderRejected: ...
    def set_client_order_id(self, ClientOrderIdclient_order_id) -> Any: ...
    @staticmethod
    def to_dict(OrderRejectedobj) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...

class OrderReleased(OrderEvent):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    account_id: OrderReleased.account_id
    client_order_id: OrderReleased.client_order_id
    id: OrderReleased.id
    instrument_id: OrderReleased.instrument_id
    reconciliation: OrderReleased.reconciliation
    released_price: OrderReleased.released_price
    strategy_id: OrderReleased.strategy_id
    trader_id: OrderReleased.trader_id
    ts_event: OrderReleased.ts_event
    ts_init: OrderReleased.ts_init
    venue_order_id: OrderReleased.venue_order_id
    def __init__(self, TraderIdtrader_id, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, Pricereleased_price, UUID4event_id, uint64_tts_init) -> Any: ...
    @staticmethod
    def from_dict(dictvalues) -> OrderReleased: ...
    def set_client_order_id(self, ClientOrderIdclient_order_id) -> Any: ...
    @staticmethod
    def to_dict(OrderReleasedobj) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...

class OrderSubmitted(OrderEvent):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    account_id: OrderSubmitted.account_id
    client_order_id: OrderSubmitted.client_order_id
    id: OrderSubmitted.id
    instrument_id: OrderSubmitted.instrument_id
    reconciliation: OrderSubmitted.reconciliation
    strategy_id: OrderSubmitted.strategy_id
    trader_id: OrderSubmitted.trader_id
    ts_event: OrderSubmitted.ts_event
    ts_init: OrderSubmitted.ts_init
    venue_order_id: OrderSubmitted.venue_order_id
    def __init__(self, TraderIdtrader_id, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, AccountIdaccount_id, UUID4event_id, uint64_tts_event, uint64_tts_init) -> Any: ...
    @staticmethod
    def from_dict(dictvalues) -> OrderSubmitted: ...
    def set_client_order_id(self, ClientOrderIdclient_order_id) -> Any: ...
    @staticmethod
    def to_dict(OrderSubmittedobj) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...

class OrderTriggered(OrderEvent):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    account_id: OrderTriggered.account_id
    client_order_id: OrderTriggered.client_order_id
    id: OrderTriggered.id
    instrument_id: OrderTriggered.instrument_id
    reconciliation: OrderTriggered.reconciliation
    strategy_id: OrderTriggered.strategy_id
    trader_id: OrderTriggered.trader_id
    ts_event: OrderTriggered.ts_event
    ts_init: OrderTriggered.ts_init
    venue_order_id: OrderTriggered.venue_order_id
    def __init__(self, TraderIdtrader_id, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, VenueOrderIdvenue_order_id: VenueOrderId | None, AccountIdaccount_id: AccountId | None, UUID4event_id, uint64_tts_event, uint64_tts_init, boolreconciliation=...) -> Any: ...
    @staticmethod
    def from_dict(dictvalues) -> OrderTriggered: ...
    def set_client_order_id(self, ClientOrderIdclient_order_id) -> Any: ...
    @staticmethod
    def to_dict(OrderTriggeredobj) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class OrderUpdated(OrderEvent):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    account_id: OrderUpdated.account_id
    client_order_id: OrderUpdated.client_order_id
    id: OrderUpdated.id
    instrument_id: OrderUpdated.instrument_id
    is_quote_quantity: Incomplete
    price: Incomplete
    quantity: Incomplete
    reconciliation: OrderUpdated.reconciliation
    strategy_id: OrderUpdated.strategy_id
    trader_id: OrderUpdated.trader_id
    trigger_price: Incomplete
    ts_event: OrderUpdated.ts_event
    ts_init: OrderUpdated.ts_init
    venue_order_id: OrderUpdated.venue_order_id
    def __init__(self, TraderIdtrader_id, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, VenueOrderIdvenue_order_id: VenueOrderId | None, AccountIdaccount_id: AccountId | None, Quantityquantity, Priceprice: Price | None, Pricetrigger_price: Price | None, UUID4event_id, uint64_tts_event, uint64_tts_init, boolreconciliation=..., boolis_quote_quantity=...) -> Any: ...
    @staticmethod
    def from_dict(dictvalues) -> OrderUpdated: ...
    def set_client_order_id(self, ClientOrderIdclient_order_id) -> Any: ...
    @staticmethod
    def to_dict(OrderUpdatedobj) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
