import nautilus_trader.core.message
from _typeshed import Incomplete
from typing import Any, ClassVar

__test__: dict

class PositionAdjusted(nautilus_trader.core.message.Event):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    account_id: Incomplete
    adjustment_type: Incomplete
    id: PositionAdjusted.id
    instrument_id: Incomplete
    pnl_change: Incomplete
    position_id: Incomplete
    quantity_change: Incomplete
    reason: Incomplete
    strategy_id: Incomplete
    trader_id: Incomplete
    ts_event: PositionAdjusted.ts_event
    ts_init: PositionAdjusted.ts_init
    def __init__(self, TraderIdtrader_id, StrategyIdstrategy_id, InstrumentIdinstrument_id, PositionIdposition_id, AccountIdaccount_id, PositionAdjustmentTypeadjustment_type, quantity_change, Moneypnl_change: Money | None, strreason: str | None, UUID4event_id, uint64_tts_event, uint64_tts_init) -> None: ...
    @staticmethod
    def from_dict(dictvalues) -> PositionAdjusted: ...
    @staticmethod
    def to_dict(PositionAdjustedobj) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class PositionChanged(PositionEvent):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, TraderIdtrader_id, StrategyIdstrategy_id, InstrumentIdinstrument_id, PositionIdposition_id, AccountIdaccount_id, ClientOrderIdopening_order_id, OrderSideentry, PositionSideside, doublesigned_qty, Quantityquantity, Quantitypeak_qty, Quantitylast_qty, Pricelast_px, Currencycurrency, doubleavg_px_open, doubleavg_px_close, doublerealized_return, Moneyrealized_pnl, Moneyunrealized_pnl, UUID4event_id, uint64_tts_opened, uint64_tts_event, uint64_tts_init) -> Any: ...
    @staticmethod
    def create(Positionposition, OrderFilledfill, UUID4event_id, uint64_tts_init) -> Any: ...
    @staticmethod
    def from_dict(dictvalues) -> PositionChanged: ...
    @staticmethod
    def to_dict(PositionChangedobj) -> Any: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class PositionClosed(PositionEvent):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, TraderIdtrader_id, StrategyIdstrategy_id, InstrumentIdinstrument_id, PositionIdposition_id, AccountIdaccount_id, ClientOrderIdopening_order_id, ClientOrderIdclosing_order_id, OrderSideentry, PositionSideside, doublesigned_qty, Quantityquantity, Quantitypeak_qty, Quantitylast_qty, Pricelast_px, Currencycurrency, doubleavg_px_open, doubleavg_px_close, doublerealized_return, Moneyrealized_pnl, UUID4event_id, uint64_tts_opened, uint64_tts_closed, uint64_tduration_ns, uint64_tts_init) -> Any: ...
    @staticmethod
    def create(Positionposition, OrderFilledfill, UUID4event_id, uint64_tts_init) -> Any: ...
    @staticmethod
    def from_dict(dictvalues) -> PositionClosed: ...
    @staticmethod
    def to_dict(PositionClosedobj) -> Any: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class PositionEvent(nautilus_trader.core.message.Event):
    account_id: Incomplete
    avg_px_close: Incomplete
    avg_px_open: Incomplete
    closing_order_id: Incomplete
    currency: Incomplete
    duration_ns: Incomplete
    entry: Incomplete
    id: PositionEvent.id
    instrument_id: Incomplete
    last_px: Incomplete
    last_qty: Incomplete
    opening_order_id: Incomplete
    peak_qty: Incomplete
    position_id: Incomplete
    quantity: Incomplete
    realized_pnl: Incomplete
    realized_return: Incomplete
    side: Incomplete
    signed_qty: Incomplete
    strategy_id: Incomplete
    trader_id: Incomplete
    ts_closed: Incomplete
    ts_event: PositionEvent.ts_event
    ts_init: PositionEvent.ts_init
    ts_opened: Incomplete
    unrealized_pnl: Incomplete
    def __init__(self, TraderIdtrader_id, StrategyIdstrategy_id, InstrumentIdinstrument_id, PositionIdposition_id, AccountIdaccount_id, ClientOrderIdopening_order_id, ClientOrderIdclosing_order_id: ClientOrderId | None, OrderSideentry, PositionSideside, doublesigned_qty, Quantityquantity, Quantitypeak_qty, Quantitylast_qty, Pricelast_px, Currencycurrency, doubleavg_px_open, doubleavg_px_close, doublerealized_return, Moneyrealized_pnl, Moneyunrealized_pnl, UUID4event_id, uint64_tts_opened, uint64_tts_closed, uint64_tduration_ns, uint64_tts_event, uint64_tts_init) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class PositionOpened(PositionEvent):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, TraderIdtrader_id, StrategyIdstrategy_id, InstrumentIdinstrument_id, PositionIdposition_id, AccountIdaccount_id, ClientOrderIdopening_order_id, OrderSideentry, PositionSideside, doublesigned_qty, Quantityquantity, Quantitypeak_qty, Quantitylast_qty, Pricelast_px, Currencycurrency, doubleavg_px_open, Moneyrealized_pnl, UUID4event_id, uint64_tts_event, uint64_tts_init) -> Any: ...
    @staticmethod
    def create(Positionposition, OrderFilledfill, UUID4event_id, uint64_tts_init) -> Any: ...
    @staticmethod
    def from_dict(dictvalues) -> PositionOpened: ...
    @staticmethod
    def to_dict(PositionOpenedobj) -> Any: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
