from nautilus_trader.common.config import NautilusConfig as NautilusConfig

class RiskEngineConfig(NautilusConfig, frozen=True):
    bypass: bool = ...
    max_order_submit_rate: str = ...
    max_order_modify_rate: str = ...
    max_notional_per_order: dict[str, int] = ...
    debug: bool = ...
