import nautilus_trader.common.component
from _typeshed import Incomplete
from nautilus_trader.risk.config import RiskEngineConfig as RiskEngineConfig
from typing import Any, ClassVar

__test__: dict

class RiskEngine(nautilus_trader.common.component.Component):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    command_count: Incomplete
    debug: Incomplete
    event_count: Incomplete
    is_bypassed: Incomplete
    trading_state: Incomplete
    def __init__(self, PortfolioFacadeportfolio, MessageBusmsgbus, Cachecache, Clockclock, config: RiskEngineConfig | None = ...) -> None: ...
    def execute(self, Commandcommand) -> void: ...
    def max_notional_per_order(self, InstrumentIdinstrument_id) -> Any: ...
    def max_notionals_per_order(self) -> dict: ...
    def max_order_modify_rate(self) -> tuple: ...
    def max_order_submit_rate(self) -> tuple: ...
    def process(self, Eventevent) -> void: ...
    def set_max_notional_per_order(self, InstrumentIdinstrument_id, new_value) -> void: ...
    def set_trading_state(self, TradingStatestate) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
