from _typeshed import Incomplete
from decimal import Decimal
from typing import Any, ClassVar

__test__: dict

class FixedRiskSizer(PositionSizer):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, Instrumentinstrument) -> Any: ...
    def calculate(self, Priceentry, Pricestop_loss, Moneyequity, risk: Decimal, commission_rate: Decimal = ..., exchange_rate: Decimal = ..., hard_limit: Decimal | None = ..., unit_batch_size: Decimal = ..., intunits=...) -> Quantity: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class PositionSizer:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    instrument: Incomplete
    def __init__(self, Instrumentinstrument) -> Any: ...
    def calculate(self, Priceentry, Pricestop_loss, Moneyequity, risk: Decimal, commission_rate: Decimal = ..., exchange_rate: Decimal = ..., hard_limit: Decimal | None = ..., unit_batch_size: Decimal = ..., intunits=...) -> Quantity: ...
    def update_instrument(self, Instrumentinstrument) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
