from _typeshed import Incomplete
from typing import Any, ClassVar

__test__: dict

class PortfolioFacade:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    analyzer: Incomplete
    initialized: Incomplete
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def account(self, Venuevenue=..., AccountIdaccount_id=...) -> Account: ...
    def balances_locked(self, Venuevenue=..., AccountIdaccount_id=...) -> dict: ...
    def equity(self, Venuevenue=..., AccountIdaccount_id=...) -> dict: ...
    def is_completely_flat(self, AccountIdaccount_id=...) -> bool: ...
    def is_flat(self, InstrumentIdinstrument_id, AccountIdaccount_id=...) -> bool: ...
    def is_net_long(self, InstrumentIdinstrument_id, AccountIdaccount_id=...) -> bool: ...
    def is_net_short(self, InstrumentIdinstrument_id, AccountIdaccount_id=...) -> bool: ...
    def margins_init(self, Venuevenue=..., AccountIdaccount_id=...) -> dict: ...
    def margins_maint(self, Venuevenue=..., AccountIdaccount_id=...) -> dict: ...
    def mark_values(self, Venuevenue=..., AccountIdaccount_id=...) -> dict: ...
    def missing_price_instruments(self, Venuevenue) -> list: ...
    def net_exposure(self, InstrumentIdinstrument_id, Priceprice=..., AccountIdaccount_id=..., Currencytarget_currency=...) -> Money: ...
    def net_exposures(self, Venuevenue=..., AccountIdaccount_id=..., Currencytarget_currency=...) -> dict: ...
    def net_position(self, InstrumentIdinstrument_id, AccountIdaccount_id=...) -> Any: ...
    def realized_pnl(self, InstrumentIdinstrument_id, AccountIdaccount_id=..., Currencytarget_currency=...) -> Money: ...
    def realized_pnls(self, Venuevenue=..., AccountIdaccount_id=..., Currencytarget_currency=...) -> dict: ...
    def total_pnl(self, InstrumentIdinstrument_id, Priceprice=..., AccountIdaccount_id=..., Currencytarget_currency=...) -> Money: ...
    def total_pnls(self, Venuevenue=..., AccountIdaccount_id=..., Currencytarget_currency=...) -> dict: ...
    def unrealized_pnl(self, InstrumentIdinstrument_id, Priceprice=..., AccountIdaccount_id=..., Currencytarget_currency=...) -> Money: ...
    def unrealized_pnls(self, Venuevenue=..., AccountIdaccount_id=..., Currencytarget_currency=...) -> dict: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
