from nautilus_trader.common.config import NautilusConfig as NautilusConfig, PositiveInt as PositiveInt

class PortfolioConfig(NautilusConfig, frozen=True):
    use_mark_prices: bool = ...
    use_mark_xrates: bool = ...
    bar_updates: bool = ...
    convert_to_account_base_currency: bool = ...
    min_account_state_logging_interval_ms: PositiveInt | None = ...
    snapshot_interval_ms: PositiveInt | None = ...
    debug: bool = ...
