import nautilus_trader.portfolio.base
from nautilus_trader.analysis.analyzer import PortfolioAnalyzer as PortfolioAnalyzer
from nautilus_trader.core.nautilus_pyo3.analysis import AvgLoser as AvgLoser, AvgWinner as AvgWinner, Expectancy as Expectancy, LongRatio as LongRatio, MaxLoser as MaxLoser, MaxWinner as MaxWinner, MinLoser as MinLoser, MinWinner as MinWinner, ProfitFactor as ProfitFactor, ReturnsAverage as ReturnsAverage, ReturnsAverageLoss as ReturnsAverageLoss, ReturnsAverageWin as ReturnsAverageWin, ReturnsVolatility as ReturnsVolatility, RiskReturnRatio as RiskReturnRatio, SharpeRatio as SharpeRatio, SortinoRatio as SortinoRatio, WinRate as WinRate
from nautilus_trader.portfolio.config import PortfolioConfig as PortfolioConfig
from typing import Any, ClassVar

__test__: dict

class Portfolio(nautilus_trader.portfolio.base.PortfolioFacade):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, MessageBusmsgbus, CacheFacadecache, Clockclock, config: PortfolioConfig | None = ...) -> None: ...
    def account(self, Venuevenue=..., AccountIdaccount_id=...) -> Account: ...
    def balances_locked(self, Venuevenue=..., AccountIdaccount_id=...) -> dict: ...
    def dispose(self) -> None: ...
    def equity(self, Venuevenue=..., AccountIdaccount_id=...) -> dict: ...
    def initialize_orders(self) -> void: ...
    def initialize_positions(self) -> void: ...
    def is_completely_flat(self, AccountIdaccount_id=...) -> bool: ...
    def is_flat(self, InstrumentIdinstrument_id, AccountIdaccount_id=...) -> bool: ...
    def is_net_long(self, InstrumentIdinstrument_id, AccountIdaccount_id=...) -> bool: ...
    def is_net_short(self, InstrumentIdinstrument_id, AccountIdaccount_id=...) -> bool: ...
    def margins_init(self, Venuevenue=..., AccountIdaccount_id=...) -> dict: ...
    def margins_maint(self, Venuevenue=..., AccountIdaccount_id=...) -> dict: ...
    def mark_values(self, Venuevenue=..., AccountIdaccount_id=...) -> dict: ...
    def missing_price_instruments(self, Venuevenue) -> list: ...
    def net_exposure(self, InstrumentIdinstrument_id, Priceprice=..., AccountIdaccount_id=..., Currencytarget_currency=...) -> Money: ...
    def net_exposures(self, Venuevenue=..., AccountIdaccount_id=..., Currencytarget_currency=...) -> dict: ...
    def net_position(self, InstrumentIdinstrument_id, AccountIdaccount_id=...) -> Any: ...
    def on_order_event(self, OrderEventevent) -> void: ...
    def on_position_event(self, PositionEventevent) -> void: ...
    def realized_pnl(self, InstrumentIdinstrument_id, AccountIdaccount_id=..., Currencytarget_currency=...) -> Money: ...
    def realized_pnls(self, Venuevenue=..., AccountIdaccount_id=..., Currencytarget_currency=...) -> dict: ...
    def reset(self) -> None: ...
    def set_use_mark_prices(self, boolvalue) -> void: ...
    def set_use_mark_xrates(self, boolvalue) -> void: ...
    def total_pnl(self, InstrumentIdinstrument_id, Priceprice=..., AccountIdaccount_id=..., Currencytarget_currency=...) -> Money: ...
    def total_pnls(self, Venuevenue=..., AccountIdaccount_id=..., Currencytarget_currency=...) -> dict: ...
    def unrealized_pnl(self, InstrumentIdinstrument_id, Priceprice=..., AccountIdaccount_id=..., Currencytarget_currency=...) -> Money: ...
    def unrealized_pnls(self, Venuevenue=..., AccountIdaccount_id=..., Currencytarget_currency=...) -> dict: ...
    def update_account(self, AccountStateevent) -> void: ...
    def update_bar(self, Barbar) -> void: ...
    def update_mark_price(self, mark_price) -> void: ...
    def update_order(self, OrderEventevent) -> void: ...
    def update_position(self, PositionEventevent) -> void: ...
    def update_quote_tick(self, QuoteTicktick) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
