import msgspec
from nautilus_trader.adapters.binance.common.enums import BinanceAccountType as BinanceAccountType, BinanceNewOrderRespType as BinanceNewOrderRespType, BinanceOrderSide as BinanceOrderSide, BinanceSecurityType as BinanceSecurityType, BinanceTimeInForce as BinanceTimeInForce
from nautilus_trader.adapters.binance.common.schemas.market import BinanceRateLimit as BinanceRateLimit
from nautilus_trader.adapters.binance.common.symbol import BinanceSymbol as BinanceSymbol
from nautilus_trader.adapters.binance.http.account import BinanceAccountHttpAPI as BinanceAccountHttpAPI, BinanceOpenOrdersHttp as BinanceOpenOrdersHttp
from nautilus_trader.adapters.binance.http.client import BinanceHttpClient as BinanceHttpClient
from nautilus_trader.adapters.binance.http.endpoint import BinanceHttpEndpoint as BinanceHttpEndpoint
from nautilus_trader.adapters.binance.spot.schemas.account import BinanceSpotAccountInfo as BinanceSpotAccountInfo, BinanceSpotOrderOco as BinanceSpotOrderOco
from nautilus_trader.common.component import LiveClock as LiveClock
from nautilus_trader.core.nautilus_pyo3 import HttpMethod as HttpMethod

class BinanceSpotOpenOrdersHttp(BinanceOpenOrdersHttp):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class DeleteParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        timestamp: str
        symbol: BinanceSymbol
        recvWindow: str | None = ...

class BinanceSpotOrderOcoHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class PostParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        symbol: BinanceSymbol
        timestamp: str
        side: BinanceOrderSide
        quantity: str
        price: str
        stopPrice: str
        listClientOrderId: str | None = ...
        limitClientOrderId: str | None = ...
        limitStrategyId: int | None = ...
        limitStrategyType: int | None = ...
        limitIcebergQty: str | None = ...
        trailingDelta: str | None = ...
        stopClientOrderId: str | None = ...
        stopStrategyId: int | None = ...
        stopStrategyType: int | None = ...
        stopLimitPrice: str | None = ...
        stopIcebergQty: str | None = ...
        stopLimitTimeInForce: BinanceTimeInForce | None = ...
        newOrderRespType: BinanceNewOrderRespType | None = ...
        recvWindow: str | None = ...

class BinanceSpotOrderListHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class GetParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        timestamp: str
        orderListId: str | None = ...
        origClientOrderId: str | None = ...
        recvWindow: str | None = ...
    class DeleteParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        timestamp: str
        symbol: BinanceSymbol
        orderListId: str | None = ...
        listClientOrderId: str | None = ...
        newClientOrderId: str | None = ...
        recvWindow: str | None = ...
    async def get(self, params: GetParameters) -> BinanceSpotOrderOco: ...
    async def delete(self, params: DeleteParameters) -> BinanceSpotOrderOco: ...

class BinanceSpotAllOrderListHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class GetParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        timestamp: str
        fromId: int | None = ...
        startTime: int | None = ...
        endTime: int | None = ...
        limit: int | None = ...
        recvWindow: str | None = ...
    async def get(self, params: GetParameters) -> list[BinanceSpotOrderOco]: ...

class BinanceSpotOpenOrderListHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class GetParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        timestamp: str
        recvWindow: str | None = ...
    async def get(self, params: GetParameters) -> list[BinanceSpotOrderOco]: ...

class BinanceSpotAccountHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class GetParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        timestamp: str
        recvWindow: str | None = ...
    async def get(self, params: GetParameters) -> BinanceSpotAccountInfo: ...

class BinanceSpotOrderRateLimitHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class GetParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        timestamp: str
        recvWindow: str | None = ...
    async def get(self, params: GetParameters) -> list[BinanceRateLimit]: ...

class BinanceSpotAccountHttpAPI(BinanceAccountHttpAPI):
    def __init__(self, client: BinanceHttpClient, clock: LiveClock, account_type: BinanceAccountType = ...) -> None: ...
    async def new_spot_oco(self, symbol: str, side: BinanceOrderSide, quantity: str, price: str, stop_price: str, list_client_order_id: str | None = None, limit_client_order_id: str | None = None, limit_strategy_id: int | None = None, limit_strategy_type: int | None = None, limit_iceberg_qty: str | None = None, trailing_delta: str | None = None, stop_client_order_id: str | None = None, stop_strategy_id: int | None = None, stop_strategy_type: int | None = None, stop_limit_price: str | None = None, stop_iceberg_qty: str | None = None, stop_limit_time_in_force: BinanceTimeInForce | None = None, new_order_resp_type: BinanceNewOrderRespType | None = None, recv_window: str | None = None) -> BinanceSpotOrderOco: ...
    async def query_spot_oco(self, order_list_id: str | None = None, orig_client_order_id: str | None = None, recv_window: str | None = None) -> BinanceSpotOrderOco: ...
    async def cancel_all_open_orders(self, symbol: str, recv_window: str | None = None) -> bool: ...
    async def cancel_spot_oco(self, symbol: str, order_list_id: str | None = None, list_client_order_id: str | None = None, new_client_order_id: str | None = None, recv_window: str | None = None) -> BinanceSpotOrderOco: ...
    async def query_spot_all_oco(self, from_id: int | None = None, start_time: int | None = None, end_time: int | None = None, limit: int | None = None, recv_window: str | None = None) -> list[BinanceSpotOrderOco]: ...
    async def query_spot_all_open_oco(self, recv_window: str | None = None) -> list[BinanceSpotOrderOco]: ...
    async def query_spot_account_info(self, recv_window: str | None = None) -> BinanceSpotAccountInfo: ...
    async def query_spot_order_rate_limit(self, recv_window: str | None = None) -> list[BinanceRateLimit]: ...
