import msgspec
from nautilus_trader.adapters.binance.common.enums import BinanceAccountType as BinanceAccountType, BinanceSecurityType as BinanceSecurityType
from nautilus_trader.adapters.binance.common.symbol import BinanceSymbol as BinanceSymbol, BinanceSymbols as BinanceSymbols
from nautilus_trader.adapters.binance.http.client import BinanceHttpClient as BinanceHttpClient
from nautilus_trader.adapters.binance.http.endpoint import BinanceHttpEndpoint as BinanceHttpEndpoint
from nautilus_trader.adapters.binance.http.market import BinanceMarketHttpAPI as BinanceMarketHttpAPI
from nautilus_trader.adapters.binance.spot.enums import BinanceSpotPermissions as BinanceSpotPermissions
from nautilus_trader.adapters.binance.spot.schemas.market import BinanceSpotAvgPrice as BinanceSpotAvgPrice, BinanceSpotExchangeInfo as BinanceSpotExchangeInfo
from nautilus_trader.core.nautilus_pyo3 import HttpMethod as HttpMethod

class BinanceSpotExchangeInfoHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class GetParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        symbol: BinanceSymbol | None = ...
        symbols: BinanceSymbols | None = ...
        permissions: BinanceSpotPermissions | None = ...
    async def get(self, params: GetParameters | None = None) -> BinanceSpotExchangeInfo: ...

class BinanceSpotAvgPriceHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class GetParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        symbol: BinanceSymbol = ...
    async def get(self, params: GetParameters) -> BinanceSpotAvgPrice: ...

class BinanceSpotMarketHttpAPI(BinanceMarketHttpAPI):
    def __init__(self, client: BinanceHttpClient, account_type: BinanceAccountType = ...) -> None: ...
    async def query_spot_exchange_info(self, symbol: str | None = None, symbols: list[str] | None = None, permissions: BinanceSpotPermissions | None = None) -> BinanceSpotExchangeInfo: ...
    async def query_spot_average_price(self, symbol: str) -> BinanceSpotAvgPrice: ...
