import pandas as pd
from datetime import datetime
from nautilus_trader.accounting.accounts.base import Account as Account
from nautilus_trader.analysis.statistic import PortfolioStatistic as PortfolioStatistic
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.core.datetime import unix_nanos_to_dt as unix_nanos_to_dt
from nautilus_trader.model.identifiers import PositionId as PositionId
from nautilus_trader.model.objects import Currency as Currency, Money as Money
from nautilus_trader.model.position import Position as Position
from typing import Any

class PortfolioAnalyzer:
    def __init__(self) -> None: ...
    def register_statistic(self, statistic: PortfolioStatistic) -> None: ...
    def deregister_statistic(self, statistic: PortfolioStatistic) -> None: ...
    def deregister_statistics(self) -> None: ...
    def reset(self) -> None: ...
    @property
    def currencies(self) -> list[Currency]: ...
    def statistic(self, name: str) -> PortfolioStatistic | None: ...
    def returns(self) -> pd.Series: ...
    def position_returns(self) -> pd.Series: ...
    def portfolio_returns(self) -> pd.Series: ...
    def calculate_statistics(self, account: Account, positions: list[Position]) -> None: ...
    def add_positions(self, positions: list[Position]) -> None: ...
    def add_trade(self, position_id: PositionId, realized_pnl: Money, ts_event: int | None = None) -> None: ...
    def record_trade(self, position_id: PositionId, realized_pnl: Money, ts_event: int | None = None) -> None: ...
    def add_position_return(self, timestamp: datetime, value: float) -> None: ...
    def add_return(self, timestamp: datetime, value: float) -> None: ...
    def realized_pnls(self, currency: Currency | None = None) -> pd.Series | None: ...
    def total_pnl(self, currency: Currency | None = None, unrealized_pnl: Money | None = None) -> float: ...
    def total_pnl_percentage(self, currency: Currency | None = None, unrealized_pnl: Money | None = None) -> float: ...
    def get_performance_stats_pnls(self, currency: Currency | None = None, unrealized_pnl: Money | None = None) -> dict[str, float]: ...
    def get_performance_stats_returns(self) -> dict[str, Any]: ...
    def get_performance_stats_position_returns(self) -> dict[str, Any]: ...
    def get_performance_stats_portfolio_returns(self) -> dict[str, Any]: ...
    def get_performance_stats_returns_vs_benchmark(self, benchmark_returns: pd.Series, returns: pd.Series | None = None) -> dict[str, Any]: ...
    def get_performance_stats_general(self) -> dict[str, Any]: ...
    def get_stats_pnls_formatted(self, currency: Currency | None = None, unrealized_pnl: Money | None = None) -> list[str]: ...
    def get_stats_returns_formatted(self) -> list[str]: ...
    def get_stats_position_returns_formatted(self) -> list[str]: ...
    def get_stats_portfolio_returns_formatted(self) -> list[str]: ...
    def get_stats_general_formatted(self) -> list[str]: ...
