import msgspec
from nautilus_trader.common.config import NautilusConfig as NautilusConfig, PositiveInt as PositiveInt
from typing import Any

class TearsheetChart(msgspec.Struct, frozen=True, kw_only=True):
    title: str | None = ...
    @property
    def name(self) -> str: ...
    def kwargs(self) -> dict[str, Any]: ...

class TearsheetRunInfoChart(TearsheetChart, frozen=True, kw_only=True):
    @property
    def name(self) -> str: ...

class TearsheetStatsTableChart(TearsheetChart, frozen=True, kw_only=True):
    @property
    def name(self) -> str: ...

class TearsheetEquityChart(TearsheetChart, frozen=True, kw_only=True):
    @property
    def name(self) -> str: ...

class TearsheetDrawdownChart(TearsheetChart, frozen=True, kw_only=True):
    @property
    def name(self) -> str: ...

class TearsheetMonthlyReturnsChart(TearsheetChart, frozen=True, kw_only=True):
    compounding: bool = ...
    @property
    def name(self) -> str: ...
    def kwargs(self) -> dict[str, Any]: ...

class TearsheetDistributionChart(TearsheetChart, frozen=True, kw_only=True):
    @property
    def name(self) -> str: ...

class TearsheetRollingSharpeChart(TearsheetChart, frozen=True, kw_only=True):
    @property
    def name(self) -> str: ...

class TearsheetYearlyReturnsChart(TearsheetChart, frozen=True, kw_only=True):
    compounding: bool = ...
    @property
    def name(self) -> str: ...
    def kwargs(self) -> dict[str, Any]: ...

class TearsheetBarsWithFillsChart(TearsheetChart, frozen=True, kw_only=True):
    bar_type: str
    @property
    def name(self) -> str: ...
    def kwargs(self) -> dict[str, Any]: ...

class TearsheetCustomChart(TearsheetChart, frozen=True, kw_only=True):
    chart: str
    args: dict[str, Any] = msgspec.field(default_factory=dict)
    @property
    def name(self) -> str: ...
    def kwargs(self) -> dict[str, Any]: ...

class GridLayout(msgspec.Struct, frozen=True, kw_only=True):
    rows: int = ...
    cols: int = ...
    heights: list[float] = msgspec.field(default_factory=_default_heights)
    vertical_spacing: float = ...
    horizontal_spacing: float = ...

class TearsheetConfig(NautilusConfig, frozen=True, kw_only=True):
    charts: list[TearsheetChart] = msgspec.field(default_factory=_default_charts)
    theme: str = ...
    layout: GridLayout | None = ...
    title: str = ...
    include_benchmark: bool = ...
    benchmark_name: str = ...
    height: PositiveInt = ...
    show_logo: bool = ...
    @property
    def chart_names(self) -> list[str]: ...
