import pandas as pd
from nautilus_trader.model.orders import Order as Order
from nautilus_trader.model.position import Position as Position
from typing import Any

class PortfolioStatistic:
    @classmethod
    def fully_qualified_name(cls) -> str: ...
    @property
    def name(self) -> str: ...
    def calculate_from_returns(self, returns: pd.Series) -> Any | None: ...
    def calculate_from_realized_pnls(self, realized_pnls: pd.Series) -> Any | None: ...
    def calculate_from_orders(self, orders: list[Order]) -> Any | None: ...
    def calculate_from_positions(self, positions: list[Position]) -> Any | None: ...
