import pandas as pd
import plotly.graph_objects as go
from _typeshed import Incomplete
from collections.abc import Callable as Callable
from nautilus_trader.analysis import TearsheetChart as TearsheetChart
from nautilus_trader.backtest.engine import BacktestEngine as BacktestEngine
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.core.datetime import format_optional_iso8601 as format_optional_iso8601, unix_nanos_to_iso8601 as unix_nanos_to_iso8601
from nautilus_trader.core.nautilus_pyo3 import NAUTILUS_VERSION as NAUTILUS_VERSION
from nautilus_trader.core.nautilus_pyo3.backtest import BacktestNode as BacktestNode, BacktestResult as BacktestResult
from nautilus_trader.model.data import Bar as Bar, BarType as BarType
from typing import Any

PLOTLY_AVAILABLE: bool
TRADING_DAYS_PER_YEAR: int

def register_chart(name: str, func: Callable | None = None) -> Callable | None: ...
def get_chart(name: str) -> Callable: ...
def list_charts() -> list[str]: ...
def create_tearsheet(engine: BacktestEngine | BacktestResult, output_path: str | None = 'tearsheet.html', title: str = 'NautilusTrader Backtest Results', currency=None, config=None, benchmark_returns: pd.Series | None = None, benchmark_name: str = 'Benchmark', node: BacktestNode | None = None, run_config_id: str | None = None) -> str | None: ...

class _BacktestNodeEngineView:
    cache: Incomplete
    def __init__(self, node: BacktestNode, run_config_id: str) -> None: ...
    @staticmethod
    def parse_bar_type(value: str): ...
    @staticmethod
    def bar_to_dict(bar) -> dict: ...
    def generate_fills_report(self) -> pd.DataFrame: ...

def create_tearsheet_from_stats(stats_pnls: dict[str, Any] | dict[str, dict[str, Any]], stats_returns: dict[str, Any], stats_general: dict[str, Any], returns: pd.Series, output_path: str | None = 'tearsheet.html', title: str = 'NautilusTrader Backtest Results', config=None, benchmark_returns: pd.Series | None = None, benchmark_name: str = 'Benchmark', run_info: dict[str, Any] | None = None, account_info: dict[str, Any] | None = None, engine=None) -> str | None: ...
def create_equity_curve(returns: pd.Series, output_path: str | None = None, title: str = 'Equity Curve', benchmark_returns: pd.Series | None = None, benchmark_name: str = 'Benchmark') -> go.Figure: ...
def create_drawdown_chart(returns: pd.Series, output_path: str | None = None, title: str = 'Drawdown', theme: str = 'plotly_white') -> go.Figure: ...
def create_monthly_returns_heatmap(returns: pd.Series, output_path: str | None = None, title: str | None = None, compounding: bool = True) -> go.Figure: ...
def create_returns_distribution(returns: pd.Series, output_path: str | None = None, title: str = 'Returns Distribution') -> go.Figure: ...
def create_rolling_sharpe(returns: pd.Series, window: int = 60, output_path: str | None = None, title: str = 'Rolling Sharpe Ratio (60-day)') -> go.Figure: ...
def create_yearly_returns(returns: pd.Series, output_path: str | None = None, title: str | None = None, compounding: bool = True) -> go.Figure: ...
def create_bars_with_fills(engine: BacktestEngine, bar_type: BarType, title: str | None = None, theme: str = 'plotly_white', output_path: str | None = None) -> go.Figure: ...
