from nautilus_trader.core.correctness import PyCondition as PyCondition
from typing import Any

def get_theme(name: str) -> dict[str, Any]: ...
def register_theme(name: str, template: str, colors: dict[str, str]) -> None: ...
def list_themes() -> list[str]: ...
