from nautilus_trader.cache.config import CacheConfig as CacheConfig
from nautilus_trader.common import Environment as Environment
from nautilus_trader.common.config import ImportableActorConfig as ImportableActorConfig, LoggingConfig as LoggingConfig, MessageBusConfig as MessageBusConfig, NautilusConfig as NautilusConfig, OrderEmulatorConfig as OrderEmulatorConfig, PositiveFloat as PositiveFloat
from nautilus_trader.core.uuid import UUID4 as UUID4
from nautilus_trader.data.config import DataEngineConfig as DataEngineConfig
from nautilus_trader.execution.config import ExecEngineConfig as ExecEngineConfig, ImportableExecAlgorithmConfig as ImportableExecAlgorithmConfig
from nautilus_trader.model.identifiers import TraderId as TraderId
from nautilus_trader.persistence.config import DataCatalogConfig as DataCatalogConfig, StreamingConfig as StreamingConfig
from nautilus_trader.portfolio.config import PortfolioConfig as PortfolioConfig
from nautilus_trader.risk.config import RiskEngineConfig as RiskEngineConfig
from nautilus_trader.trading.config import ImportableControllerConfig as ImportableControllerConfig
from nautilus_trader.trading.strategy import ImportableStrategyConfig as ImportableStrategyConfig

class NautilusKernelConfig(NautilusConfig, frozen=True):
    environment: Environment
    trader_id: TraderId
    instance_id: UUID4 | None = ...
    cache: CacheConfig | None = ...
    message_bus: MessageBusConfig | None = ...
    data_engine: DataEngineConfig | None = ...
    risk_engine: RiskEngineConfig | None = ...
    exec_engine: ExecEngineConfig | None = ...
    portfolio: PortfolioConfig | None = ...
    emulator: OrderEmulatorConfig | None = ...
    streaming: StreamingConfig | None = ...
    catalogs: list[DataCatalogConfig] = ...
    actors: list[ImportableActorConfig] = ...
    strategies: list[ImportableStrategyConfig] = ...
    exec_algorithms: list[ImportableExecAlgorithmConfig] = ...
    controller: ImportableControllerConfig | None = ...
    load_state: bool = ...
    save_state: bool = ...
    loop_debug: bool = ...
    logging: LoggingConfig | None = ...
    timeout_connection: PositiveFloat = ...
    timeout_reconciliation: PositiveFloat = ...
    timeout_portfolio: PositiveFloat = ...
    timeout_disconnection: PositiveFloat = ...
    timeout_post_stop: PositiveFloat = ...
    timeout_shutdown: PositiveFloat = ...
