import asyncio
from collections.abc import Callable as Callable
from concurrent.futures import ThreadPoolExecutor
from nautilus_trader.cache.base import CacheFacade as CacheFacade
from nautilus_trader.cache.cache import Cache as Cache
from nautilus_trader.cache.database import CacheDatabaseAdapter as CacheDatabaseAdapter
from nautilus_trader.common import Environment as Environment
from nautilus_trader.common.actor import Actor as Actor
from nautilus_trader.common.component import Clock as Clock, LiveClock as LiveClock, LogGuard as LogGuard, Logger as Logger, MessageBus as MessageBus, TestClock as TestClock, init_logging as init_logging, is_backtest_force_stop as is_backtest_force_stop, is_logging_initialized as is_logging_initialized, log_header as log_header, register_component_clock as register_component_clock, set_backtest_force_stop as set_backtest_force_stop, set_logging_pyo3 as set_logging_pyo3
from nautilus_trader.common.config import InvalidConfiguration as InvalidConfiguration, pyo3_config_json as pyo3_config_json
from nautilus_trader.common.enums import LogColor as LogColor, LogLevel as LogLevel, log_level_from_str as log_level_from_str
from nautilus_trader.common.messages import ShutdownSystem as ShutdownSystem
from nautilus_trader.config import ActorFactory as ActorFactory, ControllerFactory as ControllerFactory, DataEngineConfig as DataEngineConfig, ExecAlgorithmFactory as ExecAlgorithmFactory, ExecEngineConfig as ExecEngineConfig, LiveDataEngineConfig as LiveDataEngineConfig, LiveExecEngineConfig as LiveExecEngineConfig, LiveRiskEngineConfig as LiveRiskEngineConfig, LoggingConfig as LoggingConfig, NautilusKernelConfig as NautilusKernelConfig, RiskEngineConfig as RiskEngineConfig, StrategyFactory as StrategyFactory, StreamingConfig as StreamingConfig
from nautilus_trader.core import nautilus_pyo3 as nautilus_pyo3
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.core.datetime import nanos_to_millis as nanos_to_millis
from nautilus_trader.core.uuid import UUID4 as UUID4
from nautilus_trader.data.engine import DataEngine as DataEngine
from nautilus_trader.execution.algorithm import ExecAlgorithm as ExecAlgorithm
from nautilus_trader.execution.emulator import OrderEmulator as OrderEmulator
from nautilus_trader.execution.engine import ExecutionEngine as ExecutionEngine
from nautilus_trader.live.data_engine import LiveDataEngine as LiveDataEngine
from nautilus_trader.live.execution_engine import LiveExecutionEngine as LiveExecutionEngine
from nautilus_trader.live.risk_engine import LiveRiskEngine as LiveRiskEngine
from nautilus_trader.model.identifiers import TraderId as TraderId
from nautilus_trader.persistence.catalog import BaseDataCatalog as BaseDataCatalog
from nautilus_trader.persistence.writer import StreamingFeatherWriter as StreamingFeatherWriter
from nautilus_trader.portfolio.base import PortfolioFacade as PortfolioFacade
from nautilus_trader.portfolio.portfolio import Portfolio as Portfolio
from nautilus_trader.risk.engine import RiskEngine as RiskEngine
from nautilus_trader.serialization.serializer import MsgSpecSerializer as MsgSpecSerializer
from nautilus_trader.trading.controller import Controller as Controller
from nautilus_trader.trading.strategy import Strategy as Strategy
from nautilus_trader.trading.trader import Trader as Trader

class NautilusKernel:
    def __init__(self, name: str, config: NautilusKernelConfig, loop: asyncio.AbstractEventLoop | None = None, loop_sig_callback: Callable | None = None) -> None: ...
    def __del__(self) -> None: ...
    @property
    def environment(self) -> Environment: ...
    @property
    def loop(self) -> asyncio.AbstractEventLoop: ...
    @property
    def loop_sig_callback(self) -> Callable | None: ...
    @property
    def executor(self) -> ThreadPoolExecutor | None: ...
    @property
    def name(self) -> str: ...
    @property
    def trader_id(self) -> TraderId: ...
    @property
    def machine_id(self) -> str: ...
    @property
    def instance_id(self) -> UUID4: ...
    @property
    def ts_created(self) -> int: ...
    @property
    def ts_started(self) -> int | None: ...
    @property
    def ts_shutdown(self) -> int | None: ...
    @property
    def load_state(self) -> bool: ...
    @property
    def save_state(self) -> bool: ...
    @property
    def clock(self) -> Clock: ...
    @property
    def logger(self) -> Logger: ...
    @property
    def msgbus(self) -> MessageBus: ...
    @property
    def msgbus_serializer(self) -> MessageBus: ...
    @property
    def msgbus_database(self) -> MessageBus: ...
    @property
    def cache(self) -> CacheFacade: ...
    @property
    def portfolio(self) -> PortfolioFacade: ...
    @property
    def data_engine(self) -> DataEngine: ...
    @property
    def risk_engine(self) -> RiskEngine: ...
    @property
    def exec_engine(self) -> ExecutionEngine: ...
    @property
    def emulator(self) -> OrderEmulator: ...
    @property
    def trader(self) -> Trader: ...
    @property
    def writer(self) -> StreamingFeatherWriter | None: ...
    @property
    def catalogs(self) -> dict[str, BaseDataCatalog]: ...
    def get_log_guard(self) -> nautilus_pyo3.LogGuard | LogGuard | None: ...
    def is_running(self) -> bool: ...
    def start(self) -> None: ...
    async def start_async(self) -> None: ...
    def stop(self) -> None: ...
    async def stop_async(self) -> None: ...
    def dispose(self) -> None: ...
    def cancel_all_tasks(self) -> None: ...
