from nautilus_trader.common import Environment as Environment
from nautilus_trader.common.config import ActorConfig as ActorConfig, ImportableConfig as ImportableConfig, InstrumentProviderConfig as InstrumentProviderConfig, NautilusConfig as NautilusConfig, NonNegativeInt as NonNegativeInt, PositiveFloat as PositiveFloat, PositiveInt as PositiveInt, msgspec_decoding_hook as msgspec_decoding_hook, msgspec_encoding_hook as msgspec_encoding_hook, resolve_config_path as resolve_config_path, resolve_path as resolve_path
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.data.config import DataEngineConfig as DataEngineConfig
from nautilus_trader.execution.config import ExecEngineConfig as ExecEngineConfig
from nautilus_trader.model.identifiers import ClientOrderId as ClientOrderId, InstrumentId as InstrumentId, TraderId as TraderId
from nautilus_trader.risk.config import RiskEngineConfig as RiskEngineConfig
from nautilus_trader.system.config import NautilusKernelConfig as NautilusKernelConfig
from nautilus_trader.trading.config import ImportableControllerConfig as ImportableControllerConfig
from typing import Any

class LiveDataEngineConfig(DataEngineConfig, frozen=True):
    qsize: PositiveInt = ...
    graceful_shutdown_on_exception: bool = ...

class LiveRiskEngineConfig(RiskEngineConfig, frozen=True):
    qsize: PositiveInt = ...
    graceful_shutdown_on_exception: bool = ...

class LiveExecEngineConfig(ExecEngineConfig, frozen=True):
    reconciliation: bool = ...
    reconciliation_lookback_mins: NonNegativeInt | None = ...
    reconciliation_instrument_ids: list[InstrumentId] | None = ...
    filter_unclaimed_external_orders: bool = ...
    filter_position_reports: bool = ...
    filtered_client_order_ids: list[ClientOrderId] | None = ...
    generate_missing_orders: bool = ...
    inflight_check_interval_ms: NonNegativeInt = ...
    inflight_check_threshold_ms: NonNegativeInt = ...
    inflight_check_retries: NonNegativeInt = ...
    own_books_audit_interval_secs: PositiveFloat | None = ...
    open_check_interval_secs: PositiveFloat | None = ...
    open_check_open_only: bool = ...
    open_check_lookback_mins: PositiveInt = ...
    open_check_threshold_ms: NonNegativeInt = ...
    open_check_missing_retries: NonNegativeInt = ...
    max_single_order_queries_per_cycle: PositiveInt = ...
    single_order_query_delay_ms: NonNegativeInt = ...
    position_check_interval_secs: PositiveFloat | None = ...
    position_check_lookback_mins: PositiveInt = ...
    position_check_threshold_ms: NonNegativeInt = ...
    position_check_retries: NonNegativeInt = ...
    reconciliation_startup_delay_secs: PositiveFloat = ...
    qsize: PositiveInt = ...
    graceful_shutdown_on_exception: bool = ...

class RoutingConfig(NautilusConfig, frozen=True):
    default: bool = ...
    venues: frozenset[str] | None = ...

class LiveDataClientConfig(NautilusConfig, frozen=True):
    handle_revised_bars: bool = ...
    instrument_provider: InstrumentProviderConfig = ...
    routing: RoutingConfig = ...

class LiveExecClientConfig(NautilusConfig, frozen=True):
    instrument_provider: InstrumentProviderConfig = ...
    routing: RoutingConfig = ...

class ControllerConfig(ActorConfig, kw_only=True, frozen=True): ...

class ControllerFactory:
    @staticmethod
    def create(config: ImportableControllerConfig, trader): ...

class TradingNodeConfig(NautilusKernelConfig, frozen=True):
    environment: Environment = ...
    trader_id: TraderId = ...
    data_engine: LiveDataEngineConfig = ...
    risk_engine: LiveRiskEngineConfig = ...
    exec_engine: LiveExecEngineConfig = ...
    data_clients: dict[str, Any] = ...
    exec_clients: dict[str, Any] = ...
    def __post_init__(self) -> None: ...
