import asyncio
from collections.abc import Callable as Callable, Coroutine
from nautilus_trader.cache.cache import Cache as Cache
from nautilus_trader.common.component import LiveClock as LiveClock, MessageBus as MessageBus
from nautilus_trader.common.config import NautilusConfig as NautilusConfig
from nautilus_trader.common.enums import LogColor as LogColor
from nautilus_trader.common.functions import format_utc_timerange as format_utc_timerange
from nautilus_trader.common.providers import InstrumentProvider as InstrumentProvider
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.data.client import DataClient as DataClient, MarketDataClient as MarketDataClient
from nautilus_trader.data.messages import RequestBars as RequestBars, RequestData as RequestData, RequestForwardPrices as RequestForwardPrices, RequestFundingRates as RequestFundingRates, RequestInstrument as RequestInstrument, RequestInstruments as RequestInstruments, RequestOrderBookDeltas as RequestOrderBookDeltas, RequestOrderBookDepth as RequestOrderBookDepth, RequestOrderBookSnapshot as RequestOrderBookSnapshot, RequestQuoteTicks as RequestQuoteTicks, RequestTradeTicks as RequestTradeTicks, SubscribeBars as SubscribeBars, SubscribeData as SubscribeData, SubscribeFundingRates as SubscribeFundingRates, SubscribeIndexPrices as SubscribeIndexPrices, SubscribeInstrument as SubscribeInstrument, SubscribeInstrumentClose as SubscribeInstrumentClose, SubscribeInstrumentStatus as SubscribeInstrumentStatus, SubscribeInstruments as SubscribeInstruments, SubscribeMarkPrices as SubscribeMarkPrices, SubscribeOptionGreeks as SubscribeOptionGreeks, SubscribeOrderBook as SubscribeOrderBook, SubscribeQuoteTicks as SubscribeQuoteTicks, SubscribeTradeTicks as SubscribeTradeTicks, UnsubscribeBars as UnsubscribeBars, UnsubscribeData as UnsubscribeData, UnsubscribeFundingRates as UnsubscribeFundingRates, UnsubscribeIndexPrices as UnsubscribeIndexPrices, UnsubscribeInstrument as UnsubscribeInstrument, UnsubscribeInstrumentClose as UnsubscribeInstrumentClose, UnsubscribeInstrumentStatus as UnsubscribeInstrumentStatus, UnsubscribeInstruments as UnsubscribeInstruments, UnsubscribeMarkPrices as UnsubscribeMarkPrices, UnsubscribeOptionGreeks as UnsubscribeOptionGreeks, UnsubscribeOrderBook as UnsubscribeOrderBook, UnsubscribeQuoteTicks as UnsubscribeQuoteTicks, UnsubscribeTradeTicks as UnsubscribeTradeTicks
from nautilus_trader.live.cancellation import cancel_tasks_with_timeout as cancel_tasks_with_timeout
from nautilus_trader.model.identifiers import ClientId as ClientId, Venue as Venue

class LiveDataClient(DataClient):
    def __init__(self, loop: asyncio.AbstractEventLoop, client_id: ClientId, venue: Venue | None, msgbus: MessageBus, cache: Cache, clock: LiveClock, config: NautilusConfig | None = None) -> None: ...
    async def run_after_delay(self, delay: float, coro: Coroutine) -> None: ...
    def create_task(self, coro: Coroutine, log_msg: str | None = None, actions: Callable | None = None, success_msg: str | None = None, success_color: LogColor = ...) -> asyncio.Task: ...
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def subscribe(self, command: SubscribeData) -> None: ...
    def unsubscribe(self, command: UnsubscribeData) -> None: ...
    def request(self, request: RequestData) -> None: ...
    async def cancel_pending_tasks(self, timeout_secs: float = 5.0) -> None: ...

class LiveMarketDataClient(MarketDataClient):
    # cdef handler surface adapters override (data_client.pxd).
    _instrument_provider: Incomplete
    # cdef handlers take the full native arg list; ``*args`` keeps the override
    # surface loose (adapter calls them with venue + payload + timestamps).
    def _handle_data(self, *args: Any, **kwargs: Any) -> None: ...
    def _handle_bars(self, *args: Any, **kwargs: Any) -> None: ...
    def _handle_trade_ticks(self, *args: Any, **kwargs: Any) -> None: ...
    def _handle_quote_ticks(self, *args: Any, **kwargs: Any) -> None: ...
    def __init__(self, loop: asyncio.AbstractEventLoop, client_id: ClientId, venue: Venue | None, msgbus: MessageBus, cache: Cache, clock: LiveClock, instrument_provider: InstrumentProvider, config: NautilusConfig | None = None, is_sync: bool = False) -> None: ...
    async def run_after_delay(self, delay: float, coro: Coroutine) -> None: ...
    def create_task(self, coro: Coroutine, log_msg: str | None = None, actions: Callable | None = None, success_msg: str | None = None, success_color: LogColor = ...) -> asyncio.Task | None: ...
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def subscribe(self, command: SubscribeData) -> None: ...
    def subscribe_instruments(self, command: SubscribeInstruments) -> None: ...
    def subscribe_instrument(self, command: SubscribeInstrument) -> None: ...
    def subscribe_order_book_deltas(self, command: SubscribeOrderBook) -> None: ...
    def subscribe_order_book_depth(self, command: SubscribeOrderBook) -> None: ...
    def subscribe_quote_ticks(self, command: SubscribeQuoteTicks) -> None: ...
    def subscribe_trade_ticks(self, command: SubscribeTradeTicks) -> None: ...
    def subscribe_mark_prices(self, command: SubscribeMarkPrices) -> None: ...
    def subscribe_index_prices(self, command: SubscribeIndexPrices) -> None: ...
    def subscribe_funding_rates(self, command: SubscribeFundingRates) -> None: ...
    def subscribe_bars(self, command: SubscribeBars) -> None: ...
    def subscribe_instrument_status(self, command: SubscribeInstrumentStatus) -> None: ...
    def subscribe_instrument_close(self, command: SubscribeInstrumentClose) -> None: ...
    def subscribe_option_greeks(self, command: SubscribeOptionGreeks) -> None: ...
    def unsubscribe(self, command: UnsubscribeData) -> None: ...
    def unsubscribe_instruments(self, command: UnsubscribeInstruments) -> None: ...
    def unsubscribe_instrument(self, command: UnsubscribeInstrument) -> None: ...
    def unsubscribe_order_book_deltas(self, command: UnsubscribeOrderBook) -> None: ...
    def unsubscribe_order_book_depth(self, command: UnsubscribeOrderBook) -> None: ...
    def unsubscribe_quote_ticks(self, command: UnsubscribeQuoteTicks) -> None: ...
    def unsubscribe_trade_ticks(self, command: UnsubscribeTradeTicks) -> None: ...
    def unsubscribe_mark_prices(self, command: UnsubscribeMarkPrices) -> None: ...
    def unsubscribe_index_prices(self, command: UnsubscribeIndexPrices) -> None: ...
    def unsubscribe_funding_rates(self, command: UnsubscribeFundingRates) -> None: ...
    def unsubscribe_bars(self, command: UnsubscribeBars) -> None: ...
    def unsubscribe_instrument_status(self, command: UnsubscribeInstrumentStatus) -> None: ...
    def unsubscribe_instrument_close(self, command: UnsubscribeInstrumentClose) -> None: ...
    def unsubscribe_option_greeks(self, command: UnsubscribeOptionGreeks) -> None: ...
    def request(self, request: RequestData) -> None: ...
    def request_instrument(self, request: RequestInstrument) -> None: ...
    def request_instruments(self, request: RequestInstruments) -> None: ...
    def request_order_book_deltas(self, request: RequestOrderBookDeltas) -> None: ...
    def request_order_book_depth(self, request: RequestOrderBookDepth) -> None: ...
    def request_order_book_snapshot(self, request: RequestOrderBookSnapshot) -> None: ...
    def request_quote_ticks(self, request: RequestQuoteTicks) -> None: ...
    def request_trade_ticks(self, request: RequestTradeTicks) -> None: ...
    def request_funding_rates(self, request: RequestFundingRates) -> None: ...
    def request_bars(self, request: RequestBars) -> None: ...
    def request_forward_prices(self, request: RequestForwardPrices) -> None: ...
    async def cancel_pending_tasks(self, timeout_secs: float = 5.0) -> None: ...
