import asyncio
from nautilus_trader.cache.cache import Cache as Cache
from nautilus_trader.common.component import LiveClock as LiveClock, MessageBus as MessageBus
from nautilus_trader.common.enums import LogColor as LogColor
from nautilus_trader.config import LiveDataEngineConfig as LiveDataEngineConfig
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.core.data import Data as Data
from nautilus_trader.data.engine import DataEngine as DataEngine
from nautilus_trader.data.messages import DataCommand as DataCommand, DataResponse as DataResponse, RequestData as RequestData
from nautilus_trader.live.enqueue import ThrottledEnqueuer as ThrottledEnqueuer

class LiveDataEngine(DataEngine):
    graceful_shutdown_on_exception: bool
    def __init__(self, loop: asyncio.AbstractEventLoop, msgbus: MessageBus, cache: Cache, clock: LiveClock, config: LiveDataEngineConfig | None = None) -> None: ...
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def get_cmd_queue_task(self) -> asyncio.Task | None: ...
    def get_req_queue_task(self) -> asyncio.Task | None: ...
    def get_res_queue_task(self) -> asyncio.Task | None: ...
    def get_data_queue_task(self) -> asyncio.Task | None: ...
    def cmd_qsize(self) -> int: ...
    def req_qsize(self) -> int: ...
    def res_qsize(self) -> int: ...
    def data_qsize(self) -> int: ...
    def kill(self) -> None: ...
    def execute(self, command: DataCommand) -> None: ...
    def request(self, request: RequestData) -> None: ...
    def response(self, response: DataResponse) -> None: ...
    def process(self, data: Data) -> None: ...
