import asyncio
from nautilus_trader.common.component import Clock as Clock, Logger as Logger
from nautilus_trader.core.nautilus_pyo3 import NANOSECONDS_IN_SECOND as NANOSECONDS_IN_SECOND

class ThrottledEnqueuer[T]:
    def __init__(self, qname: str, queue: asyncio.Queue, loop: asyncio.AbstractEventLoop, clock: Clock, logger: Logger) -> None: ...
    @property
    def qname(self) -> str: ...
    @property
    def size(self) -> int: ...
    @property
    def capacity(self) -> int: ...
    def enqueue(self, msg: T) -> None: ...
    def cancel_pending_tasks(self) -> None: ...
