import asyncio
from collections.abc import Callable as Callable, Coroutine
from nautilus_trader.cache.cache import Cache as Cache
from nautilus_trader.common.component import LiveClock as LiveClock, MessageBus as MessageBus
from nautilus_trader.common.config import NautilusConfig as NautilusConfig
from nautilus_trader.common.enums import LogColor as LogColor, LogLevel as LogLevel
from nautilus_trader.common.providers import InstrumentProvider as InstrumentProvider
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.core.nautilus_pyo3 import MILLISECONDS_IN_SECOND as MILLISECONDS_IN_SECOND
from nautilus_trader.core.uuid import UUID4 as UUID4
from nautilus_trader.execution.client import ExecutionClient as ExecutionClient
from nautilus_trader.execution.messages import BatchCancelOrders as BatchCancelOrders, CancelAllOrders as CancelAllOrders, CancelOrder as CancelOrder, GenerateFillReports as GenerateFillReports, GenerateOrderStatusReport as GenerateOrderStatusReport, GenerateOrderStatusReports as GenerateOrderStatusReports, GeneratePositionStatusReports as GeneratePositionStatusReports, ModifyOrder as ModifyOrder, QueryAccount as QueryAccount, QueryOrder as QueryOrder, SubmitOrder as SubmitOrder, SubmitOrderList as SubmitOrderList
from nautilus_trader.execution.reports import ExecutionMassStatus as ExecutionMassStatus, FillReport as FillReport, OrderStatusReport as OrderStatusReport, PositionStatusReport as PositionStatusReport
from nautilus_trader.live.cancellation import cancel_tasks_with_timeout as cancel_tasks_with_timeout
from nautilus_trader.model.enums import AccountType as AccountType, OmsType as OmsType, order_side_to_str as order_side_to_str
from nautilus_trader.model.identifiers import ClientId as ClientId, Venue as Venue
from nautilus_trader.model.objects import Currency as Currency

class LiveExecutionClient(ExecutionClient):
    reconciliation_active: bool
    def __init__(self, loop: asyncio.AbstractEventLoop, client_id: ClientId, venue: Venue | None, oms_type: OmsType, account_type: AccountType, base_currency: Currency | None, instrument_provider: InstrumentProvider, msgbus: MessageBus, cache: Cache, clock: LiveClock, config: NautilusConfig | None = None) -> None: ...
    async def run_after_delay(self, delay: float, coro: Coroutine) -> None: ...
    def create_task(self, coro: Coroutine, log_msg: str | None = None, actions: Callable | None = None, success_msg: str | None = None, success_color: LogColor = ...) -> asyncio.Task: ...
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    async def cancel_pending_tasks(self, timeout_secs: float = 5.0) -> None: ...
    def submit_order(self, command: SubmitOrder) -> None: ...
    def submit_order_list(self, command: SubmitOrderList) -> None: ...
    def modify_order(self, command: ModifyOrder) -> None: ...
    def cancel_order(self, command: CancelOrder) -> None: ...
    def cancel_all_orders(self, command: CancelAllOrders) -> None: ...
    def batch_cancel_orders(self, command: BatchCancelOrders) -> None: ...
    def query_account(self, command: QueryAccount) -> None: ...
    def query_order(self, command: QueryOrder) -> None: ...
    async def generate_order_status_report(self, command: GenerateOrderStatusReport) -> OrderStatusReport | None: ...
    async def generate_order_status_reports(self, command: GenerateOrderStatusReports) -> list[OrderStatusReport]: ...
    async def generate_fill_reports(self, command: GenerateFillReports) -> list[FillReport]: ...
    async def generate_position_status_reports(self, command: GeneratePositionStatusReports) -> list[PositionStatusReport]: ...
    async def generate_mass_status(self, lookback_mins: int | None = None) -> ExecutionMassStatus | None: ...
