import asyncio
from _typeshed import Incomplete
from collections.abc import Callable as Callable
from nautilus_trader.cache.base import CacheFacade as CacheFacade
from nautilus_trader.common.component import Logger as Logger
from nautilus_trader.common.enums import LogColor as LogColor
from nautilus_trader.common.functions import get_event_loop as get_event_loop
from nautilus_trader.config import TradingNodeConfig as TradingNodeConfig
from nautilus_trader.core import nautilus_pyo3 as nautilus_pyo3
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.core.uuid import UUID4 as UUID4
from nautilus_trader.live.factories import LiveDataClientFactory as LiveDataClientFactory, LiveExecClientFactory as LiveExecClientFactory
from nautilus_trader.live.node_builder import TradingNodeBuilder as TradingNodeBuilder
from nautilus_trader.model.identifiers import TraderId as TraderId
from nautilus_trader.portfolio.base import PortfolioFacade as PortfolioFacade
from nautilus_trader.system.kernel import NautilusKernel as NautilusKernel
from nautilus_trader.trading.trader import Trader as Trader

class TradingNode:
    kernel: Incomplete
    def __init__(self, config: TradingNodeConfig | None = None, loop: asyncio.AbstractEventLoop | None = None) -> None: ...
    @property
    def trader_id(self) -> TraderId: ...
    @property
    def machine_id(self) -> str: ...
    @property
    def instance_id(self) -> UUID4: ...
    @property
    def trader(self) -> Trader: ...
    @property
    def cache(self) -> CacheFacade: ...
    @property
    def portfolio(self) -> PortfolioFacade: ...
    def is_running(self) -> bool: ...
    def is_built(self) -> bool: ...
    def get_event_loop(self) -> asyncio.AbstractEventLoop | None: ...
    def get_logger(self) -> Logger: ...
    def add_stream_processor(self, callback: Callable) -> None: ...
    def add_data_client_factory(self, name: str, factory: type[LiveDataClientFactory]) -> None: ...
    def add_exec_client_factory(self, name: str, factory: type[LiveExecClientFactory]) -> None: ...
    def build(self) -> None: ...
    def run(self, raise_exception: bool = False) -> None: ...
    def publish_bus_message(self, bus_msg: nautilus_pyo3.BusMessage) -> None: ...
    async def run_async(self) -> None: ...
    def stop(self) -> None: ...
    async def stop_async(self) -> None: ...
    def dispose(self) -> None: ...
