from decimal import Decimal
from nautilus_trader.cache.transformers import transform_instrument_to_pyo3 as transform_instrument_to_pyo3
from nautilus_trader.common.component import Logger as Logger
from nautilus_trader.core import nautilus_pyo3 as nautilus_pyo3
from nautilus_trader.core.uuid import UUID4 as UUID4
from nautilus_trader.execution.client import ExecutionClient as ExecutionClient
from nautilus_trader.execution.reports import ExecutionMassStatus as ExecutionMassStatus, FillReport as FillReport, OrderStatusReport as OrderStatusReport
from nautilus_trader.model.currencies import register_currency as register_currency
from nautilus_trader.model.enums import LiquiditySide as LiquiditySide, OrderType as OrderType
from nautilus_trader.model.events import OrderAccepted as OrderAccepted, OrderCanceled as OrderCanceled, OrderExpired as OrderExpired, OrderFilled as OrderFilled, OrderRejected as OrderRejected, OrderTriggered as OrderTriggered, OrderUpdated as OrderUpdated
from nautilus_trader.model.identifiers import InstrumentId as InstrumentId, PositionId as PositionId, TradeId as TradeId, TraderId as TraderId, VenueOrderId as VenueOrderId
from nautilus_trader.model.instruments import Instrument as Instrument
from nautilus_trader.model.objects import Currency as Currency, Money as Money, Price as Price, Quantity as Quantity
from nautilus_trader.model.orders import Order as Order

def is_within_single_unit_tolerance(value1: Decimal, value2: Decimal, precision: int) -> bool: ...
def get_existing_fill_for_trade_id(order: Order, trade_id: TradeId) -> OrderFilled | None: ...
def create_order_rejected_event(order: Order, ts_now: int, report: OrderStatusReport | None = None, reason: str | None = None) -> OrderRejected: ...
def create_order_canceled_event(order: Order, ts_now: int, report: OrderStatusReport | None = None) -> OrderCanceled: ...
def create_order_expired_event(order: Order, ts_now: int, report: OrderStatusReport) -> OrderExpired: ...
def create_order_accepted_event(trader_id: TraderId, order: Order, ts_now: int, report: OrderStatusReport) -> OrderAccepted: ...
def create_order_triggered_event(trader_id: TraderId, order: Order, ts_now: int, report: OrderStatusReport) -> OrderTriggered: ...
def create_order_updated_event(trader_id: TraderId, order: Order, ts_now: int, report: OrderStatusReport) -> OrderUpdated: ...
def create_order_filled_event(order: Order, ts_now: int, report: FillReport, instrument: Instrument) -> OrderFilled: ...
def create_inferred_order_filled_event(order: Order, ts_now: int, report: OrderStatusReport, instrument: Instrument, client: ExecutionClient | None = None) -> OrderFilled: ...
def calculate_reconciliation_price(current_position_qty: Decimal, current_position_avg_px: Decimal | None, target_position_qty: Decimal, target_position_avg_px: Decimal | None, instrument: Instrument) -> Price | None: ...
def adjust_fills_for_partial_window_single(mass_status: ExecutionMassStatus, instrument: Instrument, logger: Logger | None = None) -> tuple[dict[VenueOrderId, OrderStatusReport], dict[VenueOrderId, list[FillReport]]]: ...
def adjust_fills_for_partial_window(mass_status: ExecutionMassStatus, instruments: list[Instrument], logger: Logger | None = None) -> dict[InstrumentId, tuple[dict[VenueOrderId, OrderStatusReport], dict[VenueOrderId, list[FillReport]]]]: ...
