import asyncio
from nautilus_trader.cache.base import CacheFacade as CacheFacade
from nautilus_trader.common.component import LiveClock as LiveClock, MessageBus as MessageBus
from nautilus_trader.common.enums import LogColor as LogColor
from nautilus_trader.config import LiveRiskEngineConfig as LiveRiskEngineConfig
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.core.message import Command as Command, Event as Event
from nautilus_trader.live.enqueue import ThrottledEnqueuer as ThrottledEnqueuer
from nautilus_trader.portfolio.base import PortfolioFacade as PortfolioFacade
from nautilus_trader.risk.engine import RiskEngine as RiskEngine

class LiveRiskEngine(RiskEngine):
    graceful_shutdown_on_exception: bool
    def __init__(self, loop: asyncio.AbstractEventLoop, portfolio: PortfolioFacade, msgbus: MessageBus, cache: CacheFacade, clock: LiveClock, config: LiveRiskEngineConfig | None = None) -> None: ...
    def get_cmd_queue_task(self) -> asyncio.Task | None: ...
    def get_evt_queue_task(self) -> asyncio.Task | None: ...
    def cmd_qsize(self) -> int: ...
    def evt_qsize(self) -> int: ...
    def kill(self) -> None: ...
    def execute(self, command: Command) -> None: ...
    def process(self, event: Event) -> None: ...
