from nautilus_trader.common.config import PositiveInt as PositiveInt
from nautilus_trader.config import LiveDataClientConfig as LiveDataClientConfig, LiveExecClientConfig as LiveExecClientConfig
from nautilus_trader.core.nautilus_pyo3 import DeribitEnvironment as DeribitEnvironment, DeribitProductType as DeribitProductType
from nautilus_trader.network import TransportBackend as TransportBackend

class DeribitDataClientConfig(LiveDataClientConfig, frozen=True):
    api_key: str | None = ...
    api_secret: str | None = ...
    product_types: tuple[DeribitProductType, ...] | None = ...
    environment: DeribitEnvironment | None = ...
    base_url_http: str | None = ...
    base_url_ws: str | None = ...
    proxy_url: str | None = ...
    transport_backend: TransportBackend | None = ...
    http_timeout_secs: PositiveInt | None = ...
    max_retries: PositiveInt | None = ...
    retry_delay_initial_ms: PositiveInt | None = ...
    retry_delay_max_ms: PositiveInt | None = ...
    update_instruments_interval_mins: PositiveInt | None = ...
    auto_load_missing_instruments: bool = ...

class DeribitExecClientConfig(LiveExecClientConfig, frozen=True):
    api_key: str | None = ...
    api_secret: str | None = ...
    product_types: tuple[DeribitProductType, ...] | None = ...
    environment: DeribitEnvironment | None = ...
    base_url_http: str | None = ...
    base_url_ws: str | None = ...
    proxy_url: str | None = ...
    transport_backend: TransportBackend | None = ...
    http_timeout_secs: PositiveInt | None = ...
    max_retries: PositiveInt | None = ...
    retry_delay_initial_ms: PositiveInt | None = ...
    retry_delay_max_ms: PositiveInt | None = ...
