from nautilus_trader.core.nautilus_pyo3 import AggressorSide as AggressorSide, Bar as Bar, BarAggregation as BarAggregation, BarSpecification as BarSpecification, BarType as BarType, BookAction as BookAction, BookOrder as BookOrder, InstrumentId as InstrumentId, OrderBookDelta as OrderBookDelta, OrderBookDepth10 as OrderBookDepth10, OrderSide as OrderSide, Price as Price, PriceType as PriceType, Quantity as Quantity, QuoteTick as QuoteTick, TradeTick as TradeTick
from nautilus_trader.test_kit.rust.identifiers_pyo3 import TestIdProviderPyo3 as TestIdProviderPyo3

class TestDataProviderPyo3:
    @staticmethod
    def order_book_delta(instrument_id: InstrumentId | None = None, price: float = 10000.0, size: float = 0.1, ts_event: int = 0, ts_init: int = 0) -> OrderBookDelta: ...
    @staticmethod
    def order_book_depth10(instrument_id: InstrumentId | None = None, flags: int = 0, sequence: int = 0, ts_event: int = 0, ts_init: int = 0) -> OrderBookDepth10: ...
    @staticmethod
    def quote_tick(instrument_id: InstrumentId | None = None, bid_price: float = 1987.0, ask_price: float = 1988.0, ask_size: float = 100000.0, bid_size: float = 100000.0, ts_event: int = 0, ts_init: int = 0) -> QuoteTick: ...
    @staticmethod
    def trade_tick(instrument_id: InstrumentId | None = None, price: float = 1987.0, size: float = 0.1, ts_event: int = 0, ts_init: int = 0) -> TradeTick: ...
    @staticmethod
    def bar_spec_1min_bid() -> BarSpecification: ...
    @staticmethod
    def bar_spec_1min_ask() -> BarSpecification: ...
    @staticmethod
    def bar_spec_1min_last() -> BarSpecification: ...
    @staticmethod
    def bar_spec_1min_mid() -> BarSpecification: ...
    @staticmethod
    def bartype_ethusdt_1min_bid() -> BarType: ...
    @staticmethod
    def bar_5decimal() -> Bar: ...
