from nautilus_trader.core.nautilus_pyo3 import AccountBalance as AccountBalance, AccountId as AccountId, AccountState as AccountState, AccountType as AccountType, CashAccount as CashAccount, ClientOrderId as ClientOrderId, ContingencyType as ContingencyType, CryptoFuture as CryptoFuture, CryptoPerpetual as CryptoPerpetual, Currency as Currency, CurrencyPair as CurrencyPair, Equity as Equity, LiquiditySide as LiquiditySide, MarketOrder as MarketOrder, Money as Money, OrderAccepted as OrderAccepted, OrderCancelRejected as OrderCancelRejected, OrderCanceled as OrderCanceled, OrderDenied as OrderDenied, OrderEmulated as OrderEmulated, OrderExpired as OrderExpired, OrderFilled as OrderFilled, OrderInitialized as OrderInitialized, OrderListId as OrderListId, OrderModifyRejected as OrderModifyRejected, OrderPendingCancel as OrderPendingCancel, OrderPendingUpdate as OrderPendingUpdate, OrderRejected as OrderRejected, OrderReleased as OrderReleased, OrderSide as OrderSide, OrderSubmitted as OrderSubmitted, OrderTriggered as OrderTriggered, OrderType as OrderType, OrderUpdated as OrderUpdated, PositionId as PositionId, Price as Price, Quantity as Quantity, StrategyId as StrategyId, TimeInForce as TimeInForce, TradeId as TradeId, TriggerType as TriggerType, UUID4 as UUID4, VenueOrderId as VenueOrderId
from nautilus_trader.test_kit.rust.identifiers_pyo3 import TestIdProviderPyo3 as TestIdProviderPyo3
from nautilus_trader.test_kit.rust.types_pyo3 import TestTypesProviderPyo3 as TestTypesProviderPyo3

class TestEventsProviderPyo3:
    @staticmethod
    def cash_account_state() -> AccountState: ...
    @staticmethod
    def cash_account_state_million_usd() -> AccountState: ...
    @staticmethod
    def cash_account_state_multi() -> AccountState: ...
    @staticmethod
    def cash_account_state_multi_changed_btc() -> AccountState: ...
    @staticmethod
    def margin_account_state() -> AccountState: ...
    @staticmethod
    def order_denied_max_submit_rate() -> OrderDenied: ...
    @staticmethod
    def order_rejected_insufficient_margin() -> OrderRejected: ...
    @staticmethod
    def order_filled_buy_limit() -> OrderFilled: ...
    @staticmethod
    def order_initialized() -> OrderInitialized: ...
    @staticmethod
    def order_triggered() -> OrderTriggered: ...
    @staticmethod
    def order_submitted() -> OrderSubmitted: ...
    @staticmethod
    def order_emulated() -> OrderEmulated: ...
    @staticmethod
    def order_released() -> OrderReleased: ...
    @staticmethod
    def order_updated() -> OrderUpdated: ...
    @staticmethod
    def order_pending_update() -> OrderPendingUpdate: ...
    @staticmethod
    def order_pending_cancel() -> OrderPendingCancel: ...
    @staticmethod
    def order_modified_rejected(): ...
    @staticmethod
    def order_accepted() -> OrderAccepted: ...
    @staticmethod
    def order_cancel_rejected() -> OrderCancelRejected: ...
    @staticmethod
    def order_canceled() -> OrderCanceled: ...
    @staticmethod
    def order_expired() -> OrderExpired: ...
    @staticmethod
    def order_filled(order: MarketOrder, instrument: CurrencyPair | CryptoPerpetual | CryptoFuture | Equity, strategy_id: StrategyId | None = None, account_id: AccountId | None = None, venue_order_id: VenueOrderId | None = None, trade_id: TradeId | None = None, position_id: PositionId | None = None, last_qty: Quantity | None = None, last_px: Price | None = None, liquidity_side: LiquiditySide = ..., ts_filled_ns: int = 0, account: CashAccount | None = None) -> OrderFilled: ...
