from nautilus_trader.core.nautilus_pyo3 import AccountId as AccountId, ClientOrderId as ClientOrderId, InstrumentId as InstrumentId, OrderListId as OrderListId, PositionId as PositionId, StrategyId as StrategyId, Symbol as Symbol, TradeId as TradeId, TraderId as TraderId, UUID4 as UUID4, Venue as Venue, VenueOrderId as VenueOrderId

class TestIdProviderPyo3:
    @staticmethod
    def uuid() -> UUID4: ...
    @staticmethod
    def trader_id() -> TraderId: ...
    @staticmethod
    def account_id() -> AccountId: ...
    @staticmethod
    def strategy_id() -> StrategyId: ...
    @staticmethod
    def position_id() -> PositionId: ...
    @staticmethod
    def btcusdt_binance_id() -> InstrumentId: ...
    @staticmethod
    def ethusdt_binance_id() -> InstrumentId: ...
    @staticmethod
    def adabtc_binance_id() -> InstrumentId: ...
    @staticmethod
    def audusd_id() -> InstrumentId: ...
    @staticmethod
    def gbpusd_id() -> InstrumentId: ...
    @staticmethod
    def usdjpy_id() -> InstrumentId: ...
    @staticmethod
    def audusd_idealpro_id() -> InstrumentId: ...
    @staticmethod
    def aapl_xnas_id() -> InstrumentId: ...
    @staticmethod
    def betting_instrument_id(): ...
    @staticmethod
    def synthetic_id(): ...
    @staticmethod
    def client_order_id(counter: int = 1) -> ClientOrderId: ...
    @staticmethod
    def order_list_id(counter: int = 1) -> OrderListId: ...
    @staticmethod
    def venue_order_id() -> VenueOrderId: ...
    @staticmethod
    def trade_id() -> TradeId: ...
