import pandas as pd
from nautilus_trader.core import nautilus_pyo3 as nautilus_pyo3
from nautilus_trader.core.nautilus_pyo3 import AssetClass as AssetClass, BettingInstrument as BettingInstrument, BinaryOption as BinaryOption, Cfd as Cfd, Commodity as Commodity, CryptoFuture as CryptoFuture, CryptoOption as CryptoOption, CryptoPerpetual as CryptoPerpetual, Currency as Currency, CurrencyPair as CurrencyPair, Equity as Equity, FuturesContract as FuturesContract, FuturesSpread as FuturesSpread, IndexInstrument as IndexInstrument, InstrumentId as InstrumentId, Money as Money, OptionContract as OptionContract, OptionKind as OptionKind, OptionSpread as OptionSpread, PerpetualContract as PerpetualContract, Price as Price, Quantity as Quantity, Symbol as Symbol, Venue as Venue

class TestInstrumentProviderPyo3:
    @staticmethod
    def default_fx_ccy(symbol: str, venue: Venue | None = None) -> CurrencyPair: ...
    @staticmethod
    def audusd_sim(): ...
    @staticmethod
    def betting_instrument() -> BettingInstrument: ...
    @staticmethod
    def binary_option() -> BinaryOption: ...
    @staticmethod
    def ethusdt_perp_binance() -> CryptoPerpetual: ...
    @staticmethod
    def ethusdt_binance() -> CurrencyPair: ...
    @staticmethod
    def xbtusd_bitmex() -> CryptoPerpetual: ...
    @staticmethod
    def ethusd_bitmex() -> CryptoPerpetual: ...
    @staticmethod
    def btcusdt_future_binance(activation: pd.Timestamp | None = None, expiration: pd.Timestamp | None = None) -> CryptoFuture: ...
    @staticmethod
    def btcusd_option_deribit() -> CryptoOption: ...
    @staticmethod
    def btcusdt_binance() -> CurrencyPair: ...
    @staticmethod
    def aapl_equity() -> Equity: ...
    @staticmethod
    def aapl_option(activation: pd.Timestamp | None = None, expiration: pd.Timestamp | None = None) -> OptionContract: ...
    @staticmethod
    def futures_contract_es(activation: pd.Timestamp | None = None, expiration: pd.Timestamp | None = None) -> FuturesContract: ...
    @staticmethod
    def futures_spread_es(activation: pd.Timestamp | None = None, expiration: pd.Timestamp | None = None) -> FuturesSpread: ...
    @staticmethod
    def option_spread(activation: pd.Timestamp | None = None, expiration: pd.Timestamp | None = None) -> OptionSpread: ...
    @staticmethod
    def commodity() -> Commodity: ...
    @staticmethod
    def index_instrument() -> IndexInstrument: ...
    @staticmethod
    def perpetual_contract_eurusd() -> PerpetualContract: ...
    @staticmethod
    def cfd() -> Cfd: ...
