import _cython_3_2_9
import nautilus_trader.core.data
from typing import Any, ClassVar

__reduce_cython__: _cython_3_2_9.cython_function_or_method
__setstate_cython__: _cython_3_2_9.cython_function_or_method
__test__: dict
py_should_handle_own_book_order: _cython_3_2_9.cython_function_or_method

class BookLevel:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    price: BookLevel.price
    side: BookLevel.side
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def exposure(self) -> double: ...
    def orders(self) -> list: ...
    def size(self) -> double: ...
    def __del__(self, *args, **kwargs) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...

class OrderBook(nautilus_trader.core.data.Data):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    book_type: OrderBook.book_type
    instrument_id: OrderBook.instrument_id
    sequence: OrderBook.sequence
    ts_event: OrderBook.ts_event
    ts_init: OrderBook.ts_init
    ts_last: OrderBook.ts_last
    update_count: OrderBook.update_count
    def __init__(self, InstrumentIdinstrument_id, BookTypebook_type) -> None: ...
    def add(self, BookOrderorder, uint64_tts_event, uint8_tflags=..., uint64_tsequence=...) -> void: ...
    def apply(self, Datadata) -> void: ...
    def apply_delta(self, OrderBookDeltadelta) -> void: ...
    def apply_deltas(self, OrderBookDeltasdeltas) -> void: ...
    def apply_depth(self, OrderBookDepth10depth) -> void: ...
    def asks(self) -> list: ...
    def best_ask_price(self) -> Any: ...
    def best_ask_size(self) -> Any: ...
    def best_bid_price(self) -> Any: ...
    def best_bid_size(self) -> Any: ...
    def bids(self) -> list: ...
    def check_integrity(self) -> void: ...
    def clear(self, uint64_tts_event, uint64_tsequence=...) -> void: ...
    def clear_asks(self, uint64_tts_event, uint64_tsequence=...) -> void: ...
    def clear_bids(self, uint64_tts_event, uint64_tsequence=...) -> void: ...
    def delete(self, BookOrderorder, uint64_tts_event, uint8_tflags=..., uint64_tsequence=...) -> void: ...
    def get_all_crossed_levels(self, OrderSideorder_side, Priceprice, uint8_tsize_prec) -> list: ...
    def get_avg_px_for_quantity(self, Quantityquantity, OrderSideorder_side) -> double: ...
    def get_quantity_at_level(self, Priceprice, OrderSideorder_side, uint8_tsize_precision) -> Quantity: ...
    def get_quantity_for_price(self, Priceprice, OrderSideorder_side) -> double: ...
    def get_worst_px_for_quantity(self, Quantityquantity, OrderSideorder_side) -> Any: ...
    def midpoint(self) -> Any: ...
    def pprint(self, intnum_levels=...) -> str: ...
    def reset(self) -> void: ...
    def simulate_fills(self, Orderorder, uint8_tprice_prec, uint8_tsize_prec, boolis_aggressive) -> list: ...
    def spread(self) -> Any: ...
    def to_deltas_c(self, uint64_tts_event, uint64_tts_init) -> OrderBookDeltas: ...
    def to_quote_tick(self) -> QuoteTick: ...
    def update(self, BookOrderorder, uint64_tts_event, uint8_tflags=..., uint64_tsequence=...) -> void: ...
    def update_quote_tick(self, QuoteTicktick) -> void: ...
    def update_trade_tick(self, TradeTicktick) -> void: ...
    def __del__(self, *args, **kwargs) -> None: ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
