import _cython_3_2_9
import enum
import nautilus_pyo3
import nautilus_trader.core.data
import np
from _typeshed import Incomplete
from typing import Any, Callable, ClassVar, overload

from nautilus_trader.model.identifiers import InstrumentId

NULL_ORDER: BookOrder
__pyx_capi__: dict
__reduce_cython__: _cython_3_2_9.cython_function_or_method
__setstate_cython__: _cython_3_2_9.cython_function_or_method
__test__: dict
bar_aggregation_not_implemented_message: _cython_3_2_9.cython_function_or_method
capsule_to_data: _cython_3_2_9.cython_function_or_method
capsule_to_list: _cython_3_2_9.cython_function_or_method
pyo3_list_to_data_list: _cython_3_2_9.cython_function_or_method
supported_bar_aggregations_str: _cython_3_2_9.cython_function_or_method

class Bar(nautilus_trader.core.data.Data):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    bar_type: Bar.bar_type
    close: Bar.close
    high: Bar.high
    is_revision: Incomplete
    low: Bar.low
    open: Bar.open
    ts_event: Bar.ts_event
    ts_init: Bar.ts_init
    volume: Bar.volume
    def __init__(self, BarTypebar_type, Priceopen, Pricehigh, Pricelow, Priceclose, Quantityvolume, uint64_tts_event, uint64_tts_init, boolis_revision=...) -> None: ...
    @staticmethod
    def from_dict(dictvalues) -> Bar: ...
    @staticmethod
    def from_pyo3(pyo3_bar) -> Bar: ...
    @staticmethod
    def from_pyo3_list(listpyo3_bars) -> list[Bar]: ...
    @staticmethod
    def from_raw(BarTypebar_type, PriceRawopen, PriceRawhigh, PriceRawlow, PriceRawclose, uint8_tprice_prec, QuantityRawvolume, uint8_tsize_prec, uint64_tts_event, uint64_tts_init) -> Bar: ...
    @staticmethod
    def from_raw_arrays_to_list(*args, **kwargs): ...
    def is_single_price(self) -> bool: ...
    @staticmethod
    def to_dict(Barobj) -> Any: ...
    def to_pyo3(self) -> nautilus_pyo3.Bar: ...
    @staticmethod
    def to_pyo3_list(listbars) -> list[nautilus_pyo3.Bar]: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class BarAggregation(enum.IntFlag):
    __new__: ClassVar[Callable] = ...
    DAY: ClassVar[BarAggregation] = ...
    HOUR: ClassVar[BarAggregation] = ...
    MILLISECOND: ClassVar[BarAggregation] = ...
    MINUTE: ClassVar[BarAggregation] = ...
    MONTH: ClassVar[BarAggregation] = ...
    RENKO: ClassVar[BarAggregation] = ...
    SECOND: ClassVar[BarAggregation] = ...
    TICK: ClassVar[BarAggregation] = ...
    TICK_IMBALANCE: ClassVar[BarAggregation] = ...
    TICK_RUNS: ClassVar[BarAggregation] = ...
    VALUE: ClassVar[BarAggregation] = ...
    VALUE_IMBALANCE: ClassVar[BarAggregation] = ...
    VALUE_RUNS: ClassVar[BarAggregation] = ...
    VOLUME: ClassVar[BarAggregation] = ...
    VOLUME_IMBALANCE: ClassVar[BarAggregation] = ...
    VOLUME_RUNS: ClassVar[BarAggregation] = ...
    WEEK: ClassVar[BarAggregation] = ...
    YEAR: ClassVar[BarAggregation] = ...
    _all_bits_: ClassVar[int] = ...
    _boundary_: ClassVar[enum.FlagBoundary] = ...
    _flag_mask_: ClassVar[int] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _hashable_values_: ClassVar[list] = ...
    _inverted_: ClassVar[None] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _singles_mask_: ClassVar[int] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    __and__: ClassVar[Callable] = ...
    __invert__: ClassVar[Callable] = ...
    __or__: ClassVar[Callable] = ...
    __rand__: ClassVar[Callable] = ...
    __ror__: ClassVar[Callable] = ...
    __rxor__: ClassVar[Callable] = ...
    __xor__: ClassVar[Callable] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class BarIntervalType(enum.IntFlag):
    __new__: ClassVar[Callable] = ...
    LEFT_OPEN: ClassVar[BarIntervalType] = ...
    RIGHT_OPEN: ClassVar[BarIntervalType] = ...
    _all_bits_: ClassVar[int] = ...
    _boundary_: ClassVar[enum.FlagBoundary] = ...
    _flag_mask_: ClassVar[int] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _hashable_values_: ClassVar[list] = ...
    _inverted_: ClassVar[None] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _singles_mask_: ClassVar[int] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    __and__: ClassVar[Callable] = ...
    __invert__: ClassVar[Callable] = ...
    __or__: ClassVar[Callable] = ...
    __rand__: ClassVar[Callable] = ...
    __ror__: ClassVar[Callable] = ...
    __rxor__: ClassVar[Callable] = ...
    __xor__: ClassVar[Callable] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class BarSpecification:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    aggregation: BarSpecification.aggregation
    price_type: BarSpecification.price_type
    step: BarSpecification.step
    timedelta: BarSpecification.timedelta
    def __init__(self, intstep, BarAggregationaggregation, PriceTypeprice_type) -> None: ...
    @staticmethod
    def check_information_aggregated(BarAggregationaggregation) -> Any: ...
    @staticmethod
    def check_threshold_aggregated(BarAggregationaggregation) -> Any: ...
    @staticmethod
    def check_time_aggregated(BarAggregationaggregation) -> Any: ...
    @staticmethod
    def from_str(strvalue) -> BarSpecification: ...
    @staticmethod
    def from_timedelta(timedeltaduration, PriceTypeprice_type) -> BarSpecification: ...
    def get_interval_ns(self) -> uint64_t: ...
    @overload
    def is_information_aggregated(self) -> bool: ...
    @overload
    def is_information_aggregated(self) -> Any: ...
    @overload
    def is_information_aggregated(self) -> Any: ...
    @overload
    def is_threshold_aggregated(self) -> bool: ...
    @overload
    def is_threshold_aggregated(self) -> Any: ...
    @overload
    def is_threshold_aggregated(self) -> Any: ...
    @overload
    def is_threshold_aggregated(self) -> Any: ...
    @overload
    def is_time_aggregated(self) -> bool: ...
    @overload
    def is_time_aggregated(self) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class BarType:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    aggregation_source: BarType.aggregation_source
    instrument_id: BarType.instrument_id
    spec: BarType.spec
    def __init__(self, InstrumentIdinstrument_id, BarSpecificationbar_spec, AggregationSourceaggregation_source=...) -> None: ...
    def composite(self) -> BarType: ...
    @staticmethod
    def from_str(strvalue) -> BarType: ...
    def id_spec_key(self) -> tuple: ...
    def is_composite(self) -> bool: ...
    def is_externally_aggregated(self) -> bool: ...
    def is_internally_aggregated(self) -> bool: ...
    def is_standard(self) -> bool: ...
    @staticmethod
    def new_composite(InstrumentIdinstrument_id, BarSpecificationbar_spec, AggregationSourceaggregation_source, intcomposite_step, BarAggregationcomposite_aggregation, AggregationSourcecomposite_aggregation_source) -> BarType: ...
    def standard(self) -> BarType: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class BookOrder:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    order_id: BookOrder.order_id
    price: BookOrder.price
    side: BookOrder.side
    size: BookOrder.size
    def __init__(self, OrderSideside, Priceprice, Quantitysize, uint64_torder_id) -> None: ...
    def exposure(self) -> double: ...
    @staticmethod
    def from_dict(dictvalues) -> BookOrder: ...
    @staticmethod
    def from_raw(OrderSideside, PriceRawprice_raw, uint8_tprice_prec, QuantityRawsize_raw, uint8_tsize_prec, uint64_torder_id) -> BookOrder: ...
    def signed_size(self) -> double: ...
    @staticmethod
    def to_dict(BookOrderobj) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class CustomData(nautilus_trader.core.data.Data):
    data: Incomplete
    data_type: Incomplete
    ts_event: CustomData.ts_event
    ts_init: CustomData.ts_init
    def __init__(self, DataTypedata_type, Datadata) -> None: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class DataType:
    identifier: Any
    metadata: Incomplete
    topic: Incomplete
    type: Incomplete
    def __init__(self, typetype, dictmetadata=..., identifier=...) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class FundingRateUpdate(nautilus_trader.core.data.Data):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    instrument_id: Incomplete
    interval: Any
    next_funding_ns: Incomplete
    rate: Incomplete
    ts_event: FundingRateUpdate.ts_event
    ts_init: FundingRateUpdate.ts_init
    def __init__(self, InstrumentIdinstrument_id, rate, uint64_tts_event, uint64_tts_init, interval=..., next_funding_ns=...) -> None: ...
    @staticmethod
    def from_dict(dictvalues) -> FundingRateUpdate: ...
    @staticmethod
    def from_pyo3(pyo3_funding_rate) -> FundingRateUpdate: ...
    @staticmethod
    def from_pyo3_list(listpyo3_funding_rates) -> list[FundingRateUpdate]: ...
    @staticmethod
    def to_dict(FundingRateUpdateobj) -> dict[str, object]: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class IndexPriceUpdate(nautilus_trader.core.data.Data):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    instrument_id: IndexPriceUpdate.instrument_id
    ts_event: IndexPriceUpdate.ts_event
    ts_init: IndexPriceUpdate.ts_init
    value: IndexPriceUpdate.value
    def __init__(self, InstrumentIdinstrument_id, Pricevalue, uint64_tts_event, uint64_tts_init) -> None: ...
    @staticmethod
    def from_dict(dictvalues) -> IndexPriceUpdate: ...
    @staticmethod
    def from_pyo3(pyo3_index_price) -> IndexPriceUpdate: ...
    @staticmethod
    def from_pyo3_list(listpyo3_index_prices) -> list[IndexPriceUpdate]: ...
    @staticmethod
    def to_dict(IndexPriceUpdateobj) -> Any: ...
    def to_pyo3(self) -> nautilus_pyo3.IndexPriceUpdate: ...
    @staticmethod
    def to_pyo3_list(listindex_prices) -> list[nautilus_pyo3.IndexPriceUpdate]: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...

class InstrumentClose(nautilus_trader.core.data.Data):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    close_price: Incomplete
    close_type: Incomplete
    instrument_id: Incomplete
    ts_event: Incomplete
    ts_init: Incomplete
    def __init__(self, InstrumentIdinstrument_id, Priceclose_price, InstrumentCloseTypeclose_type, uint64_tts_event, uint64_tts_init) -> None: ...
    @staticmethod
    def from_dict(dictvalues) -> InstrumentClose: ...
    @staticmethod
    def from_pyo3(pyo3_close) -> InstrumentClose: ...
    @staticmethod
    def from_pyo3_list(listpyo3_closes) -> list[InstrumentClose]: ...
    @staticmethod
    def to_dict(InstrumentCloseobj) -> Any: ...
    def to_pyo3(self) -> nautilus_pyo3.InstrumentClose: ...
    @staticmethod
    def to_pyo3_list(listcloses) -> list[nautilus_pyo3.InstrumentClose]: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class InstrumentStatus(nautilus_trader.core.data.Data):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    action: Incomplete
    instrument_id: Incomplete
    is_quoting: InstrumentStatus.is_quoting
    is_short_sell_restricted: InstrumentStatus.is_short_sell_restricted
    is_trading: InstrumentStatus.is_trading
    reason: Incomplete
    trading_event: Incomplete
    ts_event: Incomplete
    ts_init: Incomplete
    def __init__(self, InstrumentIdinstrument_id, MarketStatusActionaction, uint64_tts_event, uint64_tts_init, strreason=..., strtrading_event=..., boolis_trading: bool | None = ..., boolis_quoting: bool | None = ..., boolis_short_sell_restricted: bool | None = ...) -> None: ...
    @staticmethod
    def from_dict(dictvalues) -> InstrumentStatus: ...
    @staticmethod
    def from_pyo3(pyo3_status) -> InstrumentStatus: ...
    @staticmethod
    def from_pyo3_list(listpyo3_status_list) -> list[QuoteTick]: ...
    @staticmethod
    def to_dict(InstrumentStatusobj) -> Any: ...
    def to_pyo3(self) -> nautilus_pyo3.InstrumentStatus: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class MarkPriceUpdate(nautilus_trader.core.data.Data):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    instrument_id: MarkPriceUpdate.instrument_id
    ts_event: MarkPriceUpdate.ts_event
    ts_init: MarkPriceUpdate.ts_init
    value: MarkPriceUpdate.value
    def __init__(self, InstrumentIdinstrument_id, Pricevalue, uint64_tts_event, uint64_tts_init) -> None: ...
    @staticmethod
    def from_dict(dictvalues) -> MarkPriceUpdate: ...
    @staticmethod
    def from_pyo3(pyo3_mark_price) -> MarkPriceUpdate: ...
    @staticmethod
    def from_pyo3_list(listpyo3_mark_prices) -> list[MarkPriceUpdate]: ...
    @staticmethod
    def to_dict(MarkPriceUpdateobj) -> Any: ...
    def to_pyo3(self) -> nautilus_pyo3.MarkPriceUpdate: ...
    @staticmethod
    def to_pyo3_list(listmark_prices) -> list[nautilus_pyo3.MarkPriceUpdate]: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...

class OptionGreeks(nautilus_trader.core.data.Data):
    ask_iv: Incomplete
    bid_iv: Incomplete
    convention: Incomplete
    delta: Incomplete
    gamma: Incomplete
    instrument_id: Incomplete
    mark_iv: Incomplete
    open_interest: Incomplete
    rho: Incomplete
    theta: Incomplete
    ts_event: Incomplete
    ts_init: Incomplete
    underlying_price: Incomplete
    vega: Incomplete
    def __init__(self, InstrumentIdinstrument_id, doubledelta, doublegamma, doublevega, doubletheta, doublerho, mark_iv, bid_iv, ask_iv, underlying_price, open_interest, uint64_tts_event, uint64_tts_init, convention=...) -> None: ...
    @staticmethod
    def from_pyo3(pyo3_greeks) -> OptionGreeks: ...
    def to_pyo3(self) -> nautilus_pyo3.OptionGreeks: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class OrderBookDelta(nautilus_trader.core.data.Data):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    action: OrderBookDelta.action
    flags: OrderBookDelta.flags
    instrument_id: OrderBookDelta.instrument_id
    is_add: OrderBookDelta.is_add
    is_clear: OrderBookDelta.is_clear
    is_delete: OrderBookDelta.is_delete
    is_update: OrderBookDelta.is_update
    order: OrderBookDelta.order
    sequence: OrderBookDelta.sequence
    ts_event: OrderBookDelta.ts_event
    ts_init: OrderBookDelta.ts_init
    def __init__(self, InstrumentIdinstrument_id, BookActionaction, BookOrderorder: BookOrder | None, uint8_tflags, uint64_tsequence, uint64_tts_event, uint64_tts_init) -> None: ...
    @staticmethod
    def capsule_from_list(listitems) -> Any: ...
    @staticmethod
    def clear(InstrumentIdinstrument_id, uint64_tsequence, uint64_tts_event, uint64_tts_init) -> Any: ...
    @staticmethod
    def from_dict(dictvalues) -> OrderBookDelta: ...
    @staticmethod
    def from_pyo3(pyo3_delta) -> OrderBookDelta: ...
    @staticmethod
    def from_pyo3_list(listpyo3_deltas) -> list[OrderBookDelta]: ...
    @staticmethod
    def from_raw(InstrumentIdinstrument_id, BookActionaction, OrderSideside, PriceRawprice_raw, uint8_tprice_prec, QuantityRawsize_raw, uint8_tsize_prec, uint64_torder_id, uint8_tflags, uint64_tsequence, uint64_tts_event, uint64_tts_init) -> OrderBookDelta: ...
    @staticmethod
    def list_from_capsule(capsule) -> list[OrderBookDelta]: ...
    @staticmethod
    def to_dict(OrderBookDeltaobj) -> Any: ...
    @staticmethod
    def to_pyo3_list(listdeltas) -> list[nautilus_pyo3.OrderBookDelta]: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class OrderBookDeltas(nautilus_trader.core.data.Data):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    deltas: OrderBookDeltas.deltas
    flags: OrderBookDeltas.flags
    instrument_id: OrderBookDeltas.instrument_id
    is_snapshot: OrderBookDeltas.is_snapshot
    sequence: OrderBookDeltas.sequence
    ts_event: OrderBookDeltas.ts_event
    ts_init: OrderBookDeltas.ts_init
    # Constructor hand-ported from data.pyx (stubgen mangles cdef names).
    def __init__(self, instrument_id: InstrumentId, deltas: list) -> None: ...
    @staticmethod
    def batch(listdata: list[OrderBookDelta]) -> list[OrderBookDeltas]: ...
    @staticmethod
    def from_dict(dictvalues) -> OrderBookDeltas: ...
    @staticmethod
    def from_pyo3(pyo3_deltas) -> OrderBookDeltas: ...
    def to_capsule(self) -> Any: ...
    @staticmethod
    def to_dict(OrderBookDeltasobj) -> Any: ...
    def to_pyo3(self) -> Any: ...
    def __del__(self, *args, **kwargs) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class OrderBookDepth10(nautilus_trader.core.data.Data):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    ask_counts: OrderBookDepth10.ask_counts
    asks: OrderBookDepth10.asks
    bid_counts: OrderBookDepth10.bid_counts
    bids: OrderBookDepth10.bids
    flags: OrderBookDepth10.flags
    instrument_id: OrderBookDepth10.instrument_id
    sequence: OrderBookDepth10.sequence
    ts_event: OrderBookDepth10.ts_event
    ts_init: OrderBookDepth10.ts_init
    def __init__(self, InstrumentIdinstrument_id, listbids, listasks, listbid_counts, listask_counts, uint8_tflags, uint64_tsequence, uint64_tts_event, uint64_tts_init) -> None: ...
    @staticmethod
    def capsule_from_list(listitems) -> Any: ...
    @staticmethod
    def from_dict(dictvalues) -> OrderBookDepth10: ...
    @staticmethod
    def from_pyo3(pyo3_depth) -> OrderBookDepth10: ...
    @staticmethod
    def from_pyo3_list(pyo3_depths) -> list[OrderBookDepth10]: ...
    @staticmethod
    def list_from_capsule(capsule) -> list[OrderBookDepth10]: ...
    @staticmethod
    def to_dict(OrderBookDepth10obj) -> Any: ...
    def to_quote_tick(self) -> QuoteTick: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class QuoteTick(nautilus_trader.core.data.Data):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    ask_price: QuoteTick.ask_price
    ask_size: QuoteTick.ask_size
    bid_price: QuoteTick.bid_price
    bid_size: QuoteTick.bid_size
    instrument_id: QuoteTick.instrument_id
    ts_event: QuoteTick.ts_event
    ts_init: QuoteTick.ts_init
    def __init__(self, InstrumentIdinstrument_id, Pricebid_price, Priceask_price, Quantitybid_size, Quantityask_size, uint64_tts_event, uint64_tts_init) -> None: ...
    @staticmethod
    def capsule_from_list(listitems) -> Any: ...
    def extract_price(self, PriceTypeprice_type) -> Price: ...
    def extract_size(self, PriceTypeprice_type) -> Quantity: ...
    @staticmethod
    def from_dict(dictvalues) -> QuoteTick: ...
    @staticmethod
    def from_pyo3(pyo3_quote) -> QuoteTick: ...
    @staticmethod
    def from_pyo3_list(listpyo3_quotes) -> list[QuoteTick]: ...
    @staticmethod
    def from_raw(InstrumentIdinstrument_id, PriceRawbid_price_raw, PriceRawask_price_raw, uint8_tbid_price_prec, uint8_task_price_prec, QuantityRawbid_size_raw, QuantityRawask_size_raw, uint8_tbid_size_prec, uint8_task_size_prec, uint64_tts_event, uint64_tts_init) -> QuoteTick: ...
    @staticmethod
    def from_raw_arrays_to_list(InstrumentIdinstrument_id: InstrumentId, intprice_prec: int, intsize_prec: int, bid_prices_raw: np.ndarray, ask_prices_raw: np.ndarray, bid_sizes_raw: np.ndarray, ask_sizes_raw: np.ndarray, ts_events: np.ndarray, ts_inits: np.ndarray) -> list[QuoteTick]: ...
    @staticmethod
    def list_from_capsule(capsule) -> list[QuoteTick]: ...
    @staticmethod
    def to_dict(QuoteTickobj) -> Any: ...
    def to_pyo3(self) -> nautilus_pyo3.QuoteTick: ...
    @staticmethod
    def to_pyo3_list(listquotes) -> list[nautilus_pyo3.QuoteTick]: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class TradeTick(nautilus_trader.core.data.Data):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    aggressor_side: TradeTick.aggressor_side
    instrument_id: TradeTick.instrument_id
    price: TradeTick.price
    size: TradeTick.size
    trade_id: TradeTick.trade_id
    ts_event: TradeTick.ts_event
    ts_init: TradeTick.ts_init
    def __init__(self, InstrumentIdinstrument_id, Priceprice, Quantitysize, AggressorSideaggressor_side, TradeIdtrade_id, uint64_tts_event, uint64_tts_init) -> None: ...
    @staticmethod
    def capsule_from_list(items) -> Any: ...
    @staticmethod
    def from_dict(dictvalues) -> TradeTick: ...
    @staticmethod
    def from_pyo3(pyo3_trade) -> TradeTick: ...
    @staticmethod
    def from_pyo3_list(listpyo3_trades) -> list[TradeTick]: ...
    @staticmethod
    def from_raw(InstrumentIdinstrument_id, PriceRawprice_raw, uint8_tprice_prec, QuantityRawsize_raw, uint8_tsize_prec, AggressorSideaggressor_side, TradeIdtrade_id, uint64_tts_event, uint64_tts_init) -> TradeTick: ...
    @staticmethod
    def from_raw_arrays_to_list(*args, **kwargs): ...
    @staticmethod
    def list_from_capsule(capsule) -> list[TradeTick]: ...
    @staticmethod
    def to_dict(TradeTickobj) -> Any: ...
    def to_pyo3(self) -> nautilus_pyo3.TradeTick: ...
    @staticmethod
    def to_pyo3_list(listtrades) -> list[nautilus_pyo3.TradeTick]: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
