from nautilus_trader.core.rust.model import AssetClass as AssetClass, InstrumentClass as InstrumentClass, PriceType as PriceType
from nautilus_trader.model.greeks_data import GreeksData as GreeksData, PortfolioGreeks as PortfolioGreeks
from typing import Any, ClassVar

__test__: dict

class GreeksCalculator:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, CacheFacadecache, Clockclock) -> None: ...
    def cache_futures_spread(self, InstrumentIdcall_instrument_id, InstrumentIdput_instrument_id, InstrumentIdfutures_instrument_id) -> Any: ...
    def get_cached_futures_spread_price(self, InstrumentIdunderlying_instrument_id) -> Any: ...
    def instrument_greeks(self, InstrumentIdinstrument_id: InstrumentId, doubleflat_interest_rate: float = ..., floatflat_dividend_yield: float | None = ..., doublespot_shock: float = ..., doublevol_shock: float = ..., doubletime_to_expiry_shock: float = ..., booluse_cached_greeks: bool = ..., boolupdate_vol: bool = ..., boolcache_greeks: bool = ..., intts_event: int = ..., Positionposition: Position | None = ..., boolpercent_greeks: bool = ..., InstrumentIdindex_instrument_id: InstrumentId | None = ..., dictbeta_weights: dict[InstrumentId, float] | None = ..., intvega_time_weight_base: int | None = ..., InstrumentIdvol_index_instrument_id: InstrumentId | None = ..., dictvol_beta_weights: dict[InstrumentId, float] | None = ...) -> GreeksData | None: ...
    def modify_greeks(self, doubledelta_input: float, doublegamma_input: float, InstrumentIdunderlying_instrument_id: InstrumentId, doubleunderlying_price: float, doubleunshocked_underlying_price: float, boolpercent_greeks: bool, InstrumentIdindex_instrument_id: InstrumentId | None, dictbeta_weights: dict[InstrumentId, float] | None, doublevega_input: float = ..., doublevol: float = ..., intexpiry_in_days: int = ..., intvega_time_weight_base: int | None = ..., doubleunshocked_vol: float = ..., InstrumentIdvol_index_instrument_id: InstrumentId | None = ..., dictvol_beta_weights: dict[InstrumentId, float] | None = ..., floatindex_price: float | None = ..., floatvol_index_price: float | None = ...) -> tuple[float, float, float]: ...
    def portfolio_greeks(self, listunderlyings: list[str] = ..., Venuevenue=..., InstrumentIdinstrument_id=..., StrategyIdstrategy_id=..., PositionSideside=..., doubleflat_interest_rate: float = ..., floatflat_dividend_yield: float | None = ..., doublespot_shock: float = ..., doublevol_shock: float = ..., doubletime_to_expiry_shock: float = ..., booluse_cached_greeks: bool = ..., boolupdate_vol: bool = ..., boolcache_greeks: bool = ..., boolpercent_greeks: bool = ..., InstrumentIdindex_instrument_id: InstrumentId | None = ..., dictbeta_weights: dict[InstrumentId, float] | None = ..., greeks_filter: callable | None = ..., intvega_time_weight_base: int | None = ..., InstrumentIdvol_index_instrument_id: InstrumentId | None = ..., dictvol_beta_weights: dict[InstrumentId, float] | None = ...) -> PortfolioGreeks | None: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
