import _cython_3_2_9
import decimal
from _typeshed import Incomplete
from typing import Any, ClassVar

FIXED_PRECISION: int
FIXED_PRECISION_BYTES: int
FIXED_SCALAR: float
HIGH_PRECISION: bool
MONEY_MAX: float
MONEY_MIN: float
PRICE_MAX: float
PRICE_MIN: float
QUANTITY_MAX: float
QUANTITY_MIN: float
__reduce_cython__: _cython_3_2_9.cython_function_or_method
__setstate_cython__: _cython_3_2_9.cython_function_or_method
__test__: dict

class AccountBalance:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    currency: Incomplete
    free: Incomplete
    locked: Any
    total: Incomplete
    def __init__(self, Moneytotal, Moneylocked, Moneyfree) -> None: ...
    def copy(self) -> AccountBalance: ...
    @staticmethod
    def from_dict(dictvalues) -> AccountBalance: ...
    def to_dict(self) -> dict: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class Currency:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    code: Currency.code
    currency_type: Currency.currency_type
    iso4217: Currency.iso4217
    name: Currency.name
    precision: Currency.precision
    def __init__(self, strcode, uint8_tprecision, uint16_tiso4217, strname, CurrencyTypecurrency_type) -> None: ...
    @staticmethod
    def from_internal_map(strcode) -> Any: ...
    @staticmethod
    def from_str(strcode, boolstrict=...) -> Any: ...
    @staticmethod
    def is_crypto(strcode) -> Any: ...
    @staticmethod
    def is_fiat(strcode) -> Any: ...
    @staticmethod
    def register(Currencycurrency, booloverwrite=...) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class MarginBalance:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    currency: Incomplete
    initial: Incomplete
    instrument_id: Incomplete
    maintenance: Incomplete
    def __init__(self, Moneyinitial, Moneymaintenance, InstrumentIdinstrument_id=...) -> None: ...
    def copy(self) -> MarginBalance: ...
    @staticmethod
    def from_dict(dictvalues) -> MarginBalance: ...
    def to_dict(self) -> dict: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class Money:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    currency: Money.currency
    raw: Money.raw
    def __init__(self, value, Currencycurrency) -> None: ...
    def as_decimal(self) -> Any: ...
    def as_double(self) -> double: ...
    @staticmethod
    def from_decimal(amount: decimal.Decimal, Currencycurrency) -> Money: ...
    @staticmethod
    def from_raw(intraw: int, Currencycurrency) -> Money: ...
    @staticmethod
    def from_str(strvalue) -> Money: ...
    def to_formatted_str(self) -> str: ...
    def __abs__(self): ...
    def __add__(self, other): ...
    def __eq__(self, other: object) -> bool: ...
    def __float__(self) -> float: ...
    def __floordiv__(self, other): ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __mod__(self, other): ...
    def __mul__(self, other): ...
    def __ne__(self, other: object) -> bool: ...
    def __neg__(self): ...
    def __pos__(self): ...
    def __radd__(self, other): ...
    def __reduce_cython__(self) -> Any: ...
    def __rfloordiv__(self, other): ...
    def __rmod__(self, other): ...
    def __rmul__(self, other): ...
    def __round__(self, ndigits=...) -> decimal.Decimal: ...
    def __rsub__(self, other): ...
    def __rtruediv__(self, other): ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
    def __sub__(self, other): ...
    def __truediv__(self, other): ...

class Price:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    precision: Price.precision
    raw: Price.raw
    def __init__(self, doublevalue, uint8_tprecision) -> None: ...
    def as_decimal(self) -> Any: ...
    def as_double(self) -> double: ...
    @staticmethod
    def from_decimal(value: decimal.Decimal) -> Price: ...
    @staticmethod
    def from_int(intvalue: int) -> Price: ...
    @staticmethod
    def from_raw(intraw: int, uint8_tprecision) -> Price: ...
    @staticmethod
    def from_str(strvalue) -> Price: ...
    def to_formatted_str(self) -> str: ...
    def __abs__(self): ...
    def __add__(self, other): ...
    def __eq__(self, other: object) -> bool: ...
    def __float__(self) -> float: ...
    def __floordiv__(self, other): ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __mod__(self, other): ...
    def __mul__(self, other): ...
    def __ne__(self, other: object) -> bool: ...
    def __neg__(self): ...
    def __pos__(self): ...
    def __radd__(self, other): ...
    def __reduce_cython__(self) -> Any: ...
    def __rfloordiv__(self, other): ...
    def __rmod__(self, other): ...
    def __rmul__(self, other): ...
    def __round__(self, ndigits=...) -> decimal.Decimal: ...
    def __rsub__(self, other): ...
    def __rtruediv__(self, other): ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
    def __sub__(self, other): ...
    def __truediv__(self, other): ...

class Quantity:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    precision: Quantity.precision
    raw: Quantity.raw
    def __init__(self, doublevalue, uint8_tprecision) -> None: ...
    def as_decimal(self) -> Any: ...
    def as_double(self) -> double: ...
    @staticmethod
    def from_decimal(value: decimal.Decimal) -> Quantity: ...
    @staticmethod
    def from_int(intvalue: int) -> Quantity: ...
    @staticmethod
    def from_raw(intraw: int, uint8_tprecision) -> Quantity: ...
    @staticmethod
    def from_str(strvalue) -> Quantity: ...
    @staticmethod
    def raw_to_f64(raw) -> float: ...
    def saturating_sub(self, Quantityother) -> Quantity: ...
    def to_formatted_str(self) -> str: ...
    @staticmethod
    def zero(uint8_tprecision=...) -> Quantity: ...
    def __abs__(self): ...
    def __add__(self, other): ...
    def __eq__(self, other: object) -> bool: ...
    def __float__(self) -> float: ...
    def __floordiv__(self, other): ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __mod__(self, other): ...
    def __mul__(self, other): ...
    def __ne__(self, other: object) -> bool: ...
    def __neg__(self): ...
    def __pos__(self): ...
    def __radd__(self, other): ...
    def __reduce_cython__(self) -> Any: ...
    def __rfloordiv__(self, other): ...
    def __rmod__(self, other): ...
    def __rmul__(self, other): ...
    def __round__(self, ndigits=...) -> decimal.Decimal: ...
    def __rsub__(self, other): ...
    def __rtruediv__(self, other): ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
    def __sub__(self, other): ...
    def __truediv__(self, other): ...
