from _typeshed import Incomplete
from typing import Any, ClassVar

__test__: dict

class Position:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    account_id: Incomplete
    adjustments: Incomplete
    avg_px_close: Incomplete
    avg_px_open: Incomplete
    base_currency: Incomplete
    client_order_ids: Incomplete
    closing_order_id: Incomplete
    duration_ns: Incomplete
    entry: Incomplete
    event_count: Incomplete
    events: Incomplete
    id: Incomplete
    instrument_class: Incomplete
    instrument_id: Incomplete
    is_closed: Incomplete
    is_inverse: Incomplete
    is_long: Incomplete
    is_open: Incomplete
    is_short: Incomplete
    is_spot_currency: Incomplete
    last_event: Incomplete
    last_trade_id: Incomplete
    multiplier: Incomplete
    opening_order_id: Incomplete
    peak_qty: Incomplete
    price_precision: Incomplete
    quantity: Incomplete
    quote_currency: Incomplete
    realized_pnl: Incomplete
    realized_return: Incomplete
    settlement_currency: Incomplete
    side: Incomplete
    signed_qty: Incomplete
    size_precision: Incomplete
    strategy_id: Incomplete
    symbol: Incomplete
    trade_ids: Incomplete
    trader_id: Incomplete
    ts_closed: Incomplete
    ts_init: Incomplete
    ts_last: Incomplete
    ts_opened: Incomplete
    venue: Incomplete
    venue_order_ids: Incomplete
    def __init__(self, Instrumentinstrument, OrderFilledfill) -> None: ...
    def apply(self, OrderFilledfill) -> void: ...
    def apply_adjustment(self, PositionAdjustedadjustment) -> void: ...
    def calculate_pnl(self, doubleavg_px_open, doubleavg_px_close, Quantityquantity) -> Money: ...
    def closing_order_side(self) -> OrderSide: ...
    def commissions(self) -> list: ...
    def cross_notional_value(self, Priceprice, Pricequote_price, Pricebase_price, Currencytarget_currency) -> Money: ...
    def info(self) -> str: ...
    def is_opposite_side(self, OrderSideside) -> bool: ...
    def notional_value(self, Priceprice, Currencytarget_currency=..., Priceconversion_price=...) -> Money: ...
    def purge_events_for_order(self, ClientOrderIdclient_order_id) -> None: ...
    @staticmethod
    def side_from_order_side(OrderSideside) -> Any: ...
    def signed_decimal_qty(self) -> Any: ...
    def to_dict(self) -> dict: ...
    def total_pnl(self, Priceprice) -> Money: ...
    def unrealized_pnl(self, Priceprice) -> Money: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
