from nautilus_trader.adapters.hyperliquid.enums import HyperliquidProductType as HyperliquidProductType
from nautilus_trader.common.config import PositiveInt as PositiveInt
from nautilus_trader.config import LiveDataClientConfig as LiveDataClientConfig, LiveExecClientConfig as LiveExecClientConfig
from nautilus_trader.core.nautilus_pyo3 import HyperliquidEnvironment as HyperliquidEnvironment
from nautilus_trader.network import TransportBackend as TransportBackend

class HyperliquidDataClientConfig(LiveDataClientConfig, frozen=True):
    product_types: tuple[HyperliquidProductType, ...] | None = ...
    environment: HyperliquidEnvironment | None = ...
    base_url_ws: str | None = ...
    proxy_url: str | None = ...
    transport_backend: TransportBackend | None = ...
    http_timeout_secs: PositiveInt = ...

class HyperliquidExecClientConfig(LiveExecClientConfig, frozen=True):
    private_key: str | None = ...
    vault_address: str | None = ...
    account_address: str | None = ...
    product_types: tuple[HyperliquidProductType, ...] | None = ...
    environment: HyperliquidEnvironment | None = ...
    base_url_ws: str | None = ...
    proxy_url: str | None = ...
    transport_backend: TransportBackend | None = ...
    max_retries: PositiveInt | None = ...
    retry_delay_initial_ms: PositiveInt | None = ...
    retry_delay_max_ms: PositiveInt | None = ...
    http_timeout_secs: PositiveInt = ...
    ws_post_timeout_secs: PositiveInt = ...
    normalize_prices: bool = ...
    include_builder_attribution: bool = ...
