from nautilus_trader.adapters.binance.common.constants import BINANCE_VENUE as BINANCE_VENUE
from nautilus_trader.adapters.binance.common.enums import BinanceAccountType as BinanceAccountType, BinanceEnvironment as BinanceEnvironment, BinanceKeyType as BinanceKeyType
from nautilus_trader.adapters.binance.common.symbol import BinanceSymbol as BinanceSymbol
from nautilus_trader.adapters.binance.futures.enums import BinanceFuturesMarginType as BinanceFuturesMarginType
from nautilus_trader.config import InstrumentProviderConfig as InstrumentProviderConfig, LiveDataClientConfig as LiveDataClientConfig, LiveExecClientConfig as LiveExecClientConfig, PositiveInt as PositiveInt
from nautilus_trader.model.identifiers import Venue as Venue
from nautilus_trader.network import TransportBackend as TransportBackend

class BinanceInstrumentProviderConfig(InstrumentProviderConfig, frozen=True):
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    query_commission_rates: bool = ...

class BinanceDataClientConfig(LiveDataClientConfig, frozen=True):
    venue: Venue = ...
    api_key: str | None = ...
    api_secret: str | None = ...
    key_type: BinanceKeyType = ...
    account_type: BinanceAccountType = ...
    environment: BinanceEnvironment | None = ...
    base_url_http: str | None = ...
    base_url_ws: str | None = ...
    proxy_url: str | None = ...
    transport_backend: TransportBackend | None = ...
    us: bool = ...
    update_instruments_interval_mins: PositiveInt | None = ...
    use_agg_trade_ticks: bool = ...

class BinanceExecClientConfig(LiveExecClientConfig, frozen=True):
    venue: Venue = ...
    api_key: str | None = ...
    api_secret: str | None = ...
    key_type: BinanceKeyType = ...
    account_type: BinanceAccountType = ...
    environment: BinanceEnvironment | None = ...
    base_url_http: str | None = ...
    base_url_ws: str | None = ...
    base_url_ws_stream: str | None = ...
    proxy_url: str | None = ...
    transport_backend: TransportBackend | None = ...
    us: bool = ...
    use_gtd: bool = ...
    use_reduce_only: bool = ...
    use_position_ids: bool = ...
    use_trade_lite: bool = ...
    treat_expired_as_canceled: bool = ...
    recv_window_ms: PositiveInt = ...
    max_retries: PositiveInt | None = ...
    retry_delay_initial_ms: PositiveInt | None = ...
    retry_delay_max_ms: PositiveInt | None = ...
    futures_leverages: dict[BinanceSymbol, PositiveInt] | None = ...
    futures_margin_types: dict[BinanceSymbol, BinanceFuturesMarginType] | None = ...
    log_rejected_due_post_only_as_warning: bool = ...
