from decimal import Decimal
from ibapi.contract import FundAssetType, FundDistributionPolicyIndicator
from ibapi.tag_value import TagValue
from nautilus_trader.config import NautilusConfig as NautilusConfig
from nautilus_trader.model.identifiers import ClientId as ClientId, Venue as Venue
from typing import Final, Literal

IB: Final[str]
IB_VENUE: Final[Venue]
IB_CLIENT_ID: Final[ClientId]

class ContractId(int): ...

class ComboLeg(NautilusConfig, frozen=True, omit_defaults=True, repr_omit_defaults=True):
    conId: int = ...
    ratio: int = ...
    action: str = ...
    exchange: str = ...
    openClose: int = ...
    shortSaleSlot: int = ...
    designatedLocation: str = ...
    exemptCode: int = ...

class DeltaNeutralContract(NautilusConfig, frozen=True, repr_omit_defaults=True):
    conId: int = ...
    delta: float = ...
    price: float = ...

class IBContract(NautilusConfig, frozen=True, repr_omit_defaults=True):
    secType: Literal['CASH', 'STK', 'OPT', 'FUT', 'FOP', 'CONTFUT', 'CRYPTO', 'CFD', 'CMDTY', 'IND', 'BAG', ''] = ...
    conId: int = ...
    exchange: str = ...
    primaryExchange: str = ...
    symbol: str = ...
    localSymbol: str = ...
    currency: str = ...
    tradingClass: str = ...
    lastTradeDateOrContractMonth: str = ...
    lastTradeDate: str = ...
    multiplier: str = ...
    strike: float = ...
    right: str = ...
    includeExpired: bool = ...
    secIdType: str = ...
    secId: str = ...
    description: str = ...
    issuerId: str = ...
    comboLegsDescrip: str = ...
    comboLegs: list[ComboLeg] | None = ...
    deltaNeutralContract: DeltaNeutralContract | None = ...
    build_futures_chain: bool | None = ...
    build_options_chain: bool | None = ...
    options_chain_exchange: str | None = ...
    min_expiry_days: int | None = ...
    max_expiry_days: int | None = ...
    def __post_init__(self) -> None: ...

class IBOrderTags(NautilusConfig, frozen=True, repr_omit_defaults=True):
    whatIf: bool = ...
    ocaGroup: str = ...
    ocaType: int = ...
    allOrNone: bool = ...
    activeStartTime: str = ...
    activeStopTime: str = ...
    goodAfterTime: str = ...
    blockOrder = ...
    sweepToFill = ...
    outsideRth: bool = ...
    hidden: bool = ...
    conditions: list[dict] = ...
    conditionsCancelOrder: bool = ...
    NonGuaranteed: bool = ...
    @property
    def value(self): ...

class IBContractDetails(NautilusConfig, frozen=True, repr_omit_defaults=True):
    contract: IBContract | None = ...
    marketName: str = ...
    minTick: float = ...
    orderTypes: str = ...
    validExchanges: str = ...
    priceMagnifier: int = ...
    underConId: int = ...
    longName: str = ...
    contractMonth: str = ...
    industry: str = ...
    category: str = ...
    subcategory: str = ...
    timeZoneId: str = ...
    tradingHours: str = ...
    liquidHours: str = ...
    evRule: str = ...
    evMultiplier: float = ...
    mdSizeMultiplier: int = ...
    aggGroup: int = ...
    underSymbol: str = ...
    underSecType: str = ...
    marketRuleIds: str = ...
    secIdList: list[TagValue] | None = ...
    realExpirationDate: str = ...
    lastTradeTime: str = ...
    stockType: str = ...
    minSize: Decimal = ...
    sizeIncrement: Decimal = ...
    suggestedSizeIncrement: Decimal = ...
    minAlgoSize: Decimal = ...
    lastPricePrecision: Decimal = ...
    lastSizePrecision: Decimal = ...
    cusip: str = ...
    ratings: str = ...
    descAppend: str = ...
    bondType: str = ...
    couponType: str = ...
    callable: bool = ...
    putable: bool = ...
    coupon: float = ...
    convertible: bool = ...
    maturity: str = ...
    issueDate: str = ...
    nextOptionDate: str = ...
    nextOptionType: str = ...
    nextOptionPartial: bool = ...
    notes: str = ...
    fundName: str = ...
    fundFamily: str = ...
    fundType: str = ...
    fundFrontLoad: str = ...
    fundBackLoad: str = ...
    fundBackLoadTimeInterval: str = ...
    fundManagementFee: str = ...
    fundClosed: bool = ...
    fundClosedForNewInvestors: bool = ...
    fundClosedForNewMoney: bool = ...
    fundNotifyAmount: str = ...
    fundMinimumInitialPurchase: str = ...
    fundSubsequentMinimumPurchase: str = ...
    fundBlueSkyStates: str = ...
    fundBlueSkyTerritories: str = ...
    fundDistributionPolicyIndicator: FundDistributionPolicyIndicator = ...
    fundAssetType: FundAssetType = ...
    ineligibilityReasonList: list = ...
    eventContract1: str = ...
    eventContractDescription1: str = ...
    eventContractDescription2: str = ...
    @classmethod
    def from_contract_details(cls, contract_details) -> IBContractDetails: ...

def dict_to_contract_details(dict_details: dict) -> IBContractDetails: ...
