from enum import Enum
from ibapi.common import MarketDataTypeEnum as IBMarketDataTypeEnum
from nautilus_trader.adapters.interactive_brokers.common import IBContract as IBContract
from nautilus_trader.config import InstrumentProviderConfig as InstrumentProviderConfig, LiveDataClientConfig as LiveDataClientConfig, LiveExecClientConfig as LiveExecClientConfig, NautilusConfig as NautilusConfig
from typing import Literal

class SymbologyMethod(Enum):
    IB_SIMPLIFIED = 'simplified'
    IB_RAW = 'raw'

class DockerizedIBGatewayConfig(NautilusConfig, frozen=True):
    username: str | None = ...
    password: str | None = ...
    trading_mode: Literal['paper', 'live'] = ...
    read_only_api: bool = ...
    timeout: int = ...
    container_image: str = ...
    vnc_port: int | None = ...

class InteractiveBrokersInstrumentProviderConfig(InstrumentProviderConfig, frozen=True):
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    symbology_method: SymbologyMethod = ...
    load_contracts: frozenset[IBContract] | None = ...
    build_options_chain: bool | None = ...
    build_futures_chain: bool | None = ...
    min_expiry_days: int | None = ...
    max_expiry_days: int | None = ...
    convert_exchange_to_mic_venue: bool = ...
    symbol_to_mic_venue: dict = ...
    cache_validity_days: int | None = ...
    pickle_path: str | None = ...
    filter_sec_types: frozenset[str] = ...

class InteractiveBrokersDataClientConfig(LiveDataClientConfig, frozen=True):
    instrument_provider: InteractiveBrokersInstrumentProviderConfig = ...
    ibg_host: str = ...
    ibg_port: int | None = ...
    ibg_client_id: int = ...
    use_regular_trading_hours: bool = ...
    market_data_type: IBMarketDataTypeEnum = ...
    ignore_quote_tick_size_updates: bool = ...
    dockerized_gateway: DockerizedIBGatewayConfig | None = ...
    connection_timeout: int = ...
    request_timeout_secs: int = ...

class InteractiveBrokersExecClientConfig(LiveExecClientConfig, frozen=True):
    instrument_provider: InteractiveBrokersInstrumentProviderConfig = ...
    ibg_host: str = ...
    ibg_port: int | None = ...
    ibg_client_id: int = ...
    account_id: str | None = ...
    dockerized_gateway: DockerizedIBGatewayConfig | None = ...
    connection_timeout: int = ...
    request_timeout_secs: int = ...
    fetch_all_open_orders: bool = ...
    track_option_exercise_from_position_update: bool = ...
