import pandas as pd
from _typeshed import Incomplete
from ibapi.contract import ContractDetails as ContractDetails
from nautilus_trader.adapters.interactive_brokers.client import InteractiveBrokersClient as InteractiveBrokersClient
from nautilus_trader.adapters.interactive_brokers.common import ComboLeg as ComboLeg, IBContract as IBContract, IBContractDetails as IBContractDetails, dict_to_contract_details as dict_to_contract_details
from nautilus_trader.adapters.interactive_brokers.config import InteractiveBrokersInstrumentProviderConfig as InteractiveBrokersInstrumentProviderConfig
from nautilus_trader.adapters.interactive_brokers.parsing.instruments import exchange_to_mic_venue as exchange_to_mic_venue, instrument_id_to_ib_contract as instrument_id_to_ib_contract, parse_futures_spread_instrument_id as parse_futures_spread_instrument_id, parse_instrument as parse_instrument, parse_option_spread_instrument_id as parse_option_spread_instrument_id, possible_exchanges_for_venue as possible_exchanges_for_venue
from nautilus_trader.common.component import Clock as Clock
from nautilus_trader.common.providers import InstrumentProvider as InstrumentProvider
from nautilus_trader.config import resolve_path as resolve_path
from nautilus_trader.model.identifiers import InstrumentId as InstrumentId, generic_spread_id_to_list as generic_spread_id_to_list, is_generic_spread_id as is_generic_spread_id, new_generic_spread_id as new_generic_spread_id
from nautilus_trader.model.instruments import Instrument as Instrument

class InteractiveBrokersInstrumentProvider(InstrumentProvider):
    config: Incomplete
    contract_details: dict[InstrumentId, IBContractDetails]
    contract_id_to_instrument_id: dict[int, InstrumentId]
    contract: dict[InstrumentId, IBContract]
    def __init__(self, client: InteractiveBrokersClient, clock: Clock, config: InteractiveBrokersInstrumentProviderConfig) -> None: ...
    async def initialize(self, reload: bool = False) -> None: ...
    @property
    def filter_sec_types(self) -> set[str]: ...
    async def get_instrument(self, contract: IBContract) -> Instrument | None: ...
    async def instrument_id_to_ib_contract(self, instrument_id: InstrumentId) -> IBContract | None: ...
    async def instrument_id_to_ib_contract_details(self, instrument_id: InstrumentId) -> IBContractDetails | None: ...
    def get_price_magnifier(self, instrument_id: InstrumentId) -> int: ...
    async def load_all_async(self, filters: dict | None = None) -> None: ...
    async def load_ids_async(self, instrument_ids: list[InstrumentId], filters: dict | None = None) -> None: ...
    async def load_ids_with_return_async(self, instrument_ids: list[InstrumentId], filters: dict | None = None) -> list[InstrumentId]: ...
    async def load_async(self, instrument_id: InstrumentId, filters: dict | None = None) -> None: ...
    async def load_with_return_async(self, instrument_id: InstrumentId | IBContract, filters: dict | None = None) -> list[InstrumentId] | None: ...
    async def fetch_instrument_id(self, instrument_id: InstrumentId, filters: dict | None = None) -> bool: ...
    async def get_contract_details(self, contract: IBContract) -> list[ContractDetails]: ...
    async def get_future_chain_details(self, underlying: IBContract) -> list[ContractDetails]: ...
    async def get_option_chain_details_by_range(self, underlying: IBContract, min_expiry: pd.Timestamp, max_expiry: pd.Timestamp, exchange: str | None = None) -> list[ContractDetails]: ...
    async def get_option_chain_details_by_expiry(self, underlying: IBContract, last_trading_date: str, exchange: str) -> list[ContractDetails]: ...
    def determine_venue_from_contract(self, contract: IBContract, contract_details: IBContractDetails | None = None) -> str: ...
