import enum
from collections.abc import Generator
from nautilus_trader.core.nautilus_pyo3.network import http_get as http_get
from typing import Any, NamedTuple

class ProductClass(enum.Enum):
    ETFS = 'ETF'
    INDICES = 'IND'
    STOCKS = 'STK'
    OPTIONS = 'OPTGRP'
    WARRANTS = 'WANT'

class Exchange(enum.Enum):
    AEB = 'aeb'
    ALPHA = 'alpha'
    AMEX = 'amex'
    ARCA = 'arca'
    ARCAEDGE = 'arcaedge'
    ASX = 'asx'
    BATECH = 'batech'
    BATEDE = 'batede'
    BATEEN = 'bateen'
    BATEEN_BE = 'bateen-be'
    BATEEN_FR = 'bateen-fr'
    BATEES = 'batees'
    BATEUK = 'bateuk'
    BATS = 'bats'
    BEX = 'bex'
    BM = 'bm'
    BUX = 'bux'
    BVL = 'bvl'
    BVME = 'bvme'
    BYX = 'byx'
    CHIX_CA = 'chix_ca'
    CHIXAU = 'chixau'
    CHIXCH = 'chixch'
    CHIXDE = 'chixde'
    CHIXEN = 'chixen'
    CHIXEN_BE = 'chixen-be'
    CHIXEN_FR = 'chixen-fr'
    CHIXES = 'chixes'
    CHIXJ = 'chixj'
    CHIXUK = 'chixuk'
    CHX = 'chx'
    DRCTEDGE = 'drctedge'
    DXEDE = 'dxede'
    EBS = 'ebs'
    EDGEA = 'edgea'
    ENEXT_BE = 'enext.be'
    FWB = 'fwb'
    GETTEX = 'gettex'
    IBIS = 'ibis'
    IEX = 'iex'
    ISLAND = 'island'
    JPNNEXT = 'jpnnext'
    LSE = 'lse'
    LSEIOB1 = 'lseiob1'
    LTSE = 'ltse'
    MEMX = 'memx'
    MEXI = 'mexi'
    MOEX = 'moex'
    N_RIGA = 'n.riga'
    N_TALLINN = 'n.tallinn'
    N_VILNIUS = 'n.vilnius'
    NASDAQ = 'nasdaq'
    NITE = 'nite'
    NSE = 'nse'
    NYSE = 'nyse'
    NYSENAT = 'nysenat'
    OMEGA = 'omega'
    OMXNO = 'omxno'
    PEARL = 'pearl'
    PINK = 'pink'
    PSX = 'psx'
    SBF = 'sbf'
    SEHK = 'sehk'
    SEHKNTL = 'sehkntl'
    SEHKSTAR = 'sehkstar'
    SEHKSZSE = 'sehkszse'
    SFB = 'sfb'
    SGX = 'sgx'
    SWB = 'swb'
    TASE = 'tase'
    TGATE = 'tgate'
    TRQX_BE = 'trqx-be'
    TRQX_FR = 'trqx-fr'
    TRQXCH = 'trqxch'
    TRQXDE = 'trqxde'
    TRQXEN = 'trqxen'
    TSE = 'tse'
    TSEJ = 'tsej'
    VENTURE = 'venture'
    VIRTX = 'virtx'
    VSE = 'vse'
    WSE = 'wse'

class Product(NamedTuple):
    ib_symbol: Any
    description: Any
    native_symbol: Any
    currency: Any

def load_product_list(exchange: Exchange, product_class: ProductClass, limit: int = 500, debug: bool = False) -> Generator: ...
