import nautilus_trader.common.actor
from nautilus_trader.execution.config import ExecAlgorithmConfig as ExecAlgorithmConfig, ImportableExecAlgorithmConfig as ImportableExecAlgorithmConfig
from typing import Any, ClassVar

__test__: dict

class ExecAlgorithm(nautilus_trader.common.actor.Actor):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, config: ExecAlgorithmConfig | None = ...) -> Any: ...
    def cancel_order(self, Orderorder, ClientIdclient_id=...) -> void: ...
    def execute(self, TradingCommandcommand) -> void: ...
    def modify_order(self, Orderorder, Quantityquantity=..., Priceprice=..., Pricetrigger_price=..., ClientIdclient_id=...) -> void: ...
    def modify_order_in_place(self, Orderorder, Quantityquantity=..., Priceprice=..., Pricetrigger_price=...) -> void: ...
    def on_order(self, Orderorder) -> void: ...
    def on_order_accepted(self, OrderAcceptedevent) -> void: ...
    def on_order_cancel_rejected(self, OrderCancelRejectedevent) -> void: ...
    def on_order_canceled(self, OrderCanceledevent) -> void: ...
    def on_order_denied(self, OrderDeniedevent) -> void: ...
    def on_order_emulated(self, OrderEmulatedevent) -> void: ...
    def on_order_event(self, OrderEventevent) -> void: ...
    def on_order_expired(self, OrderExpiredevent) -> void: ...
    def on_order_filled(self, OrderFilledevent) -> void: ...
    def on_order_initialized(self, OrderInitializedevent) -> void: ...
    def on_order_list(self, OrderListorder_list) -> void: ...
    def on_order_modify_rejected(self, OrderModifyRejectedevent) -> void: ...
    def on_order_pending_cancel(self, OrderPendingCancelevent) -> void: ...
    def on_order_pending_update(self, OrderPendingUpdateevent) -> void: ...
    def on_order_rejected(self, OrderRejectedevent) -> void: ...
    def on_order_released(self, OrderReleasedevent) -> void: ...
    def on_order_submitted(self, OrderSubmittedevent) -> void: ...
    def on_order_triggered(self, OrderTriggeredevent) -> void: ...
    def on_order_updated(self, OrderUpdatedevent) -> void: ...
    def on_position_changed(self, PositionChangedevent) -> void: ...
    def on_position_closed(self, PositionClosedevent) -> void: ...
    def on_position_event(self, PositionEventevent) -> void: ...
    def on_position_opened(self, PositionOpenedevent) -> void: ...
    def register(self, TraderIdtrader_id, PortfolioFacadeportfolio, MessageBusmsgbus, CacheFacadecache, Clockclock) -> void: ...
    def spawn_limit(self, Orderprimary, Quantityquantity, Priceprice, TimeInForcetime_in_force=..., datetimeexpire_time=..., boolpost_only=..., boolreduce_only=..., Quantitydisplay_qty=..., TriggerTypeemulation_trigger=..., listtags=..., boolreduce_primary=...) -> LimitOrder: ...
    def spawn_market(self, Orderprimary, Quantityquantity, TimeInForcetime_in_force=..., boolreduce_only=..., listtags=..., boolreduce_primary=...) -> MarketOrder: ...
    def spawn_market_to_limit(self, Orderprimary, Quantityquantity, TimeInForcetime_in_force=..., datetimeexpire_time=..., boolreduce_only=..., Quantitydisplay_qty=..., TriggerTypeemulation_trigger=..., listtags=..., boolreduce_primary=...) -> MarketToLimitOrder: ...
    def submit_order(self, Orderorder) -> void: ...
    def to_importable_config(self) -> ImportableExecAlgorithmConfig: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
