import nautilus_trader.common.component
from _typeshed import Incomplete
from nautilus_trader.common.config import NautilusConfig as NautilusConfig
from nautilus_trader.execution.reports import ExecutionMassStatus as ExecutionMassStatus, FillReport as FillReport, OrderStatusReport as OrderStatusReport, PositionStatusReport as PositionStatusReport
from typing import Any, ClassVar

__test__: dict

class ExecutionClient(nautilus_trader.common.component.Component):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    account_id: Incomplete
    account_type: Incomplete
    base_currency: Incomplete
    is_connected: Incomplete
    oms_type: Incomplete
    venue: Incomplete
    def __init__(self, ClientIdclient_id, Venuevenue: Venue | None, OmsTypeoms_type, AccountTypeaccount_type, Currencybase_currency: Currency | None, MessageBusmsgbus, Cachecache, Clockclock, config: NautilusConfig | None = ...) -> Any: ...
    def batch_cancel_orders(self, BatchCancelOrderscommand) -> void: ...
    def calculate_commission(self, Instrumentinstrument, Quantitylast_qty, Pricelast_px, LiquiditySideliquidity_side) -> Money: ...
    def cancel_all_orders(self, CancelAllOrderscommand) -> void: ...
    def cancel_order(self, CancelOrdercommand) -> void: ...
    # Hand-ported from execution/client.pxd (stubgen mangles cdef params).
    def generate_account_state(
        self, balances: list, margins: list, reported: bool, ts_event: int, info: dict | None = None
    ) -> None: ...
    _cache: Incomplete
    def _set_account_id(self, account_id: Any) -> None: ...
    def _send_account_state(self, account_state: Any) -> None: ...
    def _send_order_event(self, event: Any) -> None: ...
    def _send_mass_status_report(self, report: Any) -> None: ...
    def _send_order_status_report(self, report: Any) -> None: ...
    def _send_fill_report(self, report: Any) -> None: ...
    def _send_position_status_report(self, report: Any) -> None: ...
    def generate_order_accepted(self, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, VenueOrderIdvenue_order_id, uint64_tts_event) -> void: ...
    def generate_order_cancel_rejected(self, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, VenueOrderIdvenue_order_id, strreason, uint64_tts_event) -> void: ...
    def generate_order_canceled(self, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, VenueOrderIdvenue_order_id, uint64_tts_event) -> void: ...
    def generate_order_denied(self, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, strreason, uint64_tts_event) -> void: ...
    def generate_order_expired(self, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, VenueOrderIdvenue_order_id, uint64_tts_event) -> void: ...
    def generate_order_filled(self, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, VenueOrderIdvenue_order_id, PositionIdvenue_position_id: PositionId | None, TradeIdtrade_id, OrderSideorder_side, OrderTypeorder_type, Quantitylast_qty, Pricelast_px, Currencyquote_currency, Moneycommission, LiquiditySideliquidity_side, uint64_tts_event, info: dict | None = ...) -> void: ...
    def generate_order_modify_rejected(self, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, VenueOrderIdvenue_order_id, strreason, uint64_tts_event) -> void: ...
    def generate_order_rejected(self, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, strreason, uint64_tts_event, booldue_post_only=...) -> void: ...
    def generate_order_submitted(self, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, uint64_tts_event) -> void: ...
    def generate_order_triggered(self, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, VenueOrderIdvenue_order_id, uint64_tts_event) -> void: ...
    def generate_order_updated(self, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, VenueOrderIdvenue_order_id, Quantityquantity, Priceprice, Pricetrigger_price, uint64_tts_event, boolvenue_order_id_modified=..., is_quote_quantity=...) -> void: ...
    def get_account(self) -> Account: ...
    def modify_order(self, ModifyOrdercommand) -> void: ...
    def query_account(self, QueryAccountcommand) -> void: ...
    def query_order(self, QueryOrdercommand) -> void: ...
    def submit_order(self, SubmitOrdercommand) -> void: ...
    def submit_order_list(self, SubmitOrderListcommand) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
