from nautilus_trader.common.config import NautilusConfig as NautilusConfig, NonNegativeInt as NonNegativeInt, PositiveFloat as PositiveFloat, PositiveInt as PositiveInt, msgspec_encoding_hook as msgspec_encoding_hook, resolve_config_path as resolve_config_path, resolve_path as resolve_path
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.model.identifiers import ClientId as ClientId, ExecAlgorithmId as ExecAlgorithmId
from typing import Any

class ExecEngineConfig(NautilusConfig, frozen=True):
    load_cache: bool = ...
    manage_own_order_books: bool = ...
    snapshot_orders: bool = ...
    snapshot_positions: bool = ...
    snapshot_positions_interval_secs: PositiveFloat | None = ...
    external_clients: list[ClientId] | None = ...
    allow_overfills: bool = ...
    purge_closed_orders_interval_mins: PositiveInt | None = ...
    purge_closed_orders_buffer_mins: NonNegativeInt | None = ...
    purge_closed_positions_interval_mins: PositiveInt | None = ...
    purge_closed_positions_buffer_mins: NonNegativeInt | None = ...
    purge_account_events_interval_mins: PositiveInt | None = ...
    purge_account_events_lookback_mins: NonNegativeInt | None = ...
    purge_from_database: bool = ...
    debug: bool = ...

class ExecAlgorithmConfig(NautilusConfig, kw_only=True, frozen=True):
    exec_algorithm_id: ExecAlgorithmId | None = ...
    log_events: bool = ...
    log_commands: bool = ...

class ImportableExecAlgorithmConfig(NautilusConfig, frozen=True):
    exec_algorithm_path: str
    config_path: str
    config: dict[str, Any]

class ExecAlgorithmFactory:
    @staticmethod
    def create(config: ImportableExecAlgorithmConfig): ...
