import nautilus_trader.common.actor
from _typeshed import Incomplete
from nautilus_trader.common.config import OrderEmulatorConfig as OrderEmulatorConfig
from typing import Any, ClassVar

__test__: dict

class OrderEmulator(nautilus_trader.common.actor.Actor):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    command_count: Incomplete
    debug: Incomplete
    event_count: Incomplete
    subscribed_quotes: OrderEmulator.subscribed_quotes
    subscribed_trades: OrderEmulator.subscribed_trades
    def __init__(self, PortfolioFacadeportfolio, MessageBusmsgbus, Cachecache, Clockclock, config: OrderEmulatorConfig | None = ...) -> Any: ...
    def create_matching_core(self, InstrumentIdinstrument_id, Priceprice_increment) -> MatchingCore: ...
    def execute(self, TradingCommandcommand) -> void: ...
    def get_matching_core(self, InstrumentIdinstrument_id) -> MatchingCore | None: ...
    def get_submit_order_commands(self) -> dict[ClientOrderId, SubmitOrder]: ...
    def on_dispose(self) -> void: ...
    def on_event(self, Eventevent) -> void: ...
    def on_order_book_deltas(self, deltas) -> void: ...
    def on_quote_tick(self, QuoteTicktick) -> void: ...
    def on_reset(self) -> void: ...
    def on_start(self) -> void: ...
    def on_stop(self) -> void: ...
    def on_trade_tick(self, TradeTicktick) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
