import nautilus_trader.common.component
from _typeshed import Incomplete
from nautilus_trader.common.config import InvalidConfiguration as InvalidConfiguration
from nautilus_trader.execution.config import ExecEngineConfig as ExecEngineConfig
from nautilus_trader.execution.reports import ExecutionMassStatus as ExecutionMassStatus, ExecutionReport as ExecutionReport
from typing import Any, ClassVar

__test__: dict

class ExecutionEngine(nautilus_trader.common.component.Component):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    allow_overfills: Incomplete
    command_count: Incomplete
    debug: Incomplete
    default_client: ExecutionEngine.default_client
    event_count: Incomplete
    manage_own_order_books: Incomplete
    purge_account_events_interval_mins: Incomplete
    purge_account_events_lookback_mins: Incomplete
    purge_closed_orders_buffer_mins: Incomplete
    purge_closed_orders_interval_mins: Incomplete
    purge_closed_positions_buffer_mins: Incomplete
    purge_closed_positions_interval_mins: Incomplete
    purge_from_database: Incomplete
    reconciliation: ExecutionEngine.reconciliation
    registered_clients: ExecutionEngine.registered_clients
    report_count: report_count
    snapshot_orders: Incomplete
    snapshot_positions: Incomplete
    snapshot_positions_interval_secs: Incomplete
    snapshot_positions_timer_name: Incomplete
    def __init__(self, MessageBusmsgbus, Cachecache, Clockclock, config: ExecEngineConfig | None = ...) -> None: ...
    def check_connected(self) -> bool: ...
    def check_disconnected(self) -> bool: ...
    def check_integrity(self) -> bool: ...
    def check_residuals(self) -> bool: ...
    def connect(self) -> None: ...
    def deregister_client(self, ExecutionClientclient) -> void: ...
    def disconnect(self) -> None: ...
    def execute(self, Commandcommand) -> void: ...
    def flush_db(self) -> void: ...
    def get_clients_for_orders(self, listorders) -> set: ...
    def get_external_client_ids(self) -> set: ...
    def get_external_order_claim(self, InstrumentIdinstrument_id) -> StrategyId: ...
    def get_external_order_claims_instruments(self) -> set: ...
    def load_cache(self) -> void: ...
    def position_id_count(self, StrategyIdstrategy_id) -> int: ...
    def process(self, OrderEventevent) -> void: ...
    def reconcile_execution_mass_status(self, report: ExecutionMassStatus) -> None: ...
    def reconcile_execution_report(self, report: ExecutionReport) -> bool: ...
    def reconcile_execution_state(self, doubletimeout_secs: float = ...) -> bool: ...
    def register_client(self, ExecutionClientclient) -> void: ...
    def register_default_client(self, ExecutionClientclient) -> void: ...
    def register_external_order_claims(self, Strategystrategy) -> void: ...
    def register_oms_type(self, Strategystrategy) -> void: ...
    def register_venue_routing(self, ExecutionClientclient, Venuevenue) -> void: ...
    def set_manage_own_order_books(self, boolvalue) -> void: ...
    def stop_clients(self) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
