from _typeshed import Incomplete
from typing import Any, Callable, ClassVar

__test__: dict

class OrderManager:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    active_local: Incomplete
    debug: Incomplete
    log_commands: Incomplete
    log_events: Incomplete
    def __init__(self, Clockclock, MessageBusmsgbus, Cachecache, strcomponent_name, boolactive_local, submit_order_handler: Callable[[SubmitOrder], None] = ..., cancel_order_handler: Callable[[Order], None] = ..., modify_order_handler: Callable[[Order, Quantity], None] = ..., booldebug=..., boollog_events=..., boollog_commands=...) -> Any: ...
    def cache_submit_order_command(self, SubmitOrdercommand) -> void: ...
    def cancel_order(self, Orderorder) -> void: ...
    def create_new_submit_order(self, Orderorder, PositionIdposition_id=..., ClientIdclient_id=...) -> void: ...
    def get_submit_order_commands(self) -> dict: ...
    def handle_contingencies(self, Orderorder) -> void: ...
    def handle_contingencies_update(self, Orderorder) -> void: ...
    def handle_event(self, Eventevent) -> void: ...
    def handle_order_canceled(self, OrderCanceledcanceled) -> void: ...
    def handle_order_expired(self, OrderExpiredexpired) -> void: ...
    def handle_order_filled(self, OrderFilledfilled) -> void: ...
    def handle_order_rejected(self, OrderRejectedrejected) -> void: ...
    def handle_order_updated(self, OrderUpdatedupdated) -> void: ...
    def handle_position_event(self, PositionEventevent) -> void: ...
    def modify_order_quantity(self, Orderorder, Quantitynew_quantity) -> void: ...
    def pop_submit_order_command(self, ClientOrderIdclient_order_id) -> SubmitOrder: ...
    def reset(self) -> void: ...
    def send_algo_command(self, TradingCommandcommand, ExecAlgorithmIdexec_algorithm_id) -> void: ...
    def send_emulator_command(self, TradingCommandcommand) -> void: ...
    def send_exec_command(self, Commandcommand) -> void: ...
    def send_exec_event(self, OrderEventevent) -> void: ...
    def send_risk_command(self, TradingCommandcommand) -> void: ...
    def send_risk_event(self, OrderEventevent) -> void: ...
    def should_manage_order(self, Orderorder) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
