from _typeshed import Incomplete
from typing import Any, Callable, ClassVar

__pyx_capi__: dict
__test__: dict

class MatchingCore:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    ask: MatchingCore.ask
    ask_raw: Incomplete
    bid: MatchingCore.bid
    bid_raw: Incomplete
    instrument_id: MatchingCore.instrument_id
    is_ask_initialized: Incomplete
    is_bid_initialized: Incomplete
    is_last_initialized: Incomplete
    last: MatchingCore.last
    last_raw: Incomplete
    price_increment: MatchingCore.price_increment
    price_precision: MatchingCore.price_precision
    def __init__(self, InstrumentIdinstrument_id, Priceprice_increment, trigger_stop_order: Callable, fill_market_order: Callable, fill_limit_order: Callable) -> Any: ...
    def add_order(self, Orderorder) -> void: ...
    def delete_order(self, Orderorder) -> void: ...
    def get_order(self, ClientOrderIdclient_order_id) -> Order: ...
    def get_orders(self) -> list: ...
    def get_orders_ask(self) -> list: ...
    def get_orders_bid(self) -> list: ...
    def is_limit_fillable(self, OrderSideside, Priceprice) -> bool: ...
    def is_limit_marketable(self, OrderSideside, Priceprice) -> bool: ...
    def is_stop_triggered(self, OrderSideside, Pricetrigger_price) -> bool: ...
    def is_touch_triggered(self, OrderSideside, Pricetrigger_price) -> bool: ...
    def iterate(self, uint64_ttimestamp_ns) -> void: ...
    def match_limit_if_touched_order(self, Orderorder, boolinitial) -> void: ...
    def match_limit_order(self, Orderorder) -> void: ...
    def match_market_if_touched_order(self, Orderorder) -> void: ...
    def match_order(self, Orderorder, boolinitial=...) -> void: ...
    def match_stop_limit_order(self, Orderorder, boolinitial) -> void: ...
    def match_stop_market_order(self, Orderorder) -> void: ...
    def match_trailing_stop_limit_order(self, Orderorder, boolinitial) -> void: ...
    def match_trailing_stop_market_order(self, Orderorder) -> void: ...
    def order_exists(self, ClientOrderIdclient_order_id) -> bool: ...
    def reset(self) -> void: ...
    def set_fill_limit_inside_spread(self, boolvalue) -> void: ...
    def update_price_increment(self, Priceprice_increment) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
