import pandas as pd
from datetime import time
from nautilus_trader.common.config import NautilusConfig as NautilusConfig
from nautilus_trader.persistence.catalog.base import BaseDataCatalog as BaseDataCatalog
from nautilus_trader.persistence.writer import RotationMode as RotationMode

class StreamingConfig(NautilusConfig, frozen=True):
    catalog_path: str
    fs_protocol: str | None = ...
    fs_storage_options: dict | None = ...
    fs_rust_storage_options: dict | None = ...
    flush_interval_ms: int | None = ...
    replace_existing: bool = ...
    include_types: list[type] | None = ...
    rotation_mode: RotationMode = ...
    max_file_size: int = ...
    rotation_interval: pd.Timedelta | None = ...
    rotation_time: time = ...
    rotation_timezone: str = ...
    @property
    def fs(self): ...
    def as_catalog(self) -> BaseDataCatalog: ...

class DataCatalogConfig(NautilusConfig, frozen=True):
    path: str
    fs_protocol: str | None = ...
    fs_storage_options: dict | None = ...
    fs_rust_storage_options: dict | None = ...
    name: str | None = ...
    def as_catalog(self) -> BaseDataCatalog: ...
