from nautilus_trader.core.inspect import is_nautilus_class as is_nautilus_class
from nautilus_trader.core.nautilus_pyo3 import convert_to_snake_case as convert_to_snake_case
from nautilus_trader.model.data import Bar as Bar, BarType as BarType, MarkPriceUpdate as MarkPriceUpdate, OptionGreeks as OptionGreeks, OrderBookDelta as OrderBookDelta, OrderBookDepth10 as OrderBookDepth10, QuoteTick as QuoteTick, TradeTick as TradeTick
from nautilus_trader.model.identifiers import InstrumentId as InstrumentId
from pyarrow.dataset import Expression as Expression

CUSTOM_DATA_PREFIX: str

def class_to_filename(cls) -> str: ...
def filename_to_class(filename: str) -> type | None: ...
def urisafe_identifier(identifier: InstrumentId | BarType | str) -> str: ...
def combine_filters(*filters): ...
def parse_filters_expr(s: str | None) -> Expression | None: ...
