import abc
import pandas as pd
import pyarrow as pa
from _typeshed import Incomplete
from nautilus_trader.core import nautilus_pyo3 as nautilus_pyo3
from nautilus_trader.model.instruments import Instrument as Instrument
from nautilus_trader.model.objects import FIXED_PRECISION as FIXED_PRECISION, FIXED_PRECISION_BYTES as FIXED_PRECISION_BYTES
from typing import Any, ClassVar, Final

RAW_BYTE_ORDER: Final[str]

class WranglerBase(abc.ABC):
    IGNORE_KEYS: ClassVar[set[bytes]]
    @classmethod
    def from_instrument(cls, instrument: Instrument, **kwargs: Any) -> Any: ...
    @classmethod
    def from_schema(cls, schema: pa.Schema) -> Any: ...

class OrderBookDeltaDataWranglerV2(WranglerBase):
    def __init__(self, instrument_id: str, price_precision: int, size_precision: int) -> None: ...
    def from_arrow(self, table: pa.Table) -> list[nautilus_pyo3.OrderBookDelta]: ...
    def from_pandas(self, df: pd.DataFrame, ts_init_delta: int = 0) -> list[nautilus_pyo3.OrderBookDelta]: ...

class OrderBookDepth10DataWranglerV2(WranglerBase):
    def __init__(self, instrument_id: str, price_precision: int, size_precision: int) -> None: ...
    def from_arrow(self, table: pa.Table) -> list[nautilus_pyo3.OrderBookDepth10]: ...
    def from_pandas(self, df: pd.DataFrame, ts_init_delta: int = 0) -> list[nautilus_pyo3.OrderBookDepth10]: ...

class QuoteTickDataWranglerV2(WranglerBase):
    def __init__(self, instrument_id: str, price_precision: int, size_precision: int) -> None: ...
    def from_arrow(self, table: pa.Table) -> list[nautilus_pyo3.QuoteTick]: ...
    def from_pandas(self, df: pd.DataFrame, default_size: float = 1000000.0, ts_init_delta: int = 0) -> list[nautilus_pyo3.QuoteTick]: ...

class TradeTickDataWranglerV2(WranglerBase):
    def __init__(self, instrument_id: str, price_precision: int, size_precision: int) -> None: ...
    def from_arrow(self, table: pa.Table) -> list[nautilus_pyo3.TradeTick]: ...
    def from_json(self, data: list[dict[str, Any]]) -> list[nautilus_pyo3.TradeTick]: ...
    def from_pandas(self, df: pd.DataFrame, ts_init_delta: int = 0) -> list[nautilus_pyo3.TradeTick]: ...

class BarDataWranglerV2(WranglerBase):
    IGNORE_KEYS: Incomplete
    bar_type: Incomplete
    def __init__(self, bar_type: str, price_precision: int, size_precision: int) -> None: ...
    def from_arrow(self, table: pa.Table) -> list[nautilus_pyo3.Bar]: ...
    def from_pandas(self, df: pd.DataFrame, default_volume: float = 1000000.0, ts_init_delta: int = 0) -> list[nautilus_pyo3.Bar]: ...
