import _cython_3_2_9
import pd
from _typeshed import Incomplete
from nautilus_trader.model.functions import book_action_from_str as book_action_from_str, order_side_from_str as order_side_from_str
from typing import Any, ClassVar

BAR_COLUMNS: tuple
BAR_PRICES: tuple
__test__: dict
align_bid_ask_bar_data: _cython_3_2_9.cython_function_or_method
calculate_bar_price_offsets: _cython_3_2_9.cython_function_or_method
calculate_volume_quarter: _cython_3_2_9.cython_function_or_method
prepare_event_and_init_timestamps: _cython_3_2_9.cython_function_or_method
preprocess_bar_data: _cython_3_2_9.cython_function_or_method

class BarDataWrangler:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    bar_type: Incomplete
    instrument: Incomplete
    def __init__(self, BarTypebar_type, Instrumentinstrument) -> Any: ...
    def process(self, data: pd.DataFrame, doubledefault_volume: float = ..., intts_init_delta: int = ...) -> Any: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class OrderBookDeltaDataWrangler:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    instrument: Incomplete
    def __init__(self, Instrumentinstrument) -> Any: ...
    def process(self, data: pd.DataFrame, intts_init_delta: int = ..., boolis_raw=...) -> Any: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class QuoteTickDataWrangler:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    instrument: Incomplete
    def __init__(self, Instrumentinstrument) -> Any: ...
    def process(self, data: pd.DataFrame, doubledefault_volume: float = ..., intts_init_delta: int = ...) -> Any: ...
    def process_bar_data(self, bid_data: pd.DataFrame, ask_data: pd.DataFrame, doubledefault_volume: float = ..., intts_init_delta: int = ..., intoffset_interval_ms: int = ..., booltimestamp_is_close: bool = ..., intrandom_seed: int | None = ..., boolis_raw: bool = ..., boolsort_data: bool = ...) -> Any: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class TradeTickDataWrangler:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    instrument: Incomplete
    processed_data: Incomplete
    def __init__(self, Instrumentinstrument) -> Any: ...
    def process(self, data: pd.DataFrame, intts_init_delta: int = ..., boolis_raw=...) -> Any: ...
    def process_bar_data(self, data: pd.DataFrame, intts_init_delta: int = ..., intoffset_interval_ms: int = ..., booltimestamp_is_close: bool = ..., intrandom_seed: int | None = ..., boolis_raw: bool = ..., boolsort_data: bool = ...) -> Any: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
