from nautilus_trader.common.config import PositiveInt as PositiveInt
from nautilus_trader.config import LiveDataClientConfig as LiveDataClientConfig, LiveExecClientConfig as LiveExecClientConfig
from nautilus_trader.core.nautilus_pyo3 import DydxNetwork as DydxNetwork

class DydxDataClientConfig(LiveDataClientConfig, frozen=True):
    wallet_address: str | None = ...
    environment: DydxNetwork | None = ...
    bars_timestamp_on_close: bool = ...
    base_url_http: str | None = ...
    base_url_ws: str | None = ...
    proxy_url: str | None = ...
    max_retries: PositiveInt | None = ...
    retry_delay_initial_ms: PositiveInt | None = ...
    retry_delay_max_ms: PositiveInt | None = ...

class DydxExecClientConfig(LiveExecClientConfig, frozen=True):
    wallet_address: str | None = ...
    subaccount: int = ...
    private_key: str | None = ...
    authenticator_ids: list[int] | None = ...
    environment: DydxNetwork | None = ...
    base_url_http: str | None = ...
    base_url_ws: str | None = ...
    base_url_grpc: str | None = ...
    proxy_url: str | None = ...
    max_retries: PositiveInt | None = ...
    retry_delay_initial_ms: PositiveInt | None = ...
    retry_delay_max_ms: PositiveInt | None = ...
    grpc_rate_limit_per_second: PositiveInt | None = ...
