import _cython_3_2_9
from nautilus_trader.execution.reports import ExecutionMassStatus as ExecutionMassStatus, FillReport as FillReport, OrderStatusReport as OrderStatusReport, PositionStatusReport as PositionStatusReport
from typing import Any, ClassVar

__pyx_capi__: dict
__test__: dict
register_serializable_type: _cython_3_2_9.cython_function_or_method

class Serializer:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self) -> Any: ...
    def deserialize(self, bytesobj_bytes) -> Any: ...
    def serialize(self, obj) -> bytes: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
