import nautilus_trader.serialization.base
from _typeshed import Incomplete
from typing import Any, ClassVar

__test__: dict

class MsgSpecSerializer(nautilus_trader.serialization.base.Serializer):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    timestamps_as_iso8601: Incomplete
    timestamps_as_str: Incomplete
    def __init__(self, encoding, booltimestamps_as_str=..., booltimestamps_as_iso8601=...) -> Any: ...
    def deserialize(self, bytesobj_bytes) -> Any: ...
    def serialize(self, obj) -> bytes: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
