import asyncio
from collections.abc import Awaitable, Callable as Callable
from nautilus_trader.adapters.binance.common.symbol import BinanceSymbol as BinanceSymbol
from nautilus_trader.common.component import LiveClock as LiveClock, Logger as Logger
from nautilus_trader.common.enums import LogColor as LogColor
from nautilus_trader.core.nautilus_pyo3 import WebSocketClient as WebSocketClient, WebSocketClientError as WebSocketClientError, WebSocketConfig as WebSocketConfig
from nautilus_trader.live.cancellation import cancel_tasks_with_timeout as cancel_tasks_with_timeout

class BinanceWebSocketClient:
    MAX_SUBSCRIPTIONS_PER_CLIENT: int
    MAX_CLIENTS: int
    def __init__(self, clock: LiveClock, base_url: str, handler: Callable[[bytes], None], handler_reconnect: Callable[..., Awaitable[None]] | None, loop: asyncio.AbstractEventLoop, proxy_url: str | None = None) -> None: ...
    @property
    def url(self) -> str: ...
    @property
    def subscriptions(self) -> list[str]: ...
    @property
    def has_subscriptions(self) -> bool: ...
    async def connect(self) -> None: ...
    async def send_pong(self, client_id: int, raw: bytes) -> None: ...
    async def disconnect(self) -> None: ...
    async def subscribe_agg_trades(self, symbol: str) -> None: ...
    async def unsubscribe_agg_trades(self, symbol: str) -> None: ...
    async def subscribe_trades(self, symbol: str) -> None: ...
    async def unsubscribe_trades(self, symbol: str) -> None: ...
    async def subscribe_bars(self, symbol: str, interval: str) -> None: ...
    async def unsubscribe_bars(self, symbol: str, interval: str) -> None: ...
    async def subscribe_mini_ticker(self, symbol: str | None = None) -> None: ...
    async def unsubscribe_mini_ticker(self, symbol: str | None = None) -> None: ...
    async def subscribe_ticker(self, symbol: str | None = None) -> None: ...
    async def unsubscribe_ticker(self, symbol: str | None = None) -> None: ...
    async def subscribe_book_ticker(self, symbol: str | None = None) -> None: ...
    async def unsubscribe_book_ticker(self, symbol: str | None = None) -> None: ...
    async def subscribe_partial_book_depth(self, symbol: str, depth: int, speed: int) -> None: ...
    async def unsubscribe_partial_book_depth(self, symbol: str, depth: int, speed: int) -> None: ...
    async def subscribe_diff_book_depth(self, symbol: str, speed: int) -> None: ...
    async def unsubscribe_diff_book_depth(self, symbol: str, speed: int) -> None: ...
    async def subscribe_mark_price(self, symbol: str | None = None, speed: int | None = None) -> None: ...
    async def unsubscribe_mark_price(self, symbol: str | None = None, speed: int | None = None) -> None: ...
