import asyncio
from collections.abc import Awaitable, Callable as Callable
from nautilus_trader.adapters.binance.common.credentials import extract_ed25519_private_key as extract_ed25519_private_key, is_ed25519_private_key as is_ed25519_private_key
from nautilus_trader.adapters.binance.common.enums import BinanceAccountType as BinanceAccountType
from nautilus_trader.adapters.binance.common.urls import get_futures_user_stream_url as get_futures_user_stream_url
from nautilus_trader.adapters.binance.http.client import BinanceHttpClient as BinanceHttpClient
from nautilus_trader.adapters.binance.http.user import BinanceUserDataHttpAPI as BinanceUserDataHttpAPI
from nautilus_trader.common.component import LiveClock as LiveClock, Logger as Logger
from nautilus_trader.common.enums import LogColor as LogColor
from nautilus_trader.core.nautilus_pyo3 import WebSocketClient as WebSocketClient, WebSocketClientError as WebSocketClientError, WebSocketConfig as WebSocketConfig, ed25519_signature as ed25519_signature, hmac_signature as hmac_signature
from typing import Any

class BinanceUserDataWebSocketClient:
    def __init__(self, clock: LiveClock, base_url: str, handler: Callable[[bytes], None], api_key: str, api_secret: str, loop: asyncio.AbstractEventLoop, is_futures: bool = False, stream_base_url: str | None = None, is_ed25519: bool | None = None, http_client: BinanceHttpClient | None = None, account_type: BinanceAccountType | None = None, on_resubscribe: Callable[[], Awaitable[None]] | None = None, proxy_url: str | None = None) -> None: ...
    @property
    def subscription_id(self) -> str | None: ...
    @property
    def is_authenticated(self) -> bool: ...
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def session_logon(self) -> dict[str, Any]: ...
    async def session_status(self) -> dict[str, Any]: ...
    async def session_logout(self) -> dict[str, Any]: ...
    async def subscribe_user_data_stream(self, pre_dispatch_hook: Callable[[], Awaitable[None]] | None = None) -> str: ...
    async def unsubscribe_user_data_stream(self) -> None: ...
