import datetime as dt
import fsspec
import pandas as pd
from _typeshed import Incomplete
from nautilus_trader import PACKAGE_ROOT as PACKAGE_ROOT, TEST_DATA_DIR as TEST_DATA_DIR
from nautilus_trader.core import nautilus_pyo3 as nautilus_pyo3
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.core.datetime import dt_to_unix_nanos as dt_to_unix_nanos, secs_to_nanos as secs_to_nanos
from nautilus_trader.model.currencies import ADA as ADA, AUD as AUD, BTC as BTC, ETH as ETH, GBP as GBP, USD as USD, USDC as USDC, USDT as USDT, XRP as XRP
from nautilus_trader.model.data import Bar as Bar, QuoteTick as QuoteTick, TradeTick as TradeTick
from nautilus_trader.model.enums import AggressorSide as AggressorSide, AssetClass as AssetClass, OptionKind as OptionKind
from nautilus_trader.model.identifiers import InstrumentId as InstrumentId, Symbol as Symbol, TradeId as TradeId, Venue as Venue
from nautilus_trader.model.instruments import BettingInstrument as BettingInstrument, BinaryOption as BinaryOption, Cfd as Cfd, Commodity as Commodity, CryptoFuture as CryptoFuture, CryptoFuturesSpread as CryptoFuturesSpread, CryptoOption as CryptoOption, CryptoOptionSpread as CryptoOptionSpread, CryptoPerpetual as CryptoPerpetual, CurrencyPair as CurrencyPair, Equity as Equity, FuturesContract as FuturesContract, FuturesSpread as FuturesSpread, IndexInstrument as IndexInstrument, Instrument as Instrument, OptionContract as OptionContract, OptionSpread as OptionSpread, SyntheticInstrument as SyntheticInstrument
from nautilus_trader.model.instruments.betting import null_handicap as null_handicap
from nautilus_trader.model.objects import Currency as Currency, Money as Money, Price as Price, Quantity as Quantity
from nautilus_trader.persistence.loaders import CSVBarDataLoader as CSVBarDataLoader, CSVTickDataLoader as CSVTickDataLoader, ParquetBarDataLoader as ParquetBarDataLoader, ParquetTickDataLoader as ParquetTickDataLoader
from pathlib import Path
from typing import Any

NANOSECONDS_IN_SECOND: int

class TestInstrumentProvider:
    __test__: bool
    @staticmethod
    def adabtc_binance() -> CurrencyPair: ...
    @staticmethod
    def adausdt_binance() -> CurrencyPair: ...
    @staticmethod
    def btcusdt_binance() -> CurrencyPair: ...
    @staticmethod
    def btcusdt_perp_binance() -> CryptoPerpetual: ...
    @staticmethod
    def ethusdt_binance() -> CurrencyPair: ...
    @staticmethod
    def ethusdt_perp_binance() -> CryptoPerpetual: ...
    @staticmethod
    def btcusdt_future_binance(activation: pd.Timestamp | None = None, expiration: pd.Timestamp | None = None) -> CryptoFuture: ...
    @staticmethod
    def xrpusdt_linear_bybit() -> CryptoPerpetual: ...
    @staticmethod
    def xbtusd_bitmex() -> CryptoPerpetual: ...
    @staticmethod
    def ethusd_bitmex() -> CryptoPerpetual: ...
    @staticmethod
    def onethousandrats_perp_binance() -> CryptoPerpetual: ...
    @staticmethod
    def default_fx_ccy(symbol: str, venue: Venue | None = None) -> CurrencyPair: ...
    @staticmethod
    def audusd_cfd() -> Cfd: ...
    @staticmethod
    def equity(symbol: str = 'AAPL', venue: str = 'XNAS') -> Equity: ...
    @staticmethod
    def es_future(expiry_year: int, expiry_month: int, venue: Venue | None = None) -> FuturesContract: ...
    @staticmethod
    def eurusd_future(expiry_year: int, expiry_month: int, venue_name: str = 'XCME') -> FuturesContract: ...
    @staticmethod
    def future(symbol: str = 'ESZ1', underlying: str = 'ES', venue: str = 'GLBX', exchange: str = 'XCME') -> FuturesContract: ...
    @staticmethod
    def aapl_option() -> OptionContract: ...
    @staticmethod
    def synthetic_instrument() -> SyntheticInstrument: ...
    @staticmethod
    def betting_instrument(venue: str | None = None) -> BettingInstrument: ...
    @staticmethod
    def binary_option() -> BinaryOption: ...
    @staticmethod
    def crypto_option() -> CryptoOption: ...
    @staticmethod
    def futures_spread() -> FuturesSpread: ...
    @staticmethod
    def option_spread() -> OptionSpread: ...
    @staticmethod
    def crypto_futures_spread_inverse() -> CryptoFuturesSpread: ...
    @staticmethod
    def crypto_option_spread_inverse() -> CryptoOptionSpread: ...
    @staticmethod
    def commodity() -> Commodity: ...
    @staticmethod
    def index_instrument() -> IndexInstrument: ...

def first_friday_two_years_six_months_ago(year: int, month: int) -> dt.date: ...
def third_friday_of_month(year: int, month: int) -> dt.date: ...
def get_contract_month_code(expiry_month: int) -> str: ...

class TestDataProvider:
    __test__: bool
    fs: fsspec.AbstractFileSystem | None
    root: str | None
    branch: Incomplete
    def __init__(self, branch: str = 'develop') -> None: ...
    def read(self, path: str) -> fsspec.core.OpenFile: ...
    def read_csv(self, path: str, **kwargs: Any) -> pd.DataFrame: ...
    def read_csv_ticks(self, path: str) -> pd.DataFrame: ...
    def read_csv_bars(self, path: str) -> pd.DataFrame: ...
    def read_parquet_ticks(self, path: str, timestamp_column: str = 'timestamp') -> pd.DataFrame: ...
    def read_parquet_bars(self, path: str) -> pd.DataFrame: ...

class TestDataGenerator:
    __test__: bool
    @staticmethod
    def simulate_value_diffs(count: int, max_diff: float = 10, prob_increase: float = 0.25, prob_decrease: float = 0.25) -> pd.Series: ...
    @staticmethod
    def generate_time_series_index(start_timestamp: str = '2020-01-01', max_freq: str = '1s', count: int = 100000) -> pd.DatetimeIndex: ...
    @staticmethod
    def generate_time_series(start_timestamp: str = '2020-01-01', start_price: float = 100.0, default_quantity: int = 10, max_freq: str = '1s', count: int = 100000) -> pd.DataFrame: ...
    @staticmethod
    def generate_quote_ticks(instrument_id: str, price_prec: int = 4, quantity_prec: int = 4, **kwargs: Any) -> list[QuoteTick]: ...
    @staticmethod
    def generate_trade_ticks(instrument_id: str, price_prec: int = 4, quantity_prec: int = 4, **kwargs: Any) -> list[TradeTick]: ...
    @staticmethod
    def generate_monotonic_bars(instrument: Instrument, first_bar: Bar, bar_count: int = 20, time_change_nanos: int = ..., price_change_ticks: int = 10, increasing_series: bool = True) -> list[Bar]: ...

def get_test_data_large_path() -> Path: ...
def get_test_data_large_checksums_filepath() -> Path: ...
def ensure_test_data_exists(filename: str, url: str) -> Path: ...
def ensure_data_exists_tardis_deribit_book_l2() -> Path: ...
def ensure_data_exists_tardis_binance_snapshot5() -> Path: ...
def ensure_data_exists_tardis_binance_snapshot25() -> Path: ...
def ensure_data_exists_tardis_huobi_quotes() -> Path: ...
def ensure_data_exists_tardis_bitmex_trades() -> Path: ...
