import pd
from typing import Any, ClassVar

__test__: dict

class RolloverInterestCalculator:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, data: pd.DataFrame) -> Any: ...
    def calc_overnight_rate(self, InstrumentIdinstrument_id, datedate) -> Any: ...
    def get_rate_data(self) -> Any: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
