from typing import Any, ClassVar

__test__: dict

class AccountFactory:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @staticmethod
    def create(AccountStateevent) -> Account: ...
    @staticmethod
    def deregister_cash_borrowing(strissuer) -> Any: ...
    @staticmethod
    def register_account_type(strissuer, typeaccount_cls) -> Any: ...
    @staticmethod
    def register_calculated_account(strissuer) -> Any: ...
    @staticmethod
    def register_cash_borrowing(strissuer) -> Any: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
