from typing import Any, ClassVar

__test__: dict

class AccountsManager:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, CacheFacadecache, Loggerlogger, Clockclock) -> None: ...
    def generate_account_state(self, Accountaccount, uint64_tts_event) -> AccountState: ...
    def update_balances(self, Accountaccount, Instrumentinstrument, OrderFilledfill) -> void: ...
    def update_orders(self, Accountaccount, Instrumentinstrument, listorders_open, uint64_tts_event) -> bool: ...
    def update_positions(self, MarginAccountaccount, Instrumentinstrument, listpositions_open, uint64_tts_event) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
