from decimal import Decimal
from typing import Any, ClassVar

__test__: dict

class LeveragedMarginModel(MarginModel):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def calculate_margin_init(self, Instrumentinstrument, Quantityquantity, Priceprice, leverage: Decimal, booluse_quote_for_inverse=...) -> Money: ...
    def calculate_margin_maint(self, Instrumentinstrument, PositionSideside, Quantityquantity, Priceprice, leverage: Decimal, booluse_quote_for_inverse=...) -> Money: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class MarginModel:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def calculate_margin_init(self, Instrumentinstrument, Quantityquantity, Priceprice, leverage: Decimal, booluse_quote_for_inverse=...) -> Money: ...
    def calculate_margin_maint(self, Instrumentinstrument, PositionSideside, Quantityquantity, Priceprice, leverage: Decimal, booluse_quote_for_inverse=...) -> Money: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class StandardMarginModel(MarginModel):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def calculate_margin_init(self, Instrumentinstrument, Quantityquantity, Priceprice, leverage: Decimal, booluse_quote_for_inverse=...) -> Money: ...
    def calculate_margin_maint(self, Instrumentinstrument, PositionSideside, Quantityquantity, Priceprice, leverage: Decimal, booluse_quote_for_inverse=...) -> Money: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
