from nautilus_trader.config import LiveDataClientConfig as LiveDataClientConfig, LiveExecClientConfig as LiveExecClientConfig, PositiveFloat as PositiveFloat, PositiveInt as PositiveInt
from nautilus_trader.core.nautilus_pyo3 import BybitEnvironment as BybitEnvironment, BybitMarginMode as BybitMarginMode, BybitPositionMode as BybitPositionMode, BybitProductType as BybitProductType
from nautilus_trader.network import TransportBackend as TransportBackend

class BybitDataClientConfig(LiveDataClientConfig, frozen=True):
    api_key: str | None = ...
    api_secret: str | None = ...
    product_types: tuple[BybitProductType, ...] | None = ...
    environment: BybitEnvironment | None = ...
    base_url_http: str | None = ...
    proxy_url: str | None = ...
    transport_backend: TransportBackend | None = ...
    update_instruments_interval_mins: PositiveInt | None = ...
    max_retries: PositiveInt | None = ...
    retry_delay_initial_ms: PositiveInt | None = ...
    retry_delay_max_ms: PositiveInt | None = ...
    recv_window_ms: PositiveInt = ...
    bars_timestamp_on_close: bool = ...
    instrument_status_poll_secs: PositiveInt | None = ...

class BybitExecClientConfig(LiveExecClientConfig, frozen=True):
    api_key: str | None = ...
    api_secret: str | None = ...
    product_types: tuple[BybitProductType, ...] | None = ...
    environment: BybitEnvironment | None = ...
    base_url_http: str | None = ...
    base_url_ws_private: str | None = ...
    base_url_ws_trade: str | None = ...
    proxy_url: str | None = ...
    transport_backend: TransportBackend | None = ...
    use_gtd: bool = ...
    use_ws_execution_fast: bool = ...
    use_http_batch_api: bool = ...
    ignore_uncached_instrument_executions: bool = ...
    auto_repay_spot_borrows: bool = ...
    repay_queue_interval_secs: PositiveFloat = ...
    max_retries: PositiveInt | None = ...
    retry_delay_initial_ms: PositiveInt | None = ...
    retry_delay_max_ms: PositiveInt | None = ...
    recv_window_ms: PositiveInt = ...
    ws_trade_timeout_secs: PositiveFloat | None = ...
    ws_auth_timeout_secs: PositiveFloat | None = ...
    futures_leverages: dict[str, PositiveInt] | None = ...
    position_mode: dict[str, BybitPositionMode] | None = ...
    margin_mode: BybitMarginMode | None = ...
    use_spot_position_reports: bool = ...
