from nautilus_trader.adapters.bybit.constants import BYBIT_MULTIPLIERS as BYBIT_MULTIPLIERS, BYBIT_VENUE as BYBIT_VENUE
from nautilus_trader.common.providers import InstrumentProvider as InstrumentProvider
from nautilus_trader.config import InstrumentProviderConfig as InstrumentProviderConfig
from nautilus_trader.core import nautilus_pyo3 as nautilus_pyo3
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.core.nautilus_pyo3 import BybitProductType as BybitProductType
from nautilus_trader.model.identifiers import InstrumentId as InstrumentId
from nautilus_trader.model.instruments import instruments_from_pyo3 as instruments_from_pyo3
from typing import Any

class BybitInstrumentProvider(InstrumentProvider):
    def __init__(self, client: nautilus_pyo3.BybitHttpClient, product_types: tuple[BybitProductType, ...], config: InstrumentProviderConfig | None = None) -> None: ...
    @property
    def product_types(self) -> tuple[BybitProductType, ...]: ...
    def instruments_pyo3(self) -> list[Any]: ...
    async def load_all_async(self, filters: dict | None = None) -> None: ...
    async def load_ids_async(self, instrument_ids: list[InstrumentId], filters: dict | None = None) -> None: ...
    async def load_async(self, instrument_id: InstrumentId, filters: dict | None = None) -> None: ...
