import pandas as pd
from abc import ABC, ABCMeta, abstractmethod
from nautilus_trader.core.data import Data as Data
from nautilus_trader.model.data import Bar as Bar, CustomData as CustomData, DataType as DataType, FundingRateUpdate as FundingRateUpdate, InstrumentClose as InstrumentClose, InstrumentStatus as InstrumentStatus, OrderBookDelta as OrderBookDelta, OrderBookDeltas as OrderBookDeltas, OrderBookDepth10 as OrderBookDepth10, QuoteTick as QuoteTick, TradeTick as TradeTick
from nautilus_trader.model.instruments import Instrument as Instrument
from nautilus_trader.persistence.catalog.singleton import Singleton as Singleton
from nautilus_trader.persistence.funcs import CUSTOM_DATA_PREFIX as CUSTOM_DATA_PREFIX
from typing import Any

class _CombinedMeta(Singleton, ABCMeta): ...

class BaseDataCatalog(ABC, metaclass=_CombinedMeta):
    @classmethod
    @abstractmethod
    def from_env(cls) -> BaseDataCatalog: ...
    @classmethod
    @abstractmethod
    def from_uri(cls, uri: str, fs_storage_options: dict[str, str] | None = None, fs_rust_storage_options: dict[str, str] | None = None) -> BaseDataCatalog: ...
    @abstractmethod
    def get_missing_intervals_for_request(self, start: int, end: int, data_cls: type, identifier: str | None = None) -> list[tuple[int, int]]: ...
    @abstractmethod
    def write_data(self, data: list, start: int | None = None, end: int | None = None, data_cls: type | None = None, identifier: str | None = None, **kwargs: Any) -> None: ...
    def instruments(self, instrument_type: type | None = None, instrument_ids: list[str] | None = None, **kwargs: Any) -> list[Instrument]: ...
    def instrument_status(self, instrument_ids: list[str] | None = None, **kwargs: Any) -> list[InstrumentStatus]: ...
    def instrument_closes(self, instrument_ids: list[str] | None = None, **kwargs: Any) -> list[InstrumentClose]: ...
    def order_book_deltas(self, instrument_ids: list[str] | None = None, batched: bool = False, **kwargs: Any) -> list[OrderBookDelta] | list[OrderBookDeltas]: ...
    def order_book_depth10(self, instrument_ids: list[str] | None = None, **kwargs: Any) -> list[OrderBookDepth10]: ...
    def quote_ticks(self, instrument_ids: list[str] | None = None, **kwargs: Any) -> list[QuoteTick]: ...
    def trade_ticks(self, instrument_ids: list[str] | None = None, **kwargs: Any) -> list[TradeTick]: ...
    def funding_rates(self, instrument_ids: list[str] | None = None, **kwargs: Any) -> list[FundingRateUpdate]: ...
    def bars(self, bar_types: list[str] | None = None, instrument_ids: list[str] | None = None, **kwargs: Any) -> list[Bar]: ...
    def custom_data(self, cls: type, instrument_ids: list[str] | None = None, as_nautilus: bool = False, metadata: dict | None = None, **kwargs: Any) -> list[CustomData]: ...
    @abstractmethod
    def query(self, data_cls: type, identifiers: list[str] | None = None, **kwargs: Any) -> list[Data]: ...
    @abstractmethod
    def query_first_timestamp(self, data_cls: type, identifier: str | None = None) -> pd.Timestamp | None: ...
    @abstractmethod
    def query_last_timestamp(self, data_cls: type, identifier: str | None = None) -> pd.Timestamp | None: ...
    @abstractmethod
    def list_data_types(self) -> list[str]: ...
    def list_generic_data_types(self) -> list[str]: ...
    @abstractmethod
    def list_backtest_runs(self) -> list[str]: ...
    @abstractmethod
    def list_live_runs(self) -> list[str]: ...
    @abstractmethod
    def read_live_run(self, instance_id: str, **kwargs: Any) -> list[str] | dict[str, list[Data]]: ...
    @abstractmethod
    def read_backtest(self, instance_id: str, **kwargs: Any) -> list[str] | dict[str, list[Data]]: ...
