import fsspec
import pandas as pd
from _typeshed import Incomplete
from nautilus_trader.core import nautilus_pyo3 as nautilus_pyo3
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.core.data import Data as Data
from nautilus_trader.core.datetime import dt_to_unix_nanos as dt_to_unix_nanos, maybe_dt_to_unix_nanos as maybe_dt_to_unix_nanos, time_object_to_dt as time_object_to_dt, unix_nanos_to_iso8601 as unix_nanos_to_iso8601
from nautilus_trader.core.inspect import is_nautilus_class as is_nautilus_class
from nautilus_trader.core.nautilus_pyo3 import DataBackendSession as DataBackendSession, NautilusDataType as NautilusDataType, drop_cvec_pycapsule as drop_cvec_pycapsule
from nautilus_trader.model.data import Bar as Bar, CustomData as CustomData, DataType as DataType, InstrumentStatus as InstrumentStatus, MarkPriceUpdate as MarkPriceUpdate, OptionGreeks as OptionGreeks, OrderBookDelta as OrderBookDelta, OrderBookDeltas as OrderBookDeltas, OrderBookDepth10 as OrderBookDepth10, QuoteTick as QuoteTick, TradeTick as TradeTick, capsule_to_list as capsule_to_list
from nautilus_trader.model.instruments import Equity as Equity, Instrument as Instrument
from nautilus_trader.persistence.catalog.base import BaseDataCatalog as BaseDataCatalog
from nautilus_trader.persistence.funcs import class_to_filename as class_to_filename, combine_filters as combine_filters, filename_to_class as filename_to_class, urisafe_identifier as urisafe_identifier
from nautilus_trader.serialization.arrow.serializer import ArrowSerializer as ArrowSerializer, get_schema as get_schema
from os import PathLike
from typing import Any, NamedTuple

TimestampLike = int | str | float
NautilusRustDataType = nautilus_pyo3.OrderBookDelta | nautilus_pyo3.OrderBookDepth10 | nautilus_pyo3.QuoteTick | nautilus_pyo3.TradeTick | nautilus_pyo3.Bar | nautilus_pyo3.OptionGreeks

class FeatherFile(NamedTuple):
    path: str
    class_name: str

class ParquetDataCatalog(BaseDataCatalog):
    fs_protocol: str
    fs_storage_options: Incomplete
    fs: fsspec.AbstractFileSystem
    fs_rust_storage_options: Incomplete
    serializer: Incomplete
    max_rows_per_group: Incomplete
    show_query_paths: Incomplete
    path: Incomplete
    def __init__(self, path: PathLike[str] | str, fs_protocol: str | None = ..., fs_storage_options: dict | None = None, fs_rust_storage_options: dict | None = None, max_rows_per_group: int = 5000, show_query_paths: bool = False) -> None: ...
    @classmethod
    def from_env(cls) -> ParquetDataCatalog: ...
    @classmethod
    def from_uri(cls, uri: str, fs_storage_options: dict[str, str] | None = None, fs_rust_storage_options: dict[str, str] | None = None) -> ParquetDataCatalog: ...
    def write_data(self, data: list, start: int | None = None, end: int | None = None, data_cls: type | None = None, identifier: str | None = None, **kwargs: Any) -> None: ...
    def extend_file_name(self, data_cls: type[Data], identifier: str | None = None, start: int | None = None, end: int | None = None): ...
    def reset_all_file_names(self) -> None: ...
    def reset_data_file_names(self, data_cls: type, identifier: str | None = None) -> None: ...
    def consolidate_catalog(self, start: TimestampLike | None = None, end: TimestampLike | None = None, ensure_contiguous_files: bool = True, deduplicate: bool = False) -> None: ...
    def consolidate_data(self, data_cls: type, identifier: str | None = None, start: TimestampLike | None = None, end: TimestampLike | None = None, ensure_contiguous_files: bool = True, deduplicate: bool = False) -> None: ...
    def consolidate_catalog_by_period(self, period: pd.Timedelta = ..., start: TimestampLike | None = None, end: TimestampLike | None = None, ensure_contiguous_files: bool = True) -> None: ...
    def consolidate_data_by_period(self, data_cls: type, identifier: str | None = None, period: pd.Timedelta = ..., start: TimestampLike | None = None, end: TimestampLike | None = None, ensure_contiguous_files: bool = True) -> None: ...
    def delete_catalog_range(self, start: TimestampLike | None = None, end: TimestampLike | None = None) -> None: ...
    def delete_data_range(self, data_cls: type, identifier: str | None = None, start: TimestampLike | None = None, end: TimestampLike | None = None) -> None: ...
    def query(self, data_cls: type, identifiers: list[str] | None = None, start: TimestampLike | None = None, end: TimestampLike | None = None, where: str | None = None, files: list[str] | None = None, **kwargs: Any) -> list[Data | CustomData]: ...
    def backend_session(self, data_cls: type, identifiers: list[str] | None = None, start: TimestampLike | None = None, end: TimestampLike | None = None, where: str | None = None, session: DataBackendSession | None = None, files: list[str] | None = None, optimize_file_loading: bool = False, **kwargs: Any) -> DataBackendSession: ...
    def filter_files(self, data_cls: type, file_paths: list[str], identifiers: list[str] | None = None, start: TimestampLike | None = None, end: TimestampLike | None = None) -> list[str]: ...
    def get_file_list_from_data_cls(self, data_cls: type) -> list[str]: ...
    def query_first_timestamp(self, data_cls: type, identifier: str | None = None) -> pd.Timestamp | None: ...
    def query_last_timestamp(self, data_cls: type, identifier: str | None = None) -> pd.Timestamp | None: ...
    def get_missing_intervals_for_request(self, start: int, end: int, data_cls: type, identifier: str | None = None) -> list[tuple[int, int]]: ...
    def get_intervals(self, data_cls: type, identifier: str | None = None) -> list[tuple[int, int]]: ...
    def list_data_types(self) -> list[str]: ...
    def list_backtest_runs(self) -> list[str]: ...
    def list_live_runs(self) -> list[str]: ...
    def read_live_run(self, instance_id: str, **kwargs: Any) -> list[Data] | dict[str, list[Data]]: ...
    def read_backtest(self, instance_id: str, **kwargs: Any) -> list[Data] | dict[str, list[Data]]: ...
    def convert_stream_to_data(self, instance_id: str, data_cls: type, other_catalog: ParquetDataCatalog | None = None, subdirectory: str = 'backtest', identifiers: list[str] | None = None, use_ts_event_for_ts_init: bool = False) -> None: ...
