from typing import Any

class Singleton(type):
    def __init__(cls, name, bases, dict_like) -> None: ...
    def __call__(cls, *args, **kw): ...

def clear_singleton_instances(cls) -> None: ...
def resolve_kwargs(func, *args, **kwargs): ...
def check_value(v: Any) -> Any: ...
def freeze_dict(dict_like: dict) -> tuple: ...
