from typing import Any, ClassVar

__test__: dict

class Condition:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class PyCondition:
    @staticmethod
    def callable(argument, strparam, ex_type=...) -> Any: ...
    @staticmethod
    def callable_or_none(argument, strparam, ex_type=...) -> Any: ...
    @staticmethod
    def dict_types(argument, key_type, value_type, strparam, ex_type=...) -> Any: ...
    @staticmethod
    def empty(argument, strparam, ex_type=...) -> Any: ...
    @staticmethod
    def equal(argument1, argument2, strparam1, strparam2, ex_type=...) -> Any: ...
    @staticmethod
    def in_range(doublevalue, doublestart, doubleend, strparam, ex_type=...) -> Any: ...
    @staticmethod
    def in_range_int(intvalue: int, intstart: int, intend: int, param, ex_type=...) -> Any: ...
    @staticmethod
    def is_false(boolpredicate, strfail_msg, ex_type=...) -> Any: ...
    @staticmethod
    def is_in(element, collection, strparam1, strparam2, ex_type=...) -> Any: ...
    @staticmethod
    def is_true(boolpredicate, strfail_msg, ex_type=...) -> Any: ...
    @staticmethod
    def list_type(argument, expected_type, strparam, ex_type=...) -> Any: ...
    @staticmethod
    def none(argument, strparam, ex_type=...) -> Any: ...
    @staticmethod
    def not_empty(argument, strparam, ex_type=...) -> Any: ...
    @staticmethod
    def not_equal(argument1, argument2, strparam1, strparam2, ex_type=...) -> Any: ...
    @staticmethod
    def not_in(element, collection, strparam1, strparam2, ex_type=...) -> Any: ...
    @staticmethod
    def not_negative(doublevalue, strparam, ex_type=...) -> Any: ...
    @staticmethod
    def not_negative_int(intvalue: int, strparam, ex_type=...) -> Any: ...
    @staticmethod
    def not_none(argument, strparam, ex_type=...) -> Any: ...
    @staticmethod
    def positive(doublevalue, strparam, ex_type=...) -> Any: ...
    @staticmethod
    def positive_int(intvalue: int, strparam, ex_type=...) -> Any: ...
    @staticmethod
    def type(argument, expected, strparam, ex_type=...) -> Any: ...
    @staticmethod
    def type_or_none(argument, expected, strparam, ex_type=...) -> Any: ...
    @staticmethod
    def valid_string(strargument, strparam, ex_type=...) -> Any: ...
