from _typeshed import Incomplete
from typing import Any, Callable, ClassVar

__test__: dict

class FiniteStateMachine:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    state: Incomplete
    state_string: FiniteStateMachine.state_string
    def __init__(self, dictstate_transition_table, intinitial_state, trigger_parser: Callable[[int], str] = ..., state_parser: Callable[[int], str] = ...) -> Any: ...
    def trigger(self, inttrigger) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class InvalidStateTrigger(Exception):
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
