from _typeshed import Incomplete
from typing import Any, Callable

__test__: dict

class Command:
    correlation_id: Incomplete
    id: Incomplete
    ts_init: Incomplete
    def __init__(self, UUID4command_id, uint64_tts_init, UUID4correlation_id=...) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class Document:
    id: Incomplete
    ts_init: Incomplete
    def __init__(self, UUID4document_id, uint64_tts_init) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class Event:
    id: Event.id
    ts_event: Event.ts_event
    ts_init: Event.ts_init
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class Request:
    callback: Incomplete
    correlation_id: Incomplete
    id: Incomplete
    ts_init: Incomplete
    def __init__(self, callback: Callable[[Any], None] | None, UUID4request_id, uint64_tts_init, UUID4correlation_id=...) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class Response:
    correlation_id: Incomplete
    id: Incomplete
    ts_init: Incomplete
    def __init__(self, UUID4correlation_id, UUID4response_id, uint64_tts_init) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
