import _cython_3_2_9
from typing import Any, ClassVar

__reduce_cython__: _cython_3_2_9.cython_function_or_method
__setstate_cython__: _cython_3_2_9.cython_function_or_method
__test__: dict

class UUID4:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    value: UUID4.value
    def __init__(self) -> Any: ...
    @staticmethod
    def from_str(strvalue) -> UUID4: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
