from nautilus_trader.config import BacktestDataConfig as BacktestDataConfig, BacktestEngineConfig as BacktestEngineConfig, BacktestRunConfig as BacktestRunConfig, BacktestVenueConfig as BacktestVenueConfig, ExecEngineConfig as ExecEngineConfig, ImportableStrategyConfig as ImportableStrategyConfig, LoggingConfig as LoggingConfig, PortfolioConfig as PortfolioConfig, RiskEngineConfig as RiskEngineConfig, StreamingConfig as StreamingConfig
from nautilus_trader.core.data import Data as Data
from nautilus_trader.model.data import QuoteTick as QuoteTick
from nautilus_trader.model.identifiers import InstrumentId as InstrumentId
from nautilus_trader.persistence.catalog.parquet import ParquetDataCatalog as ParquetDataCatalog
from nautilus_trader.test_kit.providers import TestInstrumentProvider as TestInstrumentProvider
from nautilus_trader.test_kit.stubs.identifiers import TestIdStubs as TestIdStubs

class TestConfigStubs:
    @staticmethod
    def streaming_config(catalog: ParquetDataCatalog) -> StreamingConfig: ...
    @staticmethod
    def backtest_venue_config() -> BacktestVenueConfig: ...
    @staticmethod
    def order_book_imbalance(instrument_id: InstrumentId | None = None) -> ImportableStrategyConfig: ...
    @staticmethod
    def exec_engine_config() -> ExecEngineConfig: ...
    @staticmethod
    def risk_engine_config() -> RiskEngineConfig: ...
    @staticmethod
    def portfolio_config() -> PortfolioConfig: ...
    @staticmethod
    def strategies_config() -> list[ImportableStrategyConfig]: ...
    @staticmethod
    def backtest_engine_config(catalog: ParquetDataCatalog, log_level: str = 'INFO', bypass_logging: bool = True, bypass_risk: bool = False, persist: bool = False, strategies: list[ImportableStrategyConfig] | None = None) -> BacktestEngineConfig: ...
    @staticmethod
    def venue_config() -> BacktestVenueConfig: ...
    @staticmethod
    def backtest_data_config(catalog: ParquetDataCatalog, data_cls: Data = ..., instrument_id: str | None = None) -> BacktestDataConfig: ...
    @staticmethod
    def backtest_run_config(catalog: ParquetDataCatalog, config: BacktestEngineConfig | None = None, instrument_ids: list[str] | None = None, data_types: tuple[Data, ...] = ..., venues: list[BacktestVenueConfig] | None = None) -> BacktestRunConfig: ...
