from _typeshed import Incomplete
from nautilus_trader.core.data import Data as Data
from nautilus_trader.core.datetime import millis_to_nanos as millis_to_nanos
from nautilus_trader.model.book import OrderBook as OrderBook
from nautilus_trader.model.data import Bar as Bar, BarSpecification as BarSpecification, BarType as BarType, BookOrder as BookOrder, IndexPriceUpdate as IndexPriceUpdate, InstrumentClose as InstrumentClose, InstrumentStatus as InstrumentStatus, MarkPriceUpdate as MarkPriceUpdate, NULL_ORDER as NULL_ORDER, OrderBookDelta as OrderBookDelta, OrderBookDeltas as OrderBookDeltas, OrderBookDepth10 as OrderBookDepth10, QuoteTick as QuoteTick, TradeTick as TradeTick
from nautilus_trader.model.enums import AggressorSide as AggressorSide, BarAggregation as BarAggregation, BookAction as BookAction, BookType as BookType, InstrumentCloseType as InstrumentCloseType, MarketStatusAction as MarketStatusAction, OrderSide as OrderSide, PriceType as PriceType
from nautilus_trader.model.identifiers import InstrumentId as InstrumentId, Symbol as Symbol, TradeId as TradeId, Venue as Venue
from nautilus_trader.model.instruments import Instrument as Instrument
from nautilus_trader.model.objects import FIXED_SCALAR as FIXED_SCALAR, Price as Price, Quantity as Quantity
from nautilus_trader.persistence.wranglers import BarDataWrangler as BarDataWrangler, QuoteTickDataWrangler as QuoteTickDataWrangler
from nautilus_trader.test_kit.providers import TestDataProvider as TestDataProvider, TestInstrumentProvider as TestInstrumentProvider
from nautilus_trader.test_kit.stubs.identifiers import TestIdStubs as TestIdStubs
from os import PathLike
from typing import Any

UNIX_EPOCH: Incomplete

class TestDataStubs:
    @staticmethod
    def quote_tick(instrument: Instrument | None = None, bid_price: float = 1.0, ask_price: float = 1.0, bid_size: float = 100000.0, ask_size: float = 100000.0, ts_event: int = 0, ts_init: int = 0) -> QuoteTick: ...
    @staticmethod
    def trade_tick(instrument: Instrument | None = None, price: float = 1.0, size: float = 100000, aggressor_side: AggressorSide = ..., trade_id: str = '123456', ts_event: int = 0, ts_init: int = 0) -> TradeTick: ...
    @staticmethod
    def quote_ticks_usdjpy() -> list[QuoteTick]: ...
    @staticmethod
    def bar_spec_1min_bid() -> BarSpecification: ...
    @staticmethod
    def bar_spec_5min_bid() -> BarSpecification: ...
    @staticmethod
    def bar_spec_1min_ask() -> BarSpecification: ...
    @staticmethod
    def bar_spec_1min_last() -> BarSpecification: ...
    @staticmethod
    def bar_spec_1min_mid() -> BarSpecification: ...
    @staticmethod
    def bar_spec_1sec_mid() -> BarSpecification: ...
    @staticmethod
    def bar_spec_100tick_last() -> BarSpecification: ...
    @staticmethod
    def bar_spec_month_mid() -> BarSpecification: ...
    @staticmethod
    def bartype_audusd_1min_bid() -> BarType: ...
    @staticmethod
    def bartype_audusd_5min_bid() -> BarType: ...
    @staticmethod
    def bartype_audusd_month_mid() -> BarType: ...
    @staticmethod
    def bartype_audusd_1min_ask() -> BarType: ...
    @staticmethod
    def bartype_gbpusd_1min_bid() -> BarType: ...
    @staticmethod
    def bartype_gbpusd_1min_ask() -> BarType: ...
    @staticmethod
    def bartype_gbpusd_1sec_mid() -> BarType: ...
    @staticmethod
    def bartype_usdjpy_1min_bid() -> BarType: ...
    @staticmethod
    def bartype_usdjpy_1min_ask() -> BarType: ...
    @staticmethod
    def bartype_btcusdt_binance_100tick_last() -> BarType: ...
    @staticmethod
    def bartype_adabtc_binance_1min_last() -> BarType: ...
    @staticmethod
    def bar_5decimal(ts_event: int = 0, ts_init: int = 0) -> Bar: ...
    @staticmethod
    def bar_5decimal_5min_bid() -> Bar: ...
    @staticmethod
    def bar_month_mid() -> Bar: ...
    @staticmethod
    def bar_3decimal() -> Bar: ...
    @staticmethod
    def mark_price(instrument_id: InstrumentId | None = None, value: Price | None = None) -> MarkPriceUpdate: ...
    @staticmethod
    def index_price(instrument_id: InstrumentId | None = None, value: Price | None = None) -> IndexPriceUpdate: ...
    @staticmethod
    def instrument_close(instrument_id: InstrumentId | None = None, price: Price | None = None, close_type: InstrumentCloseType | None = None, ts_event: int = 0) -> InstrumentClose: ...
    @staticmethod
    def instrument_status(instrument_id: InstrumentId | None = None, action: MarketStatusAction | None = None) -> InstrumentStatus: ...
    @staticmethod
    def order(instrument: Instrument | None = None, side: OrderSide = ..., price: float = 100.0, size: float = 100.0) -> BookOrder: ...
    @staticmethod
    def order_book(instrument: Instrument | None = None, book_type: BookType = ..., bid_price: float = 100.0, ask_price: float = 101.0, bid_size: float = 1000.0, ask_size: float = 1000.0, bid_levels: int = 3, ask_levels: int = 3, ts_event: int = 0, ts_init: int = 0) -> OrderBook: ...
    @staticmethod
    def order_book_snapshot(instrument: Instrument | None = None, bid_price: float = 100.0, ask_price: float = 101.0, bid_size: float = 1000.0, ask_size: float = 1000.0, bid_levels: int = 3, ask_levels: int = 3, ts_event: int = 0, ts_init: int = 0) -> OrderBookDeltas: ...
    @staticmethod
    def order_book_delta(instrument_id: InstrumentId | None = None, action: BookAction | None = None, order: BookOrder | None = None, flags: int = 0, sequence: int = 0, ts_event: int = 0, ts_init: int = 0) -> OrderBookDeltas: ...
    @staticmethod
    def order_book_depth10(instrument: Instrument | None = None, instrument_id: InstrumentId | None = None, flags: int = 0, sequence: int = 0, ts_event: int = 0, ts_init: int = 0, levels: int = 10, price_precision: int = 2, size_precision: int = 0) -> OrderBookDepth10: ...
    @staticmethod
    def order_book_delta_clear(instrument_id: InstrumentId | None = None) -> OrderBookDeltas: ...
    @staticmethod
    def order_book_deltas(instrument_id: InstrumentId | None = None, deltas: list[OrderBookDelta] | None = None, flags: int = 0) -> OrderBookDeltas: ...
    @staticmethod
    def make_book(instrument: Instrument, book_type: BookType, bids: list[tuple] | None = None, asks: list[tuple] | None = None) -> OrderBook: ...
    @staticmethod
    def l1_feed(): ...
    @staticmethod
    def l2_feed(filename: PathLike[str] | str) -> list: ...
    @staticmethod
    def l3_feed(filename: PathLike[str] | str) -> list[dict[str, Any]]: ...
    @staticmethod
    def bar_data_from_csv(filename: str, bar_type: BarType, instrument: Instrument, names=None) -> list[Bar]: ...
    @staticmethod
    def binance_bars_from_csv(filename: str, bar_type: BarType, instrument: Instrument): ...

class MyData(Data):
    value: Incomplete
    def __init__(self, value, ts_event: int = 0, ts_init: int = 0) -> None: ...
    @property
    def ts_event(self) -> int: ...
    @property
    def ts_init(self) -> int: ...
