from nautilus_trader.accounting.accounts.base import Account as Account
from nautilus_trader.common.enums import ComponentState as ComponentState
from nautilus_trader.common.messages import ComponentStateChanged as ComponentStateChanged, TradingStateChanged as TradingStateChanged
from nautilus_trader.core.uuid import UUID4 as UUID4
from nautilus_trader.model.currencies import AUD as AUD, GBP as GBP, USD as USD
from nautilus_trader.model.enums import AccountType as AccountType, LiquiditySide as LiquiditySide, OrderSide as OrderSide, TradingState as TradingState
from nautilus_trader.model.events import AccountState as AccountState, OrderAccepted as OrderAccepted, OrderCanceled as OrderCanceled, OrderExpired as OrderExpired, OrderFilled as OrderFilled, OrderPendingCancel as OrderPendingCancel, OrderPendingUpdate as OrderPendingUpdate, OrderRejected as OrderRejected, OrderReleased as OrderReleased, OrderSubmitted as OrderSubmitted, OrderTriggered as OrderTriggered, OrderUpdated as OrderUpdated, PositionChanged as PositionChanged, PositionClosed as PositionClosed, PositionOpened as PositionOpened
from nautilus_trader.model.identifiers import AccountId as AccountId, ClientOrderId as ClientOrderId, ComponentId as ComponentId, PositionId as PositionId, StrategyId as StrategyId, TradeId as TradeId, VenueOrderId as VenueOrderId
from nautilus_trader.model.instruments import Instrument as Instrument
from nautilus_trader.model.objects import AccountBalance as AccountBalance, Currency as Currency, MarginBalance as MarginBalance, Money as Money, Price as Price, Quantity as Quantity
from nautilus_trader.model.orders import Order as Order
from nautilus_trader.model.position import Position as Position
from nautilus_trader.test_kit.stubs.identifiers import TestIdStubs as TestIdStubs

class TestEventStubs:
    @staticmethod
    def component_state_changed() -> ComponentStateChanged: ...
    @staticmethod
    def trading_state_changed() -> TradingStateChanged: ...
    @staticmethod
    def cash_account_state(account_id: AccountId | None = None, base_currency: Currency | None = ...) -> AccountState: ...
    @staticmethod
    def margin_account_state(account_id: AccountId | None = None) -> AccountState: ...
    @staticmethod
    def betting_account_state(balance: float = 10000, currency: Currency = ..., account_id: AccountId | None = None) -> AccountState: ...
    @staticmethod
    def order_released(order: Order, released_price: Price | None = None) -> OrderReleased: ...
    @staticmethod
    def order_submitted(order: Order, account_id: AccountId | None = None, ts_event: int = 0) -> OrderSubmitted: ...
    @staticmethod
    def order_accepted(order: Order, account_id: AccountId | None = None, venue_order_id: VenueOrderId | None = None, ts_event: int = 0) -> OrderAccepted: ...
    @staticmethod
    def order_rejected(order: Order, account_id: AccountId | None = None, ts_event: int = 0) -> OrderRejected: ...
    @staticmethod
    def order_pending_update(order: Order, ts_event: int = 0) -> OrderPendingUpdate: ...
    @staticmethod
    def order_updated(order: Order, quantity: Quantity | None = None, price: Price | None = None, trigger_price: Price | None = None, ts_event: int = 0) -> OrderUpdated: ...
    @staticmethod
    def order_pending_cancel(order: Order, ts_event: int = 0) -> OrderPendingCancel: ...
    @staticmethod
    def order_filled(order: Order, instrument: Instrument, strategy_id: StrategyId | None = None, account_id: AccountId | None = None, venue_order_id: VenueOrderId | None = None, trade_id: TradeId | None = None, position_id: PositionId | None = None, last_qty: Quantity | None = None, last_px: Price | None = None, side: OrderSide | None = None, liquidity_side: LiquiditySide = ..., commission: Money | None = None, currency: Currency | None = None, client_order_id: ClientOrderId | None = None, account: Account | None = None, ts_event: int = 0) -> OrderFilled: ...
    @staticmethod
    def order_canceled(order: Order, account_id: AccountId | None = None, ts_event: int = 0) -> OrderCanceled: ...
    @staticmethod
    def order_expired(order: Order, ts_event: int = 0) -> OrderExpired: ...
    @staticmethod
    def order_triggered(order: Order, ts_event: int = 0) -> OrderTriggered: ...
    @staticmethod
    def position_opened(position: Position) -> PositionOpened: ...
    @staticmethod
    def position_changed(position: Position) -> PositionChanged: ...
    @staticmethod
    def position_closed(position: Position) -> PositionClosed: ...
