from nautilus_trader.common.config import PositiveInt as PositiveInt
from nautilus_trader.config import LiveDataClientConfig as LiveDataClientConfig, LiveExecClientConfig as LiveExecClientConfig
from nautilus_trader.core.nautilus_pyo3 import BitmexEnvironment as BitmexEnvironment
from nautilus_trader.network import TransportBackend as TransportBackend

class BitmexDataClientConfig(LiveDataClientConfig, frozen=True):
    api_key: str | None = ...
    api_secret: str | None = ...
    environment: BitmexEnvironment | None = ...
    base_url_http: str | None = ...
    base_url_ws: str | None = ...
    proxy_url: str | None = ...
    transport_backend: TransportBackend | None = ...
    http_timeout_secs: PositiveInt | None = ...
    max_retries: PositiveInt | None = ...
    retry_delay_initial_ms: PositiveInt | None = ...
    retry_delay_max_ms: PositiveInt | None = ...
    recv_window_ms: PositiveInt | None = ...
    update_instruments_interval_mins: PositiveInt | None = ...
    max_requests_per_second: PositiveInt = ...
    max_requests_per_minute: PositiveInt = ...

class BitmexExecClientConfig(LiveExecClientConfig, frozen=True):
    api_key: str | None = ...
    api_secret: str | None = ...
    environment: BitmexEnvironment | None = ...
    base_url_http: str | None = ...
    base_url_ws: str | None = ...
    proxy_url: str | None = ...
    transport_backend: TransportBackend | None = ...
    http_timeout_secs: PositiveInt | None = ...
    max_retries: PositiveInt | None = ...
    retry_delay_initial_ms: PositiveInt | None = ...
    retry_delay_max_ms: PositiveInt | None = ...
    recv_window_ms: PositiveInt | None = ...
    max_requests_per_second: PositiveInt = ...
    max_requests_per_minute: PositiveInt = ...
    submitter_pool_size: PositiveInt | None = ...
    canceller_pool_size: PositiveInt | None = ...
    submitter_proxy_urls: list[str] | None = ...
    canceller_proxy_urls: list[str] | None = ...
    deadmans_switch_timeout_secs: PositiveInt | None = ...
