import pandas as pd
from _typeshed import Incomplete
from ibapi.contract import ContractDetails as ContractDetails
from nautilus_trader.adapters.interactive_brokers.common import ComboLeg as ComboLeg, IBContract as IBContract, IBContractDetails as IBContractDetails
from nautilus_trader.adapters.interactive_brokers.config import SymbologyMethod as SymbologyMethod
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.model.enums import AssetClass as AssetClass, OptionKind as OptionKind, asset_class_from_str as asset_class_from_str
from nautilus_trader.model.identifiers import InstrumentId as InstrumentId, Symbol as Symbol, Venue as Venue, generic_spread_id_to_list as generic_spread_id_to_list, is_generic_spread_id as is_generic_spread_id, new_generic_spread_id as new_generic_spread_id
from nautilus_trader.model.instruments import Cfd as Cfd, Commodity as Commodity, CryptoPerpetual as CryptoPerpetual, CurrencyPair as CurrencyPair, Equity as Equity, FuturesContract as FuturesContract, FuturesSpread as FuturesSpread, IndexInstrument as IndexInstrument, Instrument as Instrument, OptionContract as OptionContract
from nautilus_trader.model.instruments.option_spread import OptionSpread as OptionSpread
from nautilus_trader.model.objects import Currency as Currency, Price as Price, Quantity as Quantity

VENUE_MEMBERS: dict[str, list[str]]
FUTURES_MONTH_TO_CODE: dict[str, str]
FUTURES_CODE_TO_MONTH: Incomplete
VENUES_FUT: Incomplete
VENUES_CASH: Incomplete
VENUES_CRYPTO: Incomplete
VENUES_OPT: Incomplete
VENUES_CFD: Incomplete
VENUES_CMDTY: Incomplete
EXCHANGES_BY_SEC_TYPE: dict[str, frozenset[str]]
RE_CASH: Incomplete
RE_CFD_CASH: Incomplete
RE_OPT: Incomplete
RE_OPT_UNPADDED: Incomplete
RE_OPT2: Incomplete
RE_FUT_UNDERLYING: Incomplete
RE_FUT: Incomplete
RE_FUT2: Incomplete
RE_FUT3: Incomplete
RE_FUT4: Incomplete
RE_FOP: Incomplete
RE_CRYPTO: Incomplete

def exchange_supports_sec_type(exchange: str, sec_type: str) -> bool: ...
def possible_exchanges_for_venue(venue: str) -> tuple[str, ...]: ...
def exchange_to_mic_venue(exchange: str) -> str | None: ...
def sec_type_to_asset_class(sec_type: str) -> AssetClass: ...
def contract_details_to_ib_contract_details(contract_details: ContractDetails) -> IBContractDetails: ...
def parse_instrument(contract_details: IBContractDetails, venue: str, symbology_method: SymbologyMethod = ..., contract_details_map: dict[int, IBContractDetails] | None = None) -> Instrument: ...
def parse_equity_contract(contract_details: IBContractDetails, instrument_id: InstrumentId) -> Equity: ...
def parse_index_contract(contract_details: IBContractDetails, instrument_id: InstrumentId) -> IndexInstrument: ...
def parse_futures_contract(contract_details: IBContractDetails, instrument_id: InstrumentId) -> FuturesContract: ...
def parse_option_contract(contract_details: IBContractDetails, instrument_id: InstrumentId, symbology_method: SymbologyMethod = ...) -> OptionContract: ...
def expiry_timestring_to_datetime(contract_details: IBContractDetails) -> pd.Timestamp: ...
def parse_forex_contract(contract_details: IBContractDetails, instrument_id: InstrumentId) -> CurrencyPair: ...
def parse_crypto_contract(contract_details: IBContractDetails, instrument_id: InstrumentId) -> CryptoPerpetual: ...
def parse_cfd_contract(contract_details: IBContractDetails, instrument_id: InstrumentId) -> Cfd: ...
def parse_commodity_contract(contract_details: IBContractDetails, instrument_id: InstrumentId) -> Commodity: ...
def parse_option_spread(contract_details: IBContractDetails, instrument_id: InstrumentId) -> OptionSpread: ...
def parse_option_spread_instrument_id(instrument_id: InstrumentId, leg_contract_details: list[tuple[IBContractDetails, int]], clock_timestamp_ns: int | None = None) -> OptionSpread: ...
def parse_futures_spread(contract_details: IBContractDetails, instrument_id: InstrumentId) -> FuturesSpread: ...
def parse_futures_spread_instrument_id(instrument_id: InstrumentId, leg_contract_details: list[tuple[IBContractDetails, int]], clock_timestamp_ns: int | None = None) -> FuturesSpread: ...
def contract_details_to_dict(contract_details: IBContractDetails) -> dict: ...
def decade_digit(last_digit: str, contract: IBContract) -> int: ...
def ib_contract_to_instrument_id(contract: IBContract, venue: str, symbology_method: SymbologyMethod = ..., contract_details_map: dict[int, IBContractDetails] | None = None) -> InstrumentId: ...
def ib_contract_to_instrument_id_simplified_symbology(contract: IBContract, venue: str, contract_details_map: dict[int, IBContractDetails] | None = None) -> InstrumentId: ...
def bag_contract_to_instrument_id(contract: IBContract, venue: str, contract_details_map: dict[int, IBContractDetails] | None = None) -> InstrumentId: ...
def ib_contract_to_instrument_id_raw_symbology(contract: IBContract, venue: str) -> InstrumentId: ...
def instrument_id_to_ib_contract(instrument_id: InstrumentId, exchange: str, symbology_method: SymbologyMethod = ..., contract_details_map: dict[InstrumentId, IBContractDetails] | None = None) -> IBContract: ...
def instrument_id_to_ib_contract_simplified_symbology(instrument_id: InstrumentId, exchange: str, contract_details_map: dict[InstrumentId, IBContractDetails] | None = None) -> IBContract: ...
def instrument_id_to_bag_contract(instrument_id: InstrumentId, exchange: str, contract_details_map: dict[InstrumentId, IBContractDetails] | None = None) -> IBContract: ...
def instrument_id_to_ib_contract_raw_symbology(instrument_id: InstrumentId) -> IBContract: ...
