from nautilus_trader.model.identifiers import InstrumentId as InstrumentId

def ib_price_to_nautilus_price(ib_price: float, price_magnifier: int | None) -> float: ...
def nautilus_price_to_ib_price(nautilus_price: float, price_magnifier: int | None) -> float: ...
def get_price_magnifier_for_instrument(instrument_id: InstrumentId, instrument_provider) -> int: ...
