import enum
import nautilus_trader.indicators.base
from _typeshed import Incomplete
from typing import Any, Callable, ClassVar

__test__: dict

class AdaptiveMovingAverage(MovingAverage):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    alpha_diff: Incomplete
    alpha_fast: Incomplete
    alpha_slow: Incomplete
    period_alpha_fast: Incomplete
    period_alpha_slow: Incomplete
    period_er: Incomplete
    def __init__(self, intperiod_er, intperiod_alpha_fast, intperiod_alpha_slow, PriceTypeprice_type=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def handle_quote_tick(self, QuoteTicktick) -> void: ...
    def handle_trade_tick(self, TradeTicktick) -> void: ...
    def update_raw(self, doublevalue) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class DoubleExponentialMovingAverage(MovingAverage):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, intperiod, PriceTypeprice_type=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def handle_quote_tick(self, QuoteTicktick) -> void: ...
    def handle_trade_tick(self, TradeTicktick) -> void: ...
    def update_raw(self, doublevalue) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class ExponentialMovingAverage(MovingAverage):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    alpha: Incomplete
    def __init__(self, intperiod, PriceTypeprice_type=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def handle_quote_tick(self, QuoteTicktick) -> void: ...
    def handle_trade_tick(self, TradeTicktick) -> void: ...
    def update_raw(self, doublevalue) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class HullMovingAverage(MovingAverage):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, intperiod, PriceTypeprice_type=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def handle_quote_tick(self, QuoteTicktick) -> void: ...
    def handle_trade_tick(self, TradeTicktick) -> void: ...
    def update_raw(self, doublevalue) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class MovingAverage(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    count: Incomplete
    period: Incomplete
    price_type: Incomplete
    value: Incomplete
    def __init__(self, intperiod, listparams, PriceTypeprice_type) -> Any: ...
    def update_raw(self, doublevalue) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class MovingAverageFactory:
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @staticmethod
    def create(intperiod, MovingAverageTypema_type: MovingAverageType, **kwargs) -> MovingAverage: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class MovingAverageType(enum.IntFlag):
    __new__: ClassVar[Callable] = ...
    ADAPTIVE: ClassVar[MovingAverageType] = ...
    DOUBLE_EXPONENTIAL: ClassVar[MovingAverageType] = ...
    EXPONENTIAL: ClassVar[MovingAverageType] = ...
    HULL: ClassVar[MovingAverageType] = ...
    SIMPLE: ClassVar[MovingAverageType] = ...
    VARIABLE_INDEX_DYNAMIC: ClassVar[MovingAverageType] = ...
    WEIGHTED: ClassVar[MovingAverageType] = ...
    WILDER: ClassVar[MovingAverageType] = ...
    _all_bits_: ClassVar[int] = ...
    _boundary_: ClassVar[enum.FlagBoundary] = ...
    _flag_mask_: ClassVar[int] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _hashable_values_: ClassVar[list] = ...
    _inverted_: ClassVar[None] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _singles_mask_: ClassVar[int] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    __and__: ClassVar[Callable] = ...
    __invert__: ClassVar[Callable] = ...
    __or__: ClassVar[Callable] = ...
    __rand__: ClassVar[Callable] = ...
    __ror__: ClassVar[Callable] = ...
    __rxor__: ClassVar[Callable] = ...
    __xor__: ClassVar[Callable] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class SimpleMovingAverage(MovingAverage):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, intperiod, PriceTypeprice_type=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def handle_quote_tick(self, QuoteTicktick) -> void: ...
    def handle_trade_tick(self, TradeTicktick) -> void: ...
    def update_raw(self, doublevalue) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class VariableIndexDynamicAverage(MovingAverage):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    alpha: Incomplete
    cmo_pct: Incomplete
    def __init__(self, intperiod, PriceTypeprice_type=..., MovingAverageTypecmo_ma_type=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def handle_quote_tick(self, QuoteTicktick) -> void: ...
    def handle_trade_tick(self, TradeTicktick) -> void: ...
    def update_raw(self, doublevalue) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class WeightedMovingAverage(MovingAverage):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    weights: Incomplete
    def __init__(self, intperiod, weights=..., PriceTypeprice_type=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def handle_quote_tick(self, QuoteTicktick) -> void: ...
    def handle_trade_tick(self, TradeTicktick) -> void: ...
    def update_raw(self, doublevalue) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class WilderMovingAverage(MovingAverage):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    alpha: Incomplete
    def __init__(self, intperiod, PriceTypeprice_type=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def handle_quote_tick(self, QuoteTicktick) -> void: ...
    def handle_trade_tick(self, TradeTicktick) -> void: ...
    def update_raw(self, doublevalue) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
