from _typeshed import Incomplete
from typing import Any, ClassVar

__test__: dict

class Indicator:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    has_inputs: Incomplete
    initialized: Incomplete
    name: Incomplete
    def __init__(self, listparams) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def handle_quote_tick(self, QuoteTicktick) -> void: ...
    def handle_trade_tick(self, TradeTicktick) -> void: ...
    def reset(self) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
