import nautilus_trader.indicators.base
from _typeshed import Incomplete
from typing import Any, ClassVar

__test__: dict

class FuzzyCandle:
    body_size: Incomplete
    direction: Incomplete
    lower_wick_size: Incomplete
    size: Incomplete
    upper_wick_size: Incomplete
    def __init__(self, CandleDirectiondirection, CandleSizesize, CandleBodySizebody_size, CandleWickSizeupper_wick_size, CandleWickSizelower_wick_size) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class FuzzyCandlesticks(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    period: Incomplete
    value: Incomplete
    vector: Incomplete
    def __init__(self, intperiod, doublethreshold1=..., doublethreshold2=..., doublethreshold3=..., doublethreshold4=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doubleopen, doublehigh, doublelow, doubleclose) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
