import nautilus_trader.indicators.base
from _typeshed import Incomplete
from typing import Any, ClassVar

__test__: dict

class ChandeMomentumOscillator(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    period: Incomplete
    value: Incomplete
    def __init__(self, intperiod, ma_type=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doubleclose) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class CommodityChannelIndex(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    period: Incomplete
    scalar: Incomplete
    value: Incomplete
    def __init__(self, intperiod, doublescalar=..., ma_type=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doublehigh, doublelow, doubleclose) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class EfficiencyRatio(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    period: Incomplete
    value: Incomplete
    def __init__(self, intperiod) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doubleprice) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class PsychologicalLine(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    period: Incomplete
    value: Incomplete
    def __init__(self, intperiod, ma_type=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doubleclose) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class RateOfChange(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    period: Incomplete
    value: Incomplete
    def __init__(self, intperiod, booluse_log=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doubleprice) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class RelativeStrengthIndex(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    period: Incomplete
    value: Incomplete
    def __init__(self, intperiod, ma_type=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doublevalue) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class RelativeVolatilityIndex(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    period: Incomplete
    scalar: Incomplete
    value: Incomplete
    def __init__(self, intperiod, doublescalar=..., ma_type=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doubleclose) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class Stochastics(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    d_method: Incomplete
    ma_type: Incomplete
    period_d: Incomplete
    period_k: Incomplete
    slowing: Incomplete
    value_d: Incomplete
    value_k: Incomplete
    def __init__(self, intperiod_k, intperiod_d, intslowing=..., ma_type=..., strd_method=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doublehigh, doublelow, doubleclose) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class StochasticsDMethod:
    MOVING_AVERAGE: ClassVar[str] = ...
    RATIO: ClassVar[str] = ...
