import nautilus_trader.indicators.base
from _typeshed import Incomplete
from typing import Any, ClassVar

__test__: dict

class SpreadAnalyzer(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    average: Incomplete
    capacity: Incomplete
    current: Incomplete
    instrument_id: Incomplete
    def __init__(self, InstrumentIdinstrument_id, intcapacity) -> None: ...
    def handle_quote_tick(self, QuoteTicktick) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
