import nautilus_trader.indicators.base
from _typeshed import Incomplete
from nautilus_trader.indicators.averages import MovingAverageFactory as MovingAverageFactory
from typing import Any, ClassVar

__test__: dict

class ArcherMovingAveragesTrends(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    fast_period: Incomplete
    long_run: Incomplete
    short_run: Incomplete
    signal_period: Incomplete
    slow_period: Incomplete
    def __init__(self, intfast_period, intslow_period, intsignal_period, MovingAverageTypema_type=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doubleclose) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class AroonOscillator(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    aroon_down: Incomplete
    aroon_up: Incomplete
    period: Incomplete
    value: Incomplete
    def __init__(self, intperiod) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doublehigh, doublelow) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class Bias(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    period: Incomplete
    value: Incomplete
    def __init__(self, intperiod, MovingAverageTypema_type=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doubleclose) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class DirectionalMovement(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    neg: Incomplete
    period: Incomplete
    pos: Incomplete
    value: Incomplete
    def __init__(self, intperiod, MovingAverageTypema_type=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doublehigh, doublelow) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class IchimokuCloud(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    chikou_span: Incomplete
    displacement: Incomplete
    kijun_period: Incomplete
    kijun_sen: Incomplete
    senkou_period: Incomplete
    senkou_span_a: Incomplete
    senkou_span_b: Incomplete
    tenkan_period: Incomplete
    tenkan_sen: Incomplete
    def __init__(self, inttenkan_period=..., intkijun_period=..., intsenkou_period=..., intdisplacement=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doublehigh, doublelow, doubleclose) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class LinearRegression(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    R2: Incomplete
    cfo: Incomplete
    degree: Incomplete
    intercept: Incomplete
    period: Incomplete
    slope: Incomplete
    value: Incomplete
    def __init__(self, intperiod=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doubleclose) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class MovingAverageConvergenceDivergence(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    fast_period: Incomplete
    slow_period: Incomplete
    value: Incomplete
    def __init__(self, intfast_period, intslow_period, MovingAverageTypema_type=..., PriceTypeprice_type=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def handle_quote_tick(self, QuoteTicktick) -> void: ...
    def handle_trade_tick(self, TradeTicktick) -> void: ...
    def update_raw(self, doubleclose) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class Swings(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    changed: Incomplete
    direction: Incomplete
    duration: Incomplete
    high_datetime: Incomplete
    high_price: Incomplete
    length: Incomplete
    low_datetime: Incomplete
    low_price: Incomplete
    period: Incomplete
    since_high: Incomplete
    since_low: Incomplete
    def __init__(self, intperiod) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doublehigh, doublelow, datetimetimestamp) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
