import nautilus_trader.indicators.base
from _typeshed import Incomplete
from nautilus_trader.indicators.averages import MovingAverageFactory as MovingAverageFactory
from typing import Any, ClassVar

__test__: dict

class AverageTrueRange(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    period: Incomplete
    value: Incomplete
    def __init__(self, intperiod, MovingAverageTypema_type=..., booluse_previous=..., doublevalue_floor=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doublehigh, doublelow, doubleclose) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class BollingerBands(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    k: Incomplete
    lower: Incomplete
    middle: Incomplete
    period: Incomplete
    upper: Incomplete
    def __init__(self, intperiod, doublek, MovingAverageTypema_type=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def handle_quote_tick(self, QuoteTicktick) -> void: ...
    def handle_trade_tick(self, TradeTicktick) -> void: ...
    def update_raw(self, doublehigh, doublelow, doubleclose) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class DonchianChannel(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    lower: Incomplete
    middle: Incomplete
    period: Incomplete
    upper: Incomplete
    def __init__(self, intperiod) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def handle_quote_tick(self, QuoteTicktick) -> void: ...
    def handle_trade_tick(self, TradeTicktick) -> void: ...
    def update_raw(self, doublehigh, doublelow) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class KeltnerChannel(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    k_multiplier: Incomplete
    lower: Incomplete
    middle: Incomplete
    period: Incomplete
    upper: Incomplete
    def __init__(self, intperiod, doublek_multiplier, MovingAverageTypema_type=..., MovingAverageTypema_type_atr=..., booluse_previous=..., doubleatr_floor=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doublehigh, doublelow, doubleclose) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class KeltnerPosition(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    k_multiplier: Incomplete
    period: Incomplete
    value: Incomplete
    def __init__(self, intperiod, doublek_multiplier, MovingAverageTypema_type=..., MovingAverageTypema_type_atr=..., booluse_previous=..., doubleatr_floor=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doublehigh, doublelow, doubleclose) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class VerticalHorizontalFilter(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    period: Incomplete
    value: Incomplete
    def __init__(self, intperiod, MovingAverageTypema_type=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doubleclose) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class VolatilityRatio(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    fast_period: Incomplete
    slow_period: Incomplete
    value: Incomplete
    def __init__(self, intfast_period, intslow_period, MovingAverageTypema_type=..., booluse_previous=..., doublevalue_floor=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doublehigh, doublelow, doubleclose) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
