import nautilus_trader.indicators.base
from _typeshed import Incomplete
from nautilus_trader.indicators.averages import MovingAverageFactory as MovingAverageFactory
from nautilus_trader.indicators.volatility import AverageTrueRange as AverageTrueRange
from typing import Any, ClassVar

__test__: dict

class KlingerVolumeOscillator(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    fast_period: Incomplete
    signal_period: Incomplete
    slow_period: Incomplete
    value: Incomplete
    def __init__(self, intfast_period, intslow_period, intsignal_period, MovingAverageTypema_type=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doublehigh, doublelow, doubleclose, doublevolume) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class OnBalanceVolume(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    period: Incomplete
    value: Incomplete
    def __init__(self, intperiod=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doubleopen, doubleclose, doublevolume) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class Pressure(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    period: Incomplete
    value: Incomplete
    value_cumulative: Incomplete
    def __init__(self, intperiod, MovingAverageTypema_type=..., doubleatr_floor=...) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doublehigh, doublelow, doubleclose, doublevolume) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class VolumeWeightedAveragePrice(nautilus_trader.indicators.base.Indicator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    value: Incomplete
    def __init__(self) -> Any: ...
    def handle_bar(self, Barbar) -> void: ...
    def update_raw(self, doubleprice, doublevolume, datetimetimestamp) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
