import msgspec
from nautilus_trader.adapters.binance.common.enums import BinanceFuturesPositionSide as BinanceFuturesPositionSide, BinanceOrderSide as BinanceOrderSide, BinanceOrderType as BinanceOrderType, BinanceTimeInForce as BinanceTimeInForce
from nautilus_trader.adapters.binance.futures.enums import BinanceFuturesEnumParser as BinanceFuturesEnumParser
from nautilus_trader.core.datetime import millis_to_nanos as millis_to_nanos
from nautilus_trader.core.uuid import UUID4 as UUID4
from nautilus_trader.execution.reports import OrderStatusReport as OrderStatusReport, PositionStatusReport as PositionStatusReport
from nautilus_trader.model.enums import ContingencyType as ContingencyType, OrderStatus as OrderStatus, PositionSide as PositionSide, TimeInForce as TimeInForce, TrailingOffsetType as TrailingOffsetType, TriggerType as TriggerType
from nautilus_trader.model.identifiers import AccountId as AccountId, ClientOrderId as ClientOrderId, InstrumentId as InstrumentId, PositionId as PositionId, VenueOrderId as VenueOrderId
from nautilus_trader.model.objects import AccountBalance as AccountBalance, Currency as Currency, MarginBalance as MarginBalance, Money as Money, Price as Price, Quantity as Quantity

class BinanceFuturesBalanceInfo(msgspec.Struct, frozen=True):
    asset: str
    walletBalance: str
    unrealizedProfit: str
    marginBalance: str
    maintMargin: str
    initialMargin: str
    positionInitialMargin: str
    openOrderInitialMargin: str
    crossWalletBalance: str
    crossUnPnl: str
    availableBalance: str
    maxWithdrawAmount: str
    marginAvailable: bool | None = ...
    updateTime: int | None = ...
    def parse_to_account_balance(self) -> AccountBalance: ...
    def parse_to_margin_balance(self) -> MarginBalance: ...

class BinanceFuturesAccountInfo(msgspec.Struct, kw_only=True, frozen=True):
    feeTier: int
    canTrade: bool
    canDeposit: bool
    canWithdraw: bool
    updateTime: int
    totalInitialMargin: str | None = ...
    totalMaintMargin: str | None = ...
    totalWalletBalance: str | None = ...
    totalUnrealizedProfit: str | None = ...
    totalMarginBalance: str | None = ...
    totalPositionInitialMargin: str | None = ...
    totalOpenOrderInitialMargin: str | None = ...
    totalCrossWalletBalance: str | None = ...
    totalCrossUnPnl: str | None = ...
    availableBalance: str | None = ...
    maxWithdrawAmount: str | None = ...
    assets: list[BinanceFuturesBalanceInfo]
    def parse_to_account_balances(self) -> list[AccountBalance]: ...
    def parse_to_margin_balances(self) -> list[MarginBalance]: ...

class BinanceFuturesPositionRisk(msgspec.Struct, kw_only=True, frozen=True):
    symbol: str
    positionSide: BinanceFuturesPositionSide
    positionAmt: str
    entryPrice: str
    markPrice: str
    unRealizedProfit: str
    liquidationPrice: str
    isolatedMargin: str
    updateTime: int
    marginType: str | None = ...
    isAutoAddMargin: str | None = ...
    leverage: str | None = ...
    maxNotionalValue: str | None = ...
    breakEvenPrice: str | None = ...
    notional: str | None = ...
    marginAsset: str | None = ...
    isolatedWallet: str | None = ...
    initialMargin: str | None = ...
    maintMargin: str | None = ...
    positionInitialMargin: str | None = ...
    openOrderInitialMargin: str | None = ...
    adl: int | None = ...
    bidNotional: str | None = ...
    askNotional: str | None = ...
    def parse_to_position_status_report(self, account_id: AccountId, instrument_id: InstrumentId, enum_parser: BinanceFuturesEnumParser, report_id: UUID4, ts_init: int) -> PositionStatusReport: ...

class BinanceFuturesDualSidePosition(msgspec.Struct, frozen=True):
    dualSidePosition: bool

class BinanceFuturesFeeRates(msgspec.Struct, frozen=True):
    feeTier: int
    maker: str
    taker: str

class BinanceFuturesLeverage(msgspec.Struct, frozen=True):
    leverage: int
    maxNotionalValue: str
    symbol: str

class BinanceFuturesSymbolConfig(msgspec.Struct, frozen=True):
    symbol: str
    marginType: str
    isAutoAddMargin: bool
    leverage: int
    maxNotionalValue: str

class BinanceFuturesMarginTypeResponse(msgspec.Struct, frozen=True):
    code: int
    msg: str

class BinanceFuturesAlgoOrder(msgspec.Struct, frozen=True):
    algoId: int
    clientAlgoId: str
    algoType: str
    orderType: str
    symbol: str
    side: str
    positionSide: str | None = ...
    timeInForce: str | None = ...
    quantity: str | None = ...
    algoStatus: str | None = ...
    triggerPrice: str | None = ...
    price: str | None = ...
    workingType: str | None = ...
    priceMatch: str | None = ...
    closePosition: bool | None = ...
    priceProtect: bool | None = ...
    reduceOnly: bool | None = ...
    selfTradePreventionMode: str | None = ...
    activatePrice: str | None = ...
    callbackRate: str | None = ...
    createTime: int | None = ...
    updateTime: int | None = ...
    triggerTime: int | None = ...
    goodTillDate: int | None = ...
    actualOrderId: str | None = ...
    def parse_to_order_status_report(self, account_id: AccountId, instrument_id: InstrumentId, report_id: UUID4, enum_parser: BinanceFuturesEnumParser, ts_init: int) -> OrderStatusReport: ...

class BinanceFuturesAlgoOrderCancelResponse(msgspec.Struct, frozen=True):
    algoId: int
    clientAlgoId: str
    code: str
    msg: str
