import datetime as dt
from nautilus_trader.core import nautilus_pyo3 as nautilus_pyo3
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.model.data import BarType as BarType, FundingRateUpdate as FundingRateUpdate, OrderBookDelta as OrderBookDelta, OrderBookDepth10 as OrderBookDepth10, QuoteTick as QuoteTick, TradeTick as TradeTick
from nautilus_trader.model.identifiers import InstrumentId as InstrumentId
from nautilus_trader.model.instruments import CryptoFuture as CryptoFuture, CryptoOption as CryptoOption, CryptoPerpetual as CryptoPerpetual, CurrencyPair as CurrencyPair, Instrument as Instrument

def create_instrument_info(instrument: Instrument) -> nautilus_pyo3.TardisInstrumentMiniInfo: ...
def infer_tardis_exchange_str(instrument: Instrument) -> str: ...
def get_ws_client_key(instrument_id: InstrumentId, tardis_data_type: str) -> str: ...
def convert_nautilus_data_type_to_tardis_data_type(data_type: type) -> str: ...
def convert_nautilus_bar_type_to_tardis_data_type(bar_type: BarType) -> str: ...
def create_replay_normalized_request_options(exchange: str, symbols: list[str], from_date: dt.date, to_date: dt.date, data_types: list[str]) -> nautilus_pyo3.ReplayNormalizedRequestOptions: ...
def create_stream_normalized_request_options(exchange: str, symbols: list[str], data_types: list[str]) -> nautilus_pyo3.StreamNormalizedRequestOptions: ...
