from nautilus_trader.common.config import PositiveInt as PositiveInt
from nautilus_trader.config import LiveDataClientConfig as LiveDataClientConfig

class TardisDataClientConfig(LiveDataClientConfig, frozen=True):
    api_key: str | None = ...
    base_url_http: str | None = ...
    base_url_ws: str | None = ...
    proxy_url: str | None = ...
    update_instruments_interval_mins: PositiveInt | None = ...
    ws_connection_delay_secs: PositiveInt = ...
