from collections.abc import Generator
from nautilus_trader.core import nautilus_pyo3 as nautilus_pyo3
from nautilus_trader.model.data import FundingRateUpdate as FundingRateUpdate, OrderBookDelta as OrderBookDelta, OrderBookDeltas as OrderBookDeltas, OrderBookDepth10 as OrderBookDepth10, QuoteTick as QuoteTick, TradeTick as TradeTick, capsule_to_data as capsule_to_data
from nautilus_trader.model.identifiers import InstrumentId as InstrumentId
from os import PathLike

class TardisCSVDataLoader:
    def __init__(self, price_precision: int | None = None, size_precision: int | None = None, instrument_id: InstrumentId | None = None) -> None: ...
    def load_deltas(self, filepath: PathLike[str] | str, as_legacy_cython: bool = True, limit: int | None = None) -> list[OrderBookDelta] | list[nautilus_pyo3.OrderBookDelta]: ...
    def load_depth10(self, filepath: PathLike[str] | str, levels: int, as_legacy_cython: bool = True, limit: int | None = None) -> list[OrderBookDepth10] | list[nautilus_pyo3.OrderBookDepth10]: ...
    def load_quotes(self, filepath: PathLike[str] | str, as_legacy_cython: bool = True, limit: int | None = None) -> list[QuoteTick] | list[nautilus_pyo3.QuoteTick]: ...
    def load_trades(self, filepath: PathLike[str] | str, as_legacy_cython: bool = True, limit: int | None = None) -> list[TradeTick] | list[nautilus_pyo3.TradeTick]: ...
    def load_funding_rates(self, filepath: PathLike[str] | str, as_legacy_cython: bool = True, limit: int | None = None) -> list[FundingRateUpdate] | list[nautilus_pyo3.FundingRateUpdate]: ...
    def load_options_chain(self, filepath: PathLike[str] | str, underlyings: list[str] | None = None, limit: int | None = None) -> list[object]: ...
    def convert_options_chain_csv(self, filepaths: list[PathLike[str] | str], catalog_path: PathLike[str] | str, underlyings: list[str] | None = None, snapshot_interval_ms: int | None = None, extract_bbo_as_quotes: bool = True, write_instruments: bool = True) -> None: ...
    def stream_deltas(self, filepath: PathLike[str] | str, chunk_size: int = 100000, as_legacy_cython: bool = True, limit: int | None = None) -> Generator[list[OrderBookDelta] | list[nautilus_pyo3.OrderBookDelta], None, None]: ...
    def stream_batched_deltas(self, filepath: PathLike[str] | str, chunk_size: int = 100000, limit: int | None = None) -> Generator[list[OrderBookDeltas], None, None]: ...
    def stream_quotes(self, filepath: PathLike[str] | str, chunk_size: int = 100000, as_legacy_cython: bool = True, limit: int | None = None) -> Generator[list[QuoteTick] | list[nautilus_pyo3.QuoteTick], None, None]: ...
    def stream_options_chain(self, filepath: PathLike[str] | str, chunk_size: int = 100000, underlyings: list[str] | None = None, limit: int | None = None) -> Generator[list[object], None, None]: ...
    def stream_trades(self, filepath: PathLike[str] | str, chunk_size: int = 100000, as_legacy_cython: bool = True, limit: int | None = None) -> Generator[list[TradeTick] | list[nautilus_pyo3.TradeTick], None, None]: ...
    def stream_depth10(self, filepath: PathLike[str] | str, levels: int, chunk_size: int = 100000, as_legacy_cython: bool = True, limit: int | None = None) -> Generator[list[OrderBookDepth10] | list[nautilus_pyo3.OrderBookDepth10], None, None]: ...
    def stream_funding_rates(self, filepath: PathLike[str] | str, chunk_size: int = 100000, as_legacy_cython: bool = True, limit: int | None = None) -> Generator[list[FundingRateUpdate] | list[nautilus_pyo3.FundingRateUpdate], None, None]: ...
