from nautilus_trader.adapters.binance.common.enums import BinanceAccountType as BinanceAccountType, BinanceEnvironment as BinanceEnvironment
from nautilus_trader.adapters.env import get_env_key as get_env_key

def is_ed25519_private_key(api_secret: str) -> bool: ...
def extract_ed25519_private_key(api_secret: str) -> bytes: ...
def get_api_key(account_type: BinanceAccountType, environment: BinanceEnvironment) -> str: ...
def get_api_secret(account_type: BinanceAccountType, environment: BinanceEnvironment) -> str: ...
