from nautilus_trader.adapters.binance.common.enums import BinanceAccountType as BinanceAccountType
from nautilus_trader.core.correctness import PyCondition as PyCondition

class BinanceSymbol(str):
    def __new__(cls, symbol: str) -> BinanceSymbol: ...
    def parse_as_nautilus(self, account_type: BinanceAccountType) -> str: ...

class BinanceSymbols(str):
    def __new__(cls, symbols: list[str]) -> BinanceSymbols: ...
    def parse_str_to_list(self) -> list[BinanceSymbol]: ...
