from nautilus_trader.adapters.binance.common.enums import BinanceAccountType as BinanceAccountType, BinanceEnvironment as BinanceEnvironment

def get_http_base_url(account_type: BinanceAccountType, environment: BinanceEnvironment, is_us: bool) -> str: ...
def get_ws_api_base_url(account_type: BinanceAccountType, environment: BinanceEnvironment, is_us: bool) -> str: ...
def get_ws_base_url(account_type: BinanceAccountType, environment: BinanceEnvironment, is_us: bool) -> str: ...
def get_ws_public_base_url(account_type: BinanceAccountType, environment: BinanceEnvironment, is_us: bool) -> str: ...
def get_ws_private_base_url(account_type: BinanceAccountType, environment: BinanceEnvironment, is_us: bool) -> str: ...
def get_futures_user_stream_url(account_type: BinanceAccountType, base_url: str, listen_key: str) -> str: ...
def get_usdm_ws_route_base_url(base_url: str, route: str) -> str: ...
