from nautilus_trader.common.config import PositiveInt as PositiveInt
from nautilus_trader.config import LiveDataClientConfig as LiveDataClientConfig, LiveExecClientConfig as LiveExecClientConfig
from nautilus_trader.core.nautilus_pyo3 import OKXContractType as OKXContractType, OKXEnvironment as OKXEnvironment, OKXInstrumentType as OKXInstrumentType, OKXMarginMode as OKXMarginMode, OKXRegion as OKXRegion, OKXVipLevel as OKXVipLevel
from nautilus_trader.network import TransportBackend as TransportBackend

class OKXDataClientConfig(LiveDataClientConfig, frozen=True):
    api_key: str | None = ...
    api_secret: str | None = ...
    api_passphrase: str | None = ...
    instrument_types: tuple[OKXInstrumentType, ...] = ...
    instrument_families: tuple[str, ...] | None = ...
    contract_types: tuple[OKXContractType, ...] | None = ...
    environment: OKXEnvironment | None = ...
    region: OKXRegion | None = ...
    base_url_http: str | None = ...
    base_url_ws: str | None = ...
    proxy_url: str | None = ...
    transport_backend: TransportBackend | None = ...
    http_timeout_secs: PositiveInt | None = ...
    max_retries: PositiveInt | None = ...
    retry_delay_initial_ms: PositiveInt | None = ...
    retry_delay_max_ms: PositiveInt | None = ...
    update_instruments_interval_mins: PositiveInt | None = ...
    load_spreads: bool = ...
    vip_level: OKXVipLevel | None = ...

class OKXExecClientConfig(LiveExecClientConfig, frozen=True):
    api_key: str | None = ...
    api_secret: str | None = ...
    api_passphrase: str | None = ...
    instrument_types: tuple[OKXInstrumentType, ...] = ...
    contract_types: tuple[OKXContractType, ...] | None = ...
    instrument_families: tuple[str, ...] | None = ...
    environment: OKXEnvironment | None = ...
    region: OKXRegion | None = ...
    base_url_http: str | None = ...
    base_url_ws: str | None = ...
    proxy_url: str | None = ...
    transport_backend: TransportBackend | None = ...
    margin_mode: OKXMarginMode | None = ...
    use_spot_margin: bool = ...
    http_timeout_secs: PositiveInt | None = ...
    max_retries: PositiveInt | None = ...
    retry_delay_initial_ms: PositiveInt | None = ...
    retry_delay_max_ms: PositiveInt | None = ...
    use_fills_channel: bool = ...
    use_mm_mass_cancel: bool = ...
    use_spot_cash_position_reports: bool = ...
    ws_auth_timeout_secs: PositiveInt | None = ...
    load_spreads: bool = ...
