from nautilus_trader.adapters.okx.constants import OKX_VENUE as OKX_VENUE
from nautilus_trader.common.providers import InstrumentProvider as InstrumentProvider
from nautilus_trader.config import InstrumentProviderConfig as InstrumentProviderConfig
from nautilus_trader.core import nautilus_pyo3 as nautilus_pyo3
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.core.nautilus_pyo3 import OKXContractType as OKXContractType, OKXInstrumentType as OKXInstrumentType
from nautilus_trader.model.identifiers import InstrumentId as InstrumentId
from nautilus_trader.model.instruments import instruments_from_pyo3 as instruments_from_pyo3
from typing import Any

class OKXInstrumentProvider(InstrumentProvider):
    def __init__(self, client: nautilus_pyo3.OKXHttpClient, instrument_types: tuple[OKXInstrumentType, ...], contract_types: tuple[OKXContractType, ...] | None = None, instrument_families: tuple[str, ...] | None = None, load_spreads: bool = False, config: InstrumentProviderConfig | None = None) -> None: ...
    @property
    def instrument_types(self) -> tuple[OKXInstrumentType, ...]: ...
    @property
    def contract_types(self) -> tuple[OKXContractType, ...] | None: ...
    @property
    def instrument_families(self) -> tuple[str, ...] | None: ...
    @property
    def load_spreads(self) -> bool: ...
    def instruments_pyo3(self) -> list[Any]: ...
    def inst_id_codes(self) -> list[tuple[str, int]]: ...
    async def load_all_async(self, filters: dict | None = None) -> None: ...
    async def load_ids_async(self, instrument_ids: list[InstrumentId], filters: dict | None = None) -> None: ...
    async def load_async(self, instrument_id: InstrumentId, filters: dict | None = None) -> None: ...
