import asyncio
import nautilus_trader.common.component
from _typeshed import Incomplete
from concurrent.futures._base import Executor
from nautilus_trader.common.config import ActorConfig as ActorConfig, ImportableActorConfig as ImportableActorConfig
from nautilus_trader.common.executor import ActorExecutor as ActorExecutor, TaskId as TaskId
from nautilus_trader.common.signal import generate_signal_class as generate_signal_class
from typing import Any, Callable, ClassVar

__test__: dict

class Actor(nautilus_trader.common.component.Component):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    cache: Incomplete
    clock: Incomplete
    config: Incomplete
    greeks: Incomplete
    log: Incomplete
    msgbus: Incomplete
    portfolio: Incomplete
    registered_indicators: Incomplete
    def __init__(self, config: ActorConfig | None = ...) -> None: ...
    def active_task_ids(self) -> list: ...
    def add_synthetic(self, SyntheticInstrumentsynthetic) -> void: ...
    def cancel_all_tasks(self) -> void: ...
    def cancel_task(self, task_id: TaskId) -> void: ...
    def deregister_warning_event(self, typeevent) -> void: ...
    def handle_bar(self, Barbar, boolhistorical=...) -> void: ...
    def handle_data(self, Datadata) -> void: ...
    def handle_event(self, Eventevent) -> void: ...
    def handle_funding_rate(self, FundingRateUpdatefunding_rate, boolhistorical=...) -> void: ...
    def handle_historical_bar(self, Barbar) -> void: ...
    def handle_historical_data(self, data) -> void: ...
    def handle_historical_funding_rate(self, FundingRateUpdatefunding_rate) -> void: ...
    def handle_historical_order_book_deltas(self, OrderBookDeltasdeltas) -> void: ...
    def handle_historical_order_book_depth(self, OrderBookDepth10depth) -> void: ...
    def handle_historical_quote_tick(self, QuoteTicktick) -> void: ...
    def handle_historical_trade_tick(self, TradeTicktick) -> void: ...
    def handle_index_price(self, IndexPriceUpdateindex_price) -> void: ...
    def handle_instrument(self, Instrumentinstrument) -> void: ...
    def handle_instrument_close(self, InstrumentCloseupdate) -> void: ...
    def handle_instrument_status(self, InstrumentStatusdata) -> void: ...
    def handle_mark_price(self, MarkPriceUpdatemark_price) -> void: ...
    def handle_option_chain(self, option_chain_slice) -> void: ...
    def handle_option_greeks(self, OptionGreeksoption_greeks) -> void: ...
    def handle_order_book(self, OrderBookorder_book) -> void: ...
    def handle_order_book_deltas(self, deltas, boolhistorical=...) -> void: ...
    def handle_order_book_depth(self, OrderBookDepth10depth, boolhistorical=...) -> void: ...
    def handle_quote_tick(self, QuoteTicktick, boolhistorical=...) -> void: ...
    def handle_signal(self, Datasignal) -> void: ...
    def handle_trade_tick(self, TradeTicktick, boolhistorical=...) -> void: ...
    def has_active_tasks(self) -> bool: ...
    def has_any_tasks(self) -> bool: ...
    def has_pending_requests(self) -> bool: ...
    def has_queued_tasks(self) -> bool: ...
    def indicators_initialized(self) -> bool: ...
    def is_pending_request(self, UUID4request_id) -> bool: ...
    def load(self, dictstate) -> void: ...
    def on_bar(self, bar) -> void: ...
    def on_data(self, data) -> void: ...
    def on_degrade(self) -> void: ...
    def on_dispose(self) -> void: ...
    def on_event(self, Eventevent) -> void: ...
    def on_fault(self) -> void: ...
    def on_funding_rate(self, FundingRateUpdatefunding_rate) -> void: ...
    def on_historical_data(self, data) -> void: ...
    def on_index_price(self, IndexPriceUpdateindex_price) -> void: ...
    def on_instrument(self, Instrumentinstrument) -> void: ...
    def on_instrument_close(self, InstrumentCloseupdate) -> void: ...
    def on_instrument_status(self, InstrumentStatusdata) -> void: ...
    def on_load(self, dictstate) -> void: ...
    def on_mark_price(self, MarkPriceUpdatemark_price) -> void: ...
    def on_option_chain(self, option_chain_slice) -> void: ...
    def on_option_greeks(self, OptionGreeksoption_greeks) -> void: ...
    def on_order_book(self, OrderBookorder_book) -> void: ...
    def on_order_book_deltas(self, deltas) -> void: ...
    def on_order_book_depth(self, depth) -> void: ...
    def on_quote_tick(self, tick) -> void: ...
    def on_reset(self) -> void: ...
    def on_resume(self) -> void: ...
    def on_save(self) -> dict: ...
    def on_signal(self, signal) -> void: ...
    def on_start(self) -> void: ...
    def on_stop(self) -> void: ...
    def on_trade_tick(self, tick) -> void: ...
    def pending_requests(self) -> set: ...
    def publish_data(self, DataTypedata_type, Datadata) -> void: ...
    def publish_signal(self, strname, value, uint64_tts_event=...) -> void: ...
    def queue_for_executor(self, func: Callable[..., Any], tupleargs=..., dictkwargs=...) -> Any: ...
    def queued_task_ids(self) -> list: ...
    def register_base(self, PortfolioFacadeportfolio, MessageBusmsgbus, CacheFacadecache, Clockclock) -> void: ...
    def register_executor(self, loop: asyncio.AbstractEventLoop, executor: Executor) -> void: ...
    def register_indicator_for_bars(self, BarTypebar_type, Indicatorindicator) -> void: ...
    def register_indicator_for_quote_ticks(self, InstrumentIdinstrument_id, Indicatorindicator) -> void: ...
    def register_indicator_for_trade_ticks(self, InstrumentIdinstrument_id, Indicatorindicator) -> void: ...
    def register_warning_event(self, typeevent) -> void: ...
    def request_aggregated_bars(self, listbar_types, datetimestart, datetimeend=..., intlimit=..., ClientIdclient_id=..., callback: Callable[[UUID4], None] | None = ..., boolinclude_external_data=..., boolupdate_subscriptions=..., boolupdate_catalog=..., boolaggregate_spread_quotes=..., UUID4request_id=..., dictparams=...) -> UUID4: ...
    def request_bars(self, BarTypebar_type, datetimestart, datetimeend=..., intlimit=..., ClientIdclient_id=..., callback: Callable[[UUID4], None] | None = ..., boolupdate_catalog=..., booljoin_request=..., UUID4request_id=..., dictparams=...) -> UUID4: ...
    def request_data(self, DataTypedata_type, ClientIdclient_id, InstrumentIdinstrument_id=..., datetimestart=..., datetimeend=..., intlimit=..., callback: Callable[[UUID4], None] | None = ..., boolupdate_catalog=..., booljoin_request=..., UUID4request_id=..., dictparams=...) -> UUID4: ...
    def request_funding_rates(self, InstrumentIdinstrument_id, datetimestart, datetimeend=..., intlimit=..., ClientIdclient_id=..., callback: Callable[[UUID4], None] | None = ..., boolupdate_catalog=..., booljoin_request=..., UUID4request_id=..., dictparams=...) -> UUID4: ...
    def request_instrument(self, InstrumentIdinstrument_id, datetimestart=..., datetimeend=..., ClientIdclient_id=..., callback: Callable[[UUID4], None] | None = ..., boolupdate_catalog=..., booljoin_request=..., UUID4request_id=..., dictparams=...) -> UUID4: ...
    def request_instruments(self, Venuevenue, datetimestart=..., datetimeend=..., ClientIdclient_id=..., callback: Callable[[UUID4], None] | None = ..., boolupdate_catalog=..., booljoin_request=..., UUID4request_id=..., dictparams=...) -> UUID4: ...
    def request_join(self, tuplerequest_ids, datetimestart, datetimeend=..., ClientIdclient_id=..., Venuevenue=..., callback: Callable[[UUID4], None] | None = ..., UUID4request_id=..., dictparams=...) -> UUID4: ...
    def request_order_book_deltas(self, InstrumentIdinstrument_id, datetimestart, datetimeend=..., intlimit=..., ClientIdclient_id=..., callback: Callable[[UUID4], None] | None = ..., boolupdate_catalog=..., booljoin_request=..., UUID4request_id=..., dictparams=...) -> UUID4: ...
    def request_order_book_depth(self, InstrumentIdinstrument_id, datetimestart, datetimeend=..., intlimit=..., intdepth=..., ClientIdclient_id=..., callback: Callable[[UUID4], None] | None = ..., boolupdate_catalog=..., booljoin_request=..., UUID4request_id=..., dictparams=...) -> UUID4: ...
    def request_order_book_snapshot(self, InstrumentIdinstrument_id, intlimit=..., ClientIdclient_id=..., callback: Callable[[UUID4], None] | None = ..., booljoin_request=..., UUID4request_id=..., dictparams=...) -> UUID4: ...
    def request_quote_ticks(self, InstrumentIdinstrument_id, datetimestart, datetimeend=..., intlimit=..., ClientIdclient_id=..., callback: Callable[[UUID4], None] | None = ..., boolupdate_catalog=..., boolaggregate_spread_quotes=..., booljoin_request=..., UUID4request_id=..., dictparams=...) -> UUID4: ...
    def request_trade_ticks(self, InstrumentIdinstrument_id, datetimestart, datetimeend=..., intlimit=..., ClientIdclient_id=..., callback: Callable[[UUID4], None] | None = ..., boolupdate_catalog=..., booljoin_request=..., UUID4request_id=..., dictparams=...) -> UUID4: ...
    def run_in_executor(self, func: Callable[..., Any], tupleargs=..., dictkwargs=...) -> Any: ...
    def save(self) -> dict: ...
    def subscribe_bars(self, BarTypebar_type, ClientIdclient_id=..., boolupdate_catalog=..., dictparams=...) -> void: ...
    def subscribe_data(self, DataTypedata_type, ClientIdclient_id=..., InstrumentIdinstrument_id=..., boolupdate_catalog=..., dictparams=...) -> void: ...
    def subscribe_funding_rates(self, InstrumentIdinstrument_id, ClientIdclient_id=..., dictparams=...) -> void: ...
    def subscribe_index_prices(self, InstrumentIdinstrument_id, ClientIdclient_id=..., dictparams=...) -> void: ...
    def subscribe_instrument(self, InstrumentIdinstrument_id, ClientIdclient_id=..., boolupdate_catalog=..., dictparams=...) -> void: ...
    def subscribe_instrument_close(self, InstrumentIdinstrument_id, ClientIdclient_id=..., dictparams=...) -> void: ...
    def subscribe_instrument_status(self, InstrumentIdinstrument_id, ClientIdclient_id=..., dictparams=...) -> void: ...
    def subscribe_instruments(self, Venuevenue, ClientIdclient_id=..., boolupdate_catalog=..., dictparams=...) -> void: ...
    def subscribe_mark_prices(self, InstrumentIdinstrument_id, ClientIdclient_id=..., dictparams=...) -> void: ...
    def subscribe_option_chain(self, series_id, strike_range=..., snapshot_interval_ms=..., ClientIdclient_id=..., dictparams=...) -> void: ...
    def subscribe_option_greeks(self, InstrumentIdinstrument_id, ClientIdclient_id=..., dictparams=...) -> void: ...
    def subscribe_order_book_at_interval(self, InstrumentIdinstrument_id, BookTypebook_type=..., intdepth=..., intinterval_ms=..., ClientIdclient_id=..., dictparams=...) -> void: ...
    def subscribe_order_book_deltas(self, InstrumentIdinstrument_id, BookTypebook_type=..., intdepth=..., ClientIdclient_id=..., boolmanaged=..., boolpyo3_conversion=..., dictparams=...) -> void: ...
    def subscribe_order_book_depth(self, InstrumentIdinstrument_id, BookTypebook_type=..., intdepth=..., ClientIdclient_id=..., boolmanaged=..., boolpyo3_conversion=..., boolupdate_catalog=..., dictparams=...) -> void: ...
    def subscribe_quote_ticks(self, instrument_id, client_id=..., update_catalog=..., aggregate_spread_quotes=..., params=...) -> void: ...
    def subscribe_signal(self, strname=...) -> void: ...
    def subscribe_trade_ticks(self, InstrumentIdinstrument_id, ClientIdclient_id=..., boolupdate_catalog=..., dictparams=...) -> void: ...
    def to_importable_config(self) -> ImportableActorConfig: ...
    def unsubscribe_bars(self, BarTypebar_type, ClientIdclient_id=..., dictparams=...) -> void: ...
    def unsubscribe_data(self, DataTypedata_type, ClientIdclient_id=..., InstrumentIdinstrument_id=..., dictparams=...) -> void: ...
    def unsubscribe_funding_rates(self, InstrumentIdinstrument_id, ClientIdclient_id=..., dictparams=...) -> void: ...
    def unsubscribe_index_prices(self, InstrumentIdinstrument_id, ClientIdclient_id=..., dictparams=...) -> void: ...
    def unsubscribe_instrument(self, InstrumentIdinstrument_id, ClientIdclient_id=..., dictparams=...) -> void: ...
    def unsubscribe_instrument_close(self, InstrumentIdinstrument_id, ClientIdclient_id=..., dictparams=...) -> void: ...
    def unsubscribe_instrument_status(self, InstrumentIdinstrument_id, ClientIdclient_id=..., dictparams=...) -> void: ...
    def unsubscribe_instruments(self, Venuevenue, ClientIdclient_id=..., dictparams=...) -> void: ...
    def unsubscribe_mark_prices(self, InstrumentIdinstrument_id, ClientIdclient_id=..., dictparams=...) -> void: ...
    def unsubscribe_option_chain(self, series_id, ClientIdclient_id=..., dictparams=...) -> void: ...
    def unsubscribe_option_greeks(self, InstrumentIdinstrument_id, ClientIdclient_id=..., dictparams=...) -> void: ...
    def unsubscribe_order_book_at_interval(self, InstrumentIdinstrument_id, intinterval_ms=..., ClientIdclient_id=..., dictparams=...) -> void: ...
    def unsubscribe_order_book_deltas(self, InstrumentIdinstrument_id, ClientIdclient_id=..., dictparams=...) -> void: ...
    def unsubscribe_order_book_depth(self, InstrumentIdinstrument_id, ClientIdclient_id=..., dictparams=...) -> void: ...
    def unsubscribe_quote_ticks(self, InstrumentIdinstrument_id, ClientIdclient_id=..., boolaggregate_spread_quotes=..., dictparams=...) -> void: ...
    def unsubscribe_trade_ticks(self, InstrumentIdinstrument_id, ClientIdclient_id=..., dictparams=...) -> void: ...
    def update_synthetic(self, SyntheticInstrumentsynthetic) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
