import _cython_3_2_9
import nautilus_pyo3
import nautilus_trader.core.message
from _typeshed import Incomplete
from nautilus_trader.common.config import NautilusConfig as NautilusConfig
from nautilus_trader.core.rust.common import PyComponentState as PyComponentState
from typing import Any, Callable, ClassVar

__pyx_capi__: dict
__reduce_cython__: _cython_3_2_9.cython_function_or_method
__setstate_cython__: _cython_3_2_9.cython_function_or_method
__test__: dict
component_state_from_str: _cython_3_2_9.cython_function_or_method
component_state_to_str: _cython_3_2_9.cython_function_or_method
component_trigger_from_str: _cython_3_2_9.cython_function_or_method
component_trigger_to_str: _cython_3_2_9.cython_function_or_method
create_pyo3_conversion_wrapper: _cython_3_2_9.cython_function_or_method
deregister_component_clock: _cython_3_2_9.cython_function_or_method
flush_logger: _cython_3_2_9.cython_function_or_method
init_logging: _cython_3_2_9.cython_function_or_method
is_backtest_force_stop: _cython_3_2_9.cython_function_or_method
is_logging_initialized: _cython_3_2_9.cython_function_or_method
is_logging_pyo3: _cython_3_2_9.cython_function_or_method
is_matching_py: _cython_3_2_9.cython_function_or_method
log_color_from_str: _cython_3_2_9.cython_function_or_method
log_color_to_str: _cython_3_2_9.cython_function_or_method
log_header: _cython_3_2_9.cython_function_or_method
log_level_from_str: _cython_3_2_9.cython_function_or_method
log_level_to_str: _cython_3_2_9.cython_function_or_method
log_sysinfo: _cython_3_2_9.cython_function_or_method
register_component_clock: _cython_3_2_9.cython_function_or_method
remove_instance_component_clocks: _cython_3_2_9.cython_function_or_method
set_backtest_force_stop: _cython_3_2_9.cython_function_or_method
set_logging_pyo3: _cython_3_2_9.cython_function_or_method
sync_logger_to_disk: _cython_3_2_9.cython_function_or_method

class Clock:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    timer_count: Clock.timer_count
    timer_names: Clock.timer_names
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def cancel_callbacks(self) -> void: ...
    def cancel_default_handler(self) -> void: ...
    def cancel_timer(self, strname) -> void: ...
    def cancel_timers(self) -> void: ...
    def local_now(self, tzinfotz=...) -> datetime: ...
    def next_time_ns(self, strname) -> uint64_t: ...
    def register_default_handler(self, handler: Callable[[TimeEvent], None]) -> void: ...
    def set_time_alert(self, strname, datetimealert_time, callback: Callable[[TimeEvent], None] = ..., booloverride=..., boolallow_past=...) -> void: ...
    def set_time_alert_ns(self, strname, uint64_talert_time_ns, callback: Callable[[TimeEvent], None] = ..., boolallow_past=...) -> void: ...
    def set_timer(self, strname, timedeltainterval, datetimestart_time=..., datetimestop_time=..., callback: Callable[[TimeEvent], None] | None = ..., boolallow_past=..., boolfire_immediately=...) -> void: ...
    def set_timer_ns(self, strname, uint64_tinterval_ns, uint64_tstart_time_ns, uint64_tstop_time_ns, callback: Callable[[TimeEvent], None] | None = ..., boolallow_past=..., boolfire_immediately=...) -> void: ...
    def timestamp(self) -> double: ...
    def timestamp_ms(self) -> uint64_t: ...
    def timestamp_ns(self) -> uint64_t: ...
    def timestamp_us(self) -> uint64_t: ...
    def utc_now(self) -> datetime: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class Component:
    fully_qualified_name: ClassVar[method] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    # cdef attribute surface (from component.pxd) that subclasses use directly.
    _clock: Incomplete
    _log: Incomplete
    _msgbus: Incomplete
    _loop: Incomplete
    id: Incomplete
    is_degraded: Component.is_degraded
    is_disposed: Component.is_disposed
    is_faulted: Component.is_faulted
    is_initialized: Component.is_initialized
    is_running: Component.is_running
    is_stopped: Component.is_stopped
    state: Component.state
    trader_id: Incomplete
    type: Incomplete
    def __init__(self, Clockclock, TraderIdtrader_id=..., Identifiercomponent_id=..., strcomponent_name=..., MessageBusmsgbus=..., config: NautilusConfig | None = ...) -> Any: ...
    def degrade(self) -> void: ...
    def dispose(self) -> void: ...
    def fault(self) -> void: ...
    def reset(self) -> void: ...
    def resume(self) -> void: ...
    def shutdown_system(self, strreason=...) -> void: ...
    def start(self) -> void: ...
    def stop(self) -> void: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class ComponentFSMFactory:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @staticmethod
    def get_state_transition_table() -> dict: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class LiveClock(Clock):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    timer_count: LiveClock.timer_count
    timer_names: LiveClock.timer_names
    def __init__(self) -> Any: ...
    def cancel_callbacks(self) -> void: ...
    def cancel_default_handler(self) -> void: ...
    def cancel_timer(self, strname) -> void: ...
    def cancel_timers(self) -> void: ...
    def next_time_ns(self, strname) -> uint64_t: ...
    def register_default_handler(self, callback: Callable[[TimeEvent], None]) -> void: ...
    def set_time_alert_ns(self, strname, uint64_talert_time_ns, callback: Callable[[TimeEvent], None] | None = ..., boolallow_past=...) -> void: ...
    def set_timer_ns(self, strname, uint64_tinterval_ns, uint64_tstart_time_ns, uint64_tstop_time_ns, callback: Callable[[TimeEvent], None] | None = ..., boolallow_past=..., boolfire_immediately=...) -> void: ...
    def timestamp(self) -> double: ...
    def timestamp_ms(self) -> uint64_t: ...
    def timestamp_ns(self) -> uint64_t: ...
    def timestamp_us(self) -> uint64_t: ...
    def __del__(self, *args, **kwargs) -> None: ...
    def __reduce__(self): ...

class LogGuard:
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __del__(self, *args, **kwargs) -> None: ...
    def __reduce__(self): ...

class Logger:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    name: Logger.name
    def __init__(self, strname) -> None: ...
    def debug(self, strmessage, LogColorcolor=...) -> void: ...
    def error(self, strmessage, LogColorcolor=...) -> void: ...
    def exception(self, strmessage, ex) -> void: ...
    def info(self, strmessage, LogColorcolor=...) -> void: ...
    def warning(self, strmessage, LogColorcolor=...) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class MessageBus:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    has_backing: Incomplete
    pub_count: Incomplete
    req_count: Incomplete
    res_count: Incomplete
    sent_count: Incomplete
    serializer: Incomplete
    trader_id: Incomplete
    def __init__(self, TraderIdtrader_id, Clockclock, UUID4instance_id=..., strname=..., Serializerserializer=..., database: nautilus_pyo3.RedisMessageBusBacking | None = ..., config: Any | None = ...) -> None: ...
    def add_listener(self, listener: nautilus_pyo3.MessageBusListener) -> void: ...
    def add_streaming_type(self, typecls) -> void: ...
    def deregister(self, strendpoint, handler: Callable[[Any], None]) -> void: ...
    def dispose(self) -> void: ...
    def endpoints(self) -> list: ...
    def has_subscribers(self, strpattern=...) -> bool: ...
    def is_pending_request(self, UUID4request_id) -> bool: ...
    def is_streaming_type(self, typecls) -> bool: ...
    def is_subscribed(self, strtopic, handler: Callable[[Any], None]) -> bool: ...
    def publish(self, strtopic, msg: Any, boolexternal_pub=...) -> void: ...
    def register(self, strendpoint, handler: Callable[[Any], None]) -> void: ...
    def request(self, strendpoint, Requestrequest) -> void: ...
    def response(self, Responseresponse) -> void: ...
    def send(self, strendpoint, msg: Any) -> void: ...
    def streaming_types(self) -> set: ...
    def subscribe(self, strtopic, handler: Callable[[Any], None], intpriority=...) -> void: ...
    def subscriptions(self, strpattern=...) -> list: ...
    def topics(self) -> list: ...
    def unsubscribe(self, strtopic, handler: Callable[[Any], None]) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class Subscription:
    handler: Incomplete
    priority: Incomplete
    topic: Incomplete
    def __init__(self, strtopic, handler: Callable[[Any], None], intpriority=...) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class TestClock(Clock):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    __test__: ClassVar[bool] = ...
    timer_count: TestClock.timer_count
    timer_names: TestClock.timer_names
    def __init__(self) -> Any: ...
    def advance_time(self, uint64_tto_time_ns, boolset_time=...) -> list: ...
    def cancel_callbacks(self) -> void: ...
    def cancel_default_handler(self) -> void: ...
    def cancel_timer(self, strname) -> void: ...
    def cancel_timers(self) -> void: ...
    def next_time_ns(self, strname) -> uint64_t: ...
    def register_default_handler(self, callback: Callable[[TimeEvent], None]) -> void: ...
    def set_time(self, uint64_tto_time_ns) -> void: ...
    def set_time_alert_ns(self, strname, uint64_talert_time_ns, callback: Callable[[TimeEvent], None] | None = ..., boolallow_past=...) -> void: ...
    def set_timer_ns(self, strname, uint64_tinterval_ns, uint64_tstart_time_ns, uint64_tstop_time_ns, callback: Callable[[TimeEvent], None] | None = ..., boolallow_past=..., boolfire_immediately=...) -> void: ...
    def timestamp(self) -> double: ...
    def timestamp_ms(self) -> uint64_t: ...
    def timestamp_ns(self) -> uint64_t: ...
    def timestamp_us(self) -> uint64_t: ...
    def __del__(self, *args, **kwargs) -> None: ...
    def __reduce__(self): ...

class Throttler:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    interval: Incomplete
    is_limiting: Incomplete
    limit: Incomplete
    name: Incomplete
    qsize: Throttler.qsize
    recv_count: Incomplete
    sent_count: Incomplete
    def __init__(self, strname, intlimit, timedeltainterval, Clockclock, output_send: Callable[[Any], None], output_drop: Callable[[Any], None] | None = ...) -> None: ...
    def reset(self) -> void: ...
    def send(self, msg) -> void: ...
    def used(self) -> double: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class TimeEvent(nautilus_trader.core.message.Event):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    id: TimeEvent.id
    name: TimeEvent.name
    ts_event: TimeEvent.ts_event
    ts_init: TimeEvent.ts_init
    def __init__(self, strname, UUID4event_id, uint64_tts_event, uint64_tts_init) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class TimeEventHandler:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    event: Incomplete
    def __init__(self, TimeEventevent, handler: Callable[[TimeEvent], None]) -> None: ...
    def handle(self) -> void: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
