import msgspec
from _typeshed import Incomplete
from collections.abc import Callable as Callable
from nautilus_trader.common import Environment as Environment
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.core.uuid import UUID4 as UUID4
from nautilus_trader.model.data import BarSpecification as BarSpecification, BarType as BarType
from nautilus_trader.model.enums import AccountType as AccountType, BookType as BookType, OmsType as OmsType, OtoTriggerMode as OtoTriggerMode, TimeInForce as TimeInForce, TriggerType as TriggerType
from nautilus_trader.model.identifiers import ComponentId as ComponentId, Identifier as Identifier, InstrumentId as InstrumentId
from nautilus_trader.model.objects import Currency as Currency, Money as Money, Price as Price, Quantity as Quantity
from typing import Any

PositiveInt: Incomplete
NonNegativeInt: Incomplete
PositiveFloat: Incomplete
NonNegativeFloat: Incomplete
CUSTOM_ENCODINGS: dict[type, Callable]
CUSTOM_DECODINGS: dict[type, Callable]

class InvalidConfiguration(RuntimeError): ...

def resolve_path(path: str) -> type: ...
def resolve_config_path(path: str) -> type[NautilusConfig]: ...
def nautilus_schema_hook(type_: type[Any]) -> dict[str, Any]: ...
def msgspec_encoding_hook(obj: Any) -> Any: ...
def msgspec_decoding_hook(obj_type: type, obj: Any) -> Any: ...
def register_config_encoding(type_: type, encoder: Callable) -> None: ...
def register_config_decoding(type_: type, decoder: Callable) -> None: ...
def tokenize_config(obj: NautilusConfig) -> str: ...
def pyo3_config_json(config: NautilusConfig) -> bytes: ...

class NautilusConfig(msgspec.Struct, kw_only=True, frozen=True, forbid_unknown_fields=True):
    @property
    def id(self) -> str: ...
    @classmethod
    def fully_qualified_name(cls) -> str: ...
    @classmethod
    def json_schema(cls) -> dict[str, Any]: ...
    @classmethod
    def parse(cls, raw: bytes | str) -> Any: ...
    def dict(self) -> dict[str, Any]: ...
    def json(self) -> bytes: ...
    def json_primitives(self) -> dict[str, Any]: ...
    def validate(self) -> bool: ...

class DatabaseConfig(NautilusConfig, frozen=True):
    type: str = ...
    host: str | None = ...
    port: int | None = ...
    username: str | None = ...
    password: str | None = ...
    ssl: bool = ...
    connection_timeout: int = ...
    response_timeout: int = ...
    number_of_retries: int = ...
    exponent_base: int = ...
    max_delay: int = ...
    factor: int = ...

class MessageBusConfig(NautilusConfig, frozen=True):
    database: DatabaseConfig | None = ...
    encoding: str = ...
    timestamps_as_iso8601: bool = ...
    buffer_interval_ms: PositiveInt | None = ...
    autotrim_mins: int | None = ...
    use_trader_prefix: bool = ...
    use_trader_id: bool = ...
    use_instance_id: bool = ...
    streams_prefix: str = ...
    stream_per_topic: bool = ...
    external_streams: list[str] | None = ...
    types_filter: list[type] | None = ...
    heartbeat_interval_secs: PositiveInt | None = ...

class InstrumentProviderConfig(NautilusConfig, frozen=True):
    def __eq__(self, other): ...
    def __hash__(self): ...
    load_all: bool = ...
    load_ids: frozenset[InstrumentId] | None = ...
    filters: dict[str, Any] | None = ...
    filter_callable: str | None = ...
    log_warnings: bool = ...
    use_gamma_markets: bool = ...

class OrderEmulatorConfig(NautilusConfig, frozen=True):
    debug: bool = ...

class ActorConfig(NautilusConfig, kw_only=True, frozen=True):
    component_id: ComponentId | None = ...
    log_events: bool = ...
    log_commands: bool = ...

class ImportableActorConfig(NautilusConfig, frozen=True):
    actor_path: str
    config_path: str
    config: dict

class ActorFactory:
    @staticmethod
    def create(config: ImportableActorConfig): ...

class LoggingConfig(NautilusConfig, frozen=True):
    log_level: str = ...
    log_level_file: str | None = ...
    log_directory: str | None = ...
    log_file_name: str | None = ...
    log_file_format: str | None = ...
    log_file_max_size: PositiveInt | None = ...
    log_file_max_backup_count: NonNegativeInt = ...
    log_colors: bool = ...
    log_component_levels: dict[str, str] | None = ...
    log_components_only: bool = ...
    bypass_logging: bool = ...
    print_config: bool = ...
    use_tracing: bool = ...
    use_pyo3: bool = ...
    clear_log_file: bool = ...
    fileout_sync_on_flush: bool = ...
    buffered_stdout: bool = ...

class ImportableFactoryConfig(NautilusConfig, frozen=True):
    path: str
    def create(self): ...

class ImportableConfig(NautilusConfig, frozen=True):
    path: str
    config: dict = ...
    factory: ImportableFactoryConfig | None = ...
    @staticmethod
    def is_importable(data: dict) -> bool: ...
    def create(self): ...
