from typing import Any, ClassVar

__test__: dict

class TopicCache:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self) -> Any: ...
    def clear_cache(self) -> void: ...
    def get_bars_topic(self, BarTypebar_type, boolhistorical=...) -> str: ...
    def get_book_topic(self, typebook_data_type, InstrumentIdinstrument_id, boolhistorical=...) -> str: ...
    def get_close_prices_topic(self, InstrumentIdinstrument_id, boolhistorical=...) -> str: ...
    def get_custom_data_topic(self, DataTypedata_type, InstrumentIdinstrument_id=..., boolhistorical=...) -> str: ...
    def get_deltas_topic(self, InstrumentIdinstrument_id, boolhistorical=...) -> str: ...
    def get_depth_topic(self, InstrumentIdinstrument_id, boolhistorical=...) -> str: ...
    def get_funding_rates_topic(self, InstrumentIdinstrument_id, boolhistorical=...) -> str: ...
    def get_index_prices_topic(self, InstrumentIdinstrument_id, boolhistorical=...) -> str: ...
    def get_instrument_topic(self, InstrumentIdinstrument_id, boolhistorical=...) -> str: ...
    def get_instruments_topic(self, Venuevenue) -> str: ...
    def get_mark_prices_topic(self, InstrumentIdinstrument_id, boolhistorical=...) -> str: ...
    def get_option_chain_topic(self, strseries_id_str) -> str: ...
    def get_option_greeks_topic(self, InstrumentIdinstrument_id, boolhistorical=...) -> str: ...
    def get_quotes_topic(self, InstrumentIdinstrument_id, boolhistorical=...) -> str: ...
    def get_signal_topic(self, strname) -> str: ...
    def get_snapshots_topic(self, InstrumentIdinstrument_id, intinterval_ms, boolhistorical=...) -> str: ...
    def get_status_topic(self, InstrumentIdinstrument_id, boolhistorical=...) -> str: ...
    def get_trades_topic(self, InstrumentIdinstrument_id, boolhistorical=...) -> str: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
