import asyncio
from asyncio import Future
from collections.abc import Callable as Callable
from concurrent.futures import Executor
from dataclasses import dataclass
from nautilus_trader.common.component import Logger as Logger
from nautilus_trader.core.uuid import UUID4 as UUID4
from typing import Any

@dataclass(frozen=True)
class TaskId:
    value: str
    @classmethod
    def create(cls) -> TaskId: ...

class ActorExecutor:
    def __init__(self, loop: asyncio.AbstractEventLoop, executor: Executor, logger: Logger | None = None) -> None: ...
    def reset(self) -> None: ...
    def get_future(self, task_id: TaskId) -> Future | None: ...
    async def shutdown(self) -> None: ...
    def queue_for_executor(self, func: Callable[..., Any], *args: Any, **kwargs: Any) -> TaskId: ...
    def run_in_executor(self, func: Callable[..., Any], *args: Any, **kwargs: Any) -> TaskId: ...
    def queued_task_ids(self) -> list[TaskId]: ...
    def active_task_ids(self) -> list[TaskId]: ...
    def has_queued_tasks(self) -> bool: ...
    def has_active_tasks(self) -> bool: ...
    def cancel_task(self, task_id: TaskId) -> None: ...
    def cancel_all_tasks(self) -> None: ...
