from _typeshed import Incomplete
from typing import Any, ClassVar

__test__: dict

class ClientOrderIdGenerator(IdentifierGenerator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    count: Incomplete
    use_hyphens: Incomplete
    use_uuids: Incomplete
    def __init__(self, TraderIdtrader_id, StrategyIdstrategy_id, Clockclock, intinitial_count=..., booluse_uuids=..., booluse_hyphens=...) -> Any: ...
    def generate(self) -> ClientOrderId: ...
    def reset(self) -> void: ...
    def set_count(self, intcount) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class IdentifierGenerator:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, TraderIdtrader_id, Clockclock) -> Any: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class OrderListIdGenerator(IdentifierGenerator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    count: Incomplete
    def __init__(self, TraderIdtrader_id, StrategyIdstrategy_id, Clockclock, intinitial_count=...) -> Any: ...
    def generate(self) -> OrderListId: ...
    def reset(self) -> void: ...
    def set_count(self, intcount) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class PositionIdGenerator(IdentifierGenerator):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, TraderIdtrader_id, Clockclock) -> Any: ...
    def generate(self, StrategyIdstrategy_id, boolflipped=...) -> PositionId: ...
    def get_count(self, StrategyIdstrategy_id) -> int: ...
    def reset(self) -> void: ...
    def set_count(self, StrategyIdstrategy_id, intcount) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
