from nautilus_trader.common.component import Logger as Logger
from nautilus_trader.common.functions import get_event_loop as get_event_loop
from nautilus_trader.config import InstrumentProviderConfig as InstrumentProviderConfig
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.model.currencies import register_currency as register_currency
from nautilus_trader.model.identifiers import InstrumentId as InstrumentId
from nautilus_trader.model.instruments import Instrument as Instrument
from nautilus_trader.model.objects import Currency as Currency

class InstrumentProvider:
    def __init__(self, config: InstrumentProviderConfig | None = None) -> None: ...
    @property
    def count(self) -> int: ...
    async def load_all_async(self, filters: dict | None = None) -> None: ...
    async def load_ids_async(self, instrument_ids: list[InstrumentId], filters: dict | None = None) -> None: ...
    async def load_async(self, instrument_id: InstrumentId, filters: dict | None = None) -> None: ...
    async def initialize(self, reload: bool = False) -> None: ...
    def load_all(self, filters: dict | None = None) -> None: ...
    def load_ids(self, instrument_ids: list[InstrumentId], filters: dict | None = None) -> None: ...
    def load(self, instrument_id: InstrumentId, filters: dict | None = None) -> None: ...
    def add_currency(self, currency: Currency) -> None: ...
    def add(self, instrument: Instrument) -> None: ...
    def add_bulk(self, instruments: list[Instrument]) -> None: ...
    def list_all(self) -> list[Instrument]: ...
    def get_all(self) -> dict[InstrumentId, Instrument]: ...
    def currencies(self) -> dict[str, Currency]: ...
    def currency(self, code: str) -> Currency | None: ...
    def find(self, instrument_id: InstrumentId) -> Instrument | None: ...
