class SecureString:
    def __init__(self, value: str, name: str = 'credential') -> None: ...
    def get_value(self) -> str: ...
    def get_redacted(self, visible_chars: int = 4) -> str: ...
    def clear(self) -> None: ...
    def __del__(self) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    __hash__: None
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    @classmethod
    def from_env(cls, env_var: str, name: str | None = None) -> SecureString: ...

def mask_api_key(api_key: str, visible_chars: int = 4) -> str: ...
