import msgspec
from _typeshed import Incomplete
from nautilus_trader.adapters.binance.common.enums import BinanceAccountType as BinanceAccountType, BinanceFuturesPositionSide as BinanceFuturesPositionSide, BinanceNewOrderRespType as BinanceNewOrderRespType, BinanceOrderSide as BinanceOrderSide, BinanceOrderType as BinanceOrderType, BinanceSecurityType as BinanceSecurityType, BinanceTimeInForce as BinanceTimeInForce
from nautilus_trader.adapters.binance.common.schemas.account import BinanceOrder as BinanceOrder, BinanceUserTrade as BinanceUserTrade
from nautilus_trader.adapters.binance.common.symbol import BinanceSymbol as BinanceSymbol
from nautilus_trader.adapters.binance.http.client import BinanceHttpClient as BinanceHttpClient
from nautilus_trader.adapters.binance.http.endpoint import BinanceHttpEndpoint as BinanceHttpEndpoint
from nautilus_trader.common.component import LiveClock as LiveClock
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.core.nautilus_pyo3 import HttpMethod as HttpMethod

class BinanceOrderHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str, testing_endpoint: bool | None = False) -> None: ...
    class GetDeleteParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        symbol: BinanceSymbol
        timestamp: str
        orderId: int | None = ...
        origClientOrderId: str | None = ...
        recvWindow: str | None = ...
    class PostParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        symbol: BinanceSymbol
        timestamp: str
        side: BinanceOrderSide
        type: BinanceOrderType
        timeInForce: BinanceTimeInForce | None = ...
        positionSide: BinanceFuturesPositionSide | None = ...
        quantity: str | None = ...
        quoteOrderQty: str | None = ...
        price: str | None = ...
        priceMatch: str | None = ...
        newClientOrderId: str | None = ...
        strategyId: int | None = ...
        strategyType: int | None = ...
        stopPrice: str | None = ...
        trailingDelta: str | None = ...
        icebergQty: str | None = ...
        reduceOnly: str | None = ...
        closePosition: str | None = ...
        activationPrice: str | None = ...
        callbackRate: str | None = ...
        workingType: str | None = ...
        priceProtect: str | None = ...
        newOrderRespType: BinanceNewOrderRespType | None = ...
        goodTillDate: int | None = ...
        recvWindow: str | None = ...
    class PutParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        symbol: BinanceSymbol
        side: BinanceOrderSide
        quantity: str
        price: str
        timestamp: str
        orderId: int | None = ...
        origClientOrderId: str | None = ...
        recvWindow: str | None = ...
    async def get(self, params: GetDeleteParameters) -> BinanceOrder: ...
    async def delete(self, params: GetDeleteParameters) -> BinanceOrder: ...
    async def post(self, params: PostParameters) -> BinanceOrder: ...
    async def put(self, params: PutParameters) -> BinanceOrder: ...

class BinanceAllOrdersHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class GetParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        symbol: BinanceSymbol
        timestamp: str
        orderId: int | None = ...
        startTime: int | None = ...
        endTime: int | None = ...
        limit: int | None = ...
        recvWindow: str | None = ...
    async def get(self, params: GetParameters) -> list[BinanceOrder]: ...

class BinanceOpenOrdersHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str, methods: dict[HttpMethod, BinanceSecurityType] | None = None) -> None: ...
    class GetParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        timestamp: str
        symbol: BinanceSymbol | None = ...
        recvWindow: str | None = ...
    async def get(self, params: GetParameters) -> list[BinanceOrder]: ...

class BinanceUserTradesHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, url_path: str) -> None: ...
    class GetParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        symbol: BinanceSymbol
        timestamp: str
        orderId: int | None = ...
        startTime: int | None = ...
        endTime: int | None = ...
        fromId: int | None = ...
        limit: int | None = ...
        recvWindow: str | None = ...

class BinanceAccountHttpAPI:
    client: Incomplete
    base_endpoint: str
    def __init__(self, client: BinanceHttpClient, clock: LiveClock, account_type: BinanceAccountType) -> None: ...
    async def query_order(self, symbol: str, order_id: int | None = None, orig_client_order_id: str | None = None, recv_window: str | None = None) -> BinanceOrder: ...
    async def cancel_all_open_orders(self, symbol: str, recv_window: str | None = None) -> bool: ...
    async def cancel_order(self, symbol: str, order_id: int | None = None, orig_client_order_id: str | None = None, recv_window: str | None = None) -> BinanceOrder: ...
    async def new_order(self, symbol: str, side: BinanceOrderSide, order_type: BinanceOrderType, time_in_force: BinanceTimeInForce | None = None, position_side: BinanceFuturesPositionSide | None = None, quantity: str | None = None, quote_order_qty: str | None = None, price: str | None = None, price_match: str | None = None, new_client_order_id: str | None = None, strategy_id: int | None = None, strategy_type: int | None = None, stop_price: str | None = None, trailing_delta: str | None = None, iceberg_qty: str | None = None, reduce_only: str | None = None, close_position: str | None = None, activation_price: str | None = None, callback_rate: str | None = None, working_type: str | None = None, price_protect: str | None = None, good_till_date: int | None = None, new_order_resp_type: BinanceNewOrderRespType | None = None, recv_window: str | None = None) -> BinanceOrder: ...
    async def modify_order(self, symbol: str, side: BinanceOrderSide, quantity: str, price: str, order_id: int | None = None, orig_client_order_id: str | None = None, recv_window: str | None = None) -> BinanceOrder: ...
    async def query_all_orders(self, symbol: str, order_id: int | None = None, start_time: int | None = None, end_time: int | None = None, limit: int | None = None, recv_window: str | None = None) -> list[BinanceOrder]: ...
    async def query_open_orders(self, symbol: str | None = None, recv_window: str | None = None) -> list[BinanceOrder]: ...
    async def query_user_trades(self, symbol: str, order_id: int | None = None, start_time: int | None = None, end_time: int | None = None, from_id: int | None = None, limit: int | None = None, recv_window: str | None = None) -> list[BinanceUserTrade]: ...
