from nautilus_trader.adapters.binance.http.error import BinanceClientError as BinanceClientError, BinanceServerError as BinanceServerError
from nautilus_trader.common.component import LiveClock as LiveClock, Logger as Logger
from nautilus_trader.common.enums import LogColor as LogColor
from nautilus_trader.core.nautilus_pyo3 import HttpClient as HttpClient, HttpMethod as HttpMethod, HttpResponse as HttpResponse, Quota as Quota, ed25519_signature as ed25519_signature, hmac_signature as hmac_signature, mask_api_key as mask_api_key, rsa_signature as rsa_signature
from typing import Any

class BinanceHttpClient:
    def __init__(self, clock: LiveClock, api_key: str | None, api_secret: str | None, base_url: str, rsa_private_key: str | None = None, ed25519_private_key: str | None = None, ratelimiter_quotas: list[tuple[str, Quota]] | None = None, ratelimiter_default_quota: Quota | None = None, proxy_url: str | None = None) -> None: ...
    @property
    def base_url(self) -> str: ...
    @property
    def api_key(self) -> str | None: ...
    @property
    def api_key_masked(self) -> str: ...
    @property
    def headers(self): ...
    async def sign_request(self, http_method: HttpMethod, url_path: str, payload: dict[str, str] | None = None, ratelimiter_keys: list[str] | None = None) -> Any: ...
    async def send_request(self, http_method: HttpMethod, url_path: str, payload: dict[str, str] | None = None, ratelimiter_keys: list[str] | None = None) -> bytes: ...
