import msgspec
from _typeshed import Incomplete
from nautilus_trader.adapters.binance.common.enums import BinanceAccountType as BinanceAccountType, BinanceKlineInterval as BinanceKlineInterval, BinanceSecurityType as BinanceSecurityType
from nautilus_trader.adapters.binance.common.schemas.market import BinanceAggTrade as BinanceAggTrade, BinanceDepth as BinanceDepth, BinanceKline as BinanceKline, BinanceTicker24hr as BinanceTicker24hr, BinanceTickerBook as BinanceTickerBook, BinanceTickerPrice as BinanceTickerPrice, BinanceTime as BinanceTime, BinanceTrade as BinanceTrade
from nautilus_trader.adapters.binance.common.symbol import BinanceSymbol as BinanceSymbol, BinanceSymbols as BinanceSymbols
from nautilus_trader.adapters.binance.common.types import BinanceBar as BinanceBar
from nautilus_trader.adapters.binance.http.client import BinanceHttpClient as BinanceHttpClient
from nautilus_trader.adapters.binance.http.endpoint import BinanceHttpEndpoint as BinanceHttpEndpoint
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.core.datetime import nanos_to_millis as nanos_to_millis
from nautilus_trader.core.nautilus_pyo3 import HttpMethod as HttpMethod
from nautilus_trader.model.data import BarType as BarType, OrderBookDeltas as OrderBookDeltas, TradeTick as TradeTick
from nautilus_trader.model.identifiers import InstrumentId as InstrumentId

class BinancePingHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    async def get(self) -> dict: ...

class BinanceTimeHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    async def get(self) -> BinanceTime: ...

class BinanceDepthHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class GetParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        symbol: BinanceSymbol
        limit: int | None = ...
    async def get(self, params: GetParameters) -> BinanceDepth: ...

class BinanceTradesHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class GetParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        symbol: BinanceSymbol
        limit: int | None = ...
    async def get(self, params: GetParameters) -> list[BinanceTrade]: ...

class BinanceHistoricalTradesHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class GetParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        symbol: BinanceSymbol
        limit: int | None = ...
        fromId: int | None = ...
    async def get(self, params: GetParameters) -> list[BinanceTrade]: ...

class BinanceAggTradesHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class GetParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        symbol: BinanceSymbol
        limit: int | None = ...
        fromId: int | None = ...
        startTime: int | None = ...
        endTime: int | None = ...
    async def get(self, params: GetParameters) -> list[BinanceAggTrade]: ...

class BinanceKlinesHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class GetParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        symbol: BinanceSymbol
        interval: BinanceKlineInterval
        limit: int | None = ...
        startTime: int | None = ...
        endTime: int | None = ...
    async def get(self, params: GetParameters) -> list[BinanceKline]: ...

class BinanceTicker24hrHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class GetParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        symbol: BinanceSymbol | None = ...
        symbols: BinanceSymbols | None = ...
        type: str | None = ...

class BinanceTickerPriceHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class GetParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        symbol: BinanceSymbol | None = ...
        symbols: BinanceSymbols | None = ...

class BinanceTickerBookHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, base_endpoint: str) -> None: ...
    class GetParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        symbol: BinanceSymbol | None = ...
        symbols: BinanceSymbols | None = ...

class BinanceMarketHttpAPI:
    client: Incomplete
    base_endpoint: str
    def __init__(self, client: BinanceHttpClient, account_type: BinanceAccountType) -> None: ...
    async def ping(self) -> dict: ...
    async def request_server_time(self) -> int: ...
    async def query_depth(self, symbol: str, limit: int | None = None) -> BinanceDepth: ...
    async def request_order_book_snapshot(self, instrument_id: InstrumentId, ts_init: int, limit: int | None = None) -> OrderBookDeltas: ...
    async def query_trades(self, symbol: str, limit: int | None = None) -> list[BinanceTrade]: ...
    async def request_trade_ticks(self, instrument_id: InstrumentId, limit: int | None = None) -> list[TradeTick]: ...
    async def query_agg_trades(self, symbol: str, limit: int | None = None, start_time: int | None = None, end_time: int | None = None, from_id: int | None = None) -> list[BinanceAggTrade]: ...
    async def request_agg_trade_ticks(self, instrument_id: InstrumentId, limit: int | None = 1000, start_time: int | None = None, end_time: int | None = None, from_id: int | None = None) -> list[TradeTick]: ...
    async def query_historical_trades(self, symbol: str, limit: int | None = None, from_id: int | None = None) -> list[BinanceTrade]: ...
    async def request_historical_trade_ticks(self, instrument_id: InstrumentId, limit: int | None = None, from_id: int | None = None) -> list[TradeTick]: ...
    async def query_klines(self, symbol: str, interval: BinanceKlineInterval, limit: int | None = None, start_time: int | None = None, end_time: int | None = None) -> list[BinanceKline]: ...
    async def request_binance_bars(self, bar_type: BarType, interval: BinanceKlineInterval, limit: int | None = None, start_time: int | None = None, end_time: int | None = None) -> list[BinanceBar]: ...
    async def query_ticker_24hr(self, symbol: str | None = None, symbols: list[str] | None = None, response_type: str | None = None) -> list[BinanceTicker24hr]: ...
    async def query_ticker_price(self, symbol: str | None = None, symbols: list[str] | None = None) -> list[BinanceTickerPrice]: ...
    async def query_ticker_book(self, symbol: str | None = None, symbols: list[str] | None = None) -> list[BinanceTickerBook]: ...
