import msgspec
from _typeshed import Incomplete
from nautilus_trader.adapters.binance.common.enums import BinanceAccountType as BinanceAccountType, BinanceSecurityType as BinanceSecurityType
from nautilus_trader.adapters.binance.common.schemas.user import BinanceListenKey as BinanceListenKey
from nautilus_trader.adapters.binance.common.symbol import BinanceSymbol as BinanceSymbol
from nautilus_trader.adapters.binance.http.client import BinanceHttpClient as BinanceHttpClient
from nautilus_trader.adapters.binance.http.endpoint import BinanceHttpEndpoint as BinanceHttpEndpoint
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.core.nautilus_pyo3 import HttpMethod as HttpMethod

class BinanceListenKeyHttp(BinanceHttpEndpoint):
    def __init__(self, client: BinanceHttpClient, url_path: str) -> None: ...
    class PostParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        symbol: BinanceSymbol | None = ...
    class PutDeleteParameters(msgspec.Struct, omit_defaults=True, frozen=True):
        symbol: BinanceSymbol | None = ...
        listenKey: str | None = ...

class BinanceUserDataHttpAPI:
    client: Incomplete
    account_type: Incomplete
    def __init__(self, client: BinanceHttpClient, account_type: BinanceAccountType) -> None: ...
    async def create_listen_key(self, symbol: str | None = None) -> BinanceListenKey: ...
    async def keepalive_listen_key(self, symbol: str | None = None, listen_key: str | None = None): ...
    async def close_listen_key(self, symbol: str | None = None, listen_key: str | None = None): ...
