from _typeshed import Incomplete
from nautilus_trader.accounting.error import AccountBalanceNegative as AccountBalanceNegative
from typing import Any, ClassVar

__test__: dict

class Account:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    base_currency: Incomplete
    calculate_account_state: Incomplete
    event_count: Incomplete
    events: Incomplete
    id: Incomplete
    is_cash_account: Incomplete
    is_margin_account: Incomplete
    last_event: Incomplete
    type: Incomplete
    def __init__(self, AccountStateevent, boolcalculate_account_state) -> Any: ...
    def apply(self, AccountStateevent) -> void: ...
    def balance(self, Currencycurrency=...) -> AccountBalance: ...
    def balance_free(self, Currencycurrency=...) -> Money: ...
    def balance_impact(self, Instrumentinstrument, Quantityquantity, Priceprice, OrderSideorder_side) -> Money: ...
    def balance_locked(self, Currencycurrency=...) -> Money: ...
    def balance_total(self, Currencycurrency=...) -> Money: ...
    def balances(self) -> dict: ...
    def balances_free(self) -> dict: ...
    def balances_locked(self) -> dict: ...
    def balances_total(self) -> dict: ...
    def calculate_commission(self, Instrumentinstrument, Quantitylast_qty, Pricelast_px, LiquiditySideliquidity_side, booluse_quote_for_inverse=...) -> Money: ...
    def calculate_pnls(self, Instrumentinstrument, OrderFilledfill, Positionposition: Position | None = ...) -> list: ...
    def commission(self, Currencycurrency) -> Money: ...
    def commissions(self) -> dict: ...
    def currencies(self) -> list: ...
    def is_unleveraged(self, InstrumentIdinstrument_id) -> bool: ...
    def purge_account_events(self, uint64_tts_now, uint64_tlookback_secs=...) -> void: ...
    def starting_balances(self) -> dict: ...
    def update_balances(self, listbalances) -> void: ...
    def update_commissions(self, Moneycommission) -> void: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
