import _cython_3_2_9
import nautilus_trader.accounting.accounts.cash
import nautilus_trader.core
from typing import Any, ClassVar

__pyx_capi__: dict
__test__: dict
exposure: _cython_3_2_9.cython_function_or_method
liability: _cython_3_2_9.cython_function_or_method
lose_payoff: _cython_3_2_9.cython_function_or_method
stake: _cython_3_2_9.cython_function_or_method
win_payoff: _cython_3_2_9.cython_function_or_method

class BettingAccount(nautilus_trader.accounting.accounts.cash.CashAccount):
    ACCOUNT_TYPE: ClassVar[nautilus_trader.core.rust.model.AccountType] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def balance_impact(self, Instrumentinstrument, Quantityquantity, Priceprice, OrderSideorder_side) -> Money: ...
    def calculate_balance_locked(self, Instrumentinstrument, OrderSideside, Quantityquantity, Priceprice, booluse_quote_for_inverse=...) -> Money: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
