import nautilus_trader.accounting.accounts.base
import nautilus_trader.core
from _typeshed import Incomplete
from nautilus_trader.accounting.error import AccountBalanceNegative as AccountBalanceNegative
from typing import Any, ClassVar

__test__: dict

class CashAccount(nautilus_trader.accounting.accounts.base.Account):
    ACCOUNT_TYPE: ClassVar[nautilus_trader.core.rust.model.AccountType] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    allow_borrowing: Incomplete
    def __init__(self, AccountStateevent, boolcalculate_account_state=..., boolallow_borrowing=...) -> Any: ...
    def apply(self, AccountStateevent) -> void: ...
    def balance_impact(self, Instrumentinstrument, Quantityquantity, Priceprice, OrderSideorder_side) -> Money: ...
    def calculate_balance_locked(self, Instrumentinstrument, OrderSideside, Quantityquantity, Priceprice, booluse_quote_for_inverse=...) -> Money: ...
    def calculate_commission(self, Instrumentinstrument, Quantitylast_qty, Pricelast_px, LiquiditySideliquidity_side, booluse_quote_for_inverse=...) -> Money: ...
    def calculate_pnls(self, Instrumentinstrument, OrderFilledfill, Positionposition: Position | None = ...) -> list: ...
    def clear_balance_locked(self, InstrumentIdinstrument_id) -> void: ...
    @staticmethod
    def from_dict(dictvalues) -> Any: ...
    def is_unleveraged(self, InstrumentIdinstrument_id) -> bool: ...
    @staticmethod
    def to_dict(CashAccountobj) -> Any: ...
    def update_balance_locked(self, InstrumentIdinstrument_id, Moneylocked) -> void: ...
    def update_balances(self, listbalances) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
