import nautilus_trader.accounting.accounts.base
from _typeshed import Incomplete
from decimal import Decimal
from typing import Any, ClassVar

__test__: dict

class MarginAccount(nautilus_trader.accounting.accounts.base.Account):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    default_leverage: Incomplete
    def __init__(self, AccountStateevent, boolcalculate_account_state=...) -> Any: ...
    def account_margins(self) -> dict: ...
    def account_margins_init(self) -> dict: ...
    def account_margins_maint(self) -> dict: ...
    def apply(self, AccountStateevent) -> void: ...
    def balance_impact(self, Instrumentinstrument, Quantityquantity, Priceprice, OrderSideorder_side) -> Money: ...
    def calculate_commission(self, Instrumentinstrument, Quantitylast_qty, Pricelast_px, LiquiditySideliquidity_side, booluse_quote_for_inverse=...) -> Money: ...
    def calculate_margin_init(self, Instrumentinstrument, Quantityquantity, Priceprice, booluse_quote_for_inverse=...) -> Money: ...
    def calculate_margin_maint(self, Instrumentinstrument, PositionSideside, Quantityquantity, Priceprice, booluse_quote_for_inverse=...) -> Money: ...
    def calculate_pnls(self, Instrumentinstrument, OrderFilledfill, Positionposition: Position | None = ...) -> list: ...
    def clear_account_margin(self, Currencycurrency) -> void: ...
    def clear_margin(self, InstrumentIdinstrument_id) -> void: ...
    def clear_margin_init(self, InstrumentIdinstrument_id) -> void: ...
    def clear_margin_maint(self, InstrumentIdinstrument_id) -> void: ...
    @staticmethod
    def from_dict(dictvalues) -> Any: ...
    def is_unleveraged(self, InstrumentIdinstrument_id) -> bool: ...
    def leverage(self, InstrumentIdinstrument_id) -> Any: ...
    def leverages(self) -> dict: ...
    def margin(self, InstrumentIdinstrument_id) -> MarginBalance: ...
    def margin_for_currency(self, Currencycurrency) -> MarginBalance: ...
    def margin_init(self, InstrumentIdinstrument_id) -> Money: ...
    def margin_init_for_currency(self, Currencycurrency) -> Money: ...
    def margin_maint(self, InstrumentIdinstrument_id) -> Money: ...
    def margin_maint_for_currency(self, Currencycurrency) -> Money: ...
    def margins(self) -> dict: ...
    def margins_init(self) -> dict: ...
    def margins_maint(self) -> dict: ...
    def set_default_leverage(self, leverage: Decimal) -> void: ...
    def set_leverage(self, InstrumentIdinstrument_id, leverage: Decimal) -> void: ...
    def set_margin_model(self, MarginModelmargin_model) -> void: ...
    @staticmethod
    def to_dict(MarginAccountobj) -> Any: ...
    def total_margin_init(self, Currencycurrency) -> Money: ...
    def total_margin_maint(self, Currencycurrency) -> Money: ...
    def update_margin(self, MarginBalancemargin) -> void: ...
    def update_margin_init(self, InstrumentIdinstrument_id, Moneymargin_init) -> void: ...
    def update_margin_maint(self, InstrumentIdinstrument_id, Moneymargin_maint) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
