from nautilus_trader.common.config import NautilusConfig as NautilusConfig, PositiveInt as PositiveInt, msgspec_encoding_hook as msgspec_encoding_hook, resolve_config_path as resolve_config_path, resolve_path as resolve_path
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.model.enums import TimeInForce as TimeInForce
from nautilus_trader.model.identifiers import InstrumentId as InstrumentId, StrategyId as StrategyId
from typing import Any

class StrategyConfig(NautilusConfig, kw_only=True, frozen=True):
    strategy_id: StrategyId | None = ...
    order_id_tag: str | None = ...
    use_uuid_client_order_ids: bool = ...
    use_hyphens_in_client_order_ids: bool = ...
    oms_type: str | None = ...
    external_order_claims: list[InstrumentId] | None = ...
    manage_contingent_orders: bool = ...
    manage_gtd_expiry: bool = ...
    manage_stop: bool = ...
    market_exit_interval_ms: PositiveInt = ...
    market_exit_max_attempts: PositiveInt = ...
    market_exit_time_in_force: TimeInForce = ...
    market_exit_reduce_only: bool = ...
    log_events: bool = ...
    log_commands: bool = ...
    log_rejected_due_post_only_as_warning: bool = ...

class ImportableStrategyConfig(NautilusConfig, frozen=True):
    strategy_path: str
    config_path: str
    config: dict[str, Any]

class StrategyFactory:
    @staticmethod
    def create(config: ImportableStrategyConfig): ...

class ImportableControllerConfig(NautilusConfig, frozen=True):
    controller_path: str
    config_path: str
    config: dict
