from nautilus_trader.cache.base import CacheFacade as CacheFacade
from nautilus_trader.common.actor import Actor as Actor
from nautilus_trader.common.component import Clock as Clock, MessageBus as MessageBus
from nautilus_trader.common.config import ActorConfig as ActorConfig, ActorFactory as ActorFactory, ImportableActorConfig as ImportableActorConfig
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.core.message import Command as Command
from nautilus_trader.model.identifiers import ComponentId as ComponentId, StrategyId as StrategyId
from nautilus_trader.portfolio.base import PortfolioFacade as PortfolioFacade
from nautilus_trader.trading.config import ImportableStrategyConfig as ImportableStrategyConfig, StrategyFactory as StrategyFactory
from nautilus_trader.trading.messages import CreateActor as CreateActor, CreateStrategy as CreateStrategy, RemoveActor as RemoveActor, RemoveStrategy as RemoveStrategy, StartActor as StartActor, StartStrategy as StartStrategy, StopActor as StopActor, StopStrategy as StopStrategy
from nautilus_trader.trading.strategy import Strategy as Strategy
from nautilus_trader.trading.trader import Trader as Trader

class Controller(Actor):
    def __init__(self, trader: Trader, config: ActorConfig | None = None) -> None: ...
    def register_base(self, portfolio: PortfolioFacade, msgbus: MessageBus, cache: CacheFacade, clock: Clock) -> None: ...
    def execute(self, command: Command) -> None: ...
    def create_actor(self, actor: Actor, start: bool = True) -> None: ...
    def create_strategy(self, strategy: Strategy, start: bool = True) -> None: ...
    def start_actor(self, actor: Actor) -> None: ...
    def start_strategy(self, strategy: Strategy) -> None: ...
    def stop_actor(self, actor: Actor) -> None: ...
    def stop_strategy(self, strategy: Strategy) -> None: ...
    def market_exit_strategy(self, strategy: Strategy) -> None: ...
    def remove_actor(self, actor: Actor) -> None: ...
    def remove_strategy(self, strategy: Strategy) -> None: ...
    def create_actor_from_config(self, actor_config: ImportableActorConfig, start: bool = True) -> None: ...
    def create_strategy_from_config(self, strategy_config: ImportableStrategyConfig, start: bool = True) -> None: ...
    def start_actor_from_id(self, actor_id: ComponentId) -> None: ...
    def start_strategy_from_id(self, strategy_id: StrategyId) -> None: ...
    def stop_actor_from_id(self, actor_id: ComponentId) -> None: ...
    def stop_strategy_from_id(self, strategy_id: StrategyId) -> None: ...
    def market_exit_strategy_from_id(self, strategy_id: StrategyId) -> None: ...
    def remove_actor_from_id(self, actor_id: ComponentId) -> None: ...
    def remove_strategy_from_id(self, strategy_id: StrategyId) -> None: ...
