import pandas as pd
from datetime import datetime
from enum import Enum
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.core.data import Data as Data
from nautilus_trader.core.datetime import is_datetime_utc as is_datetime_utc
from nautilus_trader.model.objects import Currency as Currency

class NewsImpact(Enum):
    NONE = 1
    LOW = 2
    MEDIUM = 3
    HIGH = 4

class NewsEvent(Data):
    def __init__(self, impact: NewsImpact, name: str, currency: Currency, ts_event: int, ts_init: int) -> None: ...
    @property
    def impact(self) -> NewsImpact: ...
    @property
    def name(self) -> str: ...
    @property
    def currency(self) -> Currency: ...
    @property
    def ts_event(self) -> int: ...
    @property
    def ts_init(self) -> int: ...

class EconomicNewsEventFilter:
    def __init__(self, currencies: list[str], impacts: list[str], news_data: pd.DataFrame) -> None: ...
    @property
    def unfiltered_data_start(self): ...
    @property
    def unfiltered_data_end(self): ...
    @property
    def currencies(self): ...
    @property
    def impacts(self): ...
    def next_event(self, time_now: datetime) -> NewsEvent | None: ...
    def prev_event(self, time_now: datetime) -> NewsEvent | None: ...
