import nautilus_trader.common.actor
from _typeshed import Incomplete
from nautilus_trader.trading.config import ImportableStrategyConfig as ImportableStrategyConfig, StrategyConfig as StrategyConfig
from typing import Any, ClassVar

__test__: dict

class Strategy(nautilus_trader.common.actor.Actor):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    external_order_claims: Incomplete
    manage_contingent_orders: Incomplete
    manage_gtd_expiry: Incomplete
    oms_type: Incomplete
    order_factory: Incomplete
    order_id_tag: Incomplete
    use_hyphens_in_client_order_ids: Incomplete
    use_uuid_client_order_ids: Incomplete
    def __init__(self, config: StrategyConfig | None = ...) -> Any: ...
    def cancel_all_orders(self, InstrumentIdinstrument_id, OrderSideorder_side=..., ClientIdclient_id=..., dictparams=...) -> void: ...
    def cancel_gtd_expiry(self, Orderorder) -> void: ...
    def cancel_order(self, Orderorder, ClientIdclient_id=..., dictparams=...) -> void: ...
    def cancel_orders(self, listorders, ClientIdclient_id=..., dictparams=...) -> void: ...
    def change_id(self, StrategyIdstrategy_id) -> void: ...
    def change_order_id_tag(self, strorder_id_tag) -> void: ...
    def close_all_positions(self, InstrumentIdinstrument_id, PositionSideposition_side=..., ClientIdclient_id=..., listtags=..., TimeInForcetime_in_force=..., boolreduce_only=..., boolquote_quantity=..., dictparams=...) -> void: ...
    def close_position(self, Positionposition, ClientIdclient_id=..., listtags=..., TimeInForcetime_in_force=..., boolreduce_only=..., boolquote_quantity=..., dictparams=...) -> void: ...
    def handle_event(self, Eventevent) -> void: ...
    def is_exiting(self) -> bool: ...
    def market_exit(self) -> void: ...
    def modify_order(self, Orderorder, Quantityquantity=..., Priceprice=..., Pricetrigger_price=..., ClientIdclient_id=..., dictparams=...) -> void: ...
    def on_market_exit(self) -> void: ...
    def on_order_accepted(self, event) -> void: ...
    def on_order_cancel_rejected(self, event) -> void: ...
    def on_order_canceled(self, event) -> void: ...
    def on_order_denied(self, event) -> void: ...
    def on_order_emulated(self, event) -> void: ...
    def on_order_event(self, event) -> void: ...
    def on_order_expired(self, event) -> void: ...
    def on_order_filled(self, event) -> void: ...
    def on_order_initialized(self, event) -> void: ...
    def on_order_modify_rejected(self, event) -> void: ...
    def on_order_pending_cancel(self, event) -> void: ...
    def on_order_pending_update(self, event) -> void: ...
    def on_order_rejected(self, event) -> void: ...
    def on_order_released(self, event) -> void: ...
    def on_order_submitted(self, event) -> void: ...
    def on_order_triggered(self, event) -> void: ...
    def on_order_updated(self, event) -> void: ...
    def on_position_changed(self, event) -> void: ...
    def on_position_closed(self, event) -> void: ...
    def on_position_event(self, event) -> void: ...
    def on_position_opened(self, event) -> void: ...
    def on_reset(self) -> void: ...
    def on_resume(self) -> void: ...
    def on_start(self) -> void: ...
    def on_stop(self) -> void: ...
    def post_market_exit(self) -> void: ...
    def query_account(self, AccountIdaccount_id, ClientIdclient_id=..., dictparams=...) -> void: ...
    def query_order(self, Orderorder, ClientIdclient_id=..., dictparams=...) -> void: ...
    def register(self, TraderIdtrader_id, PortfolioFacadeportfolio, MessageBusmsgbus, CacheFacadecache, Clockclock) -> void: ...
    def stop(self) -> void: ...
    def submit_order(self, order, position_id=..., client_id=..., params=...) -> void: ...
    def submit_order_list(self, order_list, position_id=..., client_id=..., params=...) -> void: ...
    def to_importable_config(self) -> ImportableStrategyConfig: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
