import asyncio
import pandas as pd
from collections.abc import Callable as Callable
from nautilus_trader.analysis.reporter import ReportProvider as ReportProvider
from nautilus_trader.cache.cache import Cache as Cache
from nautilus_trader.common import Environment as Environment
from nautilus_trader.common.actor import Actor as Actor
from nautilus_trader.common.component import Clock as Clock, Component as Component, MessageBus as MessageBus, deregister_component_clock as deregister_component_clock, register_component_clock as register_component_clock, remove_instance_component_clocks as remove_instance_component_clocks
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.core.uuid import UUID4 as UUID4
from nautilus_trader.data.engine import DataEngine as DataEngine
from nautilus_trader.model.identifiers import AccountId as AccountId, ComponentId as ComponentId, ExecAlgorithmId as ExecAlgorithmId, StrategyId as StrategyId, TraderId as TraderId, Venue as Venue
from nautilus_trader.portfolio.portfolio import Portfolio as Portfolio
from nautilus_trader.risk.engine import RiskEngine as RiskEngine
from nautilus_trader.trading.strategy import Strategy as Strategy
from typing import Any

class Trader(Component):
    def __init__(self, trader_id: TraderId, instance_id: UUID4, msgbus: MessageBus, cache: Cache, portfolio: Portfolio, data_engine: DataEngine, risk_engine: RiskEngine, exec_engine: Any, clock: Clock, environment: Environment, has_controller: bool = False, loop: asyncio.AbstractEventLoop | None = None) -> None: ...
    @property
    def instance_id(self) -> UUID4: ...
    def actors(self) -> list[Actor]: ...
    def strategies(self) -> list[Strategy]: ...
    def exec_algorithms(self) -> list[Any]: ...
    def actor_ids(self) -> list[ComponentId]: ...
    def strategy_ids(self) -> list[StrategyId]: ...
    def exec_algorithm_ids(self) -> list[ExecAlgorithmId]: ...
    def actor_states(self) -> dict[ComponentId, str]: ...
    def strategy_states(self) -> dict[StrategyId, str]: ...
    def exec_algorithm_states(self) -> dict[ExecAlgorithmId, str]: ...
    def add_actor(self, actor: Actor) -> None: ...
    def add_actors(self, actors: list[Actor]) -> None: ...
    def add_strategy(self, strategy: Strategy) -> None: ...
    def add_strategies(self, strategies: list[Strategy]) -> None: ...
    def add_exec_algorithm(self, exec_algorithm: Any) -> None: ...
    def add_exec_algorithms(self, exec_algorithms: list[Any]) -> None: ...
    def start_actor(self, actor_id: ComponentId) -> None: ...
    def start_strategy(self, strategy_id: StrategyId) -> None: ...
    def stop_actor(self, actor_id: ComponentId) -> None: ...
    def stop_strategy(self, strategy_id: StrategyId) -> None: ...
    def market_exit_strategy(self, strategy_id: StrategyId) -> None: ...
    def remove_actor(self, actor_id: ComponentId) -> None: ...
    def remove_strategy(self, strategy_id: StrategyId) -> None: ...
    def clear_actors(self) -> None: ...
    def clear_strategies(self) -> None: ...
    def clear_exec_algorithms(self) -> None: ...
    def subscribe(self, topic: str, handler: Callable[[Any], None]) -> None: ...
    def unsubscribe(self, topic: str, handler: Callable[[Any], None]) -> None: ...
    def save(self) -> None: ...
    def load(self) -> None: ...
    def check_residuals(self) -> None: ...
    def generate_orders_report(self) -> pd.DataFrame: ...
    def generate_order_fills_report(self) -> pd.DataFrame: ...
    def generate_fills_report(self) -> pd.DataFrame: ...
    def generate_positions_report(self) -> pd.DataFrame: ...
    def generate_account_report(self, venue: Venue = None, account_id: AccountId = None) -> pd.DataFrame: ...
