import msgspec
from nautilus_trader.adapters.binance.common.enums import BinanceEnumParser as BinanceEnumParser, BinanceOrderSide as BinanceOrderSide, BinanceOrderStatus as BinanceOrderStatus, BinanceOrderType as BinanceOrderType, BinanceTimeInForce as BinanceTimeInForce
from nautilus_trader.core.datetime import millis_to_nanos as millis_to_nanos, unix_nanos_to_dt as unix_nanos_to_dt
from nautilus_trader.core.uuid import UUID4 as UUID4
from nautilus_trader.execution.reports import FillReport as FillReport, OrderStatusReport as OrderStatusReport
from nautilus_trader.model.enums import ContingencyType as ContingencyType, LiquiditySide as LiquiditySide, OrderSide as OrderSide, OrderStatus as OrderStatus, OrderType as OrderType, TimeInForce as TimeInForce, TrailingOffsetType as TrailingOffsetType, TriggerType as TriggerType
from nautilus_trader.model.identifiers import AccountId as AccountId, ClientOrderId as ClientOrderId, InstrumentId as InstrumentId, OrderListId as OrderListId, PositionId as PositionId, TradeId as TradeId, VenueOrderId as VenueOrderId
from nautilus_trader.model.objects import Currency as Currency, Money as Money, Price as Price, Quantity as Quantity

class BinanceUserTrade(msgspec.Struct, frozen=True):
    commission: str
    commissionAsset: str
    price: str
    qty: str
    symbol: str | None = ...
    id: int | None = ...
    orderId: int | None = ...
    time: int | None = ...
    quoteQty: str | None = ...
    orderListId: int | None = ...
    isBuyer: bool | None = ...
    isMaker: bool | None = ...
    isBestMatch: bool | None = ...
    tradeId: int | None = ...
    buyer: bool | None = ...
    maker: bool | None = ...
    realizedPnl: str | None = ...
    side: BinanceOrderSide | None = ...
    positionSide: str | None = ...
    baseQty: str | None = ...
    pair: str | None = ...
    def parse_to_fill_report(self, account_id: AccountId, instrument_id: InstrumentId, report_id: UUID4, ts_init: int, use_position_ids: bool = True) -> FillReport: ...

class BinanceOrder(msgspec.Struct, frozen=True):
    symbol: str
    orderId: int
    clientOrderId: str
    price: str | None = ...
    origQty: str | None = ...
    executedQty: str | None = ...
    status: BinanceOrderStatus | None = ...
    timeInForce: BinanceTimeInForce | None = ...
    goodTillDate: int | None = ...
    type: BinanceOrderType | None = ...
    side: BinanceOrderSide | None = ...
    stopPrice: str | None = ...
    time: int | None = ...
    updateTime: int | None = ...
    orderListId: int | None = ...
    cummulativeQuoteQty: str | None = ...
    icebergQty: str | None = ...
    isWorking: bool | None = ...
    workingTime: int | None = ...
    origQuoteOrderQty: str | None = ...
    selfTradePreventionMode: str | None = ...
    transactTime: int | None = ...
    fills: list[BinanceUserTrade] | None = ...
    avgPrice: str | None = ...
    origType: BinanceOrderType | None = ...
    reduceOnly: bool | None = ...
    positionSide: str | None = ...
    closePosition: bool | None = ...
    activatePrice: str | None = ...
    priceRate: str | None = ...
    workingType: str | None = ...
    priceProtect: bool | None = ...
    cumQuote: str | None = ...
    cumBase: str | None = ...
    pair: str | None = ...
    def parse_to_order_status_report(self, account_id: AccountId, instrument_id: InstrumentId, report_id: UUID4, enum_parser: BinanceEnumParser, treat_expired_as_canceled: bool, ts_init: int) -> OrderStatusReport: ...

class BinanceStatusCode(msgspec.Struct, frozen=True):
    code: int
    msg: str
