from nautilus_trader.config import LiveDataClientConfig as LiveDataClientConfig, LiveExecClientConfig as LiveExecClientConfig, PositiveInt as PositiveInt
from nautilus_trader.core.nautilus_pyo3 import KrakenEnvironment as KrakenEnvironment, KrakenProductType as KrakenProductType
from nautilus_trader.model.enums import AccountType as AccountType
from nautilus_trader.network import TransportBackend as TransportBackend

class KrakenDataClientConfig(LiveDataClientConfig, frozen=True):
    api_key: str | None = ...
    api_secret: str | None = ...
    environment: KrakenEnvironment | None = ...
    product_types: tuple[KrakenProductType, ...] | None = ...
    base_url_http_spot: str | None = ...
    base_url_http_futures: str | None = ...
    base_url_ws_spot: str | None = ...
    base_url_ws_futures: str | None = ...
    base_url_ws_l3_spot: str | None = ...
    proxy_url: str | None = ...
    transport_backend: TransportBackend | None = ...
    update_instruments_interval_mins: PositiveInt | None = ...
    max_retries: PositiveInt | None = ...
    retry_delay_initial_ms: PositiveInt | None = ...
    retry_delay_max_ms: PositiveInt | None = ...
    http_timeout_secs: PositiveInt | None = ...
    ws_heartbeat_secs: PositiveInt = ...
    max_requests_per_second: PositiveInt | None = ...
    validate_l3_checksum: bool = ...

class KrakenExecClientConfig(LiveExecClientConfig, frozen=True):
    api_key: str | None = ...
    api_secret: str | None = ...
    environment: KrakenEnvironment | None = ...
    product_types: tuple[KrakenProductType, ...] | None = ...
    base_url_http_spot: str | None = ...
    base_url_http_futures: str | None = ...
    base_url_ws_spot: str | None = ...
    base_url_ws_futures: str | None = ...
    proxy_url: str | None = ...
    transport_backend: TransportBackend | None = ...
    max_retries: PositiveInt | None = ...
    retry_delay_initial_ms: PositiveInt | None = ...
    retry_delay_max_ms: PositiveInt | None = ...
    http_timeout_secs: PositiveInt | None = ...
    ws_heartbeat_secs: PositiveInt = ...
    max_requests_per_second: PositiveInt | None = ...
    use_spot_position_reports: bool = ...
    spot_positions_quote_currency: str = ...
    spot_account_type: AccountType = ...
    default_leverage: int | None = ...
    margin_balance_asset: str | None = ...
    def __post_init__(self) -> None: ...
