import pandas as pd
from nautilus_trader.cache.config import CacheConfig as CacheConfig
from nautilus_trader.common import Environment as Environment
from nautilus_trader.common.config import ActorConfig as ActorConfig, ImportableActorConfig as ImportableActorConfig, NautilusConfig as NautilusConfig, NonNegativeInt as NonNegativeInt, msgspec_encoding_hook as msgspec_encoding_hook, resolve_config_path as resolve_config_path, resolve_path as resolve_path
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.core.datetime import dt_to_unix_nanos as dt_to_unix_nanos
from nautilus_trader.data.config import DataEngineConfig as DataEngineConfig
from nautilus_trader.execution.config import ExecEngineConfig as ExecEngineConfig
from nautilus_trader.live.config import LiveDataClientConfig as LiveDataClientConfig
from nautilus_trader.model.data import Bar as Bar
from nautilus_trader.model.enums import AccountType as AccountType, BookType as BookType, OmsType as OmsType, OtoTriggerMode as OtoTriggerMode
from nautilus_trader.model.identifiers import InstrumentId as InstrumentId, TraderId as TraderId
from nautilus_trader.persistence.funcs import parse_filters_expr as parse_filters_expr
from nautilus_trader.risk.config import RiskEngineConfig as RiskEngineConfig
from nautilus_trader.system.config import NautilusKernelConfig as NautilusKernelConfig
from typing import Any

class BacktestVenueConfig(NautilusConfig, frozen=True):
    name: str
    oms_type: OmsType | str
    account_type: AccountType | str
    starting_balances: list[str]
    base_currency: str | None = ...
    default_leverage: float = ...
    leverages: dict[str, float] | None = ...
    margin_model: MarginModelConfig | None = ...
    modules: list[ImportableActorConfig] | None = ...
    fill_model: ImportableFillModelConfig | None = ...
    latency_model: ImportableLatencyModelConfig | None = ...
    fee_model: ImportableFeeModelConfig | None = ...
    book_type: BookType | str = ...
    routing: bool = ...
    reject_stop_orders: bool = ...
    support_gtd_orders: bool = ...
    support_contingent_orders: bool = ...
    oto_trigger_mode: OtoTriggerMode | str = ...
    use_position_ids: bool = ...
    use_random_ids: bool = ...
    use_reduce_only: bool = ...
    use_market_order_acks: bool = ...
    bar_execution: bool = ...
    bar_adaptive_high_low_ordering: bool = ...
    trade_execution: bool = ...
    liquidity_consumption: bool = ...
    queue_position: bool = ...
    allow_cash_borrowing: bool = ...
    frozen_account: bool = ...
    price_protection_points: NonNegativeInt = ...
    settlement_prices: dict[InstrumentId, float] | None = ...
    liquidation_enabled: bool = ...
    liquidation_trigger_ratio: float = ...
    liquidation_cancel_open_orders: bool = ...

class BacktestDataConfig(NautilusConfig, frozen=True):
    catalog_path: str
    data_cls: str
    catalog_fs_protocol: str | None = ...
    catalog_fs_storage_options: dict | None = ...
    catalog_fs_rust_storage_options: dict | None = ...
    instrument_id: InstrumentId | None = ...
    start_time: str | int | None = ...
    end_time: str | int | None = ...
    filter_expr: str | None = ...
    client_id: str | None = ...
    metadata: dict | Any | None = ...
    bar_spec: str | None = ...
    instrument_ids: list[str] | None = ...
    bar_types: list[str] | None = ...
    optimize_file_loading: bool = ...
    @property
    def data_type(self) -> type: ...
    @property
    def query(self) -> dict[str, Any]: ...
    @property
    def start_time_nanos(self) -> int: ...
    @property
    def end_time_nanos(self) -> int: ...

class BacktestEngineConfig(NautilusKernelConfig, frozen=True):
    environment: Environment = ...
    trader_id: TraderId = ...
    cache: CacheConfig | None = ...
    data_engine: DataEngineConfig | None = ...
    risk_engine: RiskEngineConfig | None = ...
    exec_engine: ExecEngineConfig | None = ...
    run_analysis: bool = ...
    def __post_init__(self) -> None: ...

class BacktestRunConfig(NautilusConfig, frozen=True):
    venues: list[BacktestVenueConfig]
    data: list[BacktestDataConfig]
    engine: BacktestEngineConfig | None = ...
    chunk_size: int | None = ...
    raise_exception: bool = ...
    dispose_on_completion: bool = ...
    start: str | int | None = ...
    end: str | int | None = ...
    data_clients: dict[str, type[LiveDataClientConfig]] | None = ...

class SimulationModuleConfig(ActorConfig, frozen=True): ...

class FillModelConfig(NautilusConfig, frozen=True):
    prob_fill_on_limit: float = ...
    prob_slippage: float = ...
    random_seed: int | None = ...

class ImportableFillModelConfig(NautilusConfig, frozen=True):
    fill_model_path: str
    config_path: str
    config: dict[str, Any]

class FillModelFactory:
    @staticmethod
    def create(config: ImportableFillModelConfig): ...

class LatencyModelConfig(NautilusConfig, frozen=True):
    base_latency_nanos: NonNegativeInt = ...
    insert_latency_nanos: NonNegativeInt = ...
    update_latency_nanos: NonNegativeInt = ...
    cancel_latency_nanos: NonNegativeInt = ...

class ImportableLatencyModelConfig(NautilusConfig, frozen=True):
    latency_model_path: str
    config_path: str
    config: dict[str, Any]

class LatencyModelFactory:
    @staticmethod
    def create(config: ImportableLatencyModelConfig): ...

class FeeModelConfig(NautilusConfig, frozen=True): ...
class MakerTakerFeeModelConfig(FeeModelConfig, frozen=True): ...

class FixedFeeModelConfig(FeeModelConfig, frozen=True):
    commission: str
    charge_commission_once: bool = ...

class PerContractFeeModelConfig(FeeModelConfig, frozen=True):
    commission: str

class ImportableFeeModelConfig(NautilusConfig, frozen=True):
    fee_model_path: str
    config_path: str
    config: dict[str, Any]

class FeeModelFactory:
    @staticmethod
    def create(config: ImportableFeeModelConfig): ...

class FXRolloverInterestConfig(SimulationModuleConfig, frozen=True):
    rate_data: pd.DataFrame

class MarginModelConfig(NautilusConfig, frozen=True):
    model_type: str = ...
    config: dict = ...

class MarginModelFactory:
    @staticmethod
    def create(config: MarginModelConfig): ...
