import _cython_3_2_9
import nautilus_pyo3
from _typeshed import Incomplete
from decimal import Decimal
from nautilus_trader.accounting.error import AccountError as AccountError
from nautilus_trader.backtest.config import BacktestEngineConfig as BacktestEngineConfig
from nautilus_trader.backtest.results import BacktestResult as BacktestResult
from nautilus_trader.common.component import is_logging_pyo3 as is_logging_pyo3
from nautilus_trader.common.config import InvalidConfiguration as InvalidConfiguration
from nautilus_trader.core.inspect import is_nautilus_class as is_nautilus_class
from nautilus_trader.core.rust.model import OtoTriggerMode as OtoTriggerMode
from nautilus_trader.data.engine import get_time_range_generator as get_time_range_generator
from nautilus_trader.system.kernel import NautilusKernel as NautilusKernel
from nautilus_trader.trading.trader import Trader as Trader
from typing import Any, ClassVar, Generator, overload

BOOK_DATA_TYPES: set
NAUTILUS_PYO3_DATA_TYPES: tuple
__reduce_cython__: _cython_3_2_9.cython_function_or_method
__setstate_cython__: _cython_3_2_9.cython_function_or_method
__test__: dict

class BacktestDataIterator:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self) -> None: ...
    def add_data(self, strdata_name, listdata, boolappend_data=..., boolpresorted=...) -> None: ...
    def all_data(self) -> dict: ...
    def data(self, strdata_name) -> list: ...
    def init_data(self, strdata_name, data_generator, boolappend_data=...) -> None: ...
    def is_done(self) -> bool: ...
    def next(self) -> Data: ...
    def remove_data(self, strdata_name, boolcomplete_remove=...) -> void: ...
    def set_index(self, strdata_name, intindex) -> void: ...
    def __iter__(self): ...
    def __next__(self): ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class BacktestEngine:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    backtest_end: BacktestEngine.backtest_end
    backtest_start: BacktestEngine.backtest_start
    cache: BacktestEngine.cache
    data: BacktestEngine.data
    instance_id: BacktestEngine.instance_id
    iteration: BacktestEngine.iteration
    kernel: BacktestEngine.kernel
    logger: BacktestEngine.logger
    machine_id: BacktestEngine.machine_id
    portfolio: BacktestEngine.portfolio
    run_config_id: BacktestEngine.run_config_id
    run_finished: BacktestEngine.run_finished
    run_id: BacktestEngine.run_id
    run_started: BacktestEngine.run_started
    trader: BacktestEngine.trader
    trader_id: BacktestEngine.trader_id
    def __init__(self, config: BacktestEngineConfig | None = ...) -> None: ...
    def add_actor(self, Actoractor: Actor) -> None: ...
    def add_actors(self, listactors: list[Actor]) -> None: ...
    @overload
    def add_data(self, listdata, ClientIdclient_id=..., boolvalidate=..., boolsort=...) -> None: ...
    @overload
    def add_data(self) -> Any: ...
    @overload
    def add_data(self, instrument1_bars, sort=...) -> Any: ...
    @overload
    def add_data(self, instrument2_bars, sort=...) -> Any: ...
    @overload
    def add_data(self, instrument3_bars, sort=...) -> Any: ...
    def add_data_iterator(self, strdata_name, generator: Generator[list[Data], None, None], ClientIdclient_id=...) -> None: ...
    def add_exec_algorithm(self, ExecAlgorithmexec_algorithm: ExecAlgorithm) -> None: ...
    def add_exec_algorithms(self, listexec_algorithms: list[ExecAlgorithm]) -> None: ...
    def add_instrument(self, Instrumentinstrument) -> None: ...
    def add_strategies(self, liststrategies: list[Strategy]) -> None: ...
    def add_strategy(self, Strategystrategy: Strategy) -> None: ...
    def add_venue(self, Venuevenue: Venue, OmsTypeoms_type: OmsType, AccountTypeaccount_type: AccountType, liststarting_balances: list[Money], Currencybase_currency: Currency | None = ..., default_leverage: Decimal | None = ..., dictleverages: dict[InstrumentId, Decimal] | None = ..., MarginModelmargin_model: MarginModel = ..., listmodules: list[SimulationModule] | None = ..., FillModelfill_model: FillModel | None = ..., FeeModelfee_model: FeeModel | None = ..., LatencyModellatency_model: LatencyModel | None = ..., BookTypebook_type: BookType = ..., boolrouting: bool = ..., boolreject_stop_orders: bool = ..., boolsupport_gtd_orders: bool = ..., boolsupport_contingent_orders: bool = ..., OtoTriggerModeoto_trigger_mode: OtoTriggerMode = ..., booluse_position_ids: bool = ..., booluse_random_ids: bool = ..., booluse_reduce_only: bool = ..., booluse_message_queue: bool = ..., booluse_market_order_acks: bool = ..., boolbar_execution: bool = ..., boolbar_adaptive_high_low_ordering: bool = ..., booltrade_execution: bool = ..., boolliquidity_consumption: bool = ..., boolqueue_position: bool = ..., boolallow_cash_borrowing: bool = ..., boolfrozen_account: bool = ..., price_protection_points=..., dictsettlement_prices: dict[InstrumentId, float] | None = ...) -> None: ...
    def change_fill_model(self, Venuevenue, FillModelmodel) -> None: ...
    def clear_actors(self) -> None: ...
    def clear_data(self) -> None: ...
    def clear_exec_algorithms(self) -> None: ...
    def clear_strategies(self) -> None: ...
    def dispose(self) -> None: ...
    def dump_pickled_data(self) -> bytes: ...
    def end(self) -> Any: ...
    def get_log_guard(self) -> nautilus_pyo3.LogGuard | LogGuard | None: ...
    def get_result(self) -> Any: ...
    def list_venues(self) -> list[Venue]: ...
    def load_pickled_data(self, bytesdata) -> None: ...
    def reset(self) -> None: ...
    @overload
    def run(self, start: datetime | str | int | None = ..., end: datetime | str | int | None = ..., strrun_config_id: str | None = ..., boolstreaming: bool = ...) -> None: ...
    @overload
    def run(self, streaming=...) -> Any: ...
    @overload
    def run(self) -> Any: ...
    def set_default_market_data_client(self) -> None: ...
    def sort_data(self) -> None: ...
    def __del__(self, *args, **kwargs) -> None: ...
    def __reduce__(self): ...

class OrderMatchingEngine:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    account_type: Incomplete
    book_type: Incomplete
    cache: Incomplete
    instrument: Incomplete
    market_status: Incomplete
    msgbus: Incomplete
    oms_type: Incomplete
    raw_id: Incomplete
    venue: Incomplete
    def __init__(self, Instrumentinstrument, uint32_traw_id, FillModelfill_model, FeeModelfee_model, BookTypebook_type, OmsTypeoms_type, AccountTypeaccount_type, MessageBusmsgbus, CacheFacadecache, TestClockclock, boolreject_stop_orders=..., boolsupport_gtd_orders=..., boolsupport_contingent_orders=..., booloto_full_trigger=..., booluse_position_ids=..., booluse_random_ids=..., booluse_reduce_only=..., booluse_market_order_acks=..., boolbar_execution=..., boolbar_adaptive_high_low_ordering=..., booltrade_execution=..., boolliquidity_consumption=..., boolqueue_position=..., price_protection_points=..., dictsettlement_prices: dict[InstrumentId, float] | None = ...) -> None: ...
    def accept_order(self, Orderorder) -> void: ...
    def apply_fills(self, Orderorder, listfills, LiquiditySideliquidity_side, PositionIdvenue_position_id: PositionId | None = ..., Positionposition: Position | None = ..., Priceprotection_price: Price | None = ...) -> void: ...
    def best_ask_price(self) -> Price: ...
    def best_bid_price(self) -> Price: ...
    def cancel_order(self, Orderorder, boolcancel_contingencies=...) -> void: ...
    def check_instrument_expiration(self, uint64_ttimestamp_ns) -> void: ...
    def determine_limit_price_and_volume(self, Orderorder) -> list: ...
    def determine_market_price_and_volume(self, Orderorder) -> list: ...
    def expire_order(self, Orderorder) -> void: ...
    def fill_limit_order(self, Orderorder) -> void: ...
    def fill_market_order(self, Orderorder) -> void: ...
    def fill_order(self, Orderorder, Pricelast_px, Quantitylast_qty, LiquiditySideliquidity_side, PositionIdvenue_position_id: PositionId | None = ..., Positionposition: Position | None = ...) -> void: ...
    def get_book(self) -> OrderBook: ...
    def get_open_ask_orders(self) -> list: ...
    def get_open_bid_orders(self) -> list: ...
    def get_open_orders(self) -> list: ...
    def iterate(self, uint64_ttimestamp_ns, AggressorSideaggressor_side=...) -> void: ...
    def order_exists(self, ClientOrderIdclient_order_id) -> bool: ...
    def process_bar(self, Barbar) -> void: ...
    def process_batch_cancel(self, BatchCancelOrderscommand, AccountIdaccount_id) -> void: ...
    def process_cancel(self, CancelOrdercommand, AccountIdaccount_id) -> void: ...
    def process_cancel_all(self, CancelAllOrderscommand, AccountIdaccount_id) -> void: ...
    def process_instrument_close(self, InstrumentCloseclose) -> void: ...
    def process_modify(self, ModifyOrdercommand, AccountIdaccount_id) -> void: ...
    def process_order(self, Orderorder, AccountIdaccount_id) -> void: ...
    def process_order_book_delta(self, OrderBookDeltadelta) -> void: ...
    def process_order_book_deltas(self, OrderBookDeltasdeltas) -> void: ...
    def process_order_book_depth10(self, OrderBookDepth10depth) -> void: ...
    def process_quote_tick(self, QuoteTicktick) -> void: ...
    def process_status(self, MarketStatusActionstatus) -> void: ...
    def process_trade_tick(self, TradeTicktick) -> void: ...
    def reset(self) -> void: ...
    def set_fill_model(self, FillModelfill_model) -> void: ...
    def trigger_stop_order(self, Orderorder) -> void: ...
    def update_instrument(self, Instrumentinstrument) -> void: ...
    def update_order(self, Orderorder, Quantityqty, Priceprice=..., Pricetrigger_price=..., boolupdate_contingencies=...) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class SimulatedExchange:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    account_type: Incomplete
    bar_adaptive_high_low_ordering: Incomplete
    bar_execution: Incomplete
    base_currency: Incomplete
    book_type: Incomplete
    cache: Incomplete
    default_leverage: Incomplete
    exec_client: Incomplete
    fee_model: Incomplete
    fill_model: Incomplete
    id: Incomplete
    instruments: Incomplete
    is_frozen_account: Incomplete
    latency_model: Incomplete
    leverages: Incomplete
    liquidity_consumption: Incomplete
    margin_model: Incomplete
    modules: Incomplete
    msgbus: Incomplete
    oms_type: Incomplete
    oto_full_trigger: Incomplete
    price_protection_points: Incomplete
    queue_position: Incomplete
    reject_stop_orders: Incomplete
    starting_balances: Incomplete
    support_contingent_orders: Incomplete
    support_gtd_orders: Incomplete
    trade_execution: Incomplete
    use_market_order_acks: Incomplete
    use_message_queue: Incomplete
    use_position_ids: Incomplete
    use_random_ids: Incomplete
    use_reduce_only: Incomplete
    def __init__(self, Venuevenue, OmsTypeoms_type, AccountTypeaccount_type, liststarting_balances, Currencybase_currency: Currency | None, default_leverage: Decimal, dictleverages: dict[InstrumentId, Decimal], listmodules, PortfolioFacadeportfolio, MessageBusmsgbus, CacheFacadecache, TestClockclock, FillModelfill_model, FeeModelfee_model, LatencyModellatency_model=..., MarginModelmargin_model=..., BookTypebook_type=..., boolfrozen_account=..., boolreject_stop_orders=..., boolsupport_gtd_orders=..., boolsupport_contingent_orders=..., OtoTriggerModeoto_trigger_mode=..., booluse_position_ids=..., booluse_random_ids=..., booluse_reduce_only=..., booluse_message_queue=..., booluse_market_order_acks=..., boolbar_execution=..., boolbar_adaptive_high_low_ordering=..., booltrade_execution=..., boolliquidity_consumption=..., boolqueue_position=..., price_protection_points=..., dictsettlement_prices: dict[InstrumentId, float] | None = ...) -> None: ...
    def add_instrument(self, Instrumentinstrument) -> void: ...
    def adjust_account(self, Moneyadjustment) -> void: ...
    def best_ask_price(self, InstrumentIdinstrument_id) -> Price: ...
    def best_bid_price(self, InstrumentIdinstrument_id) -> Price: ...
    def get_account(self) -> Account: ...
    def get_book(self, InstrumentIdinstrument_id) -> OrderBook: ...
    def get_books(self) -> dict: ...
    def get_matching_engine(self, InstrumentIdinstrument_id) -> OrderMatchingEngine: ...
    def get_matching_engines(self) -> dict: ...
    def get_open_ask_orders(self, InstrumentIdinstrument_id=...) -> list: ...
    def get_open_bid_orders(self, InstrumentIdinstrument_id=...) -> list: ...
    def get_open_orders(self, InstrumentIdinstrument_id=...) -> list: ...
    def initialize_account(self) -> void: ...
    def process(self, uint64_tts_now) -> void: ...
    def process_bar(self, Barbar) -> void: ...
    def process_instrument_close(self, InstrumentCloseclose) -> void: ...
    def process_instrument_status(self, InstrumentStatusdata) -> void: ...
    def process_order_book_delta(self, OrderBookDeltadelta) -> void: ...
    def process_order_book_deltas(self, OrderBookDeltasdeltas) -> void: ...
    def process_order_book_depth10(self, OrderBookDepth10depth) -> void: ...
    def process_quote_tick(self, QuoteTicktick) -> void: ...
    def process_trade_tick(self, TradeTicktick) -> void: ...
    def register_client(self, BacktestExecClientclient) -> void: ...
    def reset(self) -> void: ...
    def send(self, TradingCommandcommand) -> void: ...
    def set_fill_model(self, FillModelfill_model) -> void: ...
    def set_latency_model(self, LatencyModellatency_model) -> void: ...
    def update_instrument(self, Instrumentinstrument) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
