import nautilus_trader.execution.client
from nautilus_trader.accounting.factory import AccountFactory as AccountFactory
from nautilus_trader.common.config import NautilusConfig as NautilusConfig
from typing import Any, ClassVar

__test__: dict

class BacktestExecClient(nautilus_trader.execution.client.ExecutionClient):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, SimulatedExchangeexchange, MessageBusmsgbus, Cachecache, TestClockclock, boolrouting=..., boolfrozen_account=..., boolallow_cash_borrowing=...) -> None: ...
    def batch_cancel_orders(self, BatchCancelOrderscommand) -> void: ...
    def cancel_all_orders(self, CancelAllOrderscommand) -> void: ...
    def cancel_order(self, CancelOrdercommand) -> void: ...
    def modify_order(self, ModifyOrdercommand) -> void: ...
    def submit_order(self, SubmitOrdercommand) -> void: ...
    def submit_order_list(self, SubmitOrderListcommand) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
