import nautilus_trader.common.actor
from _typeshed import Incomplete
from nautilus_trader.backtest.config import FXRolloverInterestConfig as FXRolloverInterestConfig, SimulationModuleConfig as SimulationModuleConfig
from nautilus_trader.common.config import ActorConfig as ActorConfig
from typing import Any, ClassVar

__test__: dict

class FXRolloverInterestModule(SimulationModule):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, config: FXRolloverInterestConfig) -> Any: ...
    def log_diagnostics(self, Loggerlogger) -> void: ...
    def process(self, uint64_tts_now) -> void: ...
    def reset(self) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class SimulationModule(nautilus_trader.common.actor.Actor):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    exchange: Incomplete
    def __init__(self, config: SimulationModuleConfig) -> Any: ...
    def log_diagnostics(self, Loggerlogger) -> void: ...
    def pre_process(self, Datadata) -> void: ...
    def process(self, uint64_tts_now) -> void: ...
    def register_venue(self, SimulatedExchangeexchange) -> void: ...
    def reset(self) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
