from decimal import Decimal
from nautilus_trader.backtest.config import BacktestDataConfig as BacktestDataConfig, BacktestRunConfig as BacktestRunConfig, BacktestVenueConfig as BacktestVenueConfig, FeeModelFactory as FeeModelFactory, FillModelFactory as FillModelFactory, LatencyModelFactory as LatencyModelFactory, MarginModelFactory as MarginModelFactory
from nautilus_trader.backtest.engine import BacktestEngine as BacktestEngine, BacktestEngineConfig as BacktestEngineConfig
from nautilus_trader.backtest.models import FeeModel as FeeModel, FillModel as FillModel, LatencyModel as LatencyModel
from nautilus_trader.backtest.node_builder import BacktestNodeBuilder as BacktestNodeBuilder
from nautilus_trader.backtest.results import BacktestResult as BacktestResult
from nautilus_trader.common.actor import Actor as Actor
from nautilus_trader.common.component import LogGuard as LogGuard, Logger as Logger, init_logging as init_logging, is_backtest_force_stop as is_backtest_force_stop, is_logging_initialized as is_logging_initialized
from nautilus_trader.common.config import ActorConfig as ActorConfig, ActorFactory as ActorFactory, InvalidConfiguration as InvalidConfiguration
from nautilus_trader.common.enums import LogColor as LogColor
from nautilus_trader.config import ImportableActorConfig as ImportableActorConfig, LiveDataClientConfig as LiveDataClientConfig
from nautilus_trader.core import nautilus_pyo3 as nautilus_pyo3
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.core.datetime import dt_to_unix_nanos as dt_to_unix_nanos, max_date as max_date, min_date as min_date
from nautilus_trader.core.inspect import is_nautilus_class as is_nautilus_class
from nautilus_trader.core.nautilus_pyo3 import DataBackendSession as DataBackendSession, drop_cvec_pycapsule as drop_cvec_pycapsule
from nautilus_trader.live.factories import LiveDataClientFactory as LiveDataClientFactory
from nautilus_trader.model import BOOK_DATA_TYPES as BOOK_DATA_TYPES
from nautilus_trader.model.data import Bar as Bar, BarType as BarType, capsule_to_list as capsule_to_list, pyo3_list_to_data_list as pyo3_list_to_data_list
from nautilus_trader.model.enums import AccountType as AccountType, BookType as BookType, OmsType as OmsType, OtoTriggerMode as OtoTriggerMode, account_type_from_str as account_type_from_str, book_type_from_str as book_type_from_str, oms_type_from_str as oms_type_from_str, oto_trigger_mode_from_str as oto_trigger_mode_from_str
from nautilus_trader.model.identifiers import ClientId as ClientId, InstrumentId as InstrumentId, Venue as Venue
from nautilus_trader.model.objects import Currency as Currency, Money as Money
from nautilus_trader.persistence.catalog.parquet import ParquetDataCatalog as ParquetDataCatalog
from nautilus_trader.persistence.catalog.types import CatalogDataResult as CatalogDataResult
from nautilus_trader.persistence.config import DataCatalogConfig as DataCatalogConfig

class BacktestNode:
    def __init__(self, configs: list[BacktestRunConfig]) -> None: ...
    @property
    def configs(self) -> list[BacktestRunConfig]: ...
    def get_log_guard(self) -> nautilus_pyo3.LogGuard | LogGuard | None: ...
    def get_engine(self, run_config_id: str) -> BacktestEngine | None: ...
    def get_engines(self) -> list[BacktestEngine]: ...
    def dispose(self) -> None: ...
    def add_data_client_factory(self, name: str, factory: type[LiveDataClientFactory]) -> None: ...
    def build(self) -> None: ...
    def setup_download_engine(self, catalog_config: DataCatalogConfig, data_clients: dict[str, type[LiveDataClientConfig]]) -> None: ...
    def download_data(self, request_function: str, **kwargs) -> None: ...
    def run(self) -> list[BacktestResult]: ...
    @classmethod
    def load_data_config(cls, config: BacktestDataConfig, start: str | int | None = None, end: str | int | None = None) -> CatalogDataResult: ...
    @classmethod
    def load_catalog(cls, config: BacktestDataConfig) -> ParquetDataCatalog: ...
    def log_backtest_exception(self, e: Exception, config: BacktestRunConfig) -> None: ...

def get_instrument_ids(config: BacktestDataConfig) -> list[InstrumentId]: ...
def get_oms_type(config: BacktestVenueConfig) -> OmsType: ...
def get_account_type(config: BacktestVenueConfig) -> AccountType: ...
def get_book_type(config: BacktestVenueConfig) -> BookType | None: ...
def get_oto_trigger_mode(config: BacktestVenueConfig) -> OtoTriggerMode: ...
def get_starting_balances(config: BacktestVenueConfig) -> list[Money]: ...
def get_base_currency(config: BacktestVenueConfig) -> Currency | None: ...
def get_leverages(config: BacktestVenueConfig) -> dict[InstrumentId, Decimal]: ...
def get_price_protection_points(config: BacktestVenueConfig) -> int | None: ...
def get_fill_model(config: BacktestVenueConfig) -> FillModel | None: ...
def get_latency_model(config: BacktestVenueConfig) -> LatencyModel | None: ...
def get_fee_model(config: BacktestVenueConfig) -> FeeModel | None: ...
def get_margin_model(config: BacktestVenueConfig): ...
