import nautilus_trader.model.tick_scheme.base
from _typeshed import Incomplete
from typing import Any, ClassVar

FOREX_3DECIMAL_TICK_SCHEME: FixedTickScheme
FOREX_5DECIMAL_TICK_SCHEME: FixedTickScheme
__test__: dict
precision: int
tick_scheme: FixedTickScheme

class FixedTickScheme(nautilus_trader.model.tick_scheme.base.TickScheme):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    increment: Incomplete
    price_precision: Incomplete
    def __init__(self, strname, intprice_precision, Pricemin_tick, Pricemax_tick, floatincrement: float | None = ...) -> Any: ...
    def next_ask_price(self, doublevalue, intn=...) -> Price: ...
    def next_bid_price(self, doublevalue, intn=...) -> Price: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
