import nautilus_trader.model.tick_scheme.base
from _typeshed import Incomplete
from typing import Any, ClassVar

TOPIX100_TICK_SCHEME: TieredTickScheme
__test__: dict

class TieredTickScheme(nautilus_trader.model.tick_scheme.base.TickScheme):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    ticks: Incomplete
    def __init__(self, strname, listtiers, intprice_precision, intmax_ticks_per_tier=...) -> Any: ...
    def find_tick_index(self, doublevalue) -> int: ...
    def next_ask_price(self, doublevalue, intn=...) -> Price: ...
    def next_bid_price(self, doublevalue, intn=...) -> Price: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
