from _typeshed import Incomplete
from decimal import Decimal
from nautilus_trader.common.enums import LogColor as LogColor
from nautilus_trader.config import PositiveInt as PositiveInt, StrategyConfig as StrategyConfig
from nautilus_trader.model.book import OrderBook as OrderBook
from nautilus_trader.model.data import Bar as Bar, MarkPriceUpdate as MarkPriceUpdate, OrderBookDeltas as OrderBookDeltas, QuoteTick as QuoteTick, TradeTick as TradeTick
from nautilus_trader.model.enums import BookType as BookType, OrderSide as OrderSide, OrderType as OrderType, TimeInForce as TimeInForce, TrailingOffsetType as TrailingOffsetType, TriggerType as TriggerType
from nautilus_trader.model.identifiers import ClientId as ClientId, InstrumentId as InstrumentId
from nautilus_trader.model.instruments import Instrument as Instrument
from nautilus_trader.model.objects import Price as Price, Quantity as Quantity
from nautilus_trader.model.orders import LimitIfTouchedOrder as LimitIfTouchedOrder, LimitOrder as LimitOrder, MarketIfTouchedOrder as MarketIfTouchedOrder, MarketOrder as MarketOrder, Order as Order, StopLimitOrder as StopLimitOrder, StopMarketOrder as StopMarketOrder, TrailingStopMarketOrder as TrailingStopMarketOrder
from nautilus_trader.trading.strategy import Strategy as Strategy
from typing import Any

class ExecTesterConfig(StrategyConfig, frozen=True):
    instrument_id: InstrumentId
    order_qty: Decimal
    order_display_qty: Decimal | None = ...
    order_expire_time_delta_mins: PositiveInt | None = ...
    order_params: dict[str, Any] | None = ...
    client_id: ClientId | None = ...
    subscribe_quotes: bool = ...
    subscribe_trades: bool = ...
    subscribe_book: bool = ...
    book_type: BookType = ...
    book_depth: PositiveInt | None = ...
    book_interval_ms: PositiveInt = ...
    book_levels_to_print: PositiveInt = ...
    open_position_on_start_qty: Decimal | None = ...
    open_position_time_in_force: TimeInForce = ...
    enable_limit_buys: bool = ...
    enable_limit_sells: bool = ...
    enable_stop_buys: bool = ...
    enable_stop_sells: bool = ...
    tob_offset_ticks: PositiveInt = ...
    limit_time_in_force: TimeInForce | None = ...
    stop_order_type: OrderType = ...
    stop_offset_ticks: PositiveInt = ...
    stop_limit_offset_ticks: PositiveInt | None = ...
    stop_trigger_type: TriggerType | str | None = ...
    stop_time_in_force: TimeInForce | None = ...
    trailing_offset: Decimal | None = ...
    trailing_offset_type: TrailingOffsetType = ...
    enable_brackets: bool = ...
    bracket_entry_order_type: OrderType = ...
    bracket_offset_ticks: PositiveInt = ...
    modify_orders_to_maintain_tob_offset: bool = ...
    modify_stop_orders_to_maintain_offset: bool = ...
    cancel_replace_orders_to_maintain_tob_offset: bool = ...
    cancel_replace_stop_orders_to_maintain_offset: bool = ...
    use_post_only: bool = ...
    use_quote_quantity: bool = ...
    emulation_trigger: TriggerType | str | None = ...
    cancel_orders_on_stop: bool = ...
    close_positions_on_stop: bool = ...
    close_positions_time_in_force: TimeInForce | None = ...
    reduce_only_on_stop: bool = ...
    use_individual_cancels_on_stop: bool = ...
    use_batch_cancel_on_stop: bool = ...
    dry_run: bool = ...
    log_data: bool = ...
    test_reject_post_only: bool = ...
    test_reject_reduce_only: bool = ...
    can_unsubscribe: bool = ...

class ExecTester(Strategy):
    instrument: Instrument | None
    client_id: Incomplete
    buy_order: LimitOrder | None
    sell_order: LimitOrder | None
    buy_stop_order: Order | None
    sell_stop_order: Order | None
    def __init__(self, config: ExecTesterConfig) -> None: ...
    price_offset: Incomplete
    def on_start(self) -> None: ...
    def on_order_book(self, book: OrderBook) -> None: ...
    def on_order_book_deltas(self, deltas: OrderBookDeltas) -> None: ...
    def on_quote_tick(self, quote: QuoteTick) -> None: ...
    def on_trade_tick(self, trade: TradeTick) -> None: ...
    def on_mark_price(self, update: MarkPriceUpdate) -> None: ...
    def on_index_price(self, update: MarkPriceUpdate) -> None: ...
    def on_bar(self, bar: Bar) -> None: ...
    def maintain_orders(self, best_bid: Price, best_ask: Price) -> None: ...
    def maintain_buy_orders(self, instrument: Instrument, best_bid: Price, best_ask: Price) -> None: ...
    def maintain_sell_orders(self, instrument: Instrument, best_bid: Price, best_ask: Price) -> None: ...
    def open_position(self, net_qty: Decimal) -> None: ...
    def get_price_offset(self, instrument: Instrument) -> Decimal: ...
    def is_order_active(self, order: Order) -> bool: ...
    def submit_limit_order(self, order_side: OrderSide, price: Price) -> None: ...
    def submit_bracket_order(self, order_side: OrderSide, price: Price) -> None: ...
    def submit_stop_order(self, order_side: OrderSide, trigger_price: Price, limit_price: Price | None = None) -> None: ...
    def maintain_stop_buy_orders(self, instrument: Instrument, best_bid: Price, best_ask: Price) -> None: ...
    def maintain_stop_sell_orders(self, instrument: Instrument, best_bid: Price, best_ask: Price) -> None: ...
    def get_order_trigger_price(self, order: Order) -> Price | None: ...
    def modify_stop_order(self, order: Order, trigger_price: Price, limit_price: Price | None = None) -> None: ...
    def on_stop(self) -> None: ...
