import pandas as pd
from decimal import Decimal
from nautilus_trader.common.actor import Actor as Actor
from nautilus_trader.common.config import ActorConfig as ActorConfig, PositiveInt as PositiveInt
from nautilus_trader.common.enums import LogColor as LogColor
from nautilus_trader.core import nautilus_pyo3 as nautilus_pyo3
from nautilus_trader.model.book import OrderBook as OrderBook
from nautilus_trader.model.data import Bar as Bar, BarType as BarType, FundingRateUpdate as FundingRateUpdate, IndexPriceUpdate as IndexPriceUpdate, InstrumentStatus as InstrumentStatus, MarkPriceUpdate as MarkPriceUpdate, OrderBookDeltas as OrderBookDeltas, OrderBookDepth10 as OrderBookDepth10, QuoteTick as QuoteTick, TradeTick as TradeTick
from nautilus_trader.model.enums import BookType as BookType
from nautilus_trader.model.identifiers import ClientId as ClientId, InstrumentId as InstrumentId
from nautilus_trader.model.instruments import Instrument as Instrument
from typing import Any

class DataTesterConfig(ActorConfig, frozen=True):
    instrument_ids: list[InstrumentId]
    client_id: ClientId | None = ...
    bar_types: list[BarType] | None = ...
    subscribe_book_deltas: bool = ...
    subscribe_book_depth: bool = ...
    subscribe_book_at_interval: bool = ...
    subscribe_quotes: bool = ...
    subscribe_trades: bool = ...
    subscribe_mark_prices: bool = ...
    subscribe_index_prices: bool = ...
    subscribe_funding_rates: bool = ...
    subscribe_bars: bool = ...
    subscribe_instrument: bool = ...
    subscribe_instrument_status: bool = ...
    subscribe_instrument_close: bool = ...
    subscribe_params: dict[str, Any] | None = ...
    can_unsubscribe: bool = ...
    request_instruments: bool = ...
    request_book_snapshot: bool = ...
    request_book_deltas: bool = ...
    request_quotes: bool = ...
    request_trades: bool = ...
    request_bars: bool = ...
    request_funding_rates: bool = ...
    request_params: dict[str, Any] | None = ...
    requests_start_delta: pd.Timedelta | None = ...
    book_type: BookType = ...
    book_depth: PositiveInt | None = ...
    book_group_size: Decimal | None = ...
    book_interval_ms: PositiveInt = ...
    book_levels_to_print: PositiveInt = ...
    manage_book: bool = ...
    use_pyo3_book: bool = ...
    log_data: bool = ...

class DataTester(Actor):
    def __init__(self, config: DataTesterConfig) -> None: ...
    def on_start(self) -> None: ...
    def setup_book(self, instrument_id: InstrumentId) -> None: ...
    def setup_book_pyo3(self, instrument_id: InstrumentId) -> None: ...
    def on_stop(self) -> None: ...
    def on_historical_data(self, data: Any) -> None: ...
    def on_instrument(self, instrument: Instrument) -> None: ...
    def on_instruments(self, instruments: list[Instrument]) -> None: ...
    def on_order_book_deltas(self, deltas: OrderBookDeltas) -> None: ...
    def on_order_book_depth(self, depth: OrderBookDepth10) -> None: ...
    def on_order_book(self, order_book: OrderBook) -> None: ...
    def on_quote_tick(self, quote: QuoteTick) -> None: ...
    def on_trade_tick(self, trade: TradeTick) -> None: ...
    def on_mark_price(self, mark_price: MarkPriceUpdate) -> None: ...
    def on_index_price(self, index_price: IndexPriceUpdate) -> None: ...
    def on_instrument_status(self, data: InstrumentStatus) -> None: ...
    def on_funding_rate(self, funding_rate: FundingRateUpdate) -> None: ...
    def on_bar(self, bar: Bar) -> None: ...
