import nautilus_trader.model.orders.base
from _typeshed import Incomplete
from typing import Any, ClassVar

__test__: dict

class LimitIfTouchedOrder(nautilus_trader.model.orders.base.Order):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    display_qty: Incomplete
    expire_time: Incomplete
    expire_time_ns: Incomplete
    is_triggered: Incomplete
    price: Any
    trigger_price: Incomplete
    trigger_type: Incomplete
    ts_triggered: Incomplete
    def __init__(self, TraderIdtrader_id, StrategyIdstrategy_id, InstrumentIdinstrument_id, ClientOrderIdclient_order_id, OrderSideorder_side, Quantityquantity, Priceprice, Pricetrigger_price, TriggerTypetrigger_type, UUID4init_id, uint64_tts_init, TimeInForcetime_in_force=..., uint64_texpire_time_ns=..., boolpost_only=..., boolreduce_only=..., boolquote_quantity=..., Quantitydisplay_qty=..., TriggerTypeemulation_trigger=..., InstrumentIdtrigger_instrument_id=..., ContingencyTypecontingency_type=..., OrderListIdorder_list_id=..., listlinked_order_ids=..., ClientOrderIdparent_order_id=..., ExecAlgorithmIdexec_algorithm_id=..., dictexec_algorithm_params=..., ClientOrderIdexec_spawn_id=..., listtags=...) -> Any: ...
    @staticmethod
    def create(init) -> Any: ...
    def info(self) -> str: ...
    def to_dict(self) -> dict: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
