from _typeshed import Incomplete
from typing import Any, ClassVar

__test__: dict

class OrderList:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    first: Incomplete
    id: Incomplete
    instrument_id: Incomplete
    orders: Incomplete
    strategy_id: Incomplete
    ts_init: Incomplete
    def __init__(self, OrderListIdorder_list_id, listorders) -> None: ...
    def instrument_ids(self) -> set: ...
    def is_bracket(self) -> bool: ...
    def is_uniform_instrument(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __len__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
