from typing import Any, ClassVar

__test__: dict

class OrderUnpacker:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @staticmethod
    def from_init(OrderInitializedinit) -> Order: ...
    @staticmethod
    def unpack(dictvalues) -> Order: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
