from nautilus_trader.common.component import LogColor as LogColor
from nautilus_trader.config import ExecAlgorithmConfig as ExecAlgorithmConfig
from nautilus_trader.execution.algorithm import ExecAlgorithm as ExecAlgorithm
from nautilus_trader.model.identifiers import ExecAlgorithmId as ExecAlgorithmId
from nautilus_trader.model.orders import Order as Order, OrderList as OrderList

class MyExecAlgorithmConfig(ExecAlgorithmConfig, frozen=True):
    exec_algorithm_id: ExecAlgorithmId | None = ...

class MyExecAlgorithm(ExecAlgorithm):
    def __init__(self, config: MyExecAlgorithmConfig) -> None: ...
    def on_start(self) -> None: ...
    def on_stop(self) -> None: ...
    def on_reset(self) -> None: ...
    def on_dispose(self) -> None: ...
    def on_save(self) -> dict[str, bytes]: ...
    def on_load(self, state: dict[str, bytes]) -> None: ...
    def on_order(self, order: Order) -> None: ...
    def on_order_list(self, order_list: OrderList) -> None: ...
