from decimal import Decimal
from nautilus_trader.common.enums import LogColor as LogColor
from nautilus_trader.common.events import TimeEvent as TimeEvent
from nautilus_trader.config import ExecAlgorithmConfig as ExecAlgorithmConfig
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.execution.algorithm import ExecAlgorithm as ExecAlgorithm
from nautilus_trader.model.enums import OrderType as OrderType
from nautilus_trader.model.identifiers import ClientOrderId as ClientOrderId, ExecAlgorithmId as ExecAlgorithmId
from nautilus_trader.model.instruments import Instrument as Instrument
from nautilus_trader.model.objects import Quantity as Quantity
from nautilus_trader.model.orders import MarketOrder as MarketOrder, Order as Order

class TWAPExecAlgorithmConfig(ExecAlgorithmConfig, frozen=True):
    exec_algorithm_id: ExecAlgorithmId | None = ...

class TWAPExecAlgorithm(ExecAlgorithm):
    def __init__(self, config: TWAPExecAlgorithmConfig | None = None) -> None: ...
    def on_start(self) -> None: ...
    def on_stop(self) -> None: ...
    def on_reset(self) -> None: ...
    def on_save(self) -> dict[str, bytes]: ...
    def on_load(self, state: dict[str, bytes]) -> None: ...
    def round_decimal_down(self, amount: Decimal, precision: int) -> Decimal: ...
    def on_order(self, order: Order) -> None: ...
    def on_time_event(self, event: TimeEvent) -> None: ...
    def complete_sequence(self, exec_spawn_id: ClientOrderId) -> None: ...
