from typing import Any, ClassVar

__test__: dict

class FeeModel:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def get_commission(self, Orderorder, Quantityfill_qty, Pricefill_px, Instrumentinstrument) -> Money: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class FixedFeeModel(FeeModel):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, Moneycommission=..., boolcharge_commission_once: bool = ..., config=...) -> None: ...
    def get_commission(self, Orderorder, Quantityfill_qty, Pricefill_px, Instrumentinstrument) -> Money: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class MakerTakerFeeModel(FeeModel):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, config=...) -> None: ...
    def get_commission(self, Orderorder, Quantityfill_qty, Pricefill_px, Instrumentinstrument) -> Money: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class PerContractFeeModel(FeeModel):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, Moneycommission=..., config=...) -> None: ...
    def get_commission(self, Orderorder, Quantityfill_qty, Pricefill_px, Instrumentinstrument) -> Money: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
