from _typeshed import Incomplete
from typing import Any, ClassVar

__test__: dict

class BestPriceFillModel(FillModel):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def fill_limit_inside_spread(self) -> bool: ...
    def get_orderbook_for_fill_simulation(self, Instrumentinstrument, Orderorder, Pricebest_bid, Pricebest_ask) -> OrderBook: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class CompetitionAwareFillModel(FillModel):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, doubleprob_fill_on_limit=..., doubleprob_slippage=..., random_seed=..., doubleliquidity_factor=...) -> Any: ...
    def get_orderbook_for_fill_simulation(self, Instrumentinstrument, Orderorder, Pricebest_bid, Pricebest_ask) -> OrderBook: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class FillModel:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    prob_fill_on_limit: Incomplete
    prob_slippage: Incomplete
    def __init__(self, doubleprob_fill_on_limit=..., doubleprob_slippage=..., intrandom_seed: int | None = ..., config=...) -> None: ...
    def fill_limit_inside_spread(self) -> bool: ...
    def get_orderbook_for_fill_simulation(self, Instrumentinstrument, Orderorder, Pricebest_bid, Pricebest_ask) -> OrderBook: ...
    def is_limit_filled(self) -> bool: ...
    def is_slipped(self) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class LimitOrderPartialFillModel(FillModel):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def get_orderbook_for_fill_simulation(self, Instrumentinstrument, Orderorder, Pricebest_bid, Pricebest_ask) -> OrderBook: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class MarketHoursFillModel(FillModel):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, doubleprob_fill_on_limit=..., doubleprob_slippage=..., random_seed=...) -> Any: ...
    def get_orderbook_for_fill_simulation(self, Instrumentinstrument, Orderorder, Pricebest_bid, Pricebest_ask) -> OrderBook: ...
    def is_low_liquidity_period(self) -> bool: ...
    def set_low_liquidity_period(self, boolis_low_liquidity) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class OneTickSlippageFillModel(FillModel):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def get_orderbook_for_fill_simulation(self, Instrumentinstrument, Orderorder, Pricebest_bid, Pricebest_ask) -> OrderBook: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class ProbabilisticFillModel(FillModel):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def get_orderbook_for_fill_simulation(self, Instrumentinstrument, Orderorder, Pricebest_bid, Pricebest_ask) -> OrderBook: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class SizeAwareFillModel(FillModel):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def get_orderbook_for_fill_simulation(self, Instrumentinstrument, Orderorder, Pricebest_bid, Pricebest_ask) -> OrderBook: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class ThreeTierFillModel(FillModel):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def get_orderbook_for_fill_simulation(self, Instrumentinstrument, Orderorder, Pricebest_bid, Pricebest_ask) -> OrderBook: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class TwoTierFillModel(FillModel):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def get_orderbook_for_fill_simulation(self, Instrumentinstrument, Orderorder, Pricebest_bid, Pricebest_ask) -> OrderBook: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...

class VolumeSensitiveFillModel(FillModel):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, doubleprob_fill_on_limit=..., doubleprob_slippage=..., random_seed=...) -> Any: ...
    def get_orderbook_for_fill_simulation(self, Instrumentinstrument, Orderorder, Pricebest_bid, Pricebest_ask) -> OrderBook: ...
    def set_recent_volume(self, doublevolume) -> void: ...
    def __reduce__(self): ...
    def __reduce_cython__(self) -> Any: ...
    def __setstate_cython__(self, __pyx_state) -> Any: ...
