from _typeshed import Incomplete
from decimal import Decimal
from nautilus_trader.common.enums import LogColor as LogColor
from nautilus_trader.config import PositiveFloat as PositiveFloat, PositiveInt as PositiveInt, StrategyConfig as StrategyConfig
from nautilus_trader.core.data import Data as Data
from nautilus_trader.core.message import Event as Event
from nautilus_trader.indicators import BollingerBands as BollingerBands, RelativeStrengthIndex as RelativeStrengthIndex
from nautilus_trader.model.data import Bar as Bar, BarType as BarType
from nautilus_trader.model.enums import OrderSide as OrderSide, TimeInForce as TimeInForce
from nautilus_trader.model.identifiers import InstrumentId as InstrumentId
from nautilus_trader.model.instruments import Instrument as Instrument
from nautilus_trader.model.orders import MarketOrder as MarketOrder
from nautilus_trader.trading.strategy import Strategy as Strategy

class BBMeanReversionConfig(StrategyConfig, frozen=True):
    instrument_id: InstrumentId
    bar_type: BarType
    trade_size: Decimal
    bb_period: PositiveInt = ...
    bb_std: PositiveFloat = ...
    rsi_period: PositiveInt = ...
    rsi_buy_threshold: float = ...
    rsi_sell_threshold: float = ...
    close_positions_on_stop: bool = ...

class BBMeanReversion(Strategy):
    instrument: Instrument
    bb: Incomplete
    rsi: Incomplete
    def __init__(self, config: BBMeanReversionConfig) -> None: ...
    def on_start(self) -> None: ...
    def on_bar(self, bar: Bar) -> None: ...
    def buy(self) -> None: ...
    def sell(self) -> None: ...
    def on_data(self, data: Data) -> None: ...
    def on_event(self, event: Event) -> None: ...
    def on_stop(self) -> None: ...
    def on_reset(self) -> None: ...
    def on_save(self) -> dict[str, bytes]: ...
    def on_load(self, state: dict[str, bytes]) -> None: ...
    def on_dispose(self) -> None: ...
