from nautilus_trader.config import StrategyConfig as StrategyConfig
from nautilus_trader.core.data import Data as Data
from nautilus_trader.core.message import Event as Event
from nautilus_trader.model.data import Bar as Bar, QuoteTick as QuoteTick, TradeTick as TradeTick
from nautilus_trader.model.identifiers import InstrumentId as InstrumentId
from nautilus_trader.model.instruments import Instrument as Instrument
from nautilus_trader.trading.strategy import Strategy as Strategy

class MyStrategyConfig(StrategyConfig, frozen=True):
    instrument_id: InstrumentId

class MyStrategy(Strategy):
    def __init__(self, config: MyStrategyConfig) -> None: ...
    def on_start(self) -> None: ...
    def on_stop(self) -> None: ...
    def on_reset(self) -> None: ...
    def on_dispose(self) -> None: ...
    def on_save(self) -> dict[str, bytes]: ...
    def on_load(self, state: dict[str, bytes]) -> None: ...
    def on_instrument(self, instrument: Instrument) -> None: ...
    def on_quote_tick(self, tick: QuoteTick) -> None: ...
    def on_trade_tick(self, tick: TradeTick) -> None: ...
    def on_bar(self, bar: Bar) -> None: ...
    def buy(self) -> None: ...
    def sell(self) -> None: ...
    def on_data(self, data: Data) -> None: ...
    def on_event(self, event: Event) -> None: ...
