from _typeshed import Incomplete
from decimal import Decimal
from nautilus_trader.common.enums import LogColor as LogColor
from nautilus_trader.config import PositiveFloat as PositiveFloat, PositiveInt as PositiveInt, StrategyConfig as StrategyConfig
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.core.data import Data as Data
from nautilus_trader.core.message import Event as Event
from nautilus_trader.indicators import ExponentialMovingAverage as ExponentialMovingAverage
from nautilus_trader.model.book import OrderBook as OrderBook
from nautilus_trader.model.data import Bar as Bar, BarType as BarType, OrderBookDeltas as OrderBookDeltas, QuoteTick as QuoteTick, TradeTick as TradeTick
from nautilus_trader.model.enums import OrderSide as OrderSide, TimeInForce as TimeInForce
from nautilus_trader.model.identifiers import ExecAlgorithmId as ExecAlgorithmId, InstrumentId as InstrumentId
from nautilus_trader.model.instruments import Instrument as Instrument
from nautilus_trader.model.orders import MarketOrder as MarketOrder
from nautilus_trader.trading.strategy import Strategy as Strategy
from typing import Any

class EMACrossTWAPConfig(StrategyConfig, frozen=True):
    instrument_id: InstrumentId
    bar_type: BarType
    trade_size: Decimal
    fast_ema_period: PositiveInt = ...
    slow_ema_period: PositiveInt = ...
    twap_horizon_secs: PositiveFloat = ...
    twap_interval_secs: PositiveFloat = ...
    close_positions_on_stop: bool = ...

class EMACrossTWAP(Strategy):
    instrument: Instrument
    fast_ema: Incomplete
    slow_ema: Incomplete
    twap_exec_algorithm_id: Incomplete
    twap_exec_algorithm_params: dict[str, Any]
    def __init__(self, config: EMACrossTWAPConfig) -> None: ...
    def on_start(self) -> None: ...
    def on_instrument(self, instrument: Instrument) -> None: ...
    def on_order_book_deltas(self, deltas: OrderBookDeltas) -> None: ...
    def on_order_book(self, order_book: OrderBook) -> None: ...
    def on_quote_tick(self, tick: QuoteTick) -> None: ...
    def on_trade_tick(self, tick: TradeTick) -> None: ...
    def on_bar(self, bar: Bar) -> None: ...
    def buy(self) -> None: ...
    def sell(self) -> None: ...
    def on_data(self, data: Data) -> None: ...
    def on_event(self, event: Event) -> None: ...
    def on_stop(self) -> None: ...
    def on_reset(self) -> None: ...
    def on_save(self) -> dict[str, bytes]: ...
    def on_load(self, state: dict[str, bytes]) -> None: ...
    def on_dispose(self) -> None: ...
