from _typeshed import Incomplete
from decimal import Decimal
from nautilus_trader.common.enums import LogColor as LogColor
from nautilus_trader.config import PositiveFloat as PositiveFloat, PositiveInt as PositiveInt, StrategyConfig as StrategyConfig
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.core.data import Data as Data
from nautilus_trader.core.message import Event as Event
from nautilus_trader.indicators import AverageTrueRange as AverageTrueRange, ExponentialMovingAverage as ExponentialMovingAverage
from nautilus_trader.model.data import Bar as Bar, BarType as BarType, QuoteTick as QuoteTick
from nautilus_trader.model.enums import OrderSide as OrderSide, OrderType as OrderType, TimeInForce as TimeInForce, TriggerType as TriggerType
from nautilus_trader.model.identifiers import ExecAlgorithmId as ExecAlgorithmId, InstrumentId as InstrumentId
from nautilus_trader.model.instruments import Instrument as Instrument
from nautilus_trader.model.objects import Price as Price
from nautilus_trader.model.orders import OrderList as OrderList
from nautilus_trader.trading.strategy import Strategy as Strategy
from typing import Any

class EMACrossBracketAlgoConfig(StrategyConfig, frozen=True):
    instrument_id: InstrumentId
    bar_type: BarType
    trade_size: Decimal
    atr_period: PositiveInt = ...
    fast_ema_period: PositiveInt = ...
    slow_ema_period: PositiveInt = ...
    bracket_distance_atr: PositiveFloat = ...
    emulation_trigger: str = ...
    entry_exec_algorithm_id: ExecAlgorithmId | None = ...
    entry_exec_algorithm_params: dict[str, Any] | None = ...
    sl_exec_algorithm_id: ExecAlgorithmId | None = ...
    sl_exec_algorithm_params: dict[str, Any] | None = ...
    tp_exec_algorithm_id: ExecAlgorithmId | None = ...
    tp_exec_algorithm_params: dict[str, Any] | None = ...
    close_positions_on_stop: bool = ...

class EMACrossBracketAlgo(Strategy):
    instrument: Instrument | None
    atr: Incomplete
    fast_ema: Incomplete
    slow_ema: Incomplete
    def __init__(self, config: EMACrossBracketAlgoConfig) -> None: ...
    def on_start(self) -> None: ...
    def on_quote_tick(self, tick: QuoteTick) -> None: ...
    def on_bar(self, bar: Bar) -> None: ...
    def buy(self, last_bar: Bar) -> None: ...
    def sell(self, last_bar: Bar) -> None: ...
    def on_data(self, data: Data) -> None: ...
    def on_event(self, event: Event) -> None: ...
    def on_stop(self) -> None: ...
    def on_reset(self) -> None: ...
    def on_save(self) -> dict[str, bytes]: ...
    def on_load(self, state: dict[str, bytes]) -> None: ...
    def on_dispose(self) -> None: ...
