from _typeshed import Incomplete
from decimal import Decimal
from nautilus_trader.common.enums import LogColor as LogColor
from nautilus_trader.config import PositiveFloat as PositiveFloat, PositiveInt as PositiveInt, StrategyConfig as StrategyConfig
from nautilus_trader.core.correctness import PyCondition as PyCondition
from nautilus_trader.core.data import Data as Data
from nautilus_trader.core.message import Event as Event
from nautilus_trader.indicators import AverageTrueRange as AverageTrueRange, ExponentialMovingAverage as ExponentialMovingAverage
from nautilus_trader.model.book import OrderBook as OrderBook
from nautilus_trader.model.data import Bar as Bar, BarType as BarType, QuoteTick as QuoteTick, TradeTick as TradeTick
from nautilus_trader.model.enums import OrderSide as OrderSide, TrailingOffsetType as TrailingOffsetType, TriggerType as TriggerType
from nautilus_trader.model.events import OrderFilled as OrderFilled, PositionChanged as PositionChanged, PositionClosed as PositionClosed, PositionOpened as PositionOpened
from nautilus_trader.model.identifiers import InstrumentId as InstrumentId
from nautilus_trader.model.instruments import Instrument as Instrument
from nautilus_trader.model.orders import MarketOrder as MarketOrder, TrailingStopMarketOrder as TrailingStopMarketOrder
from nautilus_trader.trading.strategy import Strategy as Strategy

class EMACrossTrailingStopConfig(StrategyConfig, frozen=True):
    instrument_id: InstrumentId
    bar_type: BarType
    atr_period: PositiveInt
    trailing_atr_multiple: PositiveFloat
    trailing_offset_type: str
    trigger_type: str
    trade_size: Decimal
    fast_ema_period: PositiveInt = ...
    slow_ema_period: PositiveInt = ...
    emulation_trigger: str = ...

class EMACrossTrailingStop(Strategy):
    instrument: Instrument | None
    tick_size: Incomplete
    fast_ema: Incomplete
    slow_ema: Incomplete
    atr: Incomplete
    entry: Incomplete
    trailing_stop: Incomplete
    position_id: Incomplete
    def __init__(self, config: EMACrossTrailingStopConfig) -> None: ...
    def on_start(self) -> None: ...
    def on_stop(self) -> None: ...
    def on_reset(self) -> None: ...
    def on_instrument(self, instrument: Instrument) -> None: ...
    def on_order_book(self, order_book: OrderBook) -> None: ...
    def on_quote_tick(self, tick: QuoteTick) -> None: ...
    def on_trade_tick(self, tick: TradeTick) -> None: ...
    def on_bar(self, bar: Bar) -> None: ...
    def entry_buy(self) -> None: ...
    def entry_sell(self) -> None: ...
    def trailing_stop_buy(self) -> None: ...
    def trailing_stop_sell(self) -> None: ...
    def on_data(self, data: Data) -> None: ...
    def on_event(self, event: Event) -> None: ...
    def on_save(self) -> dict[str, bytes]: ...
    def on_load(self, state: dict[str, bytes]) -> None: ...
    def on_dispose(self) -> None: ...
