from nautilus_trader.config import NonNegativeFloat as NonNegativeFloat, PositiveInt as PositiveInt, StrategyConfig as StrategyConfig
from nautilus_trader.model.data import QuoteTick as QuoteTick
from nautilus_trader.model.enums import OrderSide as OrderSide, TimeInForce as TimeInForce
from nautilus_trader.model.events import OrderCanceled as OrderCanceled, OrderExpired as OrderExpired, OrderFilled as OrderFilled, OrderRejected as OrderRejected
from nautilus_trader.model.identifiers import ClientOrderId as ClientOrderId, InstrumentId as InstrumentId
from nautilus_trader.model.instruments import Instrument as Instrument
from nautilus_trader.model.objects import Price as Price, Quantity as Quantity
from nautilus_trader.model.tick_scheme.base import round_down as round_down, round_up as round_up
from nautilus_trader.trading.strategy import Strategy as Strategy

class GridMarketMakerConfig(StrategyConfig, frozen=True):
    instrument_id: InstrumentId
    max_position: Quantity
    trade_size: Quantity | None = ...
    num_levels: PositiveInt = ...
    grid_step_bps: PositiveInt = ...
    skew_factor: NonNegativeFloat = ...
    requote_threshold_bps: PositiveInt = ...
    expire_time_secs: PositiveInt | None = ...
    on_cancel_resubmit: bool = ...

class GridMarketMaker(Strategy):
    def __init__(self, config: GridMarketMakerConfig) -> None: ...
    def on_start(self) -> None: ...
    def on_stop(self) -> None: ...
    def on_quote_tick(self, tick: QuoteTick) -> None: ...
    def on_order_filled(self, event: OrderFilled) -> None: ...
    def on_order_rejected(self, event: OrderRejected) -> None: ...
    def on_order_expired(self, event: OrderExpired) -> None: ...
    def on_order_canceled(self, event: OrderCanceled) -> None: ...
    def on_reset(self) -> None: ...
