from _typeshed import Incomplete
from nautilus_trader.core.nautilus_pyo3 import UUID4 as UUID4
from nautilus_trader.core.nautilus_pyo3.model import ClientOrderId as ClientOrderId, ContingencyType as ContingencyType, InstrumentId as InstrumentId, MarketOrder as MarketOrder, OrderSide as OrderSide, Quantity as Quantity, TimeInForce as TimeInForce
from nautilus_trader.core.nautilus_pyo3.trading import Strategy as Strategy, StrategyConfig as StrategyConfig

class MarketBuyOnStartConfig(StrategyConfig):
    def __new__(cls, *args, **kwargs): ...
    instrument_id: Incomplete
    trade_size: Incomplete
    rebuy_after_close: Incomplete
    def __init__(self, instrument_id: str, trade_size: int, rebuy_after_close: bool = False, **kwargs) -> None: ...

class MarketBuyOnStart(Strategy):
    def __init__(self, config: MarketBuyOnStartConfig) -> None: ...
    def on_start(self) -> None: ...
    def on_quote(self, quote) -> None: ...
    def on_reset(self) -> None: ...
    def on_position_closed(self, event) -> None: ...
    def on_stop(self) -> None: ...
