from decimal import Decimal
from nautilus_trader.config import NonNegativeFloat as NonNegativeFloat, PositiveFloat as PositiveFloat, StrategyConfig as StrategyConfig
from nautilus_trader.core.rust.common import LogColor as LogColor
from nautilus_trader.model.book import OrderBook as OrderBook
from nautilus_trader.model.data import OrderBookDeltas as OrderBookDeltas, QuoteTick as QuoteTick
from nautilus_trader.model.enums import BookType as BookType, OrderSide as OrderSide, TimeInForce as TimeInForce, book_type_from_str as book_type_from_str
from nautilus_trader.model.identifiers import InstrumentId as InstrumentId
from nautilus_trader.model.instruments import Instrument as Instrument
from nautilus_trader.model.objects import Quantity as Quantity
from nautilus_trader.trading.strategy import Strategy as Strategy

class OrderBookImbalanceConfig(StrategyConfig, frozen=True):
    instrument_id: InstrumentId
    max_trade_size: Decimal
    trigger_min_size: PositiveFloat = ...
    trigger_imbalance_ratio: PositiveFloat = ...
    min_seconds_between_triggers: NonNegativeFloat = ...
    book_type: str | BookType = ...
    use_quote_ticks: bool = ...
    dry_run: bool = ...

class OrderBookImbalance(Strategy):
    instrument: Instrument | None
    book_type: BookType | None
    def __init__(self, config: OrderBookImbalanceConfig) -> None: ...
    def on_start(self) -> None: ...
    def on_order_book_deltas(self, deltas: OrderBookDeltas) -> None: ...
    def on_quote_tick(self, tick: QuoteTick) -> None: ...
    def check_trigger(self) -> None: ...
    def on_reset(self) -> None: ...
    def on_stop(self) -> None: ...
