from _typeshed import Incomplete
from decimal import Decimal
from nautilus_trader.common.enums import LogColor as LogColor
from nautilus_trader.config import StrategyConfig as StrategyConfig
from nautilus_trader.model.data import QuoteTick as QuoteTick
from nautilus_trader.model.enums import OrderSide as OrderSide
from nautilus_trader.model.events import OrderFilled as OrderFilled
from nautilus_trader.model.identifiers import InstrumentId as InstrumentId
from nautilus_trader.trading.strategy import Strategy as Strategy

class SimpleQuoterStrategyConfig(StrategyConfig, frozen=True):
    instrument_id: InstrumentId
    order_qty: Decimal = ...
    tob_offset_ticks: int = ...
    log_data: bool = ...

class SimpleQuoterStrategy(Strategy):
    instrument: Incomplete
    def __init__(self, config: SimpleQuoterStrategyConfig) -> None: ...
    def on_start(self) -> None: ...
    def on_quote_tick(self, quote: QuoteTick) -> None: ...
    def on_event(self, event) -> None: ...
    def on_stop(self) -> None: ...
