from _typeshed import Incomplete
from nautilus_trader.config import StrategyConfig as StrategyConfig
from nautilus_trader.model.book import OrderBook as OrderBook
from nautilus_trader.model.data import Bar as Bar, BarSpecification as BarSpecification, BarType as BarType, IndexPriceUpdate as IndexPriceUpdate, OrderBookDeltas as OrderBookDeltas, QuoteTick as QuoteTick, TradeTick as TradeTick
from nautilus_trader.model.enums import AggregationSource as AggregationSource, BarAggregation as BarAggregation, BookType as BookType, PriceType as PriceType
from nautilus_trader.model.identifiers import InstrumentId as InstrumentId
from nautilus_trader.trading.strategy import Strategy as Strategy

class SubscribeStrategyConfig(StrategyConfig, frozen=True):
    instrument_id: InstrumentId
    book_type: BookType | None = ...
    snapshots: bool = ...
    trade_ticks: bool = ...
    quote_ticks: bool = ...
    bars: bool = ...
    index_prices: bool = ...

class SubscribeStrategy(Strategy):
    book: OrderBook | None
    def __init__(self, config: SubscribeStrategyConfig) -> None: ...
    instrument: Incomplete
    def on_start(self) -> None: ...
    def on_order_book_deltas(self, deltas: OrderBookDeltas) -> None: ...
    def on_order_book(self, order_book: OrderBook) -> None: ...
    def on_trade_tick(self, tick: TradeTick) -> None: ...
    def on_quote_tick(self, tick: QuoteTick) -> None: ...
    def on_bar(self, bar: Bar) -> None: ...
    def on_index_price(self, price: IndexPriceUpdate) -> None: ...
