from _typeshed import Incomplete
from decimal import Decimal
from nautilus_trader.common.enums import LogColor as LogColor
from nautilus_trader.config import PositiveFloat as PositiveFloat, PositiveInt as PositiveInt, StrategyConfig as StrategyConfig
from nautilus_trader.core.data import Data as Data
from nautilus_trader.core.message import Event as Event
from nautilus_trader.indicators import AverageTrueRange as AverageTrueRange
from nautilus_trader.model.book import OrderBook as OrderBook
from nautilus_trader.model.data import Bar as Bar, BarType as BarType, MarkPriceUpdate as MarkPriceUpdate, OrderBookDeltas as OrderBookDeltas, QuoteTick as QuoteTick, TradeTick as TradeTick
from nautilus_trader.model.enums import OrderSide as OrderSide, TimeInForce as TimeInForce, TriggerType as TriggerType
from nautilus_trader.model.events import OrderFilled as OrderFilled
from nautilus_trader.model.identifiers import ClientId as ClientId, InstrumentId as InstrumentId
from nautilus_trader.model.instruments import Instrument as Instrument
from nautilus_trader.model.orders import LimitOrder as LimitOrder
from nautilus_trader.trading.strategy import Strategy as Strategy

class VolatilityMarketMakerConfig(StrategyConfig, frozen=True):
    instrument_id: InstrumentId
    bar_type: BarType
    atr_period: PositiveInt
    atr_multiple: PositiveFloat
    trade_size: Decimal
    emulation_trigger: str = ...
    client_id: ClientId | None = ...
    reduce_only_on_stop: bool = ...

class VolatilityMarketMaker(Strategy):
    instrument: Instrument | None
    client_id: Incomplete
    atr: Incomplete
    buy_order: LimitOrder | None
    sell_order: LimitOrder | None
    def __init__(self, config: VolatilityMarketMakerConfig) -> None: ...
    def on_start(self) -> None: ...
    def on_data(self, data: Data) -> None: ...
    def on_instrument(self, instrument: Instrument) -> None: ...
    def on_order_book(self, order_book: OrderBook) -> None: ...
    def on_order_book_deltas(self, deltas: OrderBookDeltas) -> None: ...
    def on_quote_tick(self, tick: QuoteTick) -> None: ...
    def on_trade_tick(self, tick: TradeTick) -> None: ...
    def on_mark_price(self, update: MarkPriceUpdate) -> None: ...
    def on_index_price(self, update: MarkPriceUpdate) -> None: ...
    def on_bar(self, bar: Bar) -> None: ...
    def create_buy_order(self, last: QuoteTick) -> None: ...
    def create_sell_order(self, last: QuoteTick) -> None: ...
    def on_event(self, event: Event) -> None: ...
    def on_stop(self) -> None: ...
    def on_reset(self) -> None: ...
